### ISSUE TITLE
DatabaseOpener custom parameters

### ISSUE THREAD

**Issue by SeniorZhai** [simolus3/moor#1000]
I want to use MoorIsolate, I need to distinguish the path of the database.
But MoorIsolate.spawn(DatabaseOpener opener), DatabaseOpener doesn't take parameters
Is there any solution?

**Comment by simolus3** [comment]
That's a bit more complicated unfortunately. The approach is documented [here](https://moor.simonbinder.eu/docs/advanced-features/isolates/#initialization-on-the-main-thread). Basically, you'll

- create your own isolate entrypoint taking the path as a parameter
- inside that entrypoint, use `MoorIsolate.inCurrent`
- spawn a new `Isolate` with that entrypoint, which effective creates a background `MoorIsolate`
- send the `MoorIsolate` instance through a `SendPort`, so that you can use it in the main isolate
