### ISSUE TITLE
type 'int' is not a subtype of type 'Value<int>'

### ISSUE THREAD

**Issue by leonardocustodio** [simolus3/moor#1005]
Hello,

I have a nullable field and when I try to assign a value to it I get the error

`type 'int' is not a subtype of type 'Value<int>'`

I'm trying to save the row with this command:
```
  ConfigsCompanion.insert(
        goal: user.goal ?? Value.absent(),
  );
```

Did I misunderstood how the library was supposed to work?

Regards,
Leonardo

**Comment by leonardocustodio** [comment]
I see just have to wrap into Value(user.goal)
But do I have to do this on all vars that can be null? Because at least dart analysis don't ask to do this on all of them.

**Comment by simolus3** [comment]
> But do I have to do this on all vars that can be null?

You'll have to do that for all columns that aren't required for an insert (either because they're nullable or because they have a default value).
To quote the documentation:

>You might have noticed that we used a `TodosCompanion` for the first update instead of just passing a `Todo`. Moor generates the `Todo` class (also called _data class_ for the table) to hold a __full__ row with all its data. For _partial_ data, prefer to use companions. In the example above, we only set the the `category` column, so we used a companion. 
Why is that necessary? If a field was set to `null`, we wouldn't know whether we need  to set that column back to null in the database or if we should just leave it unchanged. Fields in the companions have a special `Value.absent()` state which makes this explicit.
>
>Companions also have a special constructor for inserts - all columns which don't have a default value and aren't nullable are marked `@required` on that constructor. This makes companions easier to use for inserts because you know which fields to set.

For inserts, a `Value` wrapper is necessary because we can't know whether `null` means to explicitly set a column to `NULL` or whether we should use the default value. A `Value(null)` vs `Value.absent()` makes this explicit.
