### ISSUE TITLE
InsertMode in customInsert

### ISSUE THREAD

**Issue by rrifafauzikomara** [simolus3/moor#1016]
In the `insert` method below we can use `mode`.

```
Future updateDataAppVersion(LstAppVersionOrionData data) =>
      into(lstAppVersionOrion).insert(data, mode: InsertMode.insertOrReplace);
```

But if using `customInsert` how to add `mode` like the above method?

```
Future runInsertQueryFromServer(String query) async {
    return customInsert(query);
  }
```

**Comment by simolus3** [comment]
There is no `mode` parameter in `customInsert` because you need to write the SQL yourself. You could use `INSERT OR IGNORE ...` for `query`, for instance. For all options, see [the documentation](https://www.sqlite.org/lang_insert.html).

Also, please consider asking questions like these in the [discussions](https://github.com/simolus3/moor/discussions/categories/q-a). Discussions make it easier for me to answer and they have a better visibility than closed issues. Thanks!
