### ISSUE TITLE
Expecting initial single int from steam watchSingle() but listener is activated multiple times

### ISSUE THREAD

**Issue by PaulVipond** [simolus3/moor#1033]
In my DAO I have this query:

```
  Stream<int> watchGroupMessageCount(String chatGroupId) {
    final count = contentMessages.id.count();
    final query = selectOnly(contentMessages)
      ..addColumns([count])
      ..where(contentMessages.contentGroupId.equals(chatGroupId));
    return query.map((row) => row.read(count)).watchSingle();
  }
```
So I'm expecting this to emit a single count, then if the query changes, to get another count. I was getting strange results, so I simplified my consuming code to this for testing purposes:

```
  @override
  void initState() {
    super.initState();
    ChatBloc chatBloc = BlocProvider.of<ChatBloc>(context);
    chatBloc.watchGroupMessageCount(this.activeChatGroupId).listen((int newCount) {
      setState( () { this.count++; this.myController.text = "Count: $newCount, ${this.count}"; });
    });
  }

```
It turns out that the listener is being called 5002 times - there are 5001 items in the database and the count value is 5001 every time. I do have a background isolate for the database, but it's not currently doing anything. Since, I'm relatively new to Flutter, I'm expecting to at some point slap my forehead and say "oh, of course, doh!" Any advice appreciated.

**Comment by simolus3** [comment]
That looks pretty weird to me too. In general, an updated stream doesn't actually imply changes in the database (the query might run more than once), but running it for each row is excessive of course.

Are you doing some other updates while the stream runs? E.g. if you're going through all entries and manually apply an update on the `contentMessages` table, the stream would invalidate and run the query again.
If you're using a `MoorIsolate`, you can enable the `isolateDebugLog: true` parameter on `MoorIsolate.connect`. This might help to find updates causing the stream to run more than once.

And unrelated to that: Be sure to always cancel a stream subscription you create in `initState()`, otherwise you'll leak memory. If you're only doing this for debugging it's fine, but in a real app you'd store the `StreamSubscription` returned by `.listen` in a field and then call `.cancel()` on that in `dispose()`.

**Comment by PaulVipond** [comment]
Thanks for the debug tip - that helped me nail it. I generate 5001 rows of test data when the app bootstraps. Because I hadn't awaited these, they were all busily completing in the background and affecting the query watch. (Though quite why every watch listen was coming back with a full table count of 5001 is a mystery to me, but hey ho.) The debug all showed me that all of the table creation was running twice, which is now fixed. I'll allow myself the forehead slap now, "oh, of course, doh!" And thanks for your help sorting it out.

**Comment by simolus3** [comment]
No worries. If you ever end up inserting many rows outside of debugging purposes, I recommend wrapping all of that in a `transaction`. It's more performant in sqlite and moor will only invalidate stream queries once.
