### ISSUE TITLE
How can I set auto-increment instead of setting auto-increment and setting primary key?

### ISSUE THREAD

**Issue by januwA** [simolus3/moor#108]
autoIncrement does not work as expected 🥺

```dart
class Todos extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get sort => integer().autoIncrement()(); // Runtime error will cause two primary keys to be set
}
```

How to set auto-increment field 🤔

**Comment by simolus3** [comment]
Hi. Moor will use sqlite to run the queries. Like most sql databases, sqlite doesn't support more than one auto increment column, and it has to be the primary key ((see docs)[https://www.sqlite.org/autoinc.html]). So unfortunately, there's not much moor could do about that.

I have a possible workaround in my mind, I'll try it out later and let you know if it works.

**Comment by simolus3** [comment]
I tried to set `(SELECT MAX(sort)+1 FROM todos)` as a default value, but that didn't work because default values need to be constant. AFAIK there is no way to express multiple auto-increments per table in sql, so I don't think we should support it in moor.

I know Exposed has [`clientDefault`](https://github.com/JetBrains/Exposed/blob/0790d1f9414826b5a43d0042789bca3c4bc79866/exposed/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L447-L451) which could be used to achieve this. We could port something similar to moor if you need it.

**Comment by januwA** [comment]
Thank you for your quick answer. I need to add the ‘sort’ field in the version migration to sort the data list. I want to set the value of the ’sort‘ field to the current ‘id’ value. 😃

**Comment by simolus3** [comment]
Doing this directly is not possible with moor at the moment, because it requires an inner select statement during the insert (e.g. you'd want something like `INSERT INTO todos (sort) VALUES ((SELECT MAX(id) +1 FROM todos))` to match the next auto-increment id for the sort field).
As a workaround, you could use something like
```dart
class Todos extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get sort => integer().withDefault(const Constant(0))();
  // some other data
}

// to insert an item (inside your database class)
Future createTodoItem() {
  return transaction((_) async {
    final insertedId = await into(todos).insert(TodosCompanion(/* write all other data except for sort and id */));
    await customUpdate('UPDATE todos SET sort = id WHERE id = ?', variables: [Variable.withInt(insertedId)]);
  });
}
```

But ideally moor should have a way to do this in one query.

**Comment by januwA** [comment]
Thank you, this solved my problem. 🎉
