### ISSUE TITLE
Trying experimental web support on AngularDart app, doesn't execute onCreate

### ISSUE THREAD

**Issue by marcgraub** [simolus3/moor#109]
Hi!

I'm trying to use Moor on an AngularDart app.

When I do the setup, onCreate isn't executed, and if I try to do an insert or a migration, beforeOpen and onUpgrade are executed, but then appears the error:

`Uncaught (in promise) Error: no such table: table_name`

Do you have some hint of what I can do to resolve the issue?

Lots of thanks for your time and for your project.

**Comment by simolus3** [comment]
Interesting, I never ran into that problem. Does the problem persist when you clear the local storage (`window.localStorage.clear()` in the console)? I might be that you first created the database in the browser before you defined the table.

I don't really know what could have caused this otherwise, we have integration tests that verify the `onCreate` callback gets called (they run on Chrome and Firefox). If clearing the data doesn't fix it, this sounds like a bug in moor. In that case, knowing a bit more about how you create the datbase (e.g. the code for your `migration` getter) could help, thanks!

**Comment by marcgraub** [comment]
That's it! when doing the setup, I've created an empty database.

Sorry for taking up your time like that and thank you.
