### ISSUE TITLE
Why not use loveField instead of sql.js?

### ISSUE THREAD

**Issue by Elvis5566** [simolus3/moor#110]
Hi all,

I am looking for a solution to share db related code between flutter and web.
Moor with web support looks like my dream feature!!
I am not familiar with web frond-end development so I did some research about web local storage.
the following is the facts I know so far:
1. web sql is deprecated -> we can't use sqlite, not every browsers support it.
2. sql.js, a in-memory sqlite db, doesn't persist the changes, and there is a concern about the size of sql.js.
3. [LoveField](https://github.com/google/lovefield), a wrapper on indexedDb, which supports most of features on relational db, and support most of browsers.

I was wondering why not use LoveField, and how do you persist changes with sql.js 

Thank you very much

**Comment by simolus3** [comment]
You're right about web sql - it's obsolete, so not really an option here. 
`sql.js` works in-memory by default, but it lets us export the current state and persist it. We do this after each update, which is not really efficient on large databases, but works.
Lovefield does look interesting, especially from a performance perspective compared to sql.js. The issue is that it doesn't support sql, we have to use their JS api to model the queries. Currently, moor works by generating sql queries from Dart code at runtime. Generating Lovefield queries as well would be a significant change, but something that's definitely doable. However, we also have a feature called [compiled queries](https://moor.simonbinder.eu/docs/using-sql/custom_queries/#statements-with-a-generated-api) that let's users write sql directly and have moor figure out what to do with it. Rewriting sql to Lovefield would be a lot of work...

Also, the nice thing about `sql.js` is that it's a proper sqlite engine on the web (through WASM). This means that it will behave very similar to the backend we're using on Flutter (and the VM in the future). Also, it _looks_ like the experimental Dart FFI feature will eventually support WASM as well, so we don't have to depend on an external JS library and can call sqlite directly from Dart. There's still some overhead from the WASM binary, but it's an improvement.

Feel free to reply/reopen the issue if you have any further questions :)

**Comment by kanekv** [comment]
Re-writing whole database on each update seems to be very expensive... Did you think what is possible to improve this?
