### ISSUE TITLE
Incorrect InvalidDataException

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#112]
With a table defined like:
```sql
CREATE TABLE mytable
(
	someid INTEGER NOT NULL PRIMARY KEY,
	sometext TEXT
);
```
Trying to call `into(mytable).insert(MytableData(sometext: 'hello'));` throws the following exception: 
```
InvalidDataException: Sorry, MytableData(someid: null, sometext: hello) cannot be used for that because: 
• someid: This value was required, but isn't present
```
However, manually executing `insert into mytable values (null, 'hello')` works correctly. 

From https://www.sqlite.org/autoinc.html: 
> 2. In SQLite, a column with type INTEGER PRIMARY KEY is an alias for the ROWID (except in WITHOUT ROWID tables) which is always a 64-bit signed integer.

> 3. On an INSERT, if the ROWID or INTEGER PRIMARY KEY column is not explicitly given a value, then it will be filled automatically with an unused integer, usually one more than the largest ROWID currently in use. This is true regardless of whether or not the AUTOINCREMENT keyword is used.

Would it be difficult to add the special case for rowid and its aliases to the `GeneratedColumn.required` check?

**Comment by simolus3** [comment]
We (kind of) already have that check, the `GeneratedIntColumn` has an `autoIncrement` field, when set to true the column will accept absent values.

The reason we don't set that field is because there is no `AUTOINCREMENT` constraint on the column, I didn't know that sqlite also provides a default value when it's not present.

**Comment by Mike278** [comment]
Yeah it *should* be redundant to specify NOT NULL on a PRIMARY KEY column, but with sqlite it's probably best to be explicit:
> According to the SQL standard, PRIMARY KEY should always imply NOT NULL. Unfortunately, due to a bug in some early versions, this is not the case in SQLite. Unless the column is an INTEGER PRIMARY KEY or the table is a WITHOUT ROWID table or the column is declared NOT NULL, SQLite allows NULL values in a PRIMARY KEY column. SQLite could be fixed to conform to the standard, but doing so might break legacy applications. Hence, it has been decided to merely document the fact that SQLite allowing NULLs in most PRIMARY KEY columns.
https://sqlite.org/lang_createtable.html

Plus, like you mentioned in #111, once Dart NNBD lands it'll probably be best to explicitly define NOT NULL.

**Comment by simolus3** [comment]
I just fixed this on `develop` - a column declared as `INTEGER PRIMARY KEY` no longer requires a value to be present during inserts. I plan to release this with another fix this weekend.

> Yeah it _should_ be redundant to specify NOT NULL on a PRIMARY KEY column, but with sqlite it's probably best to be explicit

With tables declared in Dart, we always assume columns are non-nullable unless they explicitly use `nullable()`. We didn't write the `NOT NULL` constraint on `autoIncrement()` columns, but I'd consider that to be a bug I've now fixed. It shouldn't be backwards-incompatible because we ensured the value was not-null before insert, so there shouldn't be invalid data even if the database would have accepted it.

On tables from `.moor` files, we always copy-paste the column constraints instead of generating them from the structure, so we put the responsibility of declaring them as `NOT NULL` on the user. A column declared with `INTEGER PRIMARY KEY` is nullable, which matches the behavior from sqlite you described.
