### ISSUE TITLE
Conflict when using custom select queries for tables have similar col names.

### ISSUE THREAD

**Issue by heshaShawky** [simolus3/moor#1127]
I'm building a normal query that selects and joins other tables and I noticed that the results are missing some cols that similar on each table.

My Tables: if you look below you will find similar col names such as value and name and id ...etc
```dart
class Wallets extends Table {
  IntColumn get id => integer().nullable().autoIncrement()();
  IntColumn get value => integer()();
  TextColumn get name => text()();
  DateTimeColumn get startDate => dateTime()();
  IntColumn get userId => integer().nullable().customConstraint('NULL REFERENCES users(id)')();
}

class Transactions extends Table {
  IntColumn get id => integer().nullable().autoIncrement()();
  IntColumn get value => integer()();
  TextColumn get description => text().nullable().withLength(min: 3)();
  DateTimeColumn get date => dateTime().withDefault(Constant(DateTime.now()))();
  BoolColumn get isRepeated => boolean().withDefault(const Constant(false))();
  IntColumn get repeatedPeriod => intEnum<OutcomePeriods>().nullable()();
  IntColumn get categoryId => integer().nullable().customConstraint('NULL REFERENCES categories(id)')();
  IntColumn get walletId => integer().nullable().customConstraint('NULL REFERENCES wallets(id)')();
  TextColumn get attachments => text().map(const TransactionsAttachmentsConverter()).nullable()();
}


@DataClassName("Category")
class Categories extends Table {
  IntColumn get id => integer().nullable().autoIncrement()();
  IntColumn get parent => integer().withDefault(const Constant(0)).customConstraint('NULL REFERENCES categories(id)')();
  TextColumn get name => text().withLength(min: 2)();
  TextColumn get description => text().nullable()();
  TextColumn get logo => text().nullable()();
  IntColumn get type => intEnum<TransactionsTypes>()();
  IntColumn get priority => intEnum<TransactionPiorty>().nullable()();
}
```

My Custom Query:
```dart
final query = customSelect(
  """
  SELECT
    t.*
  FROM transactions t
  INNER JOIN wallets w ON w.id = t.wallet_id
  INNER JOIN categories c ON c.id = t.category_id
  """,
  readsFrom: {wallets, transactions, categories},
  variables: []
).watch();
```

**I have noticed also if I have to use the pre-built DAO methods like select and joins you fixing this issue by adding the table name before the column (prefix) and my question how to do that in my custom query?**

**Comment by simolus3** [comment]
Yeah, this is a limitation caused by the original moor implementation backed by sqflite. In its public api, sqflite uses a `Map<String, Object?>` to represent a row, which does not support rows with ambiguous column names. By design, sqlite allows a `SELECT` to have columns with the same name, which is what you're encountering here.

In your query however, it looks like you're only selecting `t.*` in the first place, so you might not be running into that issue at all? You can add a unique name to each column manually to fix this, but I'd really let moor do the work. You can write that query with the Dart api for instance. If you want to use SQL, I'd recommend using a [compiled query](https://moor.simonbinder.eu/docs/using-sql/custom_queries/#statements-with-a-generated-api) with the [new `**` syntax](https://moor.simonbinder.eu/docs/using-sql/moor_files/#nested-results). Something like:

```sql
  SELECT
    t.**, w.**, c.**
  FROM transactions t
  INNER JOIN wallets w ON w.id = t.wallet_id
  INNER JOIN categories c ON c.id = t.category_id
```

That still looks like sql, but the generator can transform it to avoid ambiguities.

**Comment by AZKZero** [comment]
Thanks, This helped a lot!!
