### ISSUE TITLE
Table.fromJson function fills columns with null if value is absent 

### ISSUE THREAD

**Issue by osukono** [simolus3/moor#1131]
When we deserialize a table from JSON, would it be possible to fill absent columns with their default values?

**Comment by simolus3** [comment]
Thanks for the idea! One problem with default values is that they might be generated in the database (you could consider an auto-incrementing id to be a default value), so we can't necessarily evaluate them in Dart. Default values are mainly part of the database schema, I'm not sure if they should affect json serialization by default.

We could support more features in moor's `JsonKey` compared to the one from `json_serializable`, #952 is a similar issue. I've never been particularly keen on adding those features since it invites people to use moor's row classes for everything, but moor can't add every feature one might want to data classes.
There are several outstanding issues for this, but I think the best solution for this and related features is to let users write data classes themselves and then let moor generate the bindings. I'll try to think about this and related issues some more and see what I'll come up with. So apologies for the no here, but I think I can figure out something that would let you use your own classes (using advanced `json_serializable` features) with moor, which I think is the best way forward here.
