### ISSUE TITLE
getSingle with returning last data into table

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#115]
documentation of this library is very very basic and its not good for all of developers and i can't understand how can i use more feature of that, for example:

> this operation won't put a limit clause on this statement,if that's needed you would have to do that yourself.

ok, so how can i write this query to get last row, for example:

`SELECT * FROM userTable ORDER BY id DESC LIMIT 1;`

**Comment by Mike278** [comment]
You can pretty much copy the example straight from the `Ordering` section of [the documentation](https://moor.simonbinder.eu/docs/getting-started/writing_queries/) and add a `..limit(1)` clause...

```dart
  Future<TodoEntry> getLastRow() {
    return (select(todos)
      ..orderBy([(t) => OrderingTerm(expression: t.title, mode: OrderingMode.desc)])
      ..limit(1)
    ).getSingle();
  }
```

**Comment by MahdiPishguy** [comment]
@Mike278 it doesn't throw exception?

**Comment by simolus3** [comment]
> it doesn't throw exception

I'm not sure what you mean by that. `getSingle` will return null when no data is available instead of throwing (not really intuitive, but that's described in the docs). If a query returns more than one row and you use `getSingle`, it will throw.

> documentation of this library is very very basic and its not good for all of developers and i can't understand how can i use more feature of that

Sorry to hear that. I'll improve the documentation where I can. On the documentation for `getSingle()`, we now point out that `limit` exists. I've also added an example similar to that given by @Mike278 to the documentation.

Does that help?

**Comment by MahdiPishguy** [comment]
@simolus3 thanks a lot, i'm implementing simple app to learn this library, let me to check, thanks

**Comment by simolus3** [comment]
Sure - I'll close this issue for now, but feel free to reopen if you run into any problems with `limit` and `getSingle`.

**Comment by MahdiPishguy** [comment]
@simolus3 problem solved, thanks
