### ISSUE TITLE
Model Constructors parameters should not be `required` which has default value

### ISSUE THREAD

**Issue by SirusCodes** [simolus3/moor#1178]
**Current**
Parameters of Model which has default values also is marked as required and each time we need to pass it. 

**Expected**
Parameters are named with a default value.

**Comment by simolus3** [comment]
The problem is that some default values are not valid default values in Dart, because they're not constant. For instance, the current date or the current time is a valid default value in SQL, but we can't generate `DateTime.now()` as a default in Dart. Similarly, one might expect an auto-incrementing id column to not be required in Dart, but we need to run a full insert before we know its value.

If you want to create models to insert, use the `.insert()` constructor on the associated companion class. It only uses required params for columns that need to be set during an insert. If you really want default values, moor will let you use custom data classes in the next version, you're free to add default values to them.

**Comment by SirusCodes** [comment]
Thanks a lot, got your point.

**Comment by SirusCodes** [comment]
Can you give us an ETA for next version?

**Comment by mohammedsalem97** [comment]
Is this issue still not solved? i am still facing the same problem on  v4.5.0

**Comment by simolus3** [comment]
@mohammedsalem97 What particular issue are you talking about? What I wrote about in https://github.com/simolus3/moor/issues/1178#issuecomment-832742150 still applies and is not something that I intend to change.

Custom row classes are available though, their documentation is [here](https://moor.simonbinder.eu/docs/advanced-features/custom_row_classes/).
