### ISSUE TITLE
How to get max() DateTime column from the table

### ISSUE THREAD

**Issue by sharoonamjid** [simolus3/moor#1182]
I have a dateTime() column in the table. How can I get the max() dateTime from the table. Thank you.

**Comment by simolus3** [comment]
Does `selectOnly(table)..addColumns([table.dateColumn.max()])` work?

**Comment by sharoonamjid** [comment]
compiler error for max().

The method 'max' isn't defined for the type 'GeneratedDateTimeColumn'.

**Comment by simolus3** [comment]
Oh right, those are only defined for numeric columns at the moment, sorry. I'll add them in the next moor version, you can use this until then

```dart
extension GroupDateTimes on Expression<DateTime?> {
  /// Return the maximum of all non-null values in this group.
  ///
  /// If there are no non-null values in the group, returns null.
  Expression<DateTime> max() => FunctionCallExpression('MAX', [this]);

  /// Return the minimum of all non-null values in this group.
  ///
  /// If there are no non-null values in the group, returns null.
  Expression<DateTime> min() => FunctionCallExpression('MIN', [this]);
}
```

**Comment by pashtostories** [comment]
@simolus3 Thank you for quick response. Your solution worked. But now I'm facing another issue. From the server I receive date time in the following format:

```
"created_at": "2021-04-17T14:59:55.000000Z",
"updated_at": "2021-04-17T15:00:13.000000Z"
```
but it throws the following error when Json is being saved in database:

`type 'String' is not a subtype of type 'int'`

This is because I get the timestamps `updated_at` and `created_at` in string format from the server and Moor `DateTimeColumn` accepts `int` value. How can I fix this issue? How to make `DateTimeColumn` to accept the above string format.

Thank you.

**Comment by sharoonamjid** [comment]
@simolus3 Thank you for quick response. Your solution worked. But now I'm facing another issue. From the server I receive date time in the following format:

```
"created_at": "2021-04-17T14:59:55.000000Z",
"updated_at": "2021-04-17T15:00:13.000000Z"
```
but it throws the following error when Json is being saved in database:

`type 'String' is not a subtype of type 'int'`

This is because I get the timestamps `updated_at` and `created_at` in string format from the server and Moor `DateTimeColumn` accepts `int` value. How can I fix this issue? How to make `DateTimeColumn` to accept the above string format.

Thank you.
