### ISSUE TITLE
checking returned query from table is NULL

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#119]
i want to check my query is null, 

in this simple implementation code i want to check returned future is null and showing widget, but in that `if` statement don't work

```dart
return Scaffold(
  body: Container(
    child: FutureBuilder(
      future: Provider.of<UserTableDao>(context).getSingleUser(),
      builder: (context,snapshot) {
        if (snapshot.hasData) {
          UserTableData user = snapshot.data;
          if (user != null) {
            return Center(
                child: Text(
              'true',
              style: AppTheme(context).caption(),
            ));
          } else {
            return Center(
                child: Text(
              'false',
              style: AppTheme(context).caption(),
            ));
          }
        }
        return CircularProgressIndicator();
      },
    ),
  ),
);
```

console output:

```dart
I/flutter (14985): Moor: Sent SELECT * FROM user_table ORDER BY id DESC LIMIT 1; with args []
```

i that i have only `CircularProgressIndicator` in screen

**Comment by simolus3** [comment]
This is because `hasData` is true only if the data is not null. This affects all nullable `FutureBuilder` and `StreamBuilder`, there's not much moor could do about that. As a workaround, try replacing
`if (snapshot.hasData)` with `if (snapshot.connectionState == ConnectionState.done)`.

If I remember correctly the Flutter team is aware of this and will fix it in a future Flutter version. I'll link the relevant issue when I find it.

**Comment by MahdiPishguy** [comment]
@simolus3 oh i'm sorry I didn't know this problem if for flutter not this library, thanks
