### ISSUE TITLE
[SQLParser] Error reading a create table

### ISSUE THREAD

**Issue by ErliSoares** [simolus3/moor#1194]
When reading the SQL specified in the example, the following error message occurs:

> Bad state: No reference scope found in this or any parent node

```DART
final sql = 'CREATE VIRTUAL TABLE IF NOT EXISTS `mail` USING fts4(`rowid` INTEGER NOT NULL, `text` TEXT NOT NULL, PRIMARY KEY (`rowid`), tokenize=unicode61 )';
final rootNode = SqlEngine().parse(sql).rootNode;
final tableInducingStatement = rootNode as sqlparser.TableInducingStatement;
final table = _engine.schemaReader.read(tableInducingStatement);  // Error occurs here
```

**Comment by simolus3** [comment]
Thanks for the report. `sqlparser` does not currently support fts4, it only supports fts5. If you want to add fts4 support, you can use [this](https://github.com/simolus3/moor/blob/master/sqlparser/lib/src/engine/module/fts5.dart) as a starting point and register a custom extension. PRs are welcome as well!
Further, reading virtual table statements requires the node to be analyzed. The `sqlparser` package registers known modules and tables in a scope, which first happens when analysis starts. So something like this should work instead

```dart
import 'package:sqlparser/sqlparser.dart';

void main() {
  final engine = SqlEngine(EngineOptions(enabledExtensions: [YourFts4Extension()]));
  final sql =
      'CREATE VIRTUAL TABLE IF NOT EXISTS `mail` USING fts4(`rowid` INTEGER NOT NULL, `text` TEXT NOT NULL, PRIMARY KEY (`rowid`), tokenize=unicode61 )';
  final rootNode = engine.analyze(sql).root;
  final tableInducingStatement = rootNode as TableInducingStatement;
  final table = engine.schemaReader.read(tableInducingStatement);
}
```
