### ISSUE TITLE
Joining Tables

### ISSUE THREAD

**Issue by sharoonamjid** [simolus3/moor#1196]
Is it possible to add a functionality to join tables automatically after defining relations in the Table classes. For example if we have two tables `users` and `services` defined like the following.

```
@DataClassName("User")
class Users extends Table {
  IntColumn get id => integer()();

  TextColumn get name => text().nullable()();

  TextColumn get email => text().nullable()();

  TextColumn get username => text().nullable()();

  @JsonKey('created_at')
  IntColumn get createdAt => integer().nullable()();

  @override
  Set<Column> get primaryKey => {id};

  @override
  Set<Relation> hasMany => [Service, SomeOtherTableName, ] // there those tables will be defined which are related to this table via id column with one-to-many relationship

 @override
  Set<Relation> hasOne => [SomeOtherTable, SomeOtherTableName, ] // there those tables will be defined which are related to this table via id column but with one-to-one relationship

}

@DataClassName("Service")
class Services extends Table {
  IntColumn get id => integer()();

  TextColumn get title => text().nullable()();

  TextColumn get description => text().nullable()();

  @JsonKey('user_id')
  IntColumn get userId => integer().nullable()();

  @JsonKey('created_at')
  IntColumn get createdAt => integer().nullable()();

  @override
  Set<Column> get primaryKey => {id};

  @override
  Set<Relation> belongsTo => [User] // reverse relationship. Its optional but It will be useful when we want to get user through service, but if we don't want to get user via service then we can ignor this override.
}
```
Once we have our proper relationship defined in the tables, then maybe we can simply call some helper functions to get related items for example:

```
@JoinedQuery(join: [User, Service])
UserWithServices userWithServices();
```
and for reverse relationship:

```
@JoinedQuery(join: [Service, User])
UserOfService userOfService();
```

and then in actual queries we can call those generated helpers like below maybe

```
 Stream<UserWithServices> watchUserWithServices(int userId) {
    return (select(users)..where((t) => t.id.equals(userId))..userWithServices()).watch();
  }
```

and `UserWithServices` will be consist of `User` and his/her list of services e.g `List<Service>`
so whenever we want to get services of user we will only need to add `userWithServices()` inside the query and It will return the `UserWithServices` object containing User and its all Services. And if we only need to get User and not any joined tables we will ignore adding `userWithServices()` in the query.

And same can be applied for reverse relatioship like this:

```
 Stream<UserOfService> watchUserOfService(int serviceId) {
    return (select(services)..where((t) => t.id.equals(serviceId))..userOfService()).watch();
  }
```
The above query will be able to work by overriding `belongsTo` in the Service table.

It's just my thought but you can come up with different best approach to ease the joinings of tables especially those one which has One to Many relationship because those kind of queries need external packages to work.

**Comment by sharoonamjid** [comment]
@simolus3 let me know what do think about this. Thanks.

**Comment by simolus3** [comment]
Thanks for the request! There have been similar requests in the past, most notably https://github.com/simolus3/moor/issues/114. In general, I'm reluctant to add these features to the core moor packages because I think they'd add a lot of complexity and don't necessarily solve the problems moor is trying to solve. I don't see moor as a full-scale ORM but rather a convenience layer around sqlite3 that introduces plenty of abstractions without hiding the relational aspects of sqlite3. To me, starting to automatically resolve joins at runtime feels like a step where moor stops being a database library and starts being an ORM that hides the underlying data model. 

If we start adding support for simple 1:n relations, users might expect proper support for more complicated topics like n:m relations that are much harder to solve generally. Moor's runtime is already fairly complex without having any ORM features, and most ORMs I know are really complicated by themselves.

So my general stance on this is that I don't want to work on these features and I probably don't have time to maintain them in this project either. If somebody wants to build an ORM with these features on top of moor, then I am definitely willing to help. Sorry for the unsatisfying answer, but that's my general take on features like this.

**Comment by sharoonamjid** [comment]
Ok 😢 I thought you will like my idea, even I also saw in the dream that you have accepted my suggestion and started working on it, even I thought people will leave amazing reactions (♥️ 🚀👍👌👀) to my suggestion.. I thought @simolus3 will pin this issue and all community even google, flutter and all known developers community will start to working on it. But....... I'm just kidding 😜 Thank you @simolus3 for what you have already done for this community and continually making your best effort to respond in very helpful way. I respect you sir. Good luck for ahead. Bless you.
