### ISSUE TITLE
Global type converters

### ISSUE THREAD

**Issue by westito** [simolus3/moor#1236]
**Is your feature request related to a problem? Please describe.**
I use "Property" wrapper class for fields (ex.: Property\<String\> name;), because Dart can't pass by reference. Now I use type converters for it. Would be nice to have global type converters. For ex. all 'String' column has the same type converter without declare it explicitly at column definition.

**Describe the solution you'd like**
Database or table level type converter definition:
```
@override
TypeConverter stringConverter() => const TypeConverter();
```

also a `defaultConverter()` option at definition to disable for specific column

**Comment by simolus3** [comment]
> I use "Property" wrapper class for fields (ex.: Property<String> name;), because Dart can't pass by reference

It sounds like you essentially want mutable data classes? You can enable the `mutable_classes` [build option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/) if you do. I don't generally recommend that, but using that build option beats introducing wrapper classes for everything. It's not a true reference but it may help if you need mutability.

Also, I'm reluctant to add global type converters because it breaks incremental rebuilds. If there's a really compelling reason to do so I can try to come up with something clever, but if analyzing a table requires knowing some global information that could be anywhere, the generator would be a  whole less efficient. It's not particularly efficient now either, but adding global implicit state would prevent a lot of optimizations.

**Comment by simolus3** [comment]
Also I've seen that you found custom data classes, so you could have something like this:

```dart
@UseRowClass(MyRow)
class MyTable extends Table {
  TextColumn get foo => ...
}

class MyRow {
  final Property<String> foo;

  MyRow(String foo): foo = Property(foo);
}
```

No type converters necessary :)

**Comment by westito** [comment]
Thanks for advice. I need wrapper classes to use in general functions. For ex.: I have a "getTextControllerForProperty" method and simply pass the field as reference by "getTextControllerForProperty(model.name)". Instead of `(val) => model.name = val` or something like that. So the wrapper class is necessary for me.
