### ISSUE TITLE
Add converter to Generated*Column so we can pass unconverted types

### ISSUE THREAD

**Issue by North101** [simolus3/moor#1268]
If I have this type:
```dart
enum DeckState {
  local,
  remote,
  deleted,
}

class DeckStateConverter extends TypeConverter<DeckState, String> {
  const DeckStateConverter();

  @override
  DeckState? mapToDart(String? value) {
    if (value == null) return null;

    return DeckState.values.firstWhereOrNull((e) => e.toString() == value) ?? DeckState.local;
  }

  @override
  String? mapToSql(DeckState? value) {
    if (value == null) return null;

    return value.toString();
  }
}
```

I need to do:
```dart
db.deck.state.equals(const DeckStateConverter().mapToSql(DeckState.deleted)).not()
```

It'd be nice if the converter and type was passed to `Generated*Column` which would let us do:
```dart
db.deck.state.equalsValue(DeckState.deleted).not()
```

**Comment by North101** [comment]
Alternatively, if you just pass the type then we could use the extensions on it. e.g.
```dart
extension on GeneratedTextColumn<TypeConverter<DeckState, String>> {
   Expression<bool> equalsValue(DeckState? compare) => const DeckStateConverter().mapToSql(compare);
}
```

**Comment by simolus3** [comment]
I like the idea, but thinking about this I see some practical issues.

For instance, we could have two text columns mapping to the same Dart type with two different type converters. This may seem unrealistic, but if we end up having one `TypeConverter<Object, String>` and one `TypeConverter<DeckState, String>` then there's room for conflicts. So this should probably be some instance method on the column and not an extension.

Moor currently encourages users to use classes like `IntColumn`, `TextColumn` etc. in their table definitions. I don't remember my reasoning here, but now I think it may make sense to encourage users to write `Column<int> get id => ...` instead. We could then have a single, generic, `GeneratedColumn<T>` implementation. An obvious benefit is that we can have `Column<int>` vs. `Column<int?>` to encode nullability. 
There could also be a `GeneratedColumnWithConverter` subclass providing the right `equalsValue` method for its converter. The generator would take care of using this class for the appropriate columns, and we wouldn't need one such class for every type.

This may not even have to be a breaking change since we can do `typedef IntColumn = Column<int>` in Dart 2.13 :thinking: I'll play around with this a bit and see if this approach could work.

**Comment by North101** [comment]
I was wondering if we even need a `equalsValue`. We could just use the `equals` directly.

**Comment by simolus3** [comment]
> I was wondering if we even need a `equalsValue`. We could just use the `equals` directly.

I'd prefer a text column with a converter to stay an `Expression<String>` so that all the other extensions still work. So I think it may be better to add another method that applies the converter.

I've added a `GeneratedColumnWithTypeConverter` class in f231a631a48e4c241ae543de206b9061ab911ebb, the generator will use it when appropriate.
