### ISSUE TITLE
Type converters : Want to create class instead column of JSON.

### ISSUE THREAD

**Issue by pratikbutani** [simolus3/moor#1269]
I saw the functionality of **Type Converters** that is storing more complex data in columns with type converters but I want to create a separate table of that data.

Simply, I am getting a list of Customers from the server and I want to store it in the database. I have created a model class of that JSON using **json_serializable: ^4.1.3** package.

Can you please give me the shortest way to create that class to a database table? I want it as a table, not as a column.

**Comment by simolus3** [comment]
I would write another moor table class based on the columns of your customer class. You can use [custom row classes](https://moor.simonbinder.eu/docs/advanced-features/custom_row_classes/) to make moor use your existing class instead of generating a new one.
To reference a customer, you'd then reference its id and use [joins](https://moor.simonbinder.eu/docs/advanced-features/joins/#joins) to load it in a query. I hope that helps!

**Comment by AlexKenbo** [comment]
> I would write another moor table class based on the columns of your customer class. You can use [custom row classes](https://moor.simonbinder.eu/docs/advanced-features/custom_row_classes/) to make moor use your existing class instead of generating a new one.
> To reference a customer, you'd then reference its id and use [joins](https://moor.simonbinder.eu/docs/advanced-features/joins/#joins) to load it in a query. I hope that helps!

Could you show an example with join?
There are Loads and Boxes tables. The box has a field - CargoId
There are custom row class Cargo and row class Box.
The Cargo class has a boxes field.

How can I use join to make an object out of 2 base tables?
Cargo with boxes filled? Without the With class (CargoWithBoxes), that is, immediately:
Cargo {
String id;
List <Box> boxes;
}

**Comment by simolus3** [comment]
Fetching your `Cargo` class requires more than one SQL query. You can take a look at the [relations example](https://moor.simonbinder.eu/docs/examples/relationships/) for more information.

**Comment by AlexKenbo** [comment]
> Fetching your `Cargo` class requires more than one SQL query. You can take a look at the [relations example](https://moor.simonbinder.eu/docs/examples/relationships/) for more information.

We have a lot of nesting
Route> Client> Cargo> Box> Item

Have to constantly do Something With Other

**Comment by AlexKenbo** [comment]
@simolus3 
We switched from noSql to sql - since it is easier to make changes to the data at the lower levels, by id.

But the application consumes Graph data by the model - and it's not so easy to send it :)

We need:

```
Route {
 String id;
 List<Client> clients;
}

Client {
 String id;
 List<Cargo> cargos; 
}

Cargo {
  String id;
  List<Box> boxes;
}

Box { 
 String id;
 List<Item> items;
}
```

How easy would it be to build such a tree of objects from relational tables?

**Comment by simolus3** [comment]
Unfortunately, SQL result sets don't nest. So while SQL is great for searching through (potentially deeply nested) data, individual queries can't have lists as columns and must be rather flat.

You can use multiple SQL queries to build a tree (or graph) of objects, but you it can be a bit of a hassle since you need to do the final merging in Dart.
