### ISSUE TITLE
Does Moor support offline-online sync mode across multi devices, like mobync?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1285]
Like [Mobync](https://github.com/mobync/flutter-client)

**Comment by simolus3** [comment]
Moor doesn't support offline-online synchronization out of the box. It's essentially a wrapper for sqlite3, so I don't think we should provide network synchronization and other complex features in this library. You can take a look at https://github.com/simolus3/moor/issues/136 for a further discussion, but in the end I think you'll have to implement synchronization logic yourself.

**Comment by jims57** [comment]
Do you have any good suggestion about libraries which can be used in Dart for this purpose(offline-online sync logic across multi devices)?

**Comment by simolus3** [comment]
I'm not aware of a package that does everything for you, since it's a complicated topic.

A good abstraction for this purpose are conflict-free replicated datastructures. There are some good talks on them like [this one](https://www.youtube.com/watch?v=DEcwa68f-jY). There's a [crdt](https://pub.dev/packages/crdt) package in pub, but I've never used that. Maybe you could use that together with moor somehow.

If you have a simpler synchronization behavior, you could also store when a row has last been read from a server and just attempt a refresh if you have connectivity and some time has passed. For locally-created rows, you could store whether they have been written to a server and do if necessary.

**Comment by jims57** [comment]
@simolus3 Sorry to bother you again since this bug has has been closed. 

As you can see [Mobync](https://github.com/mobync/flutter-client) client is used along with **sqlite** rather than **moor**.

My question is that if **Moor** is built on the top of sqlite like? If yes, is it possible to make **mobync** able to work with **moor**?

We are considering using **mobync**. Thanks.

**Comment by simolus3** [comment]
It looks like you can implement a moor-based `MobyncClient` client and use that, yes. I've never tried that, but I don't see why it shouldn't be possible. If you have specific questions on how to write a moor-based implementation for that I can try to answer those as well, but I can't write all of the implementation for you ;)

**Comment by jims57** [comment]
@simolus3 Thanks, apart from mobync, we have other choice, once we decide to use it and have questions, I will contact you. Thank you in advance.

**Comment by srix55** [comment]
@jims57 what did you settle on?

**Comment by aldycool** [comment]
Hi,

I've built a synchronization framework that runs on top of Moor library called `netcoresync_moor`. You can find the [repository here](https://github.com/aldycool/NETCoreSync/tree/master/netcoresync_moor) and the [pub.dev package here](https://pub.dev/packages/netcoresync_moor). This framework allows you to have local Moor databases on each user's device and synchronize them to a centralized database hosted on the server.

This framework actually was built for Xamarin technology a couple years ago, and recently ported to Flutter because our team has started moving to Flutter for building our products. And we've chosen to built it on top of Moor (after having insightful discussions with @simolus3, thanks!) because I think Moor is the perfect choice for proven database framework in Flutter right now. Give it a try and feel free to ask questions, thanks.

**Comment by jims57** [comment]
@aldycool Thank you for your framework.
