### ISSUE TITLE
Could not read tables from @UseMoor annotation

### ISSUE THREAD

**Issue by doomkin** [simolus3/moor#1301]
After update **moor** and **moor_generator** to 4.3.2:
```
flutter packages pub run build_runner build --delete-conflicting-outputs
```
```
[WARNING] moor_generator:moor_generator on lib/db/db.dart:
There were some errors while running moor_generator on package:timesheets/db/db.dart:
[INFO] moor_generator:moor_generator on lib/db/db.dart:line 199, column 7 of package:timesheets/db/db.dart: Could not read tables from @UseMoor annotation! 
Please make sure that all table classes exist.
    ╷
199 │ class Db extends _$Db {
    │       ^^
    ╵
```
I didn't correct the annotation, all the classes listed in the annotation are present in `db.g.part`
```
@UseMoor(
  include: {'model.moor'},
  tables: [
    Orgs,             
    Schedules,      
    ScheduleDays,  
    Holidays,        
    Groups,      
    Persons,         
    GroupPersons,    
    Attendances,   
    Settings,  
  ],
  daos: [
    OrgsDao,
    SchedulesDao,
    ScheduleDaysDao,
    HolidaysDao,
    GroupsDao,
    PersonsDao,
    GroupPersonsDao,
    AttendancesDao,
    SettingsDao
  ]
)
class Db extends _$Db {
```

**Comment by simolus3** [comment]
Interesting. Do you get any analysis warnings on the `@UseMoor` annotation? If moor is able to generate everything correctly you're probably importing the tables into the moor file, right? That warning means that moor can't read the `tables` part at all. It probably hasn't been able to do that before either, it just silently ignored an error condition in earlier version.

> all the classes listed in the annotation are present in `db.g.part`

Are you adding generated table classes to `@UseMoor`? There's no need to do so, moor will generate code for any table accessible in a moor file you're including. Moor can't see "db.g.part" because it's the one creating that file. So if you reference a moor-generated class in `@UseMoor` the generator will think its an unresolved reference.

**Comment by doomkin** [comment]
I deleted the list of tables and the message disappeared, thank you!
```
@UseMoor(include: {'model.moor'})
class Db extends _$Db {
```
