### ISSUE TITLE
Error when using moor classes in combination with freezed

### ISSUE THREAD

**Issue by peterhijma** [simolus3/moor#1314]
**Note:** I'm not sure where to file the bug. Here or at the https://pub.dev/packages/freezed package.

I'm trying to generate a class with the `@freezed` decorator. This works fine except when the class has a moor class as an attribute. So something like this:

```dart
@freezed
class FooModel implements _$FooModel {
  factory FooModel({
    SomeMoorDataClass? bar,
  }) = _FooModel;
}
```

Throws this error:

```
The parameter `bar` of `FooModel` is non-nullable but is neither required nor marked with @Default
   ╷
16 │     SomeMoorDataClass? bar,
   │         ^^
   ╵
```

The parameter is **nullable**!

Thanks in advance!

**Comment by simolus3** [comment]
Due to the way Dart's build system works, special setup may be necessary to use the outputs of one builder (moor) in another builder (freezed).

The [docs](https://moor.simonbinder.eu/docs/advanced-features/builder_options/#using-moor-classes-in-other-builders) contain an generic example where two builders are running on the same input file. If you're only using moor and freezed on distinct inputs, you can use a simpler approach described here: https://github.com/simolus3/moor/discussions/1266.
