### ISSUE TITLE
How to generate methods for classes that are not from the database?.

### ISSUE THREAD

**Issue by nnior** [simolus3/moor#138]
Hi, I am starting to use 'wasteland' and it is a very good tool.

Now I have found myself in the need to be able to generate the `copyWith`, `fromJson`, `toJson` methods, to a class that is not a database table, for example:

```dart
// Order, Item and Image are dataclass
class MyOrderDto {
  Order order;
  List<Item> itemList;
  List<Image> imageList;
}
```
How could I convert my `MyOrderDto` class to a `dataclass` and have the methods `fromJson`, `toJson`, `copyWith`, and more ...

Thanks and regards 😃

**Comment by simolus3** [comment]
Thanks for your request. Unfortunately, I don't think moor could help you with that. We only generate classes based on your database tables, we don't generate utility methods to do that for other classes.

If you're looking for similar functionality, you could take a look at the [`built_value`](https://pub.dev/packages/built_value) package. The first linked articles (["`built_value` for Immutable Object Models"](https://medium.com/@davidmorgan_14314/darts-built-value-for-immutable-object-models-83e2497922d4#.48dyezxcl) and ["`built_value` for Serialization"](https://medium.com/@davidmorgan_14314/darts-built-value-for-serialization-f5db9d0f4159#.h12y94wu7)) might also be helpful for you.

Sadly, you currently can't use data classes generated by moor in `built_value` objects because of a bug in the build package. We have #89 to track that moor, you can subscribe that issue to receive updates on that front. I would also suggest upvoting https://github.com/dart-lang/build/issues/2389 which is blocking us here. If you have any more questions, please let me know!
