### ISSUE TITLE
Isolate doesn't stop when using shutdownAll

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#1406]
I noticed that when using `shutdownAll` the isolate it's kept around (the VSCode Call stack menu shows that). Is this a bug, or is there any reason why it can't be killed?

**Comment by simolus3** [comment]
Good catch! I'd definitely consider this a bug, especially when using `MoorIsolate.spawn` which effectively can't be killed otherwise. I've added a parameter when using `MoorIsolate.inCurrent` (because here it might be a breaking change to alter the behavior), but isolates spawned to `MoorIsolate.spawn` should definitely stop after `shutdownAll`. I've added a fix in bcd8541a4bd9d3700861d2ada28872eda7687eac.

**Comment by davidmartos96** [comment]
Great! Thank you!!
