### ISSUE TITLE
[sqlparser] indexed column 'action' makes the parser crashing

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/moor#1415]
I'm trying to parse an index with an indexed column named 'action' like this.
```dart

  void parseCreateIndex() {
    String sql = "CREATE UNIQUE INDEX ee1 ON test ( action COLLATE NOCASE ASC)";
    sqlparser.CreateIndexStatement test = _parseSQLToCreateIndexStmt(sql);

    print(test.toString());
  }

  sqlparser.CreateIndexStatement _parseSQLToCreateIndexStmt(String sql) {
    sqlparser.SqlEngine engine = sqlparser.SqlEngine();

    sqlparser.CreateIndexStatement result;
    result = engine.parse(sql).rootNode as sqlparser.CreateIndexStatement;
    return result;
  }
```

And I have an error, I've detected that is caused by the column 'action'

![image](https://user-images.githubusercontent.com/54275508/129743132-49e4f5c7-d924-43dd-a1fb-d30574a1c707.png)

**Comment by simolus3** [comment]
Thanks for the report.

You can see what's going wrong in the parser more easily by printing the error messages:

```dart
final engine = sqlparser.SqlEngine();
final result = engine.parse(sql);
if (result.errors.isNotEmpty) {
  // sqlparser found syntax errors, report them
  result.errors.forEach(print);
  throw 'todo: report errors';
}

return result.rootNode as sqlparser.CreateIndexStatement;
```

In this case, this prints:

```
line 1, column 35: Error: Could not parse this expression. Note: This is a reserved keyword, you can escape it in double ticks
  ╷
1 │ CREATE UNIQUE INDEX ee1 ON test ( action COLLATE NOCASE ASC)
  │                                   ^^^^^^
  ╵
```

And indeed, parsing `("action" COLLATE NOCASE ASC)` works as expected :)

sqlite3 interprets keywords as identifiers in some scenarios, but the rules aren't documented and hard to reproduce for me. If I remember correctly, sqlite3's documentation recommends to escape keywords instead of relying on this behavior. As this behavior is hard to copy for me (and complicates the parser a lot), you'll have to escape identifiers if they have the same lexeme as a keyword.

**Comment by MobiliteDev** [comment]
Thank you very much for explainations and details to get more details on errors.

I've made something to test if a column is a keyword and added double quotes automatically in my code.
