### ISSUE TITLE
[sqlparser] crashes on CREATE TABLE with default values in ""

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/moor#1416]
If you try to parse this:
```dart
void parseCreateTable() {
    String sql = 'CREATE TABLE test (type TEXT DEFAULT "My default value")';
    sqlparser.CreateTableStatement test = _parseSQLToCreateTableStmt(sql);

    print(test.toString());
  }

  sqlparser.CreateTableStatement _parseSQLToCreateTableStmt(String sql) {
    sqlparser.SqlEngine engine = sqlparser.SqlEngine();
    sqlparser.CreateTableStatement result;
    result = engine.parse(sql).rootNode as sqlparser.CreateTableStatement;
    return result;
  }
```
You have an error because " for default value is not accepted (but you can use it in SQLite)

![image](https://user-images.githubusercontent.com/54275508/129751151-eed0d239-9006-4666-8157-7a0369797fee.png)

**Comment by simolus3** [comment]
This works because sqlite3 interprets identifiers with double quotes as strings when necessary. This is generally [considered to be a mistake](https://www.sqlite.org/quirks.html#dblquote). In the sqlite3 from `sqlite3_flutter_libs` for instance, this would not be accepted because we use the recommended compile-time options which disable this misfeature.

In `sqlparser`, I made the decision to not accept this feature either. It's a bad practice to rely on it and it would complicate the parser a lot. The parser reports an acceptable error here, and then returns an `InvalidStatement` which is the expected behavior.

Using single quotes will work as expected.

**Comment by MobiliteDev** [comment]
Thank you, I've found a workaround in order to not have double quotes,
