### ISSUE TITLE
Windows - Database encryption not working

### ISSUE THREAD

**Issue by KiraKmp** [simolus3/moor#1448]
```dart
  if (Platform.isWindows) {
    open.overrideFor(OperatingSystem.windows, _openOnLinux);
    final db = sql.sqlite3.openInMemory();
    db.dispose();
    final file = File(
        "$appDBFilePath");
    final executor =
        VmDatabase(file, logStatements: logStatements, setup: (rawDb) {
      rawDb.execute("PRAGMA key = '$dbKey';");
    });
    return executor;
  }
```

I am trying to encrypt the DB using pragma key ,it's working in android platform but does not encrypt the database in windows. I am able to open the DB without giving any password in windows 
 
```
  if (Platform.isIOS || Platform.isAndroid) {
    final executor = LazyDatabase(() async {
      final dbFile = File(appDBFilePath);
      return VmDatabase(dbFile, logStatements: logStatements, setup: (rawDb) {
        rawDb.execute("PRAGMA key = $dbKey;");
      });
    });
    return executor;
  }
```

**Comment by simolus3** [comment]
Did you follow the advice from [here](https://moor.simonbinder.eu/docs/platforms/#windows)? You need a compiled `sqlcipher.dll` that you include next to your application. You also need to provide an opening override so that the `sqlcipher.dll` that you ship with your app will be opened.

You can compile SQLCipher by checking out [this repo](https://github.com/sqlcipher/sqlcipher). I don't know if there are any prebuilt libraries for Windows.
