### ISSUE TITLE
Customize data class name for .moor file tables

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#147]
Something similar to dart table's `@DataClassName` for .moor files would be really nice. For example, I'd like customize `CREATE TABLE status ...` to generate `Status` instead of `Statu`, and `CREATE TABLE config ...` to generate `Config` instead of `ConfigData`.

**Comment by simolus3** [comment]
I think introducing another table constraint into our extended sql grammar could provide a decent solution here.
```sql
CREATE TABLE status (
  -- some columns,
  DATA CLASS NAME "Status"
)
```
Downside might be additional complexity during analysis (we'd have to check that only one such constraint appears in the table). For users, the constraints can also be harder to find because they could appear anywhere in a table declaration, there is no fixed place to look at. So maybe we could use
```sql
CREATE TABLE status (
  -- some columns
) AS "Status"
```
I would prefer `CREATE TABLE status AS "Status" ()`, but that conflicts with the `CREATE TABLE AS <select-statement>` syntax.

**Comment by Mike278** [comment]
Would something like this be weird, given that it’s optional? 
```sql
Status:
CREATE TABLE status ( -- columns ):
```
Just thinking of something similar to the named crud statement syntax

**Comment by simolus3** [comment]
I'm not sure about that syntax - it seems consistent with the syntax for queries, but on the other hand it doesn't feel quite right. We require that in a moor file, the components appear in the following order: imports, create table statements, named queries. If we allow named create table statements, that might be confusing to users (and introduces additional complexity in the parser). I think a postfix `AS name` could work better. If we ever support something like
```sql
CREATE TABLE view AS (SELECT * FROM other) AS ViewedRow;
```
it looks a bit weird, but it looks better on regular `CREATE TABLE` statements, which are most common.

> I also just realized this Status example will conflict with the generated table info class won’t it? I guess I can just suffix with _: `Status_`

As the data class name can be chosen and the info class name can't, I feel like it's the responsibility of the generator to rename the info class if there's a clash.

**Comment by simolus3** [comment]
Should work on `develop` - I went for the `CREATE TABLE (...) AS xyz` syntax. When the data class name for a table is equal to its info class name, we now append a "Table" to the later.
