### ISSUE TITLE
Is there a way to combine tables from different packages into a single database?

### ISSUE THREAD

**Issue by jeannelim** [simolus3/moor#1554]
I want to create a Flutter application that is modular like each application module would have its own package, and each package would have its own tables and daos. When I use the packages I want to be able to create a database with the tables from each package so I can join the tables. Is this doable with drift?

**Comment by simolus3** [comment]
At the moment, this is not really possible since Drift will generate all table classes into a single Dart file. You could have a central package into which the code is generated to support this (other packages would depend on the central package to define daos, and the central package would depend on other packages to access their tables).

#490 would change this.
