### ISSUE TITLE
access sqlite exception

### ISSUE THREAD

**Issue by selvam920** [simolus3/moor#1582]
i am trying access existing database from USB Pendrive in android 11, i'm getting below error.

SqliteException(4618): disk I/O error, disk I/O error (code 4618)
  Causing statement: PRAGMA user_version;

**Comment by simolus3** [comment]
It could be that sqlite3's locking is somehow not working on the USB stick for whatever reason, probably the device behaving weirdly. Are there other apps that might be reading the same database? Or are you opening the database on multiple threads / isolates maybe?

Also, this looks like a sqlite3 issue to me so I don't think there's much drift can do about it. I'm happy to help you with it, but I'll close this issue since it doesn't look drift-related.
