### ISSUE TITLE
weird bug :(

### ISSUE THREAD

**Issue by abehbatre** [simolus3/moor#1588]
idk how to explain, happens when a transaction is successful, suddenly getx removed all active controllers .
for detail see video below.

![image](https://user-images.githubusercontent.com/36602270/146655349-e389c3bc-018c-421b-940e-947128e441d2.png)

```
dependencies:
  get: ^4.1.4
  drift: ^1.1.0
  sqlite3_flutter_libs: ^0.5.2
  path: ^1.8.0
```

```
Future deposit(User selectedUser, double amount) async {
    return transaction(() async {
      try {
        // update current user balance
        await (update(users)..where((tbl) => tbl.username.equals(selectedUser.username))).write(UsersCompanion(
          balance: Value(selectedUser.balance + amount),
        ));

        // insert to transactionLog
        var log = TransactionLog(
          id: randomBetween(100, 123456789),
          from: selectedUser.username,
          to: selectedUser.username,
          amount: amount,
          description: 'deposit',
          createAt: DateTime.now(),
        );
        await createOrUpdateTransactionLog(log);
      } catch (e) {
         print('error => $e');
      }
    });
  }
```

main.dart
```
 test() async {
    await db.deposit(dataUser.value, double.parse('123'));
  }
```

https://user-images.githubusercontent.com/36602270/146655235-22adc5fd-5139-40ca-9d1f-b362c8103e34.mp4

**Comment by simolus3** [comment]
Sorry, but I think this is probably a getx problem that I can't do much about. I also haven't used getx, so I can't really help you debug this further :( Maybe you could set a breakpoint in `onDelete` and see the trace causing it to get called.

If it turns out to be drift doing something weird here I'm happy to take another look into that, but I don't have nearly enough information to act on this. If you find out more please let me know.
