### ISSUE TITLE
Custom statement inconsistency between web and mobile for multiple SQL statements

### ISSUE THREAD

**Issue by reinhardbluelab** [simolus3/moor#1627]
Drift version: 1.0.1

Drift mobile's `customStatement` allows execution of multiple SQL statements in a single call. Drift web's `customStatement` only executes the first SQL statement and the rest seem to be ignored. Not sure which one is _correct_, but I guess they should ideally behave the same. Our current workaround is to just execute a single statement at a time. 

Alternatively, if this inconsistency is expected, maybe it could be added as a note in the documentation?

**Comment by simolus3** [comment]
Actually it looks like this has to do with `customStatement` having parameters or not? On a `NativeDatabase`, if it has parameters, we prepare it first, which at the moment will actually _ignore_ everything after the first statement (uh oh). Otherwise we'll execute it directly (using `sqlite3_exec`), which can run multiple statements.

Reading [this](https://github.com/sql-js/sql.js/blob/997d56fb954b63e76cf8d549c4660c972381768e/src/api.js#L852-L862) and [this](https://github.com/sql-js/sql.js/blob/997d56fb954b63e76cf8d549c4660c972381768e/src/api.js#L1035), it looks like sql.js is doing the same thing. Did you encounter this behavior with or without parameters?

Either way, ignoring parts of the statement is an oversight in the implementation and not a great default behavior. IMO we can't really run multiple statements with parameters (it gets confusing when two statements have parameters with the same name), so I think we should throw an exception instead. I have fixed `NativeDatabase` in 913fb1c9e1a43532435281365b44d36a7c2980b2.

**Comment by simolus3** [comment]
I actually had to revert that fix because it triggers a false-positive for whitespace after a statement (e.g. `SELECT 1;  `). I'm not sure what the best way to fix would be. I'll have a look at what other sqlite3 wrappers are doing here, but it seems at least some of them (like sql.js) have the same issue.

**Comment by reinhardbluelab** [comment]
We were using it without parameters. I hope this is not causing too much pain; just thought you would like to know about it at least.

Thanks for all your hard work on this library!

**Comment by simolus3** [comment]
Ok, I found the source of confusion for the web implementation. When we call `run`, we always provide arguments (falling back to an empty list if `customStatement` was called without providing parameters). sql.js takes the route through prepared statements if the arguments are truthy (which an empty list is). So the easy fix for consistency is to just pass undefined instead of an empty list. This will allow running multiple statements on the web, provided they don't contain parameters.

I also figured out how to properly detect trailing data in SQL statements, ignoring harmless whitespace and comments. So now we can do a proper misuse detection with a `NativeDatabase`, the web implementation will behave weirdly (only consider the first statement) if parameters are present. We can't really work around that decision in sql.js without much effort, so that's the way it is. At least you'd probably catch this error if testing on multiple platforms.
