### ISSUE TITLE
Support creating prepared statements

### ISSUE THREAD

**Issue by NicolaVerbeeck** [simolus3/moor#1640]
**Is your feature request related to a problem? Please describe.**
When inserting a huge number of rows, a prepared statement could speed up the operations by skipping the compiler overhead. Currently there is no interface available to do this

**Describe the solution you'd like**
Add a way to create and execute prepared statements on all possible executors/connection combinations.

**Comment by simolus3** [comment]
It looks like `sqflite` does not support preparing individual statements, so this API would not be available on all implementations.

>  When inserting a huge number of rows, a prepared statement could speed up the operations by skipping the compiler overhead. Currently there is no interface available to do this

A [batch](https://drift.simonbinder.eu/api/drift/databaseconnectionuser/batch) is doing exactly that! Across all implementations, it avoids re-compiling statements. Is this your primary use-case for prepared statements? Are batches missing something you need for performance?

**Comment by NicolaVerbeeck** [comment]
I was under the impression that a batch.insertAll still just calls insert for every item and thus not pre-compile it

**Comment by simolus3** [comment]
Internally, a batch keeps a set of a SQL statements that need to be prepared and a sequence of `(statement, parameter)` pairs to run. This is happening [here](https://github.com/simolus3/moor/blob/17d49fcc07102b193b8018f2daf6e2da9cd5709c/drift/lib/src/runtime/api/batch.dart#L151-L164), the method is called by all other methods on `Batch`.

The native database implementation will not prepare more statements than necessary, other implementations behave similarly:

https://github.com/simolus3/moor/blob/17d49fcc07102b193b8018f2daf6e2da9cd5709c/drift/lib/src/ffi/database.dart#L182-L200

I'll close this since batches should address the performance concern. If you have use-cases that require custom control over prepared statements please let me know and we'll figure out something that works for that.
