### ISSUE TITLE
I want to perform select, insert, etc. operations on the old database before the new version of the database is updated. How do I do it? 

### ISSUE THREAD

**Issue by ddxl123** [simolus3/moor#1647]
I want to perform select, insert, etc. operations on the old database before the new version of the database is updated. How do I do it?

**Comment by simolus3** [comment]
I'm not sure I understand what you mean? Do you want to run statements in a migration? Because you can just do that:

```dart
MigrationStrategy get migration {
  return MigrationStrategy(
    onUpgrade: (m, old, updated) async {
      final result = await select(myTable).get();
      // run migration
    }
  );
}
```

One common problem is that the structure of your generated table classes doesn't match the actual schema in the database before a migration. Drift contains tools to [export a schema and keep generated versions of old table classes](https://drift.simonbinder.eu/docs/advanced-features/migrations/#exporting-the-schema) which can solve this. However, it's probably easier to just write custom SQL in migrations.

------

Also, this isn't a request for an enhancement. Please consider creating a discussion for questions next time, that makes it easier to answer and discuss. Thanks!

**Comment by ddxl123** [comment]
> 

But the documentation says: "You can also add individual tables or drop them - see the reference of Migrator for all the available options. You can't use the high-level query API in migrations - calling select or similar methods will throw."
https://drift.simonbinder.eu/docs/advanced-features/migrations/

So what exactly does the documentation say "You can't use the high-level query API in migrations - calling select or similar methods will throw."?

**Comment by simolus3** [comment]
The docs are wrong here, thanks for letting me know! I have improved the page in a16b7d3d3f6a8469414f1f45a99e570067d7794e to point out that these methods generally work, even though they have to be used carefully.

**Comment by mikemoore13** [comment]
@simolus3 
is the insert also supposed to work ? it seems that the inserted data are not persisted after the method is executed even if it returns no error

```
for (var p in dtos) {
        var updated = dic.putIfAbsent(p.id, () => buildId());
        await into(modelDto).insert(ModelDtoCompanion(
          id: Value(updated),
          name: Value(p.name)
        ), mode: InsertMode.insertOrReplace);
      }
```

the select works but the insert does nothing here when running under onUpgrade

**Comment by simolus3** [comment]
Yes, inserts and other writes are supposed to work in migrations too. The example uses them as well: https://github.com/simolus3/drift/blob/fae81d045666fc849eea080d0b7dd77cc69d2e79/drift/example/main.dart#L79-L89

That works, and from a quick test running inserts in `onUpgrade` seems to work as well. You can enable `logStatements: true` to log the statements created by drift, do you see the `INSERT OR REPLACE` there?

**Comment by mikemoore13** [comment]
I confirm it is working. 
Thanks for the advice about the logs
