### ISSUE TITLE
About update(todos).replace(entry)

### ISSUE THREAD

**Issue by ddxl123** [simolus3/moor#1665]
```
Future update(Todo entry) {
  return update(todos).replace(entry);
}
```

`Todo`  attribute value is automatically set to `final`, I can't change attribute value to `entry` .
so, `replace (entry)` should be :

```
replace( oldEntry.copyWith(category:newCategory) )
```

Is this correct?

However, from it can be seen:
`Todo newEntry = oldEntry.copyWith(category:newCategory) ` --- `newEntry` and  `oldEntry`  is two different objects. 
Executed `replace`, `oldEntry` object will not be updated.

So,
When the `oldEntry` object need to be updated,
If it is a `List<Todo> entries`, I must overwrite the `oldEntry` with `newEntry`.
This will affect all widgets that reference `oldEntry`.

**Comment by ddxl123** [comment]
I revised the content of the question.

**Comment by simolus3** [comment]
Essentially, I think this is a question of how data updates flow through your app? Most drift users, me included, prefer to be explicit about updates. That is:

- Most data structures (including row classes) are immutable, meaning that they only present a snapshot of the state.
- When states can change, this is made explicit, for instance by providing a `Stream<Todo>` instead of just a `Todo`.

So your widgets could simply be using a query stream and a `StreamBuilder` to always show the latest state. In this case, they would automatically be rebuilt when you call `replace` because drift will update the streams.

If that model is not what you prefer, you can also enable the `mutable_classes` [build option](https://drift.simonbinder.eu/docs/advanced-features/builder_options/), but in that case you still have to take care of updating widgets somehow.
