### ISSUE TITLE
how to get updates when some change or query fires in mobile database

### ISSUE THREAD

**Issue by Div-47** [simolus3/moor#1666]
i have a ui where i want to show a loader when the sql queries working in background. please help. i am using drift 1.0.0

**Comment by simolus3** [comment]
Drift mostly assumes that individual `SELECT`s used in streams load reasonably fast, so that a UI-level loader for them isn't necessary. There's no API also get notified when a stream is dirty.

However, you could use [`tableUpdates`](https://drift.simonbinder.eu/api/drift/databaseconnectionuser/tableupdates) to manually get notified when tables change and run expensive queries in response to that. With that you have all the information necessary to show a loading indicator before the query is finished.
