### ISSUE TITLE
SQL functions in where clause

### ISSUE THREAD

**Issue by minia68** [simolus3/moor#167]
Hi, can i use sql functions in where clause(`where upper(column1) = upper('value')`) without custom query?

**Comment by simolus3** [comment]
Moor doesn't provide a Dart api for sql functions (yet). It's a reasonable request though, I will look into that for moor 2.1

**Comment by simolus3** [comment]
I'll implement this as part of #195 after Dart 2.6 comes out with extension members. We're probably going to model sql functions with extensions as well (e.g. `column1.upper()` instead of `upper(column1)`). The latter is easier to discover through auto-complete, so we'll probably wait for Dart 2.6 (which looks like it's released soon).

**Comment by simolus3** [comment]
In the next version, we'll expose the `LOWER`, `UPPER` and `LENGTH` functions from Dart:
```dart
class Users extends Table {
  TextColumn get name => text()();
}

// ...
select(users).where((u) => u.name.upper().equals('TOM')) // SELECT * FROM users WHERE UPPER(name) = ?
select(users).where((u) => u.name.length.isSmallerThanValue(10)) // SELECT * FROM users WHERE LENGTH(name) < ?
```
