### ISSUE TITLE
How can one use Generic Foreign key relations as Django does?

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/moor#1697]
To avoid redundancy, I would like to have one table "Visitor" that can reference multiple different tables (not necessary all tables) through foreign key relations. Visitor table would hold ID (foreign key) of the other table entry and some kind of table ID to reference which table is connected with foreign key. Is it possible with moor/drift? Thanks

**Comment by simolus3** [comment]
No, it's not possible to "parameterize" table constraints like this. I'm not aware of a good way to express this in SQL, and drift tries to be a reasonably thing wrapper around SQL where possible. You could have two columns (one for the table name, one for the reference) and write the mapping / loading logic yourself. But you'd still miss out on consistency checks because (AFAIK) there's no way to express these constraints in SQL.
