### ISSUE TITLE
Unique constraint across multiple columns?

### ISSUE THREAD

**Issue by knyghtryda** [simolus3/moor#172]
I have a join table that contains foreign keys for table a and table b.  I'm trying to insure that a_id AND b_id are unique combined.  I actually have those columns set as a composite key but that doesn't seem to be doing the trick... Is there a way to do this?  The sqlite statement should just be `UNIQUE(a_id, b_id)` at the end of the table definition.

**Comment by simolus3** [comment]
Are you declaring the table in a `moor` file using SQL? That should work. We don't have a higher-level api for table constraints in Dart at the moment.

**Comment by knyghtryda** [comment]
I'm currently defining this in Dart.  Will this work in .moor for the 1.7.0 flutter_moor release?  I'm running into some issues on my side with the 2.0.0 release that needs to be sorted out before I can upgrade to it.  BTW, why did beforeOpen in MigrationStrategy lose the db parameter in 2.0.0?  Does that mean I can call `customStatement(..)` directly instead of `db.customStatement(...)`?

**Comment by simolus3** [comment]
> I'm currently defining this in Dart. Will this work in .moor for the 1.7.0 flutter_moor release

There are a lot of internal changes between 1.7 and 2.0, especially in the generator. It's hard to tell for sure. Anyway, I think you can get this behavior by overriding `customConstraints` in your table:
```dart
class MyTable extends Table {
  IntColumn get firstColumn => ...;
  IntColumn get secondColumn => ...;

  @override
  List<String> get customConstraints => [
    'UNIQUE (first_column, second_column)'
  ];
}
```

I would recommend to use the new moor files if you're writing sql manually, simply because we get to verify everything at compile time. But if you know what you're doing there's no reason to not do it in Dart :)

>  BTW, why did beforeOpen in MigrationStrategy lose the db parameter in 2.0.0? Does that mean I can call `customStatement(..)` directly instead of `db.customStatement(...)`?

Yes exactly - we dropped the parameter on `beforeOpen` and `transaction`. See the [changelog](https://pub.dev/packages/moor#-changelog-tab-) for details (this is explained in the "breaking changes" section). It makes the api simpler because you don't have to remember the `db.` prefix.

> I'm running into some issues on my side with the 2.0.0 release that needs to be sorted out before I can upgrade to it

Any issues apart from what's listed in the breaking changes? I'd love to hear them so I can make upgrading easier.

**Comment by simolus3** [comment]
Closing as this can be solved with the `customConstraints` override, which should also work in moor 1.7.

I don't think we're going to add a Dart api to express those kind of table constraints, the use-case doesn't show up very often and `customConstraints` provides an acceptable solution IMHO. I'm open to discuss this though, so if you want to have a better api for those just let me know.

**Comment by jasin** [comment]
This should be added to the documentation. The official documentation, [drift docs](https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/), shows two options and **neither work**.

**Comment by simolus3** [comment]
They should work, what doesn't work for you? If you're altering an existing table, did you set up a migration to apply the changes?
