### ISSUE TITLE
Recommended approach for copying and setting to null

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#174]
I have a query that returns a single row from a table. I'd like to make a copy of that row, set some fields to null, and insert it as a new row. Here's my current approach:
```dart
Foo foo = await getFooById(id);
FooCompanion copy = FooCompanion.insert(
  // Only copy desired fields
  field1: foo.field1,
  field2: foo.field2,
);
return insertFoo(copy);
```

Is there a way to specify the fields I *don't* want copied instead of listing the ones I do?

**Comment by simolus3** [comment]
I haven't tested it, but this should work:

```dart
final foo = await getFooById(id);

final resetSomeFieldsToNull = foo
  .createCompanion<FoosCompanion>(false)
  .copyWith(
    bar: const Value(null),
  );

await into(foos).insert(resetSomeFieldsToNull, orReplace: true);
```

Pretty ugly to make the `createCompanion` method generic, since it always returns a `FoosCompanion`. If I remember correctly this was some backwards-compatibility choice when companions were introduced, as `createCompanion` had to be a method on the `DataClass` superclass. I'll check if that method can be more friendly to users.

**Comment by Mike278** [comment]
Ah gotcha, the generic `<FoosCompanion>` signature was the part I was missing when trying to understand `createCompanion`. Thanks!

**Comment by simolus3** [comment]
FYI, as of 6e32e37dd7a8ae2999554c7f1a6b1dd8a0c424f8 we no longer include that type parameter - I must have been overthinking something when I added it. 
This is technically a breaking change, but `createCompanion` was marked as an internal method so I think we can release this without a major version bump. On develop, `Foo.createCompanion` would now be declared to return a `FoosCompanion` directly.
