### ISSUE TITLE
Example app does not run

### ISSUE THREAD

**Issue by a-ritwik** [simolus3/moor#179]
Error in database.dart of example app.

**Comment by simolus3** [comment]
It runs for me. What flutter channel are you using?

**Comment by a-ritwik** [comment]
Flutter 1.9.1+hotfix.4 • channel stable 
Dart 2.5.0

**Comment by a-ritwik** [comment]
On line 103 of database.dart, it tells 'The method map is not defined for for the class Future'

**Comment by simolus3** [comment]
This might be caused by an outdated version of `moor_generator`. The pubspec of the example contains dependency overrides to relative paths, but uses an old moor version. If you use version ^2.0.0 for both moor and moor_generator in the pubspec, get the packages and re-run the build, do the problems go away?

**Comment by a-ritwik** [comment]
Using version ^2.0.0 for moor_flutter and moor_generator and then rebuilding did not help. Since the error is only in categoriesWithCount(), so using customSelectStream for now.

**Comment by simolus3** [comment]
Weird how that works for me and somehow the builder emits different outputs for you :/ Can you post the generated implementation of `_categoriesWithCount`? I'll take another look tomorrow.

**Comment by a-ritwik** [comment]
Selectable<CategoriesWithCountResult> _categoriesWithCountQuery() {
    return customSelectQuery(
        'SELECT\n       c.id,\n       c.desc,\n       (SELECT COUNT(*) FROM todos WHERE category = c.id) AS amount\n     FROM categories c\n     UNION ALL\n     SELECT null, null, (SELECT COUNT(*) FROM todos WHERE category IS NULL)',
        variables: [],
        readsFrom: {categories, todos}).map(_rowToCategoriesWithCountResult);
  }

  Future<List<CategoriesWithCountResult>> _categoriesWithCount() {
    return _categoriesWithCountQuery().get();
  }

**Comment by simolus3** [comment]
I see. Do you have a `build.yaml` file next to the pubspec? There's [an option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/) called `compact_query_methods` that will make the generator only write the `Selectable` method and not the `Future` one. The example should run with these compact method, but I'm wondering why that didn't work for you because the [correct build.yaml](https://github.com/simolus3/moor/blob/master/moor_flutter/example/build.yaml) should be in the example folder.

**Comment by a-ritwik** [comment]
Somehow I missed build.yaml, my bad. It running now. This issue can be closed I think.
