### ISSUE TITLE
Column class clashes with Flutter

### ISSUE THREAD

**Issue by pkozlovskiy** [simolus3/moor#18]
The name 'Column' is defined in the libraries 'package:flutter/src/widgets/basic.dart' and 'package:moor/src/dsl/columns.dart'.dart(ambiguous_import)

**Comment by simolus3** [comment]
I see. If you change the import to
```dart
import 'package:moor_flutter/moor_flutter.dart' hide Column;
```
It should fix the problem, as you'll most likely won't be using the `Column` class from moor directly.

An alternative would be to put the database and the widget code in different files, so that no dart file imports both moor and flutter.

Let me know if that doesn't fix the issue, thanks!
