### ISSUE TITLE
How to not trigger data stream using `watch`when upserting/updating data which same columns? 

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/moor#1922]

**Comment by simolus3** [comment]
Drift's query stream are updated by a heuristic, you can't rely on them only updating when data has changed.

If your intention is to not update streams unnecessarily because you react to new events with side-effects, you may be able to use `.distinct()` (or perhaps `.distinct(const ListEquality().equals)` for streams with multiple rows) so that it only updates when data truly has changed.
If your idea is to now update streams too often because running the select statement itself is expensive, you can group multiple inserts in a batch or a `transaction`. They will only update streams once in that case.
