### ISSUE TITLE
Using a generated class as a returned type for a type converter results in a `dynamic`

### ISSUE THREAD

**Issue by ValentinVignal** [simolus3/moor#1928]
I'm using a `TypeConverter` with a generated class. As an example:

I have this `UserBuiltValue` class that uses [`built_value`](https://pub.dev/packages/built_value): 

```dart
abstract class UserBuiltValue
    implements Built<UserBuiltValue, UserBuiltValueBuilder> {
  String get name;

  UserBuiltValue._();

  factory UserBuiltValue([void Function(UserBuiltValueBuilder) updates]) =
      _$UserBuiltValue;
}
```

`built_value` generates a `UserBuiltValueBuilder` class.

I have this dummy table:

```dart
// user_table.dart
class UserTable extends Table {
  TextColumn get id => text()();

  TextColumn get user => text().map(const UserConverter())();
  TextColumn get userBuilder => text().map(const UserBuilderConverter())();
}
```

`UserConverter` just does a dummy conversion from `String` to `UserBuiltValue` (non-generated class).
`UserBuilderConverter` does a dummy conversion from `String` to `UserBuiltValueBuilder` (generated class).

The generated file by drift sets the type of `userBuilder` to `dynamic`.

```dart
class UserTableData extends DataClass implements Insertable<UserTableData> {
  final String id;
  final UserBuiltValue user;
  final dynamic userBuilder;  // <- It is `dynamic` here, I would like `UserBuiltValueBuilder`.

 // ...
}
```

---

How can I reuse generated classes from another builder?

You can checkout the code in this repo: https://github.com/ValentinVignal/flutter_app_stable/tree/drift/re-use-built-value

**Comment by simolus3** [comment]
The problem is that the order in which builders run is undefined, so it could be that the part file for the database is generated before `built_value` generates its classes that are used in the type converter. In this case, drift can't see those classes and has to fall back to `dynamic`.

An easy way to fix this (which seemed to work in your repository) is to split the builds into two targets: One for drift and one for the other builders. You can then use target dependencies to ensure builders run in the order in which they should be running. In your app, I was able to fix this by creating a `build.yaml` file with this content:

```yaml
targets:
  $default:
    sources:
      exclude: ['lib/database.dart']

  drift:
    dependencies: ['$default']
    sources:
      - lib/database.dart
```

**Comment by ValentinVignal** [comment]
Perfect, thank you for the quick answer

**Comment by TobiDevloft** [comment]
Hi @simolus3, I'm having a similar issue with a type converter resulting in a `dynamic Function()?` return type. This is the TypeConverter `game_pack_converter.dart`

```
class GamePackConverter extends TypeConverter<GamePack, String> {
  const GamePackConverter();

  @override
  GamePack fromSql(String fromDb) {
    String gameType = (json.decode(fromDb) as Map<String, dynamic>)['gameType'];
    if (gameType == GamePack.gameTypeToString(GameType.one)) {
      return GamePack.fromJson(json.decode(fromDb) as Map<String, dynamic>,
          gameType: GameType.one);
    }
    return GamePack.fromJson(json.decode(fromDb) as Map<String, dynamic>,
        gameType: GameType.two);
  }

  @override
  String toSql(GamePack value) {
    return json.encode(value.toJson());
  }
}
```

And this is the corresponding `gamepack_table.dart`:

```
@DataClassName("GamePackEntry")
class GamePackTable extends Table {
  IntColumn get id => integer().autoIncrement()();

  TextColumn get title => text()();

  TextColumn get name => text()();

  TextColumn get path => text()();

  TextColumn get releaseType => text()();

  TextColumn get data => text().map(const GamePackConverter()).nullable()();
}
```

In the generated `GamePackEntry` in `database.g.dart` the types are defined like this:

```
  final int id;
 // ....
  final dynamic Function()? data;
```

Instead of 

```
  final int id;
 // ....
  final GamePack data;
```


Can you point me into the right direction? Thanks a lot for your help and for maintaining this library!

**Comment by simolus3** [comment]
Your code looks correct to me, so I suspect this is an issue in drift.

To help me investigate this, could you send me the Dart language version you're using (the lower bound of `environment.sdk` in your pubspec)?

Also, there should be a file `.dart_tool/build/generated/<yourPackage>/<path to file defining the table>.drift_module.json` which describes how drift understood your table definition. There's going to be field having `"typeConverter": { ... some json object... }`, can you share that? Next to that file, there's going to be a file with the same name ending in `.types.temp.dart`, could you share that as well?
Sorry to put you through these involved steps, hopefully that will give a good clue about the source of the problem though.

**Comment by TobiDevloft** [comment]
Thank you for responding this quickly, I appreciate it!

My lower dart sdk bound is` >=2.12.0`

The `typeConverter` field for the `data` column in `gamepack_table.dart.drift_module.json` looks like this:

```
"typeConverter": {
      "expression": {
        "elements": [
          "const ",
          {
            "lexeme": "GamePackConverter",
            "import_uri": "package:package_name/database/converter/game_pack_converter.dart"
          },
          "()"
        ]
      },
      "dart_type": 0,
      "json_type": null,
      "sql_type": "string",
      "dart_type_is_nullable": false,
      "sql_type_is_nullable": false,
      "is_drift_enum_converter": false
    },
```

The content for `gamepack_table.dart.types.temp.dart` is:
```

import 'package:package_name/classes/game_pack.dart' as i0;
typedef T0 = i0.GamePack;
```

Let me know if I can help with anything else!

**Comment by simolus3** [comment]
Ah, that explains the problem I think. In Dart 2.12, `typedef T0 = i0.GamePack;` is invalid because typedefs were only allowed to denote function types in that language version.

If you're not compiling with a Dart/Flutter SDK of 2.12, could you raise the lower SDK bound to `2.13` which is where the required feature became available?

**Comment by TobiDevloft** [comment]
That worked! Thank you very much for helping out :)
