### ISSUE TITLE
[Q] Incorrect return type from a raw COUNT query or am I missing something?

### ISSUE THREAD

**Issue by 0rAX0** [simolus3/moor#193]
I needed to `COUNT` the number of items in the database using this code: 

```
queries: {

'numberOfTasks':
    'SELECT COUNT (task_name) FROM project_tasks WHERE project_id = ?;'
...
```

It generated a `watchNumberOfTasks` with a `List<int>` type, but: 
1. I need the `int` not the list
2. The list is nothing but one item (the count value) inside. :\

I'm still a beginner especially with Streams so I don't know if this is something that Moor should provide or if it's something I need to deal with. I tried asking and looking around without a single result. :\

Thanks in advance.

**Comment by simolus3** [comment]
Thanks for the question - reading a single row is actually something we improved in moor 2.0, but the updated apis aren't generated by default (because of backwards compatibility).

The easiest way to fix this is creating a file called `build.yaml` next to your pubspec. It should have the following content:
```yaml
targets:
  $default:
    builders:
      moor_generator:
        options:
          compact_query_methods: true
```

If you then re-run the build runner, the `watchNumberOfTasks` and `numberOfTasksQuery` method will go away. Instead, the generated `numberOfTasks` method will now return a `Selectable<int>`, which you can use to read a single row:
```dart
numberOfTasks().watchSingle() // returns a Stream<int>
```

Let me know if that didn't work or you have any more questions, I'll reopen the issue right away :)

**Comment by 0rAX0** [comment]
@simolus3 Thanks a lot! That's what I needed. :)

One additional question, say I have this query and another one that I expect a `List` from, does enabling `compact_query_methods: true` means that raw queries now only return Selectables?

**Comment by simolus3** [comment]
Yes, you would have to replace usages with `yourQueryName.watch()` for a stream of lists or `yourQueryName.get()` for a future (that reaolves to a list).

**Comment by 0rAX0** [comment]
Thank you so much, that was very helpful!
