### ISSUE TITLE
Compare Date not working properly

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#1933]
### Discussed in https://github.com/simolus3/drift/discussions/1225

<div type='discussions-op-text'>

<sup>Originally posted by **Adithya-13** May 26, 2021</sup>
Hello!

I have a function that return a list of task-based on a date, here is the code

```

  Stream<List<TaskWithCategory>> watchAllTaskByDate(DateTime dateTime) {
    final query = (select(tasks)
          ..where((tbl) {
            final date = tbl.deadline;

            return date.year.equals(dateTime.year) &
                date.month.equals(dateTime.month) &
                date.day.equals(dateTime.day);
          })
          ..orderBy(orderTaskByDate())) // order by date
        .join(leftOuterJoinTaskWithCategory()); // join with other table

    return toTaskWithCategory(query);
  }
```

but the where clause will only return true if the hour of deadline `date` up to 7 AM if I set the hour of  `date` below 7 AM like 6 AM, it will return false. 

I don't know what happens, thank you all, sorry for my bad English</div>

## Proposed solution:

Would it be possible to create a `toUTC()` on `DateTimeColumn` creation so that the companion would always turn the date to UTC to handle it? It would be really great if anything like this existed.

This way whenever you wanted a `DateTime` and your device changed timezone it would just fix itself. The `Companion` would solve the entry as UTC and the `toColumns` usage could transform the `DateTime` to UTC.

**Comment by simolus3** [comment]
In the next drift version, you will be able to do `dateTime.modify(DateTimeModifier.utc())` to convert date-time values to UTC. However, note that the `year`, `month` and `day` getters` already return the values in UTC. You can apply a trick and add the local UTC offset to the date time value. This is essentially doing `dateTime.modify(DateTimeModifier.local())` in drift 2. You can backport this to:

```dart
extension on Expression<DateTime?> {
  // Returns a date time value where [year], [month], [day] and other getters report values in local time.
  Expression<DateTime?> addLocalOffset() {
    return FunctionCallExpression('unixepoch', [this, Constant('unixepoch'), Constant('localtime')]);
  }
}
```

Note that there may still be some issues with this approach, especially around time zone shifts when daylight saving time starts or ends.

**Comment by simolus3** [comment]
Actually, I think a much better approach would be to compare UTC values. Instead of doing `date.year.equals(dateTime.year)` and so on, you could do this:

1. Find the start and end of the date you're interested in as `DateTime` instances.
2. Then use something like `date.isBetweenValues(startOfDay, endOfDay)` as a filter clause.

For step 1., the start date would just be `startOfDay = DateTime(dateTime.year, dateTime.month, dateTime.day)`. Maybe I'm overlooking something here, but I think the end date can reasonably be `endOfDay = DateTime(dateTime.year, dateTime.month, dateTime.day, 23, 59, 59)`. Doing a comparison in this range should give you all values with a matching date regardless of the time zone.
