### ISSUE TITLE
Shouldn't the `build_extensions` of `drift_dev` be `.drift.g.dart`

### ISSUE THREAD

**Issue by ValentinVignal** [simolus3/moor#1942]
In https://github.com/simolus3/drift/blob/867f8cbfed8cdcbd1daf00563cc2f5569eed67f0/drift_dev/build.yaml#L24-L31

The build extensions of `.dart` is `.moor.g.dart`. Shouldn't it be `.drift.g.dart` ?

I don't know if that is related but the generated code has the header `MoorGenerator`.

```dart
// **************************************************************************
// MoorGenerator
// **************************************************************************
```

Here is an example:

https://github.com/ValentinVignal/flutter_app_stable/blob/8d7d90cadd33bcedcb200f3da86f398c53066251/lib/database.g.dart#L5-L7

You can checkout https://github.com/ValentinVignal/flutter_app_stable/tree/drift/const-data-class

**Comment by simolus3** [comment]
Nice catch, thanks! Note that this isn't a generated `.dart` file, it's a hidden `.part` file which a builder from `source_gen` later picks up to emit the single `.g.dart` file.

The `MoorGenerator` that shows up as a comment is caused by something else. I have already renamed it to `DriftDatabaseGenerator` but this change hasn't been released yet. I have also renamed the hidden part file in efb4c5f50330440449bd2f7d8c172466535ba268.
