### ISSUE TITLE
FTS5 type problems

### ISSUE THREAD

**Issue by FaFre** [simolus3/moor#1943]
I encounter several issues regarding types when using fts5.

My drift file:
```sql
CREATE VIRTUAL TABLE features
	USING fts5(id UNINDEXED, 
weight UNINDEXED,
name);

poiFullTextSearch: 
    select
        distinct
            id,
        rank * weight as score
    from
        features
    where
        name match ?
    order by
        score;
``` 
Id is intend to be an integer, name is string, weight is real. There seems to be no option to strongly define the types of the columns in fts5 directly. Is there the possibility to do so in Drift? Every column is interpreted as `String` in Drift.

The actual problem is that rank in fts5 is always an real, never an int. and the generated code interprets score incorrectly as int:

```dart
Selectable<PoiFullTextSearchResult> poiFullTextSearch(String var1) {
    return customSelect(
        'SELECT DISTINCT id, rank * weight AS score FROM features WHERE name MATCH ?1 ORDER BY score',
        variables: [
          Variable<String>(var1)
        ],
        readsFrom: {
          features,
        }).map((QueryRow row) {
      return PoiFullTextSearchResult(
        id: row.read<String>('id'),
        score: row.read<int>('score'),
      );
    });
  }
```

This has been reported already in this issue https://github.com/simolus3/drift/issues/1066 but doesn't seem to have an effect when not directly selecting rank.

**Comment by simolus3** [comment]
> There seems to be no option to strongly define the types of the columns in fts5 directly. Is there the possibility to do so in Drift?

It's a shame that the type can't specified in fts5 directly, at least as a hint. I can see drift supporting something like

```dart
CREATE VIRTUAL TABLE features
	USING fts5(id INT UNINDEXED, 
weight REAL UNINDEXED,
name);
```

Drift would then omit the type in the generated  `CREATE TABLE` statement so that it's valid again. But I don't really like this syntax derivation, at the moment we can get with away with not touching virtual table statements at all.

> and the generated code interprets score incorrectly as int:

I think this is the same problem as not being able to inform drift about the correct type. When the type inference algorithm sees a multiplication that doesn't make sense to it (here, because one factor is considered to be a string), it falls back to `int`.

You could use `CAST(rank * weight AS REAL)` as a workaround for this specific problem. I wonder how annoying it is to add those casts in practice? If there are only few problems like this, that might be the easiest solution...

**Comment by FaFre** [comment]
Ah I see, fts5 brings some special flavor here :)
Maybe I will use directly your sqlite3 package for my fts5 database, to avoid those workarounds. The database structure is very simple, but will contain several hundred thousand of entries.
