### ISSUE TITLE
Should fromJson/toJson support store_date_time_values_as_text?

### ISSUE THREAD

**Issue by North101** [simolus3/moor#1948]
With `store_date_time_values_as_text = true`, `fromJson` / `toJson` expect / return an `int` instead of a `String`. Should it return a `String` when `store_date_time_values_as_text = true`?

**Comment by simolus3** [comment]
Ideally, I'd want the default serializer to be a property of the database instead of making it a global option. I think that's hardly possible now though (we'd have  to add a required parameter to every  `fromJson` factory), but I've made the behavior configurable in b6f61564075abacc67400032d5c30d176a9149a1.
