### ISSUE TITLE
Missing type operations?

### ISSUE THREAD

**Issue by North101** [simolus3/moor#1951]
I recently wrote a migration where I had to times a value by 100 and couldn't figure out how to do that (I eventually wrote a custom express). So unless I missed it I think these are missing: https://www.sqlite.org/datatype3.html#operators

I could give this a go if you'd like (though will have to wait for my RSI to go away).

**Comment by simolus3** [comment]
It's true that some binary expressions aren't exposed as operators yet, but `+`, `-`, `*` and `/` are defined as operators on `Expression<num>`, do you mean those?

PRs for additional operators are definitely welcome!

**Comment by North101** [comment]
Hmm. It wasn't showing up and it was failing when trying to do `*` on a column but I also did t look very hard.

**Comment by simolus3** [comment]
Hm, so it's [definitely there](https://pub.dev/documentation/drift/latest/drift/ArithmeticExpr/operator_multiply.html) and there are tests for it:

https://github.com/simolus3/drift/blob/10eb6b9a9c05a081965aada27f21d91ad40a7cef/drift/test/database/expressions/algebra_test.dart#L15-L20

I wonder if this the analyzer acting up or if you called it on a `Expression` with the wrong type? Since it's an extension, did you add the drift import if you're using it outside of the main database files? I'll close this issue since it looks like it's working correctly. But please let me know if you can't get it working, perhaps there's something wrong elsewhere.

**Comment by North101** [comment]
> Hm, so it's [definitely there](https://pub.dev/documentation/drift/latest/drift/ArithmeticExpr/operator_multiply.html) and there are tests for it:
> 
> https://github.com/simolus3/drift/blob/10eb6b9a9c05a081965aada27f21d91ad40a7cef/drift/test/database/expressions/algebra_test.dart#L15-L20
> 
> I wonder if this the analyzer acting up or if you called it on a `Expression` with the wrong type? Since it's an extension, did you add the drift import if you're using it outside of the main database files? I'll close this issue since it looks like it's working correctly. But please let me know if you can't get it working, perhaps there's something wrong elsewhere.

Huh its working now... Maybe its because i was switching between a local copy of drift
