### ISSUE TITLE
whereSamePrimaryKey not working with custom primarykey

### ISSUE THREAD

**Issue by Coronon** [simolus3/moor#1956]
**Describe the bug**

In one of my methods I query a Table that I defined a custom primarykey for. I then want to use the returned row in a delete statement which returns `0` -> nothing was deleted. This is not only a problem for deletion, drift in general does not seem to understand the primary key in this case (UPDATE, SELECT etc. also don't work as expected).

Table:
```dart
/// Songs and playlists the user added to their QuickPlay list
///
/// The actual view the above layers use is defined in [Favorite]
@DataClassName('FavoriteImpl')
class FavoritesImpl extends Table {
  //* Exactly one of the two columns below must be non-null

  /// Id of the	favored song
  IntColumn get song => integer().references(Songs, #id).unique().nullable()();

  /// Id of the	favored playlist
  IntColumn get playlist =>
      integer().references(Playlists, #id).unique().nullable()();

  /// Position in the QuickPlay list with 0 being the first item at the top
  IntColumn get position => integer()();

  /// Each song or playlist should be unique
  @override
  Set<Column> get primaryKey => {song, playlist};
}
```

My delete 'attempt':
```dart
await transaction(() async {
  // `favorite.song` and `favorite.playlist` are `int?` with exactly one being non-null
  final Expression<bool?> Function($FavoritesImplTable) entryExpr =
      favorite.song != null
          ? (entry) => entry.song.equals(favorite.song)
          : (entry) => entry.playlist.equals(favorite.playlist!);

  final entry = await (select(favoritesImpl)..where(entryExpr)).getSingle();

  await (delete(favoritesImpl)..whereSamePrimaryKey(entry)).go();

  // ... (The following code still uses `entry`, which is why i query it first
});
```

This will not delete the `entry` row. What also doesn't work is `await delete(favoritesImpl).delete(entry);`. The only solution I found that actually works is an explicit where clause, in this case: `await (delete(favoritesImpl)..where(entryExpr)).go();`.

PS: I checked the docs but could't find something about "Dont use `whereSamePrimaryKey` with custom primary keys" :)

**Comment by simolus3** [comment]
Custom primary keys should definitely work with `whereSamePrimaryKey`. For composite keys, it does an `AND` over all primary key columns to match rows. This should work as intended in most cases.

What seems very suspicious is that your primary key columns are nullable. in the way that it's currently written, `whereSamePrimaryKey` will _not_ match anything for null keys. This was not done intentionally, but pease note this section from the sqlite3 documentation (my emphasis):

> Each row in a table with a primary key must have a unique combination of values in its primary key columns. For the purposes of determining the uniqueness of primary key values, __NULL values are considered distinct from all other values, including other NULLs__. If an [INSERT](https://www.sqlite.org/lang_insert.html) or [UPDATE](https://www.sqlite.org/lang_update.html) statement attempts to modify the table content so that two or more rows have identical primary key values, that is a constraint violation.

From your comment, it sounds like your intention is to always have exactly one column be non-null. But please be aware that this doesn't guard against duplicates - there can be multiple rows with a `null` song and the same playlist and multiple rows with a `null` playlist for the same song. Was this intentional? It means that `whereSamePrimaryKey` would have to match multiple rows in some cases.

On the same note, it can be argued that `whereSamePrimaryKey` is working as intended here. Just like in sqlite3, a `NULL` value is considered distinct from all values including another `NULL`. So as soon as any column in your primary key is `NULL`, by definition, _no_ row has a matching primary key. I'm open for counter-arguments here, but I think my action will be to declare the current behavior intentional and document it.

----

Now, on to solve the problem you ran into :)

In the next drift version, you will be able to use `RETURNING` from the API for deletes to delete some rows and load them:

```dart
await transaction(() async {
  // `favorite.song` and `favorite.playlist` are `int?` with exactly one being non-null
  final Expression<bool?> Function($FavoritesImplTable) entryExpr =
      favorite.song != null
          ? (entry) => entry.song.equals(favorite.song)
          : (entry) => entry.playlist.equals(favorite.playlist!);

  final deletedRows = await (delete(favoritesImpl)..where(entryExpr)).goAndReturn();
  final entry = deletedRows.single; // can keep using entry now, don't need the select
});
```

Right now, couldn't you just use the same filter for the delete and the select?

```dart
await transaction(() async {
  // `favorite.song` and `favorite.playlist` are `int?` with exactly one being non-null
  final Expression<bool?> Function($FavoritesImplTable) entryExpr =
      favorite.song != null
          ? (entry) => entry.song.equals(favorite.song)
          : (entry) => entry.playlist.equals(favorite.playlist!);

  final entry = await (select(favoritesImpl)..where(entryExpr)).getSingle();

  await (delete(favoritesImpl)..where(entryExpr)).go();

  // ... (The following code still uses `entry`, which is why i query it first
});
```

**Comment by Coronon** [comment]
First of all, thank you for your very quick and detailed reply. I was indeed not aware of that behaviour but it makes intuitive sense as both the`song` and `playlist` columns are declared _unique_, which would mean that only one row may be _null_.

I that as long as this behaviour is documented (which you just did), this is not required as a "feature".

Making the `RETURNING` clause available to the API is great, at the moment I'm using it in some custom SQL queries in my `.drift` files, but I actually didn't think of using it like this.

The solution you provided is indeed what I went for after raising this issue.

Thank you for your awesome work!
Dankeschön! 👍🏻
