### ISSUE TITLE
Removing columns from `toString`

### ISSUE THREAD

**Issue by chrisnorman7** [simolus3/moor#1957]
Hi,
I'd really like to exclude (or mutate) my `data` column, which is created as a `BlobColumn`.

I'm storing sound files, and the blobs are huge as one might expect. I'd like to be able to do something like the following:

```dart
/// The table for sounds.
class Sounds extends Table
    with
        _WithPrimaryKey,
        _WithCreatedAt,
        _WithName,
        _WithPlayerId,
        _WithSoundCategoryId {
  /// The data of the uploaded sound.
  BlobColumn get data => blob().excludeFromToString()();
}

/// Or maybe:
/// The table for sounds.
class SoundsWithMutatedData extends Table
    with
        _WithPrimaryKey,
        _WithCreatedAt,
        _WithName,
        _WithPlayerId,
        _WithSoundCategoryId {
  /// The data of the uploaded sound.
  BlobColumn get data => blob().mutateDataForToString((final Uint8List data) => '${data.length}')();
}
```

Is this already possible?

I'm not exactly a database expert, so if this functionality isn't possible because only silly people put such large files into their databases, please feel free to say, and I'll store paths, rather than data.

Thank you in advance, and as they say in #1123, Thank you! :)

**Comment by simolus3** [comment]
> so if this functionality isn't possible because only silly people put such large files into their databases, please feel free to say, and I'll store paths, rather than data.

Storing large blobs in a sqlite3 database is not necessarily a bad thing. There's a comparison of the performance between internal and external blobs [here](https://www.sqlite.org/intern-v-extern-blob.htmlhttps://www.sqlite.org/intern-v-extern-blob.html), but the simplicity of having everything in one place is another compelling point in favor of internal blobs.

That said, my unfortunate and disappointing answer for these use cases is to either deal with drift-generated data classes or to use [custom row classes](https://drift.simonbinder.eu/docs/advanced-features/custom_row_classes/) which can have the `toString()` behavior you want. If I started adding `excludeFromToString` or `mutateDataForToString`, I would also have to start adding similarly-specific features for every other aspect of generated data classes. This doesn't really scale to a maintainable solution in drift. Perhaps a macro system in Dart could help you customize these classes in the future, but that degree of customizability can't really be provided by drift unfortunately. (In my opinion, drift-generated data classes are already doing way to much, but that's due to historical reasons that I can't really change now.)

Still, I agree that calling `toString()` on `Uint8List`s is not a good thing for drift to do either. If the generated classes emitted something like `blob (x bytes)` all the time, would that work for you? Since `toString()` is mostly used for debug output, I think it's rarely useful to dump the entire contents in there.

**Comment by chrisnorman7** [comment]
Hi @simolus3 
Thank you so much for the reply.

It's not disappointing at all. I actually went with not storing everything in the row eventually, reasoning that about 80% of the time, I'd be sending back the ID of a given sound, rather than the data, so I didn't need to keep dragging that across the boundary every request.

Something like `blob (x bytes)` would make me very happy in deed, but also it's not the most important thing in the world, so I'm happy for it to be low down the list of priorities.

Thank you for your explanation, and thank you again for such a wonderful package.
