### ISSUE TITLE
Cannot write data after backup restore

### ISSUE THREAD

**Issue by bawantha** [simolus3/moor#1968]
**Describe the bug**

I am using DB backup to g drive , after restoration backup I cannot use the same db it says

```Unhandled Exception: SqliteException(1032): attempt to write a readonly database, attempt to write a readonly database```

**Comment by simolus3** [comment]
How are you backing up and restoring the database? Depending on when you do that, there could be a `.lock` file next to the database, maybe that is causing some consistency issues causing the database to be considered read-only. It's hard to say what exactly is happening here without more information on what your backup process looks like.

**Comment by bawantha** [comment]
I zip the application directory and uploaded it to drive.
```final docsDir = await getApplicationDocumentsDirectory();
    final tmpDir = await getTemporaryDirectory();
    final tmpZip = IO.File(
        "${tmpDir.path}/medicare-${DateTime.now().millisecondsSinceEpoch}.zip");
    print("+++++ tmpZip: ${tmpZip.path}");
    try {
      await ZipFile.createFromDirectory(
        sourceDir: docsDir,
        zipFile: tmpZip,
        recurseSubDirs: true,
      );
      final driveFile = File();
      driveFile.modifiedTime = DateTime.now();
      final read = tmpZip.openRead();
      final length = await tmpZip.length();
      final media = Media(read, length);
      driveFile.parents = ["appDataFolder"];
      driveFile.name = "data.zip";

      ///  show local notification progress panel
      final File res =
          await driveApi.files.create(driveFile, uploadMedia: media);

```


and when restore delete the existing `ApplicationDocumentsDirectory` and extract the zip folder to `ApplicationDocumentsDirectory`

```

    final docsDir = await getApplicationDocumentsDirectory();
    await docsDir.list().forEach((element) async {
      await element.delete(recursive: true);
    });
    final tmpDir = await getTemporaryDirectory();
    try {
      /// create Stream of  Stream<int>

      final contents = (await driveApi.files
          .get(id, downloadOptions: DownloadOptions.fullMedia)) as Media;

      onMediaLoad(contents);
      final diskFile =
          await IO.File("${tmpDir.path}/medicare-data.zip").create();
      final fileSink = diskFile.openWrite();
      double sum = 0;
      contents.stream.listen((chunk) {
        /// add sum of chunk as a stream to the sink
        /// this will be used to update the progress bar
        /// sum of chunks
        sum += chunk.length;

        /// convert sum to double and divide by 1024x1024 to get the size in MB
        onWrite(sum.toMB());
        fileSink.add(chunk);
      }, onDone: () async {
        await fileSink.close();
        await ZipFile.extractToDirectory(
            zipFile: diskFile, destinationDir: docsDir);
        onDone();
      });
```

Can you please tell me what might be the issue here

**Comment by bawantha** [comment]
Can I  just replace the existing DB and expect it to work?

**Comment by simolus3** [comment]
Please note  that this

```dart
    await docsDir.list().forEach((element) async {
      await element.delete(recursive: true);
    });
```

Does not actually await all delete operations. Calling `forEach()` on a stream with an async function will not await that function! This _could_ be causing the problem, but I'd be surprised by that. Either way, since the intention is to await everything you can rewrite it as

```dart
  await for (final entry in docsDir.list()) {
    await element.delete(recursive: true);
  }
```

Your extraction logic should be fine, but adding elements in `listen` like that breaks backpressure, I'd probably use `rxdart` and do `await contents.stream.doOnData((chunk) { /* report progress */ }).pipe(fileSink)` instead. But that really shouldn't impact correctness.

Another thing to make sure is that the database was closed both during the backup and the restore operation, can you guarantee that this was the case here?

**Comment by bawantha** [comment]
it's working after closing the database `close()` however I'm receiving 
```Unhandled Exception: Bad state: Can't re-open a database after closing it. Please create a new database connection and open that instead.```

**Comment by simolus3** [comment]
You'll pretty much have to do what the error message tells you to, closing a database is a terminal operation in drift. You need to create a new instance of your database class and use that instead of the old one.

Closing this issue as the original problem was solved, but if you need any help with the second database instance let me know.
