### ISSUE TITLE
Creating new object with autoIncrement field.

### ISSUE THREAD

**Issue by raphmte** [simolus3/moor#1974]
Hello @simolus3 , How are you?

I'm currently migrating my application to the new version of Flutter, consequently leaving Moor and going to Drift, and here I had a problem that I wasn't facing in the Moor version I was using.

Consider the following table:
```dart
import 'package:drift/drift.dart';

@DataClassName("MyTable")
class MyTable extends Table{

  IntColumn get fieldCode => integer().autoIncrement()();

  TextColumn get fieldName =>  text()();

}
```

When I try to create a new Object from this table, I need to define the 'fieldCode', but as it is an autoIncrement I shouldn't need to define it, in the past I could simply put the NULL value in the field that worked, but now I can't anymore:
```dart
MyTable entity = MyTable(
  fieldCode: null,
  fieldName: "Name",
);

MyTable entity = MyTable(
  fieldName: "Name",
);
```

In the two ways above, the IDE will show me an error, if I put a value like '0' in the autoIncrement field everything works fine, but I don't want to put the value '0':
```dart
MyTable entity = MyTable(
  fieldCode: 0,
  fieldName: "Name",
);
```

How can I best resolve this?

If this issue has already been resolved here in Issues, I honestly didn't find it.

Thank you in advance for your help.

**Comment by simolus3** [comment]
Hi! This has been asked a couple of times, but I also couldn't find relevant discussions right away either so it's all good :)

Basically, this boils down to how drift (and actually, also moor) interact with null safety. A row object (so an instance of `MyTable`) is designed to represent a _full_ row as it also appears in the database. Of course, a row in the database has a non-null `fieldCode` column (because it's auto-generated by the DBMS before writing the row). So, the same field is non-nullable in the generated data class. The advantage of making it non-nullable is that when you query for rows, you don't need to write `.fieldCode!` everywhere - drift knows that a full row has the value and you can avoid unnecessary null checks. This is also mentioned [in the documentation](https://drift.simonbinder.eu/docs/getting-started/writing_queries/#updates-and-deletes).

So the basic story is that, if you want to construct an instance of `MyTable` manually, you _need_ to provide all values that are non-nullable (or avoid using null-safety).

The solution is to use companion classes which drift generates for each table. These are designed to represent a _partial_ row, making them perfect for updates or inserts. In your case, you can probably write `MyTableCompanion(fieldName: Value("Name"))` to indicate that you want to set the `fieldName` column to `"Name"` and leave the `fieldCode` column unset.
For inserts, drift also generates a helper method where only the columns that are required for an insert are marked as `required` in Dart: `MyTableCompanion.insert(fieldName: 'Name')`.

If you need a common interface that can hold both data classes and companions, use `Insertable<MyTable>`. Unfortunately, the only reliable way to avoid this problem is to migrate to companions when you don't have all columns available.

**Comment by raphmte** [comment]
Perfect explanations, thank you very much.

So if I have a MyTableCompanion object and try to insert:
```dart
MyTableCompanion _entity = MyTableCompanion( fieldName: Value('Name') );
into(myTable).insert(_entity );
```

Will this work normally?

**Comment by raphmte** [comment]
Yes, that work:
![image](https://user-images.githubusercontent.com/12343741/183492343-1e1b5039-54d6-405c-b075-281dc3ffe27b.png)

**Comment by simolus3** [comment]
> Will this work normally?

Yes, it will! But for convenience I'd use `into(myTable).insert(MyTableCompanion.insert(fieldName: Value('Name')))`. It essentially gives you a compile-time warning if you forget about a column. Either way is fine though.
