### ISSUE TITLE
BoolColumn using withDefault is annotated with @required

### ISSUE THREAD

**Issue by andruli** [simolus3/moor#198]
Hello folks 👋,

I have defined a boolean column with a default value. According to the docs that should make the parameter optional in the generated data class. However, that doesn't seem to be working.

```
class Users extends Table {
  ...
  BoolColumn get useNetCarbs => boolean().withDefault(const Constant(false))();
  ...
```

```
class User extends DataClass implements Insertable<User> {
  User(
    ...
    @required this.useNetCarbs,
    ...
```

**Comment by simolus3** [comment]
I'd say this is working as intended (see #111 for more discussion).

To summarize, a data class (`User`, in your case) always represents an entire row as it would appear in the database. And since `useNetCarbs` isn't nullable, we assume it to be required on every row.
Obviously that's not very helpful - you're probably using the `@required` annotations to know which fields need to be set during an insert. Moor helps you with that by generating a companion class, `UsersCompanion` in your example. It has a named `UsersCompanion.insert` constructor which lists all field that are actually required during an insert (it shouldn't include `useNetCarbs`). You can use the companion for inserts and updates. In general, the companion is designed to hold partial data, which works well for inserts, where default values don't have to be present.

**Comment by andruli** [comment]
Thank you for the quick answer @simolus3 . I'm pretty new to `moor` and wasn't aware of the `Companion` concept. Your answer makes total sense. I'm marking this as closed.
