### ISSUE TITLE
Nullable field cannot be queried with nullable value in select using `select(....)  ..where((...))` in v2.0.

### ISSUE THREAD

**Issue by RoarGronmo** [simolus3/moor#2002]
![image](https://user-images.githubusercontent.com/11217296/185633924-73a5e601-4565-46ef-b33e-3d40a7750cfc.png)

This worked in `v1.7` but breaks in `v2.0`

Reason why ?

Or is it just a bug...?

**Comment by North101** [comment]
Discussed here:
https://github.com/simolus3/drift/pull/1934#issuecomment-1191639787

In SQL `anything = NULL` is always `FALSE` even if `anything` is `NULL`. If you want to check for NULL then you should use `anything IS NULL`. The reason it was changed is that because of this interaction, it could be a non-obvious bug.

A workaround if you really don't want to change your code is to do `equalsExp(Variable(...))`

**Comment by RoarGronmo** [comment]
Thanx for claryfying, I'll change my code to follow conduct.

**Comment by simolus3** [comment]
Yes exactly, `equalsNullable` is the the right way to do this now.

`equals(null)` has never worked like it should, it you really need those exact semantics for some reason then `equalsExp(Variable(...))` is the way to go.
