### ISSUE TITLE
EncryptedExecutor vs Drift 2.0.2

### ISSUE THREAD

**Issue by adammach** [simolus3/moor#2006]
Hi,
how can use encryption with Drift ver 2? I'm getting:
"The argument type 'EncryptedExecutor' can't be assigned to the parameter type 'QueryExecutor'". Seems like encrypted_moor is still using QueryExecutor from moor.

**Comment by simolus3** [comment]
The `encryption` package has been depending on `drift` v2 at the time I released it, perhaps your local clone was stale?

Either way, it still had some problems which I have fixed in 03642dd7eb85eb9557e6d78740f0b6215c80f582 (which also renamed the package to `encrypted_drift`). With that revision it should work.
