### ISSUE TITLE
single_transformer singleElements throws Expected exactly one element, but got 0

### ISSUE THREAD

**Issue by jweidner-mbible** [simolus3/moor#2020]
**Describe the bug**

I've seen an error captured by Crashlytics that indicates:

```
Fatal Exception: FlutterError
Bad state: Expected exactly one element, but got 0. Error thrown null.

single_transformer.dart - Line 30
singleElements.<fn> + 30

```

I have yet to be able to reproduce the problem, but it looks like it is originating from drift/lib/src/utils/single_transformer.dart

Could the throw statement be modified to include the original exception to make this easier to track down?

**Comment by simolus3** [comment]
The problem is almost certainly that you're using `watchSingle()` on a query that emitted zero rows at some point.

I agree that the stack trace could be more helpful here. In 3426fb540823741cfd25f385d3e673c0b787d9ca, I have changed the trace to point to the place where `singleTransformer` was called, which typically points to the actual query causing this problem.
