### ISSUE TITLE
Getting started snippets issue

### ISSUE THREAD

**Issue by osaxma** [simolus3/moor#2022]
The getting started got me a bit confused.

I assumed the two snippets below represent two separate files (e.g. `tables.dart` and `database.dart` in my case). 

<img width="966" alt="Screen Shot 2022-08-27 at 7 30 12 PM" src="https://user-images.githubusercontent.com/46427323/187039332-d4ca3247-53e6-4b62-90f4-27a7c8343121.png">

- URL: https://drift.simonbinder.eu/docs/getting-started/

`MyDatabase` is defined in both snippets as highlighted in the image above:

In this setup, the generator will complain about missing `database.g.dart` import directive. 

Long story short, to get everything working,  I had to:
- Remove the table definition from the top snippet.
- Include `part 'filename.dart'` (`part 'database.g.dart'` in my case) in the bottom snippet. 
- Remove the `part 'filename.dart'` (i.e. `part 'tables.dart'` in my case) from the top snippet (for some reason build_runner generates everything in `database.g.dart` so I removed it -- unless I'm missing something). 

Sorry if there was a misunderstanding on my part.. 

Cheers and thanks for your work (I've been using `sqlite3` before and trying to test drive drift now).

**Comment by simolus3** [comment]
Hi, and thanks for the report! I agree that the two snippets may not be too helpful if you want to split your tables and the database file into two separate files. The snippets are meant to first show how to define tables followed by how to actually write the database class, but in a single file. They're split into two snippets because there's a lot going on :) I will rephrase parts of that page to make it clearer that the two snippets belong into the same file.

That said, you are completely right about where to place part statements when using multiple files. At the moment, only the main database class needs a part file as drift generates everything into that file. If tables are defined in other files, those don't need a `part` declaration.

And thanks for checking out drift. If you're running into more issues, feel free to reach out!
