### ISSUE TITLE
Synchronized selects not always necessary

### ISSUE THREAD

**Issue by FaFre** [simolus3/moor#2029]
At the moment `NativeDatabase` sets `isSequential` to `true`, without the option to change it. This always results in "exclusively locking" the database inside drift. This is not always needed, especially when having read-only databases. 

I did a rudimentary benchmark, where I got 40% speed improvement when hard-coding `isSequential` to `false` and spamming selects.

In case I understood the code correctly, when using `MultiExecutor.withReadPool` with multiple isolated read executors, the locking for selects is not happening, at least between isolates - but then again inside isolates, when using `NativeDatabase`.

Unfortunately there is at the moment no option to write an own implementation, similar to `NativeDatabase` really, because `_NativeDelegate` is private/not exported.

Actually I'm not really sure if we need to lock the complete database during selects. Maybe Drift needs this to keep some of its features going (which I'm  not aware of), but in general from a database perspective, this is often not necessary.

It would be nice to have the possibility to turn the synchronization off, or export `_NativeDelegate` to write an own implementation.

**Comment by simolus3** [comment]
Since the `NativeDatabase` is blocking internally and doesn't really support asynchronous operations to begin with, I agree that the locking layer around it makes little sense and should be removed. It shouldn't even make a difference _with_ write options.

I have set `isSequential` to `false` in e8229261e0a91d45c20d7cfec22a1085c760974a.
