### ISSUE TITLE
Feature rich generated query result classes

### ISSUE THREAD

**Issue by FaFre** [simolus3/moor#2033]
At the moment, generated query results from custom selects are plain immutable classes. In some scenarios this makes it hard to work with. There is no equality comparison or `copyWith`, which comes in handy for post processing steps.

It would be nice to have those features! 
I guess it would be fairly easy to get those things by making use of the popular freezed package (https://pub.dev/packages/freezed).

Let me know what you think :)

**Comment by simolus3** [comment]
I'll provide some background thoughts on this below, but I think that (at least in the short-term), this would best be done by allowing custom row classes (https://github.com/simolus3/drift/issues/1134) to also work with queries.

Unlike in the earlier days of this project, I now want to keep drift-generated code simple. Things like `toJson` or `copyWith` are convenient, but they invite you to use drift-generated classes as model classes in your app's architecture. This is an unfortunate trap however, as drift-generated classes weren't designed to do that, their main purpose is to represent rows in a table (or for a query).

The harsh reality is that, if you're using drift's builtin json serialization capabilities, you're getting something worse than what `json_serializable` would have to offer. Similarly, if you're using drift-generated classes as main model classes, you're not getting something as nice as what `freezed` or `built_value` could generate for you.

I don't have any plans to remove these features, since they work well enough for most users. But ideally, the question is how one would combine these packages so that each one can play out their strengths. Drift is very good at turning tables and queries into typesafe APIs, but obviously it can't also be trying to compete with `json_serializable` or `freezed` in their core domains. I like the idea of letting drift generate code that `freezed` would then pick up, but I also want drift to be somewhat neutral and not force additional packages onto a user.

I could see an option for different generator styles like "simple" (keep generated code as short as possible), "drift" (basically the current mode) or "freezed" (generate `@freezed` classes and let that package do the remaining work).

----

I'll close this issue since, in the short term, I think the feature you're asking for is best addressed by completing #1134. Ideas for different generation styles are interesting but should probably be discussed in a separate issue. At the moment I'm working on refactoring drift's analyzer to be more modular and decoupled from drift's code-generation, which will hopefully make those efforts easier in the future.
