### ISSUE TITLE
Documentation issue: Isolates - Unclear Examples

### ISSUE THREAD

**Issue by joey-needs-sleep** [simolus3/moor#2066]
I may be doing this wrong, but I've been trying to access drift from within an isolate.  I followed the directions [here](https://drift.simonbinder.eu/docs/advanced-features/isolates/) but when I actually try and connect from a background isolate the program hangs indefinitely without error on `await db.mytable.select().get()`

The documentation has no usage example for using within an isolate when started from the main flutter isolate. 

## Code Snippet
```dart 

static Future<Map<String, Map<String, String>>> export({List<String>? passIDs}) async {
    DriftIsolate dbIsolate = getDriftIsolate();
    ReceivePort receivePort = ReceivePort();
    var map = <String, dynamic> {
      "port": receivePort.sendPort
    };

    Map<String, Map<String, String>> result;
    try {
      result = await compute(_computeJsonExport, map);
      receivePort.close();
      return result;
    } catch(e) {
      rethrow;
    }
     
  }


static Future<Map<String, Map<String, String>>> _computeJsonExport(Map<String, dynamic> args) async {
    SendPort port = args["port"];
  
    final connection = drift.DatabaseConnection.delayed(Future.sync(() async {
      return await DriftIsolate.fromConnectPort(port).connect();
    }));
    final db = MyDatabase.connect(connection);
    print(await db.mytable.select().get()); // hangs here
    return {
      "test": {
        "test": "1"
      }
    };
```

Versions:
```yaml
dependencies:
  drift: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
dev_dependencies:
  drift_dev: ^2.1.0
```

Any help would be appreciated!

**Comment by simolus3** [comment]
Could you share your implementation for `getDriftIsolate()` as well? I assume you have an existing database that you also want to access in a background isolate?

One issue is that you're just creating a `ReceivePort` which you're then passing to `DriftIsolate.fromConnectPort`. But you're never using that port to listen for messages or to encode the drift isolate. For me, passing the connect port of the actual drift isolate there fixes the problem:

```dart

static Future<Map<String, Map<String, String>>> export({List<String>? passIDs}) async {
    DriftIsolate dbIsolate = getDriftIsolate();
    var map = <String, dynamic> {
      "port": dbIsolate.connectPort // note this change here
    };

    Map<String, Map<String, String>> result;
    try {
      result = await compute(_computeJsonExport, map);
      return result;
    } catch(e) {
      rethrow;
    }
     
  }
```

This is not a complete solution since it leaves the `dbIsolate` running after the client in the background disconnects. To properly fix this, I need to know the desired lifecycle of the main database (in the main isolate) and what `getDriftIsolate()` is doing.

I agree that the documentation should also provide an example for this scenario. Still, having more details about your use-case would help me come up with good examples to explain it in the docs :)

**Comment by joey-needs-sleep** [comment]
Thanks for the reply!
I ended up making it work by just passing the drift isolate straight into my compute function without any encoding.  Im not sure this this is the "correct" solution though.

`getDriftIsolate()` is pretty hacky i'll admit, but as I hate the provider package I just decided to go this route.
First this function gets called when the application starts but after `WidgetsFlutterBinding.ensureInitialized();`

```dart 
final _database = initMainDrift();
late final DriftIsolate _driftIsolate;

PassBagDatabase initMainDrift() {
  final connection = DatabaseConnection.delayed(Future.sync(() async {
    _driftIsolate = await _createDriftIsolate();
    return await _driftIsolate.connect();
  }));
  return PassBagDatabase.connect(connection);
}
```

Then `getDriftIsolate()` just returns the private variable like so:
```dart
DriftIsolate getDriftIsolate() {
  return _driftIsolate;
}
```


At the end of my compute isolate function I do close the connection using `.close()`

My desired lifecycle is i suppose the entire duration of my flutter app. 
While I did get it to work I'm open to suggestions on improvements.

**Comment by simolus3** [comment]
>  I ended up making it work by just passing the drift isolate straight into my compute function without any encoding. Im not sure this this is the "correct" solution though.

I'd try it out in release mode once. If it works, it works :D I think it should work as long as the two isolates are part of the same Flutter engine which, with `compute`, they are.

> is pretty hacky i'll admit, but as I hate the provider package I just decided to go this route.

You could use a service locator package like [get_it](https://pub.dev/packages/get_it) for that but it's not that hacky IMO.

Since you already have a single drift isolate (I assume `_createDriftIsolate()` calls `DriftIsolate.spawn` internally), there's nothing more to do here. Then you essentially have "one executor isolate, different client isolate" approach described [here](https://drift.simonbinder.eu/docs/advanced-features/isolates/#common-operation-modes).
