### ISSUE TITLE
fromData not found on drift_sqflite 2.0

### ISSUE THREAD

**Issue by heshaShawky** [simolus3/moor#2074]
**Describe the bug**

I have upgraded my packages `drift_sqflite` from 1.0.0 to 2.0.0 as well as the derift_dev and after rebuilding all files I got a lot of errors mostly about type checking but that's not the problem.

The problem is that `fromData` does not exist anymore in my tables classes and I can't find anything on the documentation for how to get it back, the only method available now in my class is `fromJson`

**Comment by simolus3** [comment]
This is mentioned in the documentation about [upgrading from drift 1 to drift 2](https://drift.simonbinder.eu/docs/upgrading/#migrating-from-drift-1x-to-drift-2x) (the last point).

Basically, you now use the `map` method on the table classes. Instead of using `MyTable.fromData`, use `yourDatabase.myTable.map`.

**Comment by alberteije** [comment]
I used fromData like that:    

lista = await (customSelect("SELECT * FROM customer WHERE $field like '%$value%'", 
                                readsFrom: { customers }).map((row) {
                                  return Customer.fromData(row.data);  
                                }).get());
    return list;

--------

Now I can't see how to change that for using only .map as mentioned in docs.
