### ISSUE TITLE
Change apis

### ISSUE THREAD

**Issue by rubywai** [simolus3/moor#2103]
My old project used drift : 1.4.0 
Now I upgrade to new version drift 2.2.0
What is the alternative of (isBiggerOrEqualValue,isSmallerOrEqualValue)

and OrderingTerm(expression: studentTable.age,mode: mode!)])

I already read the official website. But it still show the old Apis.

**Comment by simolus3** [comment]
>  What is the alternative of (isBiggerOrEqualValue,isSmallerOrEqualValue)

Both of them ([one](https://pub.dev/documentation/drift/2.2.0/drift/ComparableExpr/isBiggerOrEqualValue.html), [two](https://pub.dev/documentation/drift/2.2.0/drift/ComparableExpr/isSmallerOrEqualValue.html)) still exist. The breaking change was that an `Expression` can no longer be nullable. Did you re-generate your code and check that you have no other compile errors around that?

> and OrderingTerm(expression: studentTable.age,mode: mode!)])

This constructor [is still there as well](https://pub.dev/documentation/drift/2.2.0/drift/OrderingTerm/OrderingTerm.html)?

Are those the only things missing for you? I'm surprised that they show errors now since they are definitely still part of drift's public API, as indicated by the automated documentation on pub. It might be something weird on your side (did you try cleaning the pub cache perhaps?). I'll close this since the APIs you've mentioned didn't change in drift 2.0.
