### ISSUE TITLE
Documentation issue: Isolates

### ISSUE THREAD

**Issue by saliouseck2009** [simolus3/moor#2108]
I want to report an error from the documentation i tried to solve it but i didn't have access to the code . 
In the exemple shown on documentation , creating instance of `DatabaseConnection` like this `DatabaseConnection(executor)` doesn't work because this constructor take three args and one was given. 
So all `DatabaseConnection` should be called with `fromExecutor` constructor like this  ` DatabaseConnection.fromExecutor(database)` or `DatabaseConnection.fromExecutor(executor)`

**Comment by simolus3** [comment]
Ah, now I understand your PR as well :D `DatabaseConnection` has recently been changed so that you only need to pass the executor. Please check that you're on the latest drift version (which is the one the documentation reflects). Or keep using  `DatabaseConnection.fromExecutor` if you want to use the older version for now.

**Comment by saliouseck2009** [comment]
Thank's you right i didn't have the last version .
