### ISSUE TITLE
Error when using boolean columns in postgresql when used as a boolean expression

### ISSUE THREAD

**Issue by abitofevrything** [simolus3/moor#2113]
**Describe the bug**
Having a table such as
```dart
class MyTables extends Table {
  BoolColumn get myBool => boolean()();
}
```
and connecting to a postgresql database, running the following query fails:
```dart
(select(myTables)..where((_) => myTables.myBool)).get();
```
```
Message: [PostgreSQLSeverity.error 42804: argument of WHERE must be type boolean, not type integer ]. Stacktrace: 
#0      _PostgreSQLExecutionContextMixin._query
package:postgres/src/connection.dart:513
#1      _PostgreSQLExecutionContextMixin.query
package:postgres/src/connection.dart:474
#2      _PgDelegate.runSelect
package:drift_postgres/src/pg_database.dart:108
#3      _BaseExecutor.runSelect
package:drift/…/helpers/engines.dart:68
#4      main
```

This is due to postgres, unlike sqlite, not implicitly converting integers to booleans. Instead, it has a dedicated boolean type. So, we could simply change the `sqlTypeName` of `DriftSqlType.bool` to be `boolean` instead of `integer` in postgres, but then we run into issues with the default constraints on bool columns (`CHECK ("col_name" IN (0, 1))`) producing errors since postgres can't compare a boolean to `0` or `1`.

I'd be willing to write up a PR for this if you could give me some guidance on how to approach the issue - being a new user of drift, I'm not aware of how this stuff is usually handled.

**Comment by simolus3** [comment]
Thanks for the report and for the suggestion on how to fix this.

I agree that using a native boolean datatype for postgres would be good. At the moment, the `CHECK ("col_name" IN (0, 1))` constraint is unconditionally added by `drift_dev`. To fix this, we'd need to restructure that code to be aware of the current dialect at runtime.

We could change `GeneratedColumn.defaultConstraints` to be a `void Function(GenerationContext)` that writes the constraint into a context instead of just being a static string. Then, the generator could emit code aware of the current dialect (via `GenerationContext.dialect`) and only include the check for sqlite.

A PR for this would be most welcome! This could be approached with the callback taking a `GenerationContext`, but I'm also happy with alternative approaches if you come up with something simpler. If you have any questions on this, please let me know :)
