### ISSUE TITLE
Speed up the first operation

### ISSUE THREAD

**Issue by wurikiji** [simolus3/moor#212]
Any first operation on `moor` takes some delay even in the release mode. Is there a way to ensure the initialization of `moor` is done, all speed up the first operation.

**Comment by simolus3** [comment]
The database is always opened lazily. So when the first operation is started, moor first has to open the database and run all migrations. All of that will take some time, but it has to be done at some point before the database is usable. You could run some fake select (e.g. `customSelectQuery('SELECT 1').get()`) right after constructing the database instance so that all of this happens as soon as possible.

**Comment by wurikiji** [comment]
Alright! Thanks for your answers again! I will try it :)
