### ISSUE TITLE
[drift_postgres] Changing the column type when migrating does not work

### ISSUE THREAD

**Issue by AlexKenbo** [simolus3/moor#2133]
**Describe the bug**

I created a column with the type "text" and filled it with the value "345".
```
 //TextColumn get position => text().nullable()();
  IntColumn get position => integer().nullable()();
```

And when I try to migrate to int
```
        if (to == 7) {
          await m.alterTable(
            TableMigration(categories, columnTransformer: {
              categories.position: categories.position.cast<int>(),
            }),
          );
        }
```

Then I get an error:
`PostgreSQLException (PostgreSQLSeverity.error 42601: syntax error at or near "PRAGMA" )
`
![image](https://user-images.githubusercontent.com/14903011/200364398-02ef27d8-5223-4075-a228-af8775bb721b.png)

How can I get SQLdialect in this place? _db doesn't have it. This is to invoke other logic for postgres

It would of course be better to create another alterTable method, or better yet a separate migration class for postgres.

@simolus3  Can you give me a direction? We just started Drift from the inside out.

Instead of Pragma, we need to turn off the triggers for the table
`Alter table table_name disable trigger all;
`
Temporary solution to make a direct request to the database
`ALTER TABLE categories  ALTER COLUMN "position" TYPE integer USING ("position"::integer);
`

**Comment by simolus3** [comment]
>  Can you give me a direction? We just started Drift from the inside out.

Most parts of drift are very sqlite3-specific, as this is the database it was designed to work with best. This includes `alterTable`, which, as its documentation explains, runs a [12-step procedure](https://www.sqlite.org/lang_altertable.html#otheralter) specific to sqlite3. Thus, it won't work for other databases such as postgres.
I don't think it can reasonably be adapted to work with postgres, so unfortunately my suggestion is to write your own migration logic instead of using `alterTable`.
