### ISSUE TITLE
Reason for not supporting DateTime milliseconds?

### ISSUE THREAD

**Issue by vkammerer** [simolus3/moor#215]
Hello @simolus3 ,

After investigating a buggy behaviour in my app, I noticed that the DateTime values I store in my database are rounded to their seconds.
When looking at https://github.com/simolus3/moor/blob/77fcf7a7ba40221fef3c6b7f8e75c18ad56ba051/moor/lib/src/types/sql_types.dart#L95-L122, I can see that this is indeed the way they are stored in the database.

Is there any reason for this? My app needs milliseconds precise dates and I would rather avoid having to store a "milliseconds" fields for each DateTime field too...

**Comment by simolus3** [comment]
I don't remember the exact reason for storing them as seconds - probably because the builtin datetime functions from sqlite only support unix timestamps as seconds. Changing that behavior now would obviously be a breaking change, but you should be able to pull something like that off by using type converters:
```dart
class MillisDateConverter extends TypeConverter<DateTime, int> {
  const MillisDateConverter();
  @override
  DateTime mapToDart(int fromDb) {
    if (fromDb == null) {
      return null;
    }
    return DateTime.fromMillisecondsSinceEpoch(fromDb);
  }

  @override
  int mapToSql(DateTime value) {
    return value?.millisecondsSinceEpoch;
  }
}
```

And then use it with
```dart
IntColumn get myDate => integer().mappedBy(const MillisDateConverter())();
```

The downside is that type converters can't be used in moor files (we're blocked by the `build` package here) and that you would have to compare by integers in queries, so you can't do `myDate.isLessThanValue(DateTime.now())`.

**Comment by vkammerer** [comment]
Thank you so much for the quick reply.

I've done some more reading in the meantime and can indeed see that the time primitives in sqlite support only seconds - not milliseconds.
I use comparison functions with dates quite a lot in my app, so I will stick to the current rounded values for now.

Thank you again!
