### ISSUE TITLE
DatabaseConnection and QueryExecutor combination

### ISSUE THREAD

**Issue by clragon** [simolus3/moor#2152]
**Is your feature request related to a problem? Please describe.**
It is currently difficult for me to have nice types in my dependency injection objects,
because I might either inject a DriftIsolate DatabaseConnection or a NativeDatabase (QueryExecutor) or even a (QueryExecutor) NativeDatabase.memory().
This means I somehow have to create multiple fields and run checks on which constructor to call and which field to pass.

**Describe the solution you'd like**
It would be nice if there was a common type to this. This could also eliminate needing 2 different constructors.
The fact that this isnt the case currently however hints at that there might be a problem with unifying these two classes into a single entity. But I would've liked to inquire about it regardless, in case this is something that could be considered for a future release.

**Comment by clragon** [comment]
The alternative that I am currently using is of course that I define such a combination myself, but that is rather ugly, in my opinion:

```dart
/// Holds a database that can be connected to.
class DatabaseCarrier {
  DatabaseCarrier(QueryExecutor this.executor) : connection = null;

  DatabaseCarrier.connect(DatabaseConnection this.connection) : executor = null;

  final QueryExecutor? executor;
  final DatabaseConnection? connection;

  bool get isolated => connection != null;
}
```

which is used this way:

```dart
if (databases.followDb.isolated) {
  return FollowsService.connect(
    databases.followDb.connection!,
  );
} else {
  return FollowsService(
    databases.followDb.executor!,
  );
}
```

**Comment by simolus3** [comment]
A `DatabaseConnection` actually contains a `QueryExecutor`. Basically, a `QueryExecutor` is the implementation for the database, responsible for executing statements. A `DatabaseConnection` combines a `QueryExecutor` with drift's stateful support for stream queries. The `DatabaseConnection` class is necessary because, if you're using an isolate, different clients should also share stream query updates.

However, your `DatabaseCarrier` class should not be necessary - you can simply use a `DatabaseConnection` instead. If you're coming from an isolate, just use `connect()`. Otherwise, construct a `DatabaseConnection(NativeDatabase(...))`. So you can use `DatabaseConnection` as the relevant type for your dependency injection system and then always use `FollowsService.connect` to create the database. Regardless of whether the connection comes from an isolate or if it's just a local thing.

----

The whole `.connect()` constructor thing mainly comes from backwards compatibility. `DatabaseConnection` had to be introduced because we need to share the stream query tracker across isolates but previously every database instance would create its own tracker for that.
I think the `connect()` constructor should just be there by default and then, in a future breaking release, we can disable the old constructor that only takes a `QueryExecutor`.

**Comment by clragon** [comment]
Thats great, I have applied that change and my constructors all take `DatabaseConnection` now.
Though I am wondering, is there a point to making `DatabaseConnection` and `QueryExecutor` two distinct types?
Would it make sense to "combine" them or make `NativeDatabase` also a `DatabaseConnection` so that users can type all of this easier?

**Comment by simolus3** [comment]
With some new improvements made, I think we can otherwise leave the situation as it is. Most users will probably chose to inject their generated database class instead of the lower-level `QueryExecutor` and `DatabaseConnection` types.

Between those two, I've just landed some changes that will make `DatabaseConnection` less relevant for most apps. You typically only need it for isolates. In Drift 2.3.0, `NativeDatabase.createInBackground` returns a `QueryExecutor` that is backed by a drift isolate already, so the most common scenario where a `DatabaseConnection` is necessary is mitigated. It's still needed for advanced isolate setups or web workers, but I think these cases have an intrinsic complexity that legitimizes the distinct type.
