### ISSUE TITLE
Feature for accessing / creating the database in the same folder as of the native app

### ISSUE THREAD

**Issue by ShahoodulHassan** [simolus3/moor#2186]
Hi,

First of all, thanks a lot for such a featureful package. I found it a bit difficult to create functions for complex queries using nested relations but now I'm getting a hang of it.

Currently, I'm migrating one of my Android-Java apps to Flutter and I was finding a way to access the same database as stored in `data/data/<package_name>/databases` folder but in vain. Accessing it would retrieve the user stored data without any need to create a mechanism for retrieving all the data from old database and storing in the new one.

However, while looking for a solution, I found this `getDatabasesPath()` method in `sqflite` package that provides access to the database folder mentioned above.

Now instead of accessing/creating a database file in the folder provided by `getApplicationDocumentsDirectory()`, I'm using the folder provided by `getDatabasesPath()`. In case of users updating their apps to the flutter version, they will get seamless access to their stored data and in case of new users too, the path would be the same as before. 

The downside is that I am importing `sqflite` only for using one method and relying on `drift` for the rest of the database operations.

So, I wanted to highlight this issue and request a feature that helps in a seamless migration by utilizing the same database.

If there is already a way to do it, please point me to it.

Thanks
Shahood ul Hassan

**Comment by kuhnroyal** [comment]
This would be platform specific, which Drift is not so I doubt it should be part of the library.
You should be able to get the folder with something like `${getApplicationDocumentsDirectory()}/../databases` - maybe one more level up.
You can also just copy the sqflite implementation and put it in your app with a minimal custom MethodChannel.

**Comment by simolus3** [comment]
I agree with @kuhnroyal here - it's somewhat unfortunate that you have to ship all the native code of `sqflite` because of this, but it also can't be part of the core `drift` package (which has been carefully designed to not need a dependency on `flutter`).

The approach of using that sqflite API is also recommended in the documentation for users [migrating to a `NativeDatabase`](https://drift.simonbinder.eu/docs/other-engines/vm/#migrating-from-moor_flutter-to-moor-ffi).

If you're concerned about unnecessarily shipping sqflite, you could write a custom platform channel in your Android Activity returning the result of this: https://github.com/tekartik/sqflite/blob/1f624edbd48edf751550a39e66da890d25b5493c/sqflite/android/src/main/java/com/tekartik/sqflite/SqflitePlugin.java#L650-L654

**Comment by ShahoodulHassan** [comment]
Thanks to both of @kuhnroyal and @simolus3 for pointing me in the right direction,
Now I've created a `MethodChannel` in `FlutterActivity` to execute the code for getting database path and therefore, removed the dependence on `sqflite`.
