### ISSUE TITLE
[Feature] Add new method .toFullData()

### ISSUE THREAD

**Issue by mstfkhazaal** [simolus3/moor#2192]
### Probleme:
**Every time i have table with foreign key, I create models to merge all tables related in one instance
If I have multiple foreign keys and multiple relationships with a table I will create a lot of models**

### Simple Example:
**Customer Table:**
```
@DataClassName('Customer')
class Customers extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
  IntColumn get type=> integer()
      .references(
        CustomersType,
        #id,
        onUpdate: KeyAction.cascade,
        onDelete: KeyAction.cascade,
      )
      .nullable()();
}
```
**CustomerType Table:**
```
@DataClassName('CustomerType')
class CustomersType extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
}
```
**Class Model:**
```
class CustomerFull {
  const CustomerFull(this.id, this.name, this.type);
  final int id;
  final String name;
  final CustomersType type;
  toJson...
  fromJson....
  otherMethod....
}
```

### Feature:
Without Create any new model only i call method **.toFullData** and i get models with full data object

**Note:**
### **Sorry if my English is weak**

**Comment by simolus3** [comment]
I don't currently have plans to add this or similar functionality. As an alternative, you could try [using SQL](https://drift.simonbinder.eu/docs/using-sql/) to write the relevant joins. For each query you define that way, drift will generate matching data classes. So that way, you don't have to write models classes _and_ a way to fetch them, you just write the SQL and let drift do the rest.
