### ISSUE TITLE
[Feature] Facilitate the process Many to many relationships

### ISSUE THREAD

**Issue by mstfkhazaal** [simolus3/moor#2193]
In Documentation[ (Many to many relationships)](https://drift.simonbinder.eu/docs/examples/relationships/) It is very difficult to InnerJoin tables

**My Ideas Is Convert This Method to new Method**

**From This:**
```
Stream<List<CartWithItems>> watchAllCarts() {
  // start by watching all carts
  final cartStream = select(shoppingCarts).watch();

  return cartStream.switchMap((carts) {
    // this method is called whenever the list of carts changes. For each
    // cart, now we want to load all the items in it.
    // (we create a map from id to cart here just for performance reasons)
    final idToCart = {for (var cart in carts) cart.id: cart};
    final ids = idToCart.keys;

    // select all entries that are included in any cart that we found
    final entryQuery = select(shoppingCartEntries).join(
      [
        innerJoin(
          buyableItems,
          buyableItems.id.equalsExp(shoppingCartEntries.item),
        )
      ],
    )..where(shoppingCartEntries.shoppingCart.isIn(ids));

    return entryQuery.watch().map((rows) {
      // Store the list of entries for each cart, again using maps for faster
      // lookups.
      final idToItems = <int, List<BuyableItem>>{};

      // for each entry (row) that is included in a cart, put it in the map
      // of items.
      for (final row in rows) {
        final item = row.readTable(buyableItems);
        final id = row.readTable(shoppingCartEntries).shoppingCart;

        idToItems.putIfAbsent(id, () => []).add(item);
      }

      // finally, all that's left is to merge the map of carts with the map of
      // entries
      return [
        for (var id in ids) CartWithItems(idToCart[id]!, idToItems[id] ?? []),
      ];
    });
  });
}

```

**To This:**

```
Stream<List<CartWithItems>> watchAllCarts() {
  return select(shoppingCarts).watchCustom(tl=> CartWithItems(tl,select(shoppingCartEntries)
    ..where((t) => t.item.equals(tl.id)) );
}


```

**Comment by simolus3** [comment]
That would be a nice API, but I don't see how `watchCustom` could be implemented. Surely it would do some kind of internal `switchMap` to run the other select, but how to we get from there to a `CartWithItems`? You're calling the constructor with a `select()`, drift can't magically transform that code into passing the result of that select into `CartWithItems`.

When using custom SQL queries in drift files or as part of `queries` in `@DriftDatabase`, you can use the `LIST()` SQL macro to archive something similar. Since drift modifies your SQL either way, we're able to implement pretty much what you're asking for there. The [example here](https://drift.simonbinder.eu/docs/using-sql/drift_files/#list-subqueries) demonstrates the feature, it's a nice way to resolve n:m relationships.
