### ISSUE TITLE
Low-level schema manipulation not caught by drift_dev schema dump

### ISSUE THREAD

**Issue by ycherniavskyi** [simolus3/moor#2208]
It seems that with the current implementation of dumping schema via analyzer is impossible to catch low-level/complex schema manipulation (something like this https://github.com/simolus3/drift/discussions/1532#discussioncomment-1637521). And as a result, the schema of created database from generated migration within tests is not equal to the schema of a real database of the corresponding version.

That is why technic used in `validateDatabaseSchema` (with `SELECT * FROM sqlite_master;`) is much more promising and completely resolves described issue.

What is the reason for using a database class source code analyzer instead of a "real" database dump?

**Comment by simolus3** [comment]
The intention for schema files is indeed to reflect the state of the database schema as defined in your project's sources. There's nothing wrong with dynamically defining tables or triggers (it's really clever), but it's not what most users are doing and it allows us to capture the expected schema without running user code.

I could add a mode to `schema dump` that takes a sqlite3 file instead of a database and then creates an equivalent schema from the entities in that database. I'll adapt `schema dump` to also accept a sqlite3 file as an input, it will then dump the actual schema from that file.

**Comment by ycherniavskyi** [comment]
It will be great to get such a mode in `schema dump` - waiting for it!

**Comment by simolus3** [comment]
Should be fixed in 5f8b1e3358b937c215f136eaa40442b562d3bc1b.
