### ISSUE TITLE
Proper batch api and updateAll support

### ISSUE THREAD

**Issue by JulianBissekkou** [simolus3/moor#221]
Since `insert` and `insertAll` are available I was wondering if there is an `updateAll` next to `update`.
I couldn't find anything in the documentation. Am I missing something?

**Comment by Mike278** [comment]
`insertAll` exists because moor can generate a single sql `INSERT` statement that inserts multiple rows.
```sql
INSERT INTO users (user_id, first_name) VALUES
(1, 'a'),
(2, 'b'),
(3, 'c')
```

While there are [some fancy sql queries](https://stackoverflow.com/questions/2528181/update-multiple-rows-with-one-query) that can update multiple rows with different values conditionally, I wouldn't expect that as a default provided by moor.

**Comment by simolus3** [comment]
_TL;DR_: We should probably add a proper batch api to moor.

----
To my own surprise, we actually don't generate a single insert statement in `insertAll`, we instead create what's essentially a `Map<String, List<List<Variable>>>` of statements. Then, each key is a sql statement and we have a list of bound variables to run it with. I imagine that this can be faster than a single query for (very) large inserts because you skip duplicate parsing costs. The original motivation for adding `insertAll` was that we get to use the batch api from sqflite, which is definitely faster because we have to send less data over platform channels.

We could introduce something similar for updates, but I think that only makes sense as an `replaceAll`, because then each entity is likely to only affect one row. If we had an `updateAll`, then
```dart
(update(table)..where((row) => predicate))
  .writeAll([firstUpdate, secondUpdate, thirdUpdate])
```
would realistically only apply the `thirdUpdate`, others would be overridden. (That's not technically true if each update only applies one column, but in that case you could just merge them into a single update).

Adding a proper `updateAll` only makes sense if each update has their own where clause. If we add that, we should probably introduce a proper `batch` api to moor that replaces `insertAll`:
```dart
await batched((Batch b) {
   // none of these methods should return a future, a batch should work atomically
   b.insertAll(...);
   b.update(); // can be used in a for loop to achieve update-all behavior that works atomically
   b.replaceAll(...);
});
```
Calling `batched` inside a transaction would probably not be supported, as we don't support nested transactions at the moment.

**Comment by JulianBissekkou** [comment]
We are currently evaluating moor as db solution for a bigger (database heavy) app. 
It looks like this feature is definitely needed since the current performance of updating multiple items is way to slow.
I create a quick performance test that does operations on 10000 items.
`into(myTable).insertAll(items)` took 300ms

**Comment by simolus3** [comment]
You might be able to make that a bit faster by wrapping the for loop in a `transaction` call, but sending 10000 messages to the sqflite implementation and back just takes some time. `moor_ffi` would perform much better, but we'll have to wait for Dart 2.6 for that to be stable.

**Comment by JulianBissekkou** [comment]
I was surprised that using a transaction call increased the performance a lot.

```
await transaction(() async {
      for (var entity in entities) {
          await (update(myTable)..where((e) => e.id.equals(entity.id.value)))
              .write(entity);
    }
    });
```

Previously: ≃ 15655ms
Now: ≃ 1722ms

Can you maybe explain why this small change increases the performance? The objects have to cross the platform channel anyways 🤔

Btw: I really enjoy using moor and its great to get fast feedback on issues! 
Keep up the good work 💪🏼

**Comment by simolus3** [comment]
I didn't expect a speedup that big, but wrapping things in a transaction can make writes faster as explained in the [faq](https://www.sqlite.org/faq.html#q19) from sqlite.
Basically, sqlite creates an implicit transaction for every statement not sent inside an actual transaction. That causes a lot of duplicate IO work because the database has to be saved for each individual update before we can send the next. In a transaction, we only need to write once (on commit).

**Comment by JulianBissekkou** [comment]
Just looked at your [commit](https://github.com/simolus3/moor/commit/9f1aafbcef9826d9ba63a88471dc4154efb06bb0). 
Can we already test Batch support by fetching the dependency from github? :) 
I would love to try it out ☺️

**Comment by simolus3** [comment]
Yes, if you add something like
```yaml
dependency_overrides:
  moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: moor/
      ref: develop
```
`develop` versions can be unstable at times, but it should be fine if you're just trying things out.

**Comment by simolus3** [comment]
Just released moor 2.1.0 which contains this feature.

**Comment by kuhnroyal** [comment]
@simolus3 In the process of updating to 2.1.0 I now have some deprecated `insertAll` calls inside of transactions. 

Can I safely replace this with a batch or should I iterate and `insert` each one?

Which boils down to these two questions:
Does a batch open one transaction around everything?
Does a batch disable primary keys?

**Comment by simolus3** [comment]
When not in a transaction, you can safely replace `insertAll` with the batch api. Inside a transaction you would have to insert the entries manually.

>  Does a batch open one transaction around everything?

Unfortunately, it depends. moor_flutter uses the batch api from sqflite, which uses transactions internally. The other implementations don't currently use transactions. This mismatch is unfortunate, I'll change the `moor` package to explicitly use transactions when sending batches.

>  Does a batch disable primary keys?

No, neither did `insertAll`.

**Comment by kuhnroyal** [comment]
Ok, thanks. Maybe some of this should go into the documentation.
