### ISSUE TITLE
Memory keeps growing

### ISSUE THREAD

**Issue by HuangZiquan** [simolus3/moor#2244]
Hi,
In some cases I need to insert data in the background isolate.
When I work with large amount of data, I find that the memory keeps growing and the memory is not freed.
[issue_demo](https://github.com/HuangZiquan/drift_issue_demo.git)

**Comment by simolus3** [comment]
Thanks for the issue and for publishing the repository, that was really helpful to analyze the problem!

Essentially, the issue was that, when a client closes its database connection, the server doesn't know about it and continues to keep the connection's state. That's definitely not great, but not a huge issue for most apps which only have a single connection to a drift database server. Your repro creates a thousand, which should be fine but exposes the problem in drift.

This should be fixed in 2bf36a3b5bdf16f83202a0ceee9094f4f6d9d399. I'll have to do a bit more testing to see if/why additional memory might be leaked.

**Comment by simolus3** [comment]
Should be fixed in drift 2.4.1, let me know if you're still running into issues with this.
