### ISSUE TITLE
If a table and view have the data class definition, the data class is written twice.

### ISSUE THREAD

**Issue by North101** [simolus3/moor#2247]
https://github.com/simolus3/drift/blob/810ecb169ab50051f34c71ca78b281515d7aa674/drift_dev/lib/src/services/schema/schema_files.dart#L388
`existingRowClass` is always `null` when generating views from schema files so a another table or view might generate a data class with the same name.

**Comment by simolus3** [comment]
Huh. We can't realistically support existing classes when generating schema codes (since their definition could have changed).

> so a another table or view might generate a data class with the same name.

For tables, it seems like we always generate data classes based on the name of that table in SQL (so we essentially ignore existing types / fixed data class names). Maybe we should just do the same for views? That would technically be breaking, but views with existing row classes have always been broken it seems - so this might not be affecting anyone in practice.

I've "fixed" this in 9734aa56d13b28d23ded80d37c11f2e5a85c8443 - let's see if it turns out to be a big issue. If it breaks something for you that wasn't  broken before, please let me know.

**Comment by North101** [comment]
I think thats a good solution, it means that each data class should never conflict.

Just so that you're clear, i'll give an example of what was happening with `writeDataClasses=true`:
```sql
CREATE TABLE my_table(
  ...
) WITH MyTableData;

CREATE VIEW my_table_view1 WITH MyTableData AS
SELECT *
FROM my_table;

CREATE VIEW my_table_view2 WITH MyTableData AS
SELECT *
FROM my_table;
```

previously, drift would try and create `MyTableData` 3 times in the same file.

**Comment by North101** [comment]
I can confirm its working as expected. Thanks!

**Comment by simolus3** [comment]
Thanks for the clarifying example and for confirming the fix. It's what I've suspected: Since the table is named `my_data`, the recovered schema will _always_ have a data class named `MyTableData` - regardless of the existing row type you've explicitly added. So adding the same to views (where the name was preserved) is causing the duplicate.
