### ISSUE TITLE
equals().not() in WHERE clause with NULL value

### ISSUE THREAD

**Issue by vikalpnagar** [simolus3/moor#2267]
Following query does not return expected data if column value is NULL.

`select(products)..where((tbl) => tbl.orderTypeId.equals('RETURN_LINE').not());`

orderTypeId is a String column having NULL value. As NULL is not equals to 'RETURN_LINE', I expect it to return the data.

To make it work, I have changed the where clause to:
`tbl.orderTypeId.isNull() | tbl.orderTypeId.equals('RETURN_LINE').not()`

Any thoughts why the first query does not work?

**Comment by North101** [comment]
This is correct behaviour because of how `NULL` works in SQL (whether it's sqlite, postgresql, etc).

When an expression is evaluated and one of the values is `NULL`, it will always evaluates to `NULL`. One exception is `IS NULL` / `IS TRUE` / `IS FALSE` (I'm sure there's others but can't think of them at the moment).

`order_type_id = 'RETURN_LINE'` isn't evaluating to `FALSE` but instead to `NULL`. `NOT NULL` then also evaluates to `NULL`.

You can check this yourself at https://sqliteonline.com/ by running:
```sql
SELECT
  NULL = 'RETURN_LINE' AS a,
  NOT (NULL = 'RETURN_LINE') AS b;
```

**Comment by North101** [comment]
A shorter but less clear way to write it is:
```sql
(order_type_id = 'RETURN_LINE') IS NOT TRUE
```

But I'm not sure if drift allows you to do this in dart

**Comment by simolus3** [comment]
This is intentional - `equals` generates a `=` in SQL which behaves as @North101 described.

I think there should be a better way to do this in Drift.

> `(order_type_id = 'RETURN_LINE') IS NOT TRUE`

Is this not equivalent to just `order_type_id IS NOT 'RETURN_LINE'`? As of 6e35abb9c9c79463cec90f1fb4ec07b5d8719a40, drift exposes the `IS` operator in the Dart DSL, so you'll be able to use `tbl.orderTypeId.isValue('RETURN_LINE')` in the next drift version.

**Comment by North101** [comment]
> This is intentional - `equals` generates a `=` in SQL which behaves as @North101 described.
> 
> I think there should be a better way to do this in Drift.
> 
> > `(order_type_id = 'RETURN_LINE') IS NOT TRUE`
> 
> Is this not equivalent to just `order_type_id IS NOT 'RETURN_LINE'`? As of [6e35abb](https://github.com/simolus3/drift/commit/6e35abb9c9c79463cec90f1fb4ec07b5d8719a40), drift exposes the `IS` operator in the Dart DSL, so you'll be able to use `tbl.orderTypeId.isValue('RETURN_LINE')` in the next drift version.

I have never tried `IS` without `NULL, TRUE OR FALSE`. For some reason I thought it was limited to those values. Good to know!

**Comment by vikalpnagar** [comment]
> This is intentional - `equals` generates a `=` in SQL which behaves as @North101 described.
> 
> I think there should be a better way to do this in Drift.
> 
> > `(order_type_id = 'RETURN_LINE') IS NOT TRUE`
> 
> Is this not equivalent to just `order_type_id IS NOT 'RETURN_LINE'`? As of [6e35abb](https://github.com/simolus3/drift/commit/6e35abb9c9c79463cec90f1fb4ec07b5d8719a40), drift exposes the `IS` operator in the Dart DSL, so you'll be able to use `tbl.orderTypeId.isValue('RETURN_LINE')` in the next drift version.

The current behavior makes sense how SQL is designed and as @North101 described. Thanks for the clarification @North101 and @simolus3.
