### ISSUE TITLE
Listener of stream obtained by watch triggers after future of modifying query completes

### ISSUE THREAD

**Issue by Quijx** [simolus3/moor#2268]
When I listen to a database using watch and do for example an insert, I want the returned `Future` of the insert statement to complete after the listeners to the database have been fired.
I also found the following sentences in a comment in `lib/src/runtime/executor/stream_queries.dart`, which leads me to believe, this is also the intended behavior.
> We want to dispatch table updates before the future from the query completes. This allows streams to invalidate their cached data before the user can send another query.

## Steps to Reproduce
- Set up a project as describe in https://drift.simonbinder.eu/docs/getting-started/starting_with_sql/
- Add the following main method:
```dart
void main() async {
  final db = MyDatabase();
  final stream = db.select(db.todos).watch();
  stream.listen((event) {
    print('watch stream listener called');
  });
  // Just so that we can differentiate the initial listener firing from the one caused by the insert. 
  await Future.delayed(Duration(seconds: 2));
  print('before insert');
  await db
      .into(db.todos)
      .insert(TodosCompanion.insert(title: 'Some Title', content: ''));
  print('after insert');
}
```
- Run the program

## Expected Result
The output should be
```
watch stream listener called
before insert
watch stream listener called
after insert
```
The first listener call can be ignored. Secondly the insert is started. Before the future of the insert completes, the listener should be fired. Only afterwards the future of the insert should complete. That way we can be sure that any (synchronous) side effects of the insert have happened after we awaited it. If there is any asynchronous work done in the listener, this guarantee can of course not be made, as the insert should not wait for some random stuff that happens elsewhere. Also Streams don't support this.

## Actual result
```
watch stream listener called
before insert
after insert
watch stream listener called
```
The listener is called after the future completes.

**Comment by simolus3** [comment]
The comment refers to an internal aspect of the query stream implementation. Since query streams cache data (useful if a single query is listened to multiple times), we need to be somewhat careful with cache invalidation. To avoid stale data, we synchronously clear the cache and schedule a stream update, but the intuition isn't that we want to wait for listeners to get notified.

In fact, doing that would be problematic:

1. What if a subscription to a query stream is paused? To fullfil that contract, we'd have to suspend the future for the insert until the subscription is resumed.
2. Streams are fundamentally asynchronous - they're not callbacks. Blocking at the source until receivers were notified violates that principle.
3. There is no way to implement this reliably if other stream combinators from `rxdart` or even `dart:async` are used - these might introduce an asynchronous delay that drift wouldn't know.
4. When lots of stream queries are active, the future for inserts will take weirdly long.
5. I'm not sure if this will be a problem in practice, but I can also think of deadlocks if e.g. an insert is made in the callback of a query stream.

Note that drift ensures that streams don't emit stale data (the latest event is always fresh at the time it is emitted by drift). But we don't guarantee a maximum time for streams to update.

**Comment by Quijx** [comment]
Hmm... But how can i make sure to wait until the listener for a particular event is dispatched?
In my case i have a watch on the database that modifies some internal state. Then I make for example an insert on the database and afterwards I want to work with the modified internal state. The only safe alternative would be so call a method after every modifying query (of which there are a lot) that gets the current state from the Database, and modifies the internal state according to that. This is also error prone, since the method can easily be forgotten. The current workaround is to await a `Future.delayed` with a small delay after the insert statement before accessing the internal state. But this is also hacky. Do you have any advise?

**Comment by simolus3** [comment]
> Then I make for example an insert on the database and afterwards I want to work with the modified internal state

Just to clarify, is the internal state something derived from the database, but managed outside of drift? If you work with query stream updates, they should always reflect the new internal state.

You can also emulate notifying listeners by `await Future.delayed(Duration.zero)` after the insert.

**Comment by Quijx** [comment]
Yes, the internal state is derived from the database. Its an `AsyncNotifier` from Riverpod that basically just maps the database models to our own models and provides methods for modifying the database. Here a rough outline of what it looks like:
```dart
class TodosNotifier extends AsyncNotifier<List<TodoDomainModel>> {
  Future<List<TodoDomainModel>> build() async {
    final db = ref.watch(databaseProvider);
    final todosStatement = db.select(db.todos);
    final sub = todosStatement.watch().listen((event) {
      state = AsyncData(mapDbTodosToDomainModel(event));
    });
    ref.onDispose(() => sub.cancel());
    return mapDbTodosToDomainModel(await todosStatement.get());
  }

  Future<void> addTodo() async {
    final db = ref.watch(databaseProvider);
    await db
        .into(db.todos)
        .insert(TodosCompanion.insert(title: 'Some Title', content: ''));
  }
}
```

So for example I want to await `addTodo()` and then access the modified state from the `AsyncNotifier`.
And I want to avoid doing something like `await Future.delayed(Duration.zero)` after every method that modifies the database.

If you don't have any further ideas, that's fine though. I know you're not my personal tech-support :)
It already helps to know the behavior is intended. We'll find some way around it.
