### ISSUE TITLE
The referenced element, WorkspaceRepository, is not understood by drift

### ISSUE THREAD

**Issue by remcoanker** [simolus3/moor#2269]
After an update from drift_dev 2.2.0 to 2.3.3, My DAO's are not recognized by drift.

```
[WARNING] drift_dev on lib/container_database.dart:
line 12, column 7 of package:drift_dao/container_database.dart: The referenced element, WorkspaceRepository, is not understood by drift.
   ╷
12 │ class ContainerDatabase extends _$ContainerDatabase {
   │       ^^^^^^^^^^^^^^^^^
   ╵
```

I've made a minimal example to reproduce this issue:
https://github.com/remcoanker/drift_dao

The first commit is working with drift_dev 2.2.0, the second commit it broken on drift_dev 2.3.3.

These lines are not in container_database.g.dart anymore:
```
late final WorkspaceRepository workspaceRepository =
WorkspaceRepository(this as ContainerDatabase);
```

**Comment by simolus3** [comment]
Thanks for the report. I had a look and, while the breakage is unfortunately, my assessment is that this should have never worked and the current state appears to be working as intended.

To be recognized as a DAO, the `WorkspaceRepository` class needs a `@DriftAccessor` annotation, like this:

```dart
import 'package:drift/drift.dart';
import 'package:drift_dao/container_database.dart';

@DriftAccessor()
class WorkspaceRepository extends DatabaseAccessor<ContainerDatabase> {

  WorkspaceRepository(super.db);
}
```

I suspect this used to work because we just took the types listed in `daos:` at face value without checking whether they actually are DAOs. In the refactored analyzer that shipped in drift_dev 2.3, we can only look at classes marked with `@DriftAccessor`.
