### ISSUE TITLE
Cannot Compare DateTime and GeneratedDateTimeColumn objects

### ISSUE THREAD

**Issue by HosseinArabbeigi** [simolus3/moor#228]
Hi there

How can i get difference days of GeneratedDateTimeColumn object and DateTime objects?

**Comment by simolus3** [comment]
There's no builtin api to calculate the difference between two dates at the moment. If you just need to compare datetimes, you can use `isBiggerThanValue` or others. I'll add more sql functions in the next release of moor, so this can include methods to calculate a difference.

**Comment by HosseinArabbeigi** [comment]
thanks a lot @simolus3 , but even i cant use DateTime, difference method, if you have any suggestion i will be appreciate to tell me.
thanks.

**Comment by Mike278** [comment]
Sounds similar to [this (comment)](https://github.com/simolus3/moor/issues/226#issuecomment-549787978) - you're likely trying to compare a table class with a data class. `GeneratedDateTimeColumn` comes from the table definition class, whereas `DateTime` comes from the row data class.

**Comment by HosseinArabbeigi** [comment]
yes exactly, obviously i should be able to access my data with same type as created model.

**Comment by simolus3** [comment]
> obviously i should be able to access my data with same type as created model

I'm not sure if I understand what you mean by that. Can you show the code where you try to compare the generated column with a datetime value? Then we might be able to help you better.

Also, maybe I should have been more clear in the linked comment: Moor generates model classes that are independent from your table class. So for instance, let's say we had a table
```dart
class Users extends Table {
   IntColumn get id => integer().autoIncrement()();
   TextColumn get name => text()();
}
```
With that table, moor would (I'm slightly simplifying here) create two classes: One called `_$UsersTable` that extends the `Users` table you wrote. Both `Users` and `_$UsersTable` represent a _whole table_. They don't store an id or a name, they store two columns.
And then there's another generated class called `User` which represents a _single user_, but not the whole table. The `User` table has an `int id` and `String name` field used to actually store the values. Note that the `User` class can't extend the table class you wrote, because a `String` isn't a `TextColumn` and an `int` isn't a `IntColumn`!

Which class to use depends entirely on what you're trying to do. If you want to load results, you'd want to use the `User` class. For instance, `await select(users).get()` returns a `List<User>`.
If you want to write queries, you use the `Users` table class. For instance: `select(users).where((u) => u.id.isLessThanValue(13))`. Here, `u` is not a `User`! It's the whole table, because we want all entries in the users table where the id column is less than 13.

I know this can be a bit confusing to grasp at first, but it's easier to understand once you've seen some examples. If you can share your code where you're running into problems, I'd be glad to help!

**Comment by HosseinArabbeigi** [comment]
Thanks @simolus3  for your response.
Yes i understand what you mean, sry maybe its because of my english..
but problem is when i want to use my column methods..

for example we cant do some thing like this : 

```dart
Future<List<Location>> orderedLocationsInDay(DateTime targetDay) {
    targetDay = DateTime(targetDay.year, targetDay.month, targetDay.day);

    return (select(locations)
          ..where((location) => location.time.difference(targetDay).inDays.equals(0))
          ..orderBy([(location) => OrderingTerm(expression: location.time)]))
        .get();
  }
```

because time type is `GeneratedDateTimeColumn`  and i cant use `difference` method of my time object.

**Comment by Mike278** [comment]
> i cant use difference method of my time object

That's because `difference` is a dart method, and the sql query moor is building cannot execute dart methods. One way to represent this in sql would be to check if `time` is between `targetDay`'s start and end:
```sql
SELECT * FROM locations WHERE time BETWEEN :day_start AND :day_end ORDER BY time ASC; 
``` 
You could implement this query in a [`.moor` file](https://moor.simonbinder.eu/docs/using-sql/moor_files/), or using the dart api with something like:
```dart
  Future<List<Location>> orderedLocationsInDay(DateTime targetDay) {

    final dayStart = DateTime(targetDay.year, targetDay.month, targetDay.day);
    final dayEnd = dayStart.add(Duration(days: 1)).subtract(Duration(seconds: 1));

    return (select(locations)
      ..where((location) => location.time.isBetweenValues(dayStart, dayEnd))
      ..orderBy([(location) => OrderingTerm(expression: location.time)]))
      .get();
  }
```

**Comment by HosseinArabbeigi** [comment]
Thanks @Mike278 .
Yes i did use a way similar to your way.
I think should close this issue.
