### ISSUE TITLE
customSelect escape 

### ISSUE THREAD

**Issue by wolru** [simolus3/moor#2286]
Hello, I have a question about customSelect query
I want to substract from original date using row number
but I don't know how to escape apostrophe. 'ROW_NUMBER() OVER()' is treated as string

'DATE(date, \'-ROW_NUMBER() OVER() days\') AS start_date '

**Comment by simolus3** [comment]
Can you post the full `customSelect` invocation? It's kind of hard to analyze the problem without knowing whether the quotes are part of the Dart string literal or part of your SQL :D

> I want to substract from original date using row number

So the intention is that you want to do `-2 days`, except that instead of `-2` you want a dynamic expression? In SQL, I suppose you can do that with

```sql
DATE(date,  (-ROW_NUMBER() OVER() days) || ' days')
```

(where `||` is the string concatenation operator in SQL). To use that in ` customSelect`, you would have to add the appropriate escapes around the quotes.

**Comment by wolru** [comment]
@simolus3 
It works. Thank you so much!!!
