### ISSUE TITLE
Error with sqlparser version in drift_dev 2.5.0

### ISSUE THREAD

**Issue by Carapacik** [simolus3/moor#2288]
**Describe the bug**

Because drift_dev >=2.5.0 depends on sqlparser ^2.27.0 which doesn't match any versions, drift_dev >=2.5.0 is forbidden.
So, because <prohject> depends on drift_dev ^2.5.0, version solving failed.
pub get failed

I think we need to change the version of sqlparser to ^0.27.0, most likely there is a typo.

**Comment by simolus3** [comment]
Thanks for the report, I've just published `drift_dev: 2.5.0+1` fixing this error.

I've messed this up while preparing the release and didn't catch this while publishing. Pretty unfortunate since pub should now warn about this. There was a false-positive warning while publishing the `drift` package though, so I didn't pay attention when it warned about `drift_dev` as well. So, sorry for the delay and I hope it all works now!
