### ISSUE TITLE
Docker Alpine is not working with drift

### ISSUE THREAD

**Issue by vanlooverenkoen** [simolus3/moor#2320]
Alpine is not working with drift. even if sqlite is installed.
```
FROM dart:2.19.2 AS build

COPY backend/pubspec.* ./
COPY shared/ ./

COPY /backend/resources/locales.json /resources/locales.json
COPY /backend/resources/web/ /bin/web

RUN dart pub get

COPY . .
RUN cd backend && dart pub get
RUN dart compile exe backend/bin/server_prod.dart -o /bin/server

###
FROM alpine:3.17.2

RUN apk update && apk upgrade
RUN apk add --no-cache sqlite

COPY --from=build /resources/locales.json /app/resources/locales.json
COPY --from=build /bin/web/ /app/bin/web
COPY --from=build /runtime/ /
COPY --from=build /bin/server /app/bin/server

ENV JWT_SECRET=your-very-secret-key

# Start server.
EXPOSE 8080
CMD ["/app/bin/server"]
```

And adding this also gave an error:
```
open.overrideFor(OperatingSystem.linux, _openOnLinux);

DynamicLibrary _openOnLinux() {
  final libraryNextToScript = File(join('usr', 'bin', 'sqlite3'));
  return DynamicLibrary.open(libraryNextToScript.path);
}
```
The error
```
Failed to load dynamic library 'usr/bin/sqlite3': usr/bin/sqlite3: cannot dynamically load position-independent executable
```

-----------------------------------

This one does work
```
FROM dart:2.19.2 AS build

COPY writor_backend/pubspec.* ./
COPY writor_shared/ ./

COPY /writor_backend/resources/locales.json /resources/locales.json
COPY /writor_backend/resources/web/ /bin/web

RUN dart pub get

COPY . .
RUN cd writor_backend && dart pub get
RUN dart compile exe writor_backend/bin/server_prod.dart -o /bin/server

FROM ubuntu:rolling

RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev

COPY --from=build /resources/locales.json /app/resources/locales.json
COPY --from=build /bin/web/ /app/bin/web
#COPY --from=build /runtime/ /
COPY --from=build /bin/server /app/bin/server

ENV JWT_SECRET=your-very-secret-key

# Start server.
EXPOSE 8080
CMD ["/app/bin/server"]
```

But has a lot of security issues:
![image](https://user-images.githubusercontent.com/21172855/219883449-b01a44cd-959b-4051-ad4d-ba72f790067c.png)

Is there any way to use alpine. Or even better the `scratch` image from docker?

**Comment by davidmartos96** [comment]
To correctly use the override you would need to find a file named libsqlite3.so in /usr/lib

/usr/bin/sqlite might exist in the Docker image, but that is the sqlite executable, not the dynamic library that Dart can load.

I haven't tried myself with Alpine, but it's possible that simply changing the override works for you

**Comment by vanlooverenkoen** [comment]
That is what I was trying but indeed using sqlite instead of libsqlite3.so. Which `libsqlite3.so` should I use for alpine?

**Comment by davidmartos96** [comment]
It's very likely that if you have multiple they are pointing to the same file. So the regular libsqlite3.so should work in theory.

**Comment by North101** [comment]
https://community.fly.io/t/dart-sqlite-on-fly-machines-server-crashes/10501/9

I've found this that might help. It uses `debian:bullseye-slim` instead of `alpine` though

The sqlite file looks like its located at `/usr/lib/libsqlite3.so`

**Comment by vanlooverenkoen** [comment]
Ah right good one!! First build the so lib before using scratch

**Comment by simolus3** [comment]
If you want to use `FROM alpine`, you can add the [sqlite-libs](https://pkgs.alpinelinux.org/package/edge/main/x86/sqlite-libs) package, which installs `/usr/lib/libsqlite3.so.0`. You can either add an open override in Dart to open that file, or just add a ` RUN ln -s /usr/lib/libsqlite3.so.0 /usr/lib/libsqlite3.so` to your `Dockerfile`.

Perhaps not the best way to do this, but this works for me for example:

```Dockerfile
FROM dart:2.19.2 AS build

COPY pubspec.yaml .
COPY foo.dart
RUN dart pub get
RUN dart compile exe foo.dart -o /bin/server

FROM alpine
RUN apk add --no-cache sqlite-libs
RUN ln -s /usr/lib/libsqlite3.so.0 /usr/lib/libsqlite3.so
COPY --from=build /bin/server /bin/server
COPY --from=build /runtime/ /

CMD ["/bin/server"]
```

(where `foo.dart` just prints `sqlite3.version` without any override). That said, since the Dart runtime ships a dynamically linked libc, you can probably just copy over your `libsqlite3.so` from the Debian based `dart:2.19.2` image after getting it via `apt install libsqlite3-dev`. I didn't try that though.

**Comment by vanlooverenkoen** [comment]
That did the trick. Still running into a permission issue on my side. But I will figure that one out. I can CRUD the database now.! Thanks. I will paste my dockerfile here once it is finished

**Comment by vanlooverenkoen** [comment]
My alpine dockerfile crashes after the database is opened. I thought it was a permission thing. but that is not the case I can open, read, delete, update files before I open the database. After the database is opened. The server just silently crashes.

Maybe because the file is not closed? Anyone who has an idea why it

**Comment by simolus3** [comment]
> Maybe because the file is not closed? Anyone who has an idea why it

Doesn't it crash directly when the database file is opened? In that case, it should probably be unrelated to the database not being closed.

> The server just silently crashes.

Do you see the exit code of that process at least? Is there a way for you to get a [core dump](https://ddanilov.me/how-to-configure-core-dump-in-docker-container) in the container?
And was this with the libsqlite3.so from Alpine or Debian? I wonder if there are any issues because Dart is linking to glibc from `/runtime` while the sqlite3 library from Alpine is compiled against muslc (and has `libc.musl-x86_64.so.1` as a needed dependency in its elf). Two libcs in the same executable sounds like trouble - sorry if I put you on the wrong path with the `apk add sqlite-libs` suggestion.

FWIW, this works for me (even with `FROM scratch`). I added this Dockerfile to `drift/example` in this repository:

```Dockerfile
FROM dart:2.19.2 AS build

RUN dart create foo && cd foo && dart pub add sqlite3 drift
COPY *.dart foo
RUN dart compile exe foo/main.dart -o /bin/server
RUN apt-get update && apt-get install -y libsqlite3-dev

FROM scratch

COPY --from=build /bin/server /bin/server
COPY --from=build /runtime/ /
COPY --from=build /usr/lib/x86_64-linux-gnu/libsqlite3.so /usr/lib/libsqlite3.so
CMD ["/bin/server"]
```

Running the resulting image shows the database being created. Granted, it's an in-memory database, but if I change that to a real file in `main.dart`, it still seems to work.
