### ISSUE TITLE
Using a dynamic type in a drift file

### ISSUE THREAD

**Issue by PlugFox** [simolus3/moor#2330]
`drift: 2.5.0`
`drift_dev: 2.5.2`

I want to create a table (without `STRICT` syntax) like that:
```sql
-- Key-Value table
CREATE TABLE IF NOT EXISTS kv (
    -- req Key
    k TEXT NOT NULL PRIMARY KEY,
    -- req Value
    v,
    -- req Created date (unixtime in seconds)
    meta_created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
    -- req Updated date (unixtime in seconds)
    meta_updated_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')) CHECK(meta_updated_at >= meta_created_at)
);

-- Indexes
CREATE INDEX IF NOT EXISTS kv_meta_created_at_idx ON kv (meta_created_at);
CREATE INDEX IF NOT EXISTS kv_meta_updated_at_idx ON kv (meta_updated_at);

CREATE TRIGGER IF NOT EXISTS kv_meta_updated_at_trig AFTER UPDATE ON kv
    BEGIN
        UPDATE kv SET meta_updated_at = strftime('%s', 'now') WHERE k = NEW.k;
    END;
```

And use column `v` as an `Object?`, but drift create `Uint8List?` for me instead.

**Comment by simolus3** [comment]
Drift respects the [column affinity](https://www.sqlite.org/datatype3.html#affname) as defined by sqlite3 here, which states:

> If the declared type for a column contains the string "BLOB" or if no type is specified then the column has affinity BLOB.

So I think the behavior is correct here. I think deviating from the column affinity is a dangerous game - we won't be able to get the generated static types fully right because SQL is dynamically typed, but here we are respecting the relatively clear typing rules defined by sqlite.

There is also no clear way to go from an unknown SQL type to Dart really. For instance, the SQL value `1` could be interpreted as `true`, `1` or `DateTime.fromMillisecondsSinceEpoch(1000)` depending on  the context and used options. So drift can't give you an `Object?` without a little more instructions on how to map the value.

> without `STRICT` syntax

What's the problem with `STRICT`? If you don't like the `DriftAny` type which is needed to distinguish the types (see the point about `1`), you can always write a type converter that unwraps `DriftAny` with your preferred expected type.

**Comment by PlugFox** [comment]
> Drift respects the [column affinity](https://www.sqlite.org/datatype3.html#affname) as defined by sqlite3 here, which states:
> 
> > If the declared type for a column contains the string "BLOB" or if no type is specified then the column has affinity BLOB.
> 
> So I think the behavior is correct here. I think deviating from the column affinity is a dangerous game - we won't be able to get the generated static types fully right because SQL is dynamically typed, but here we are respecting the relatively clear typing rules defined by sqlite.
> 
> There is also no clear way to go from an unknown SQL type to Dart really. For instance, the SQL value `1` could be interpreted as `true`, `1` or `DateTime.fromMillisecondsSinceEpoch(1000)` depending on the context and used options. So drift can't give you an `Object?` without a little more instructions on how to map the value.

I understand correctly that what I want I can not achieve with the help of the package?
And it will use **TYPE FOR SORTING** as a **STATIC COLUMN TYPE** instead of using dart's `Object` and `Object?` types?
I should create a column for each standard type with VIEW to merge them or use `TEXT` field and store JSON inside as a hack?


> > without `STRICT` syntax
> 
> What's the problem with `STRICT`? If you don't like the `DriftAny` type which is needed to distinguish the types (see the point about `1`), you can always write a type converter that unwraps `DriftAny` with your preferred expected type.

Absolutely no problem.
And most of the time I use it with STRICT.
But not in this particular case for key-value table.
As for converters - I don't use anything that the library brings over the standard SQL syntax for many reasons.

**Comment by simolus3** [comment]
> And it will use __TYPE FOR SORTING__ as a __STATIC COLUMN TYPE__ instead of using dart's `Object` and `Object?` types?

Column affinity is a static notion, while the type for sorting depends dynamically on the actual values being compared (with the exception of the conversion mechanisms defined in 4.2.). Column affinity also defines the conversion for inserts, so it's not a meaningless notion. But yes, drift doesn't support a general "any" type outside of strict tables.

Essentially, generating types based on column affinity and some type inference for expressions is the best we can do. Should we generate  `meta_updated_at` as an `Object` as well just because I can do `INSERT INTO kv VALUES ('foo', 3, 0, 'whatever');` and there is no guarantee of getting an int back? I don't see a compelling reason to migrate away from this strategy - it's not fully sound, but it's a good tradeoff. And under this logic, a column without a type is interpreted as a `BLOB`.

>  But not in this particular case for key-value table.

If you could share your motivation for not using `STRICT`or drift-specific SQL features, it would be easier for me to understand possible solutions here. Since this _is_ already possible by declaring an `ANY` column in a `STRICT` table (possibly with a type converter for convenience), I'm reluctant to change the (consistent) default interpretation here.

**Comment by PlugFox** [comment]
@simolus3 I need a key-value table and table for storing characteristics in addition to regular STRICT tables.

Key-Value is a like `shared_preferences` - it's a simple idea.
```sql
CREATE TABLE IF NOT EXISTS kv (
    k TEXT NOT NULL PRIMARY KEY,
    v
    -- extra meta fields
);
```
with mixin to `Database` to cache it inside `Map<String, Object?>`.
[EXAMPLE](https://gist.github.com/PlugFox/1b89a5b98c15c22b70b1c50bf598cabe)



A characteristics table is a feature to add "extra fields" for any table in the app on the fly, without modifying source DDL.
For example, you create a store with many goods for trade with many additional fields for every item.
Boots have a foot size (integer) and brand name (text).
Pants have a color (text) and several pockets (integer), and a length (integer).
Mobile phones have PDF documentation (blob)

And, of course, you need to add any new characteristics with their value on the fly, without migration and adding hardcoded new tables. Also, you should organize searches by these custom fields.

You can to something like this:
```sql
-- Characteristics table
CREATE TABLE IF NOT EXISTS characteristic (
    -- Type (e.g. source table name)
    type TEXT NOT NULL CHECK(length(type) > 0 AND length(type) <= 255),

    -- Source row/item id
    id NOT NULL,

    -- Extra value to add for any table any field of any type
    data NOT NULL,

    -- Composite primary key
    PRIMARY KEY (type, id)
);

-- option to create combined index by type + data
```

I **CAN DO it with SQLite**, but I can't with the `drift` package.
Because the package doesn't know anything about `Object` type.

And please, with **RAW SQLite** syntax, without any custom "converters" - using something like this in a schema is not a good engineering idea at all. It's not an option **AT ALL** use something extra on top of basic SQL syntax.

Right now I see only two hacks with this package:
1) `json` text values (pretty simple, but impossible to build indexes and search by values). 
2) creating many columns for each type (hard to search, and not convenient to use).

**Comment by simolus3** [comment]
> Right now I see only two hacks with this package:

What's the problem with writing a `STRICT` table with an `ANY` column? Your `kv` table can look like this, which is accepted by sqlite3:

```sql
CREATE TABLE IF NOT EXISTS kv (
    -- req Key
    k TEXT NOT NULL PRIMARY KEY,
    -- req Value
    v ANY,
    -- req Created date (unixtime in seconds)
    meta_created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
    -- req Updated date (unixtime in seconds)
    meta_updated_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')) CHECK(meta_updated_at >= meta_created_at)
) STRICT;
```

Drift will map `ANY` types to a `DriftAny` instance, which does not interpret the value we get back from sqlite3 in any way. If you don't want to apply a type converter, you could write your KV mixin like this (only showing the relevant methods):

```dart
mixin DatabaseKeyValueMixin on _$Database implements IKeyValueStorage {
  bool _$isInitialized = false;
  final Map<String, Object?> _$store = <String, Object?>{};

  Future<void> refresh() => select(this.kv).get().then<void>((values) {
        _$isInitialized = true;
        return _$store
          ..clear()
          ..addAll(<String, Object?>{
            for (final kv in values) kv.k: _sql2Dart(kv.v)
          });
      });

  void addKey(String key, Object? value) {
    assert(_$isInitialized, 'Database is not initialized');
    _$store[key] = value;
    into(kv)
        .insertOnConflictUpdate(
            KvCompanion.insert(k: key, v: Value(_dart2Sql(value))))
        .ignore();
  }

  DriftAny? _dart2Sql(Object? e) {
    return e == null ? null : DriftAny(e);
  }

  Object? _sql2Dart(DriftAny? sql) {
    return sql?.rawSqlValue;
  }
}
```

The same is true for `characteristic` - you can make the table `STRICT` and declare `id` and `data` as `ANY`.
