### ISSUE TITLE
send DirftIsolate by sendPort.send() failed - ArgumentError (Invalid argument: is a regular instance: Instance of 'DriftIsolate')

### ISSUE THREAD

**Issue by SungHyun22** [simolus3/moor#2334]
Hi simolus3, first of all thank you for good library!

## Bug Explain
please check below code
```dart
  Future createIsolate(MyDatabase database) async {
    final isolate = await database.serializableConnection();

    final ReceivePort receivePort = ReceivePort();
    await FlutterIsolate.spawn(
      _notificationIsolate,
      receivePort.sendPort,
    );

    final sendPort = await receivePort.first as SendPort;
    sendPort.send(isolate);
  }
```

I got ```DriftIsolate``` by  ```serializableConnection() ``` and I send it using ```SendPort.send()```. but I got this error.

```
ArgumentError (Invalid argument: is a regular instance: Instance of 'DriftIsolate')
```
I read a documentation. and I think ```DriftIsolate``` can be send by ```SendPort.send```. Am I wrong understand? There are a few things that make me suspicious. I use ```FlutterIsolate``` instead of normal isolate. that is the reason of this error? Or is this an error caused by sending ```DriftIsolate``` using a ```SendPort```?

### 1. Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1265], locale en-US)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.75.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

```
### 2. dependencies
```
  drift: ^2.5.0
  flutter_isolate: ^2.0.4
```

If you need more information just ask me :)

**Comment by simolus3** [comment]
From a quick look at `flutter_isolate`, it seems like that package is spawning a new Flutter engine to run the background code. Two different Flutter engines can only share some primitive objects, not user-defined Dart classes.

Drift can generally work around this by doing the serialization itself. What if you change the last line in the snippet to `sendPort.send(isolate.connectPort)`? The receiving end in `_notificationIsolate` can use `DriftIsolate.fromConnectPort` to reconstruct a `DriftIsolate` that will work across engines.

------

But it seems to me as there is no strong reason to use `flutter_isolate` anymore, considering that you can now get platform channels to work on background isolates without an additional package. Staying in the same engine has a strong performance benefit since we can skip the serialization.

**Comment by SungHyun22** [comment]
Thnak you!!
I solved the problem.
It's perfectly work :)
