### ISSUE TITLE
Cannot save downgraded schemaVersion 

### ISSUE THREAD

**Issue by aideric** [simolus3/moor#2336]
**Describe the bug**

If we downgrade schemaVersion in GeneratedDatabase (eg. user install old version of application), the MigrationStrategy onUpgrade will call every time when we start the application.

### Version ###
```yaml
drift: ^2.5.0
drift_dev: ^2.5.2
```

### Step to reproduce ###

1. Set the schemaVersion to 1
2. Build application
3. Set the schemaVersion to 2
4. Hot restart application
5. MigrationStrategy onUpgrade called normally
6. Hot restart application again
7. MigrationStrategy onUpgrade didn't call (normal)
8. Set the schemaVersion to 1
9. Hot restart application
10. MigrationStrategy onUpgrade called normally
11. Hot restart application
12. MigrationStrategy onUpgrade called again (abnormal)
13. Set the schemaVersion to 2
14. MigrationStrategy onUpgrade didn't call (abnormal)

**Comment by aideric** [comment]
Will there a onDowngrade function in MigrationStrategy?

**Comment by simolus3** [comment]
Most apps only support schema upgrades. To efficiently support downgrades, you'd have to know about future schema versions and revert their impact, right?

That `onUpgrade` is called multiple times is a drift bug that will be fixed in the next version, but I think for backwards compatibility and since this is very rarely used, we should continue to call `onUpgrade` once. At the moment, I don't see much value in a `onDowngrade` callback.
