### ISSUE TITLE
Generated schema files produce lint errors

### ISSUE THREAD

**Issue by gnprice** [simolus3/moor#2337]
When I generate schema files for testing migrations using the `drift_dev schema generate` command, the Dart analyzer gives me a series of messages like this:
```
   info • Unnecessary 'this.' qualifier •
          test/model/generated_migrations/schema_v1.dart:182:23 • unnecessary_this
```

The code in question looks like this:
```dart
class AccountsData extends DataClass implements Insertable<AccountsData> {
  // …
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is AccountsData &&
          other.id == this.id && // <---- lint error here
```

That's the only type of error I get from these files — just `unnecessary_this`, in the `==` implementation, in `class FooData extends DataClass`.

So I believe the fix can be to just drop the `this.`.

If there's a reason that the `this.` is sometimes necessary, then (rather than try to identify when it is or isn't) another solution would be to include a line `// ignore_for_file: unnecessary_this` in these generated files.

(I can work around this with an exclude in `analysis_options.yaml`, but best not to have to.)

**Comment by simolus3** [comment]
This will be fixed in the next drift version (my preferred workaround as of 
adc2e22c46bbbb0d33728a4d485feeb3cbaf62e8 is to just add a `ignore_for_file`, just like we're doing it for regular generated `.g.dart` files).

> So I believe the fix can be to just drop the `this.`.

This is kind of me being lazy, but getting this right in general is actually quite a chunk of work. We add the `this.` unconditionally as a guard (what if `AccountsData` had a field called `other` - we really want to compare that field with `this.other` instead of referring to the parameter `other`). Of course, we could add the special case for `other` and reference other fields directly, but there are so many scenarios where a `this` may be superfluous, and in some cases it depends on user-defined options or inputs.

In addition to this default lint, if you're linting code generated by drift we'd have to be compliant with your exact set of `analysis_options` rules, which as you can imagine adds a lot of complexity (some of the available rules contradict themselves, for instance).

**Comment by gnprice** [comment]
Thanks for the swift fix!

> what if `AccountsData` had a field called `other` - we really want to compare that field with `this.other` instead of referring to the parameter `other`)

Ah right, of course :-)

> Of course, we could add the special case for `other` and reference other fields directly

Yeah, I totally agree with you that this isn't a path worth going down.
