### ISSUE TITLE
Improve error message for DriftRemoteException when wrapping SqliteException

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#2340]
**Is your feature request related to a problem? Please describe.**
Seeing the change in [sqlite3 1.9.2](https://github.com/simolus3/sqlite3.dart/releases/tag/sqlite3-1.9.2) reminded me of a problem I come across when looking at `DriftRemoteException`s in Sentry - I often don't have parameters in the message.
I now update to `sqlite3: 1.9.2` and there are still no parameters, probably since I don't use prepared statements in those cases?

Is it possible to add the parameters also for non-prepared statements?

**Comment by kuhnroyal** [comment]
Hmm the issue may actually belong in the sqlite3 repository :o
After looking at the code I also now realize, that it `DriftRemoteException` only wraps the `SqliteException.toString()` because it is send between isolates. So the main question is, can we have parameters in all cases?

**Comment by simolus3** [comment]
> that it `DriftRemoteException` only wraps the `SqliteException.toString()` because it is send between isolates

`toString()` should contain a representation of the parameters as well though. That said, it seems like serializing exceptions is not necessary anymore if the two isolates are in the same isolate group, so we can avoid the `DriftRemoteException` wrapper in lots of cases (18f3c2a933ce4fcebb2e3712ac10c0f147a6846c).

> I often don't have parameters in the message

If there's a variable in the SQL query, we are always using prepared statements of some sort.
One thing that comes to mind is that we're not providing the parameters in the exception if the error happens while preparing the statement (before binding arguments) , mostly because we don't have that information at the place where the exception is thrown. I wonder if that could be the case, and whether drift should fill in the information then.

**Comment by kuhnroyal** [comment]
Hmm in my particular test I selected from a non-existent table. I basically just tried this from the example:

```dart
customSelect(
    'SELECT COUNT(*) AS c FROM todos WHERE category = ?',
    variables: [Variable.withInt(5)],
  )
  ```

**Comment by simolus3** [comment]
Yeah, I think that explains why the parameters aren't shown: The exception doesn't happen when running the statement, but rather while preparing it.

Since the exception would happen regardless of the parameters, I don't think adding the parameters to the exception is that useful in that case. But I'll add some context to the exception message, so that it will say `SqliteException(1): while preparing statement` vs `SqliteException(1): while executing statement <with args and parameters>`, maybe that makes it clearer why an exception has happened (if it happened while preparing the statement, the actual parameter values could not have been part of the problem).
