### ISSUE TITLE
Querying the json 

### ISSUE THREAD

**Issue by Raghunandan** [simolus3/moor#235]
I know we can store the JSON as TextColumn using TypeConvertor, but is it possible to query depending on the data stored in the JSON. I want to do something like below:

**Create User Table:** 
_table user(name varchar(20), data varchar(100));_ 

**Insert json to data of the column:**
 _insert into user values("oz", json('{"cell":"+491765", "home":"+498974"}'));_

**Query on JSON data:**
_SELECT * FROM farmer WHERE json_extract(data, '$.home') = "+498974";_

**Comment by simolus3** [comment]
This would require the [JSON1 extension](https://www.sqlite.org/json1.html) which isn't available on Android. With `moor_ffi`, we compile sqlite ourselves, so we could include some extensions like JSON1. I'm not sure about adding first-class support for that in `moor` if it's only supported by some platforms, but a `CustomExpression` could help.

**Comment by simolus3** [comment]
In the next moor version, we're going to compile the json1 extension for `moor_ffi` users, so it will work on Android. It might not work on older iOS versions though.

We're definitely going to provide high-level apis for json1, but they would be behind an additional import (`package:moor/extensions/json1.dart`). Json columns are just text, so you would create the table like before:
```dart
class Users extends Table {
  TextColumn get name => text().withLength(max: 100)();
  TextColumn get data => text().withLength(max: 100)();
}
```
A query on json data in Dart could look like this
```dart
select(users)..where((u) => u.data.jsonExtract('$.home').equals('+49874'));
```

We're probably only going to expose the `json_array_length` and `json_extract` functions for the Dart api. Would that be enough for your use case, @Raghunandan?

I'm not entirely sure how the `json_*` functions should be available for compiled queries in moor files. Since they're not available on all platforms, we'd probably have hide them as a build option for now. The compiler should support all json functions except for `json_each` and `json_tree`, which require considerably more work to implement.

**Comment by Raghunandan** [comment]
Thanks. We are okay about not supporting the older version of iOS.
I'm yet to explore moor_ffi, I'll start to look into it and come back. Does moor_ffi support the writing raw SQL queries?

**Comment by simolus3** [comment]
> Does moor_ffi support the writing raw SQL queries?

Yes. moor_ffi is an alternative to moor_flutter, so all common operations are supported. Most apis are actually defined in the moor package. Everything moor_ffi and moor_flutter are doing is executing the sql statements generated by moor.

At the moment, ffi on Flutter still has some problems, so moor_flutter is still the best option for most apps. I expect that those will be resolved soon though.

**Comment by simolus3** [comment]
I'm closing this since json1 apis will be exposed in the next moor update.

**Comment by kanekv** [comment]
@simolus3 do you happen to know which ios version added json support? Thanks!

**Comment by simolus3** [comment]
IIRC it's iOS 11 and above. Note that you can also include a custom sqlite version with your app - see #547 for more. It will slightly increase your app size (by around 700kb or so), but then you can be sure that `json1` is available on all devices your app runs on.

**Comment by kanekv** [comment]
@simolus3 thanks!
