### ISSUE TITLE
Schema test code generation

### ISSUE THREAD

**Issue by WoodyMKD** [simolus3/moor#2353]
**Description**

I have a table that uses UUID as primary key:

`contact_entity.dart:`
```dart
class ContactEntity extends Table {
  TextColumn get id => text().clientDefault(() => uuid.v4())();
  TextColumn get firstName => text().nullable()();
  
  // omitted code

  @override
  Set<Column> get primaryKey => {id};
}
```

Then I've generated the schemas and the testing code from the generated json schemas:
```dart run drift_dev schema dump lib/core/storage/eon_database.dart lib/core/storage/schemas```
```dart run drift_dev schema generate lib/core/storage/schemas/ test/core/storage/generated_migrations```

Unfortunately the generated code doesn't import the UUID package, hence the `uuid.v4()` part is erroneous in the following section: 

`test/core/storage/generated_migrations/schema_v1.dart:`
```dart
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
      'id', aliasedName, false,
      type: DriftSqlType.string,
      requiredDuringInsert: false,
      clientDefault: () => uuid.v4());
```

`Undefined name 'uuid'.`

**Comment by simolus3** [comment]
Thanks for the report! This is a regression from #1240 which has been fixed again in 04539882330d80519128fec1ceb120fb1623a831.

This will be fixed in the next `drift_dev` release. To work around this problem in the meantime, you can remove the `default_client_dart` json key in the generated JSON schema file.
