### ISSUE TITLE
Spatialite databases and virutal postgres

### ISSUE THREAD

**Issue by Sc07713** [simolus3/moor#2356]
Hi There,

Sorry if this question has been asked before.

I am seeking to find out whether drift integrates well with spatialite databases.

I havent tested it myself yet, but this is a contingent component in the next application I was seeking to develop.

All the best 

Scott

**Comment by simolus3** [comment]
> I am seeking to find out whether drift integrates well with spatialite databases.

Spatialite is a sqlite3 extension, which means that you can generally use drift with those databases, yes. Drift doesn't have any built-in support for any of the functions that Spatialite adds to sqlite3 though. However, that doesn't mean that drift can't be used with those databases.

1. You can use methods like [customSelect](https://drift.simonbinder.eu/api/drift/databaseconnectionuser/customselect) or [customStatement](https://drift.simonbinder.eu/api/drift/databaseconnectionuser/customstatement) in drift to run custom SQL statements that otherwise couldn't be constructed with drift. Granted, drift doesn't provide many benefits when doing that, but there are alternatives.
2. For instance, drift's query builder API in Dart is pretty easy to extend. For instance, you could access Spatialite functions by using a [FunctionCallExpression](https://drift.simonbinder.eu/api/drift/functioncallexpression-class) or a [CustomExpression](https://drift.simonbinder.eu/api/drift/customexpression-class). Of course, you can add your own extensions or helper methods that construct these expressions for tables that need them. You can then use these custom expressions [in joins](https://drift.simonbinder.eu/docs/advanced-features/joins/) or with `addColumn`. With those API, you can access the Spatialite-specific extensions through drift's general query builder.
3. Finally, if you've been using direct SQL queries to access Spatialite before, you can use [drift files](https://drift.simonbinder.eu/docs/using-sql/drift_files/). Essentially, you just give SQL queries a name there. Drift will check the queries for validity and generate methods for them. You can add Spatialite functionality to drift files with [known custom functions](https://drift.simonbinder.eu/docs/advanced-features/builder_options/#known-custom-functions), see also [this discussion](https://github.com/simolus3/drift/discussions/2295).


So in the end, you'll have to write some parts yourself if you want a good integration between drift and spatialite. But even if you don't do that and end up using `CustomExpression`s or direct SQL for queries that need Spatialite functions, drift will probably still save you some work. So I'd say it's still a good fit for apps needing those extensions.

I hope the links to the documentation or drift classes are a good starting point for this. I can provide more guidance if you run into specific questions on the way.

**Comment by bettdouglas** [comment]
Hello @simolus3 I'd be interested in creating support for this. Could you please guide me on how we can use one of the above techniques there to say
1. Create a Column called `PointColumn` just like `IntColumn` or `TextColumn` which maps to an object of type `Point`. 
2. How to enable the `PointColumn` to enable us to a query like the following. 

```dart
class Users extends Table {
  TextColumn get id => text()();
  PointColumn get location => point()(srid: 4326)();
}

class Town extends Table {
  TextColumn get id => text()();
  PolygonColumn get boundary => polygon()(srid: 4326)();
}

class Point {
  final double latitude;
  final double longitude;
  Point(this.latitude,this.longitude);
}

class Polygon{
   final List<Point> ring;
   Polygon(this.ring);
}

@DriftDatabase(tables: [BuyableItems, Users])
class MyDatabase extends _$MyDatabase {
  MyDatabase({
    required this.queryExecutor,
  }) : super(queryExecutor);

  final QueryExecutor queryExecutor;

  @override
  int get schemaVersion => 2;
  List<User> get usersInTown(int townId) {
         select(users)..where((tbl) => 
            tbl.location.isWithin(towns..where((townsTable)=>townsTable.id.equals(townId)));
   }
}
```
The SQL query will map to 
```sql
select * from users u
join towns t on st_within(t.boundary,u.location)
where t.id == [id]
```

4. Conversion of data from postgis and to postgis will be handled by another library. 
5. Also spatialite and postgis data types are stored in the database as `Geometry` which can be `Point`, `Polygon`, `Linestring` etc. 

I appreciate the help or guidance you'll give.

**Comment by simolus3** [comment]
> Create a Column called `PointColumn` just like `IntColumn` or `TextColumn` which maps to an object of type `Point`.

You can't, these are handled by `drift_dev`. But AFAIK spatialite doesn't have a dedicated geometry type, you just declare those as `BLOB` columns, right? So you could use drift's support for blobs and a [type converter](https://drift.simonbinder.eu/docs/advanced-features/type_converters/) to map them to Dart values by following [the spatialite format](https://www.gaia-gis.it/gaia-sins/BLOB-Geometry.html).

> How to enable the `PointColumn` to enable us to a query like the following.

Define an extension for the nice `isWithin` API, then construct the function call internally:

```dart
extension on Expression<Uint8List> {
  Expression<bool> isWithin(Expression<Uint8List> other) {
    return FunctionCallExpression('st_within', [this, other]);
  }
}
```

**Comment by bettdouglas** [comment]
Thanks for that quick answer. 

> You can't, these are handled by drift_dev. But AFAIK spatialite doesn't have a dedicated geometry type, you just declare those as BLOB columns, right? 

I haven't used spatialite extensively, so I'm not sure. But in postgis for postgresql, the data type is  called `Geometry`. Is it possible to extend drift_dev to add support for such columns, so that when running migrations, we can have a create statement that looks like.
```sql
CREATE TABLE users(
    id INT PRIMARY KEY AUTOINCREMENT,
    location geometry(point, 4326)
);
CREATE TABLE towns(
    id INT PRIMARY KEY AUTOINCREMENT,
    location geometry(polygon, 4326)
);
```

**Comment by simolus3** [comment]
No, that is not possible without forking drift, since those columns would also have to have a corresponding `GeneratedColumn` and `SqlTypes` implementation.
