### ISSUE TITLE
Drift web related build errors

### ISSUE THREAD

**Issue by tangenttechno** [simolus3/moor#2359]
@simolus3 I tried drift example [app](https://github.com/simolus3/drift/tree/develop/examples/app) tried web related commands. It's working fine, but showing weird errors. Please see attached images.  Did I miss something?
<img width="550" alt="Screenshot 2023-03-26 at 4 06 14 PM" src="https://user-images.githubusercontent.com/112683333/227770161-08437c2a-943b-4678-b7e7-2218307bf117.png">
<img width="475" alt="Screenshot 2023-03-26 at 4 06 28 PM" src="https://user-images.githubusercontent.com/112683333/227770166-a786fbeb-1ada-4716-bee7-6c6dc539720f.png">

**Comment by simolus3** [comment]
How where those files generated, why is there a copy of your entire dependency graph in `web/packages`? :D They probably shouldn't be there - and since they're not part of the project they shouldn't be analyzed in the project's context.

**Comment by tangenttechno** [comment]
@simolus3 thank you for this awesome project. I am new to drift, so not sure which steps to follow. So initially I checked out the official [app](https://github.com/simolus3/drift/tree/develop/examples/app) example and then ran the command `flutter build web` then `flutter run -d chrome`. Chrome launched successfully. But showed the loading icon infinitely. when I checked the dev console found that workers were not loaded. Then I followed the official [web](https://drift.simonbinder.eu/web/) tutorial executed following commands
`flutter pub run build_runner build --delete-conflicting-outputs -o web:build/web/`
`cp -f build/web/worker.dart.js web/worker.dart.js`
files 'shared_worker.dart.js' was generated. After that when I ran `flutter run -d chrome` everything worked successfully but got the above-mentioned error in vs code. Am I missing something or following the wrong steps? 
My second question is when I try to bring drift web to my existing project by copying 'sqlite.wasm', 'worker.dart',tools folder, 'lib/database' folder, and'build.yaml'   I get sqlite related compilation errors . But if I start from the official app project as a template and copy all my existing code to the same , it works fine . I am missing some thing here?  Please help.

**Comment by simolus3** [comment]
> Am I missing something or following the wrong steps?

I think the documentation is just not ideal here, I'll update it. We use `build_web_compiler` to compile the shared web worker to JavaScript, something that needs to happen outside of the regular Flutter compilation toolchain.

You can look at [this example](https://github.com/simolus3/drift/tree/develop/examples/flutter_web_worker_example) for a script (`generate_js.sh`) that runs the build with `-o web:build/web`, copies over the shared worker and deletes everything else (so that you don't get those warnings).
An alternative is the setup used in the `app` example itself, which uses a custom builder (`tool/builder.dart` and `build.yaml`) that will automatically copy the worker when running `build_runner build` (no `-o` flag is necessary here at all).

>  I get sqlite related compilation errors

Could you post them? Be aware that you need conditional imports like [these](https://github.com/simolus3/drift/blob/develop/examples/app/lib/database/connection/connection.dart) since we can't import the regular sqlite3 on the web at all.

**Comment by tangenttechno** [comment]
@simolus3 I created a new project and followed above said steps and executed `generate_js.sh` as an extra step, then ran `flutter -d chrome` which launched successfully without any compilation error. Thank you for the help.

**Comment by tangenttechno** [comment]
@simolus3 official app example doesn't work in safari. In chrome(left side), it works as expected. In safari(right side) shows a loading icon forever. Please see attached pics.
<img width="1437" alt="Screenshot 2023-03-29 at 9 40 00 PM" src="https://user-images.githubusercontent.com/112683333/228601354-2b403f9c-362f-4ada-b43e-18a9215b9938.png">
<img width="1435" alt="Screenshot 2023-03-29 at 9 40 46 PM" src="https://user-images.githubusercontent.com/112683333/228601392-ad43a9cf-0585-436d-8fb0-92a6c78372e2.png">

**Comment by tangenttechno** [comment]
@simolus3 above-mentioned issue, can you cross check?

**Comment by simolus3** [comment]
I can reproduce the problem. This only happens in workers in Safari. It seems like the problem is using the `http` client to load sqlite3, which uses `XMLHttpRequest`s. Those generally aren't available in workers, but it looks like the request is still made. However, we then receive `XMLHttpProgressEvent`s, even though that class isn't defined in the global scope for workers (which is pretty weird, but again we're not supposed to use that API in workers).

I'll take a look if using the `fetch` API could fix this.

**Comment by simolus3** [comment]
Seems like using fetch fixes the problem - I've made those changes on the `wasm-improvements` branch which fixes the problem in Safari for me.

I've also opened a Dart SDK issue for this (https://github.com/dart-lang/sdk/issues/51918), although I guess this is a Safari problem that they won't be able to do much about. There should also be a way to do this without requiring a new dependency, I'll take a look at making these changes as well.

**Comment by tangenttechno** [comment]
@simolus3 Thank you for the reply. I checked out `wasm-improvements` branch, ran `flutter pub get` then `flutter run -d chrome` I get a compilation error. Please see the attached image. I removed .pub-cache/hosted/pub.dev/drift-2.6.0 folder and tried again, getting the same error. Please let me know your thoughts.
<img width="569" alt="Screenshot 2023-04-02 at 6 15 43 AM" src="https://user-images.githubusercontent.com/112683333/229324640-75c6232e-a3b6-418a-a090-bd7281c153c5.png">

**Comment by simolus3** [comment]
I've used the branch to work on some improvements that will make drift much easier to use with workers soon. That introduced some new APIs used in the example that haven't been published yet.

Regarding the original problem of using fetch, you can see 697da450bce51c63ae8c6326c85cf9c4adab097d for the original fix that doesn't require the new version yet.

The good news is that all of this will become _much_ easier soon :D

**Comment by tangenttechno** [comment]
@simolus3 worked fine after merging [697da45](https://github.com/simolus3/drift/commit/697da450bce51c63ae8c6326c85cf9c4adab097d) changes.  Thank you.
<img width="1244" alt="Screenshot 2023-04-07 at 8 58 48 AM" src="https://user-images.githubusercontent.com/112683333/230535194-1bf0da77-06d1-46fd-9933-d210c1ed84e7.png">
