### ISSUE TITLE
cannot query table at first time the app launched

### ISSUE THREAD

**Issue by cruvie** [simolus3/moor#2375]
**Describe the bug**
when I launch the app ,the func initState() is in the first page and will execute automatically , but the result is always empty
If I use a buttom to trigger   loadChatItemList() , it can query the data

 I supposed that may due to the DB is still initializing ,but there's no error or warning 

```dart
  @override
  void initState() {
    super.initState();
     loadChatItemList() ;
  }
  loadChatItemList() async {
    chatItemList.value = await (DBUtil.db.select(DBUtil.db.localChatItems)
          ..where(
              (a) => a.userId.equals(BigInt.parse(LogicUser.to.myPBUserInfo.value.id.toString())))
          ..orderBy([(t) => OrderingTerm(expression: t.unreadCount, mode: OrderingMode.desc)]))
        .get();
    debugPrint(chatItemList.length.toString());// 0 first time 
    chatItemList.refresh();
    for (var element in chatItemList.value) {
      debugPrint(element.toString());
    }
  }

```

**Comment by simolus3** [comment]
What does `chatItemList.refresh()` do that might make it non-empty? Is that also doing a select? (would surprise me since it's not awaited). If you refactor the code to

```dart
    final rows = await (DBUtil.db.select(....).get();
    chatItemList.value = rows;
```

And set a breakpoint on the second line, is `rows` empty too? I'm trying to figure out if this comes from the database or from whatever `chatItemList` is.

**Comment by cruvie** [comment]
> 

Thanks for your response, I record a screen, and with the code that you given.
First I doubt whether the DB no initialized, here is my way to initialize
```dart
//main
main() async {
  WidgetsFlutterBinding.ensureInitialized();
  DBUtil.initDB();
```
```dart
class DBUtil {
  // 定义一个全局的database
  static late MyDatabase db;

  static initDB() {
    // 初始化
    db = MyDatabase();
  }
}
```
```dart
@DriftDatabase(tables: [LocalChatItems])
class MyDatabase extends _$MyDatabase {
  // we tell the database where to store the data with this constructor
  MyDatabase() : super(_openConnection());

  // you should bump this number whenever you change or add a table definition.
  // Migrations are covered later in the documentation.
  @override
  int get schemaVersion => 4;
}
LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase(file);
  });
}
```
any problem?
https://user-images.githubusercontent.com/55651847/231029462-c2e330ab-4302-4243-8264-aff57b8f7cf4.mov

**Comment by simolus3** [comment]
Thanks for the additional details! Since this happens at every launch (meaning that the data is surely already in the database), maybe the problem is still in another place?

In `_openConnection()`, could you change the last line to `return NativeDatabase(file, logStatements: true)` to investigate what SQL is being generated? When `loadChatItemList()` is called twice, does that generate the same SQL or is the first one different?
Could it be that `LogicUser.to.myPBUserInfo.value.id` is not properly initialized at the first call?

**Comment by cruvie** [comment]
@simolus3  wow , thank you so much, How could I forget such a useful tool `NativeDatabase(file, logStatements: true)`, and you are right the `LogicUser.to.myPBUserInfo.value.id` doesn't initialized before the SQL run (though the initial function is before `await (DBUtil.db.select(....).get();`, but it doesn't matter, I have put the initial func to main() and it works fine.)
