### ISSUE TITLE
Feedback wanted: Drift on the web

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#2382]
Drift currently has two web implementations that are both marked as experimental. They are marked experimental because, even though they generally work, the approaches have some performance or correctness issues.

1. The approach based on `sql.js` (`package:drift/web.dart`) needs to export the whole database as a single blob after each write for persistence, which is obviously very inefficient. We also have some issues binding parameters to statements because the underlying JavaScript library doesn't export a type-safe way to do this.
2. A newer approach (`package:drift/wasm.dart`) doesn't require external JavaScript and can use a fake file system based on IndexedDB to implement the storage. This is much more efficient, but IndexedDB is an asynchronous API and sqlite3 expects a synchronous file system. This leads to us doing an in-memory cache and eventual writes which may get lost if the tab is closed/crashes at the wrong time.

The File System Access API is supported by Chrome and Firefox (with Safari support being available in Technology Preview builds) and allows websites to access app data synchronously. Tests I've been doing with this API in the sqlite3 package have been showing very promising results.

To evaluate what's needed for a drift web implementation, __I need to know how you want to use drift in your web apps__. If you have the time, answering these questions or any trouble you ran into would be very helpful and much appreciated!

1. Are you using drift on the web already? Or did you have an interest / plan for this but stopped due to the "experimental" label? Did you run into lost data or any other issues with the existing implementations, or are they working well for you?
2. It is likely that storage implementations won't work everywhere (some browsers disable them in private/incognito windows, users might be using an older browser not implementing the necessary APIs, ...). Under the assumption that it works in the latest version of all major browsers under regular circumstances, would a fallback approach of  "warn the user that persistence isn't available and fall back to an in-memory database" work for you? Or would your app not work at all in those instances?
3. How important is it for you to have real-time synchronization of the database between multiple tabs? Are users likely to open multiple tabs of your app and require database access in both of them? Would it be unacceptable if only a single tab could open a drift database at a time?
4. Related to question 3, is the situation the same about Chrome for Android (which doesn't support shared workers)? Is it acceptable if drift apps can't be shared between tabs only here?

Feedback on those questions, or anything else you think is important for me to know regarding drift on the web, would definitely help a lot to get this stable! (E.g. if the IndexedDb approach is working well for you, I can focus on writing more tests for that and declare it stable too).

And to clarify, I have no intention of discontinuing the existing APIs. This issue exists to get feedback and ideas for a way to get a stable drift web implementation. I will continue to maintain the existing implementations and we will offer migration APIs between the storage implementations, so there's no risk to existing apps.

**Comment by stx** [comment]
Thanks for your work on this!

1. Already using the existing web implementation using IndexedDB. Pretty solid with the exception of https://github.com/simolus3/sqlite3.dart/issues/128.

2. In our case the most important thing is to just make it work invisibly. If there's no data because it's in-memory and didn't persist, it would just sync again on page load. It wouldn't be an issue. No user-facing errors please - that would be a dealbreaker.

3. Synchronization between tabs is not very important, but if the database couldn't be opened in multiple tabs that basically means our app can't be opened in multiple tabs, and that would be a huge issue and a dealbreaker for using Drift.

4. That sounds totally acceptable for us.

To eliminate the issue in 1, we've migrated from Drift 2.5.0 to 2.7.0 and using your new `WasmSqlite3.loadFromUrl()` method and have seen a couple new unexplained errors:

https://github.com/simolus3/drift/issues/2387 (possibly due to Drift 2.7.0)
https://github.com/simolus3/drift/issues/1773

**Comment by rodydavis** [comment]
Also some exciting news: https://www.npmjs.com/package/@sqlite.org/sqlite-wasm

There is now an option to use [origin private file system (OPFS)](https://developer.chrome.com/articles/origin-private-file-system/#:~:text=The%20File%20System%20Standard%20introduces,is%20highly%20optimized%20for%20performance.) for the wasm version now. If it is available it will persist the file directly.

I love drift on the web and use it in a lot of my apps.

For the tabs and syncing I don't use it for a ACID backend but more for a fast firestore offline cache.

**Comment by simolus3** [comment]
Yeah essentially my idea is to replicate that in Dart (we already have basic OPFS support in the `sqlite3` package but it's quite hard to use).

My idea for this API is, instead of you having to load sqlite3 manually and set up the file system, we get back to a `package:drift/web.dart`-style API where you just give a database name and drift does everything in the background. We'd still expose the inner layers for more complex setups, but hopefully now that OPFS is about to work in all major browsers we can have very reliable defaults.

Depending on what the browser supports, I see different ways to implement this that drift can automatically try out to pick a suitable strategy:

1. Use a `SharedWorker` for database synchronization across tabs which internally uses a dedicated worker for OPFS. This is my favorite solution by far (already implemented today), but only works in Firefox because Chrome and Safari don't support shared workers spawning dedicated workers. 
2. If that's not available, we need to use two workers per tab: One hosting the file system, and another one hosting the database. They need to use `Atomics` hacks for a synchronous FS access. This is what the NPM package you've linked is doing today. A downside is that `Atomics` is only available when serving the JS file with special security headers, so it will make Flutter apps harder to deploy.
   - We could still use shared workers for stream query synchronization, or just use a broadcast channel. 
   - If I find a friendly CDN to host the worker and the Wasm file we could serve it correctly and users don't need any special setup at all unless they decide to host those files themselves.
3. If workers or OPFS aren't available, we'd probably fall back to an in-memory database (with a way to notify the app developer about this).

**Comment by nullrocket** [comment]
Just thought I would mention that I implemented part 2 of this strategy a while back,  I originally implemented shared workers but just simplified back to a regular worker though, mostly because my use case was to **not** have a shared worker.    

A bit of a hack but you can have COOP and COEP headers using service workers doing something like https://github.com/gzuidhof/coi-serviceworker, this works for flutter apps with a few changes to the index.html  but I would only rely on it if I couldn't set headers for example on demos on github pages.

Anyway here is an example using atomics for sync fs access and a service worker to set COEP and COOP headers.  This example happens to be using an encrypted version of sqlite3.

https://thinkassembly.github.io/sqlite3mc.dart/app/#/

**Comment by JCKodel** [comment]
I know it is not officially supported, but many browsers already support SQLite (Chrome 114-116, Edge 113, Opera 99, Chrome for Android 113, Samsung Internet 21, Opera Mobile 73, Android Browser 113, etc.)

If supported on the browser, and extensions are not used, would this be a better solution, making it some other option as a fallback?

EDIT: there are also some other options such as https://github.com/jlongster/absurd-sql (it seems it makes the same filesystem inside indexeddb, but in chunks)

**Comment by simolus3** [comment]
> but many browsers already support SQLite

The _-116_ part of Chrome's version range is quite telling ;) This has never been a properly standardized web API. With an increased adoption of WASM, I expect that other browsers will start deprecating this as well.

Also, I'd like to provide a sqlite3 build with consistent options on all platforms (so you can expect that you get the latest sqlite3 with JSON and FTS5 support on all platforms).

> EDIT: there are also some other options such as https://github.com/jlongster/absurd-sql (it seems it makes the same filesystem inside indexeddb, but in chunks)

Something similar is implemented with a `WasmDatabase` today [as well](https://github.com/simolus3/sqlite3.dart/blob/main/sqlite3/lib/src/wasm/file_system/indexed_db.dart), but it lacks the shared-memory synchronization primitives.

I've pushed a first version of the new APIs to the `web-v2` branch. It implements the following storage implementations and starts a feature detection at runtime to pick the best one:

1. OPFS in a shared worker spawning a dedicated worker internally. This approach is very reliable and performant, but unfortunately only works on Firefox because Chrome and Safari don't allow shared workers to spawn dedicated workers despite that being a standardized feature.
2. "What absurd-sql is doing, but with OPFS". This is also what the official wasm variant of sqlite3 is doing, but implemented in Dart. This mechanism requires the COEP and COOP headers though.
3. An IndexedDB-hosted file system in a shared worker.
4. A per-thread IndexedDB file system without synchronization (unsafe, but also what we're currently doing by default).
5. If nothing else works, an in-memory database.

We can use approach 1 in Firefox, 2 in Chrome and Chromium-based browsers (soon in Safari too) and 3 in Safari stable. The APIs have also been designed in a way that you no longer need to compile your own web worker, you'll be able to download a precompiled one that I can attach to drift releases.

**Comment by simolus3** [comment]
Drift 2.9.0 has just been released and contains the features described here :) Thank you all for the helpful feedback!

**Comment by FaFre** [comment]
Since I just recently started using the wasm implementation, I want to use this issue to provide some feedback (@simolus3 please let me know if I should branch this out in a separate issue).

I added web support to my (previously) native only database handling, and must say I was really astonished by how little work was required to get an up and running application! Drift is really doing an exceptional job here!

Since my application let's the user create an arbitrary number of databases I need access to the filesystem to determine and list the available databases.

Migrating this scenario I have the following suggestions:
- It should be possible to determine the available `WasmStorageImplementation`s by exposing the API. From my understanding it is not possible to call `proble()`from outside the drift package (preferably without connecting to any database).
- It should be possible to blacklist certain `WasmStorageImplementation`s. E.g. some apps are getting useless with only in memory support. Other implementation like `unsafeIndexedDb` are introducing possible side effects. It should at least be possible for the developer to find out on the forehand, which implementations are available and which one is preferred. Right now the logic for that is in `open()` where also some checks on existing databases are happening. It would be great to outsource this logic, so developers can implement their own logic based on that and use `openWith()` to specify the implementation.

How the OPFS implementation is really working is not clear to me. I couldn't get it up and running, since it also seems that it is not possible to use this implementation with a standard debug setup. It would be great to also have this easily available like `IndexedDbFileSystem.databases()` from the outside.

**Comment by simolus3** [comment]
Thanks, this is helpful feedback! I agree that we should give application developers more control over the storage implementation they want to use.

> Since my application let's the user create an arbitrary number of databases I need access to the filesystem to determine and list the available databases.

I'll add this information to the probe result, but we likely won't be able to report this reliably for IndexedDB because the relevant web API has not been implemented by Firefox yet (and since there is no easy way to distinguish a drift database from any other indexeddb database). We can do this for OPFS though.

> How the OPFS implementation is really working is not clear to me. I couldn't get it up and running, since it also seems that it is not possible to use this implementation with a standard debug setup

Did https://github.com/simolus3/sqlite3.dart/issues/174 work for you after changing the header consistently? I agree it's unfortunate that it doesn't work with Flutter out of the box. Do you know if there's a way to get the Flutter tool to start Chrome with special flags? When started with the `--enable-features=SharedArrayBuffer` option, the required features should be available without any headers.

**Comment by FaFre** [comment]
Yes, the sqlite3 example is working with OPFS now.

> Did [simolus3/sqlite3.dart#174](https://github.com/simolus3/sqlite3.dart/issues/174) work for you after changing the header consistently? I agree it's unfortunate that it doesn't work with Flutter out of the box. Do you know if there's a way to get the Flutter tool to start Chrome with special flags? When started with the `--enable-features=SharedArrayBuffer` option, the required features should be available without any headers.

I think it is! I found https://github.com/dart-lang/webdev/issues/1080#issuecomment-1270339480 and updated my VSCode launch config accordingly:
```json
{
    "name": "app",
    "cwd": "examples/app",
    "request": "launch",
    "type": "dart",
    "args": [
        "--web-browser-flag",
        "--enable-features=SharedArrayBuffer"
    ]
},
```

However, I don't have luck. Drift is falling back to `unsafeIndexedDb` (it's the same case for my migrated project, I wonder why the shared implementation is not getting used? `driftWorkerUri` is specified)

**Comment by simolus3** [comment]
After cloning the repository, you need to run the build in `examples/app` once for the right worker JS to be emitted. I think this might be the cause for `unsafeIndexedDb` getting chosen in the end - but you can check the missing features for details and see if they mention workers.

This configuration makes drift pick `opfsLocks` for me:

```json5
{
    "name": "app",
    "cwd": "examples/app",
    "request": "launch",
    "type": "dart",
    "args": [
        "--web-browser-flag=--enable-features=SharedArrayBuffer",
    ]
},
```

**Comment by FaFre** [comment]
Yup, after rebuilding thw worker, opfs is available now. 

I also added the build step into my application (copied from the app example), so I don't forget to update the .js file manually from the releases each time (and probably experience some nasty side effects from that). 

Could the build be probably included into `drift_dev` directly? So that users can easily configure their build.yaml by adding a flag like:
```yaml
builders:
  drift_dev:
    options:
      build_web_worker: yes
```
The builder could directly output the js file into the `/web` or any other directory (in case the database has been outsourced into a separate package). Maybe the `driftWorkerUri` could then also made optional by using `drift_worker.js` as default.

Btw, I found a pretty cool chrome extension (https://github.com/tomayac/opfs-explorer) or (https://chrome.google.com/webstore/detail/opfs-explorer/acndjpgkpaclldomagafnognkcgjignd) that allows to easily inspect the opfs files (since the DevTools doesn't seem to have out of the box support for that). It also allows the export of files e.g. databases, which will be great for debugging with SQL tools outside the app :)

**Comment by simolus3** [comment]
> (and probably experience some nasty side effects from that)

I'm actually aiming towards having a stable communication interface between the two, so you can upgrade drift without existing code breaking (but we won't fully support `WasmDatabase.probe` and definitely no deletions with an older worker).

> Could the build be probably included into `drift_dev` directly?

That's interesting, but it's probably not easy to do since you'd still need `build_web_compilers` as a dependency.

> Btw, I found a pretty cool chrome extension (https://github.com/tomayac/opfs-explorer)

Yeah I'm using it to debug drift, it's pretty neat :)
