### ISSUE TITLE
Unsupported operation: Could not access the sql.js javascript library

### ISSUE THREAD

**Issue by stx** [simolus3/moor#2383]
After migrating to `WasmSqlite3.loadFromUrl`, occasionally getting the below error in Sentry on production in Chrome.

```
Unsupported operation: Could not access the sql.js javascript library. The drift documentation contains instructions on how to setup drift the web, which might help you fix this.
```

Implementation:

```
Future<Database> openDatabase({bool logStatements = false}) async {
  IndexedDbFileSystem fs = await IndexedDbFileSystem.open(dbName: 'db');

  WasmSqlite3 sqlite = await WasmSqlite3.loadFromUrl(
    Uri.parse('sqlite3.wasm'),
    environment: SqliteEnvironment(fileSystem: fs),
  );

  return Database(
    WasmDatabase(
      sqlite3: sqlite,
      path: '/app.db',
      logStatements: logStatements,
    ),
  );
}
```

**Comment by simolus3** [comment]
That error is only thrown by the `package:drift/web.dart` library. Since you're not using a `WebDatabase`, you should not be seeing this error at all :confused:.

Do you see which version of your app was running when this exception was thrown? I think this probably a cache inconsistency issue when older versions of your app using `sql.js` are trying to use the new `sqlite3.wasm` built for a `WasmDatabase`.
