### ISSUE TITLE
.drift parsing pointing error in the wrong place

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#2391]
Consider the following .drift file:

```sql
CREATE TABLE SyncChanges (
  table           TEXT      NOT NULL,
  pk              TEXT      NOT NULL,
  data            TEXT,
  lastUpdateTime  DATETIME  NOT NULL,
  isDeleted       BOOLEAN   NOT NULL,

  PRIMARY KEY(table, pk)
) AS SyncChange;
```

For this table, drift error is:

```console
[INFO] Running build...
[WARNING] drift_dev:analyzer on lib/data/sync_changes.drift:
line 2, column 3: Expected a column name
  ╷
2 │   table      TEXT      NOT NULL,
  │   ^^^^^
  ╵
[WARNING] drift_dev:analyzer on lib/data/sync_changes.drift:
line 8, column 15: Expected an expression here, but got a reserved keyword. Did you mean to use it as an identifier? Try wrapping it in double quotes.
  ╷
8 │   PRIMARY KEY(table, pk)
  │               ^^^^^
  ╵
[WARNING] drift_dev:analyzer on lib/data/sync_changes.drift:
line 9, column 1: Expected a semicolon after the statement ended
  ╷
9 │ ) AS SyncChange;
```

The last error isn't really an error (and, as is the last one, I took some minutes to figure out what was going on).

After changing the column name to `"table"` or `collection`, all errors are gone.

So,

1) The last error doesn't really exist, it would be nice if drift parser didn't show it.

2) Is possible for drift to automatically put all column and table names in `"` to avoid this error?

**Comment by simolus3** [comment]
The first error has a confusing message, I've fixed that in a988b38ec10f9f1abafe6084afaf35fbc317ed35.

As for the second error, things are a bit complicated. sqlite3 happily accepts it, but it also mentions that reserved keywords _should_ be escaped for them to be recognized. So we're following sqlite3 as described in its documentation, whereas the real sqlite3 uses a ton of lenient backup cases that aren't documented to interpret keywords as identifiers. I think it's better to be consistent than try to play catch with sqlite3 in determining all the exceptions in the parser.

> (and, as is the last one, I took some minutes to figure out what was going on

Yeah, I can understand that. Maybe the error message should be improved to make this clearer.

>  Is possible for drift to automatically put all column and table names in `"` to avoid this error?

We do this for SQL generated with the Dart API and in generated code too if it's required. But I don't think it's safe to do it automatically for input sources, since there are cases where we really don't know whether you meant to use an identifier or a keyword.
