### ISSUE TITLE
Proper imports not being included in database.g.dart

### ISSUE THREAD

**Issue by AliEasy** [simolus3/moor#2404]
Scenario:
I have a simple table defined in `table.drift`
In `table.drift` I link a class to the table (Custom row classes) by `WITH` command and also add related import.
After executing `flutter packages pub run build_runner build` and regenerating the `database.g.dart` file, the import to the class is missing in `database.g.dart` and have to add it manually.

problem: `database.g.dart` Must not modify by hand.

**code sample**

initial table:
```
CREATE TABLE BasicInfoUrl (
        UrlId INTEGER PRIMARY KEY, Url TEXT NOT NULL, Loaded BOOLEAN NOT NULL,
        Type TEXT NOT NULL
)
```

after using Custom row classes:

```
import 'package:app/model/basic_info_url.dart';

CREATE TABLE BasicInfoUrl (
        UrlId INTEGER PRIMARY KEY, Url TEXT NOT NULL, Loaded BOOLEAN NOT NULL,
        Type TEXT NOT NULL
) WITH BasicInfoUrlModel;
```

**Comment by simolus3** [comment]
Are you using the modular builder (or more generally, do you have a `build.yaml` file that configures drift at all)?

By default, generated part files (those with a `part of` statement somewhere) cannot have any imports on their own. That's a limitation of the Dart language, and unfortunately it means that drift can't manage those imports for you. You'll just have to add the imports to `database.dart` (not the generated file!).

There is a [newer build mode](https://drift.simonbinder.eu/docs/advanced-features/builder_options/#modular-code-generation) optimized for larger drift projects defining a database across multiple files. That one should manage the imports for you.

So I'll close this since this is impossible for real part files, and already implemented in the build mode that generates standalone files capable of having their own imports. If you run into this problem with a build configuration that should support those, please let me know. Then that would be a bug that I need to look into.
