### ISSUE TITLE
`USING` keyword not being recognized in `UPDATE` with `JOIN`

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#2413]
According to docs: (https://www.sqlite.org/lang_update.html), the `JOIN` expression on the `UPDATE` commands also accepts the `USING` keyword.

On a view, Drift has no issues with that:

```sql
CREATE VIEW Customers AS
  SELECT
    c.id,
    c.companyId,
    c.isActive,
    c.displayName,
    c.email,
    c.memo,
    cc.personalId,
    cc.birthday
  FROM Contacts AS c
  INNER JOIN CustomerContacts AS cc USING(id)
  WHERE c.deleted = 0 AND cc.deleted = 0 WITH CHECK OPTION

  PRIMARY KEY(id) WITH CHECK OPTION
  FOREIGN KEY(companyId) REFERENCES Companies(id) WITH CHECK OPTION;
```

Since `CustomerContacts` and `Contacts` have both the `id` column as PK and FK, `USING` is a short version of `ON c.id = cc.id`.

But on an `UPDATE` expression, Drift fails to recognize it:

```sql
changeDeletedStatus:
  UPDATE CustomerContacts
  JOIN Contacts USING(id)
  SET 
    CustomerContacts.deleted = :deleted,
    Contacts.deleted = :deleted,
    CustomerContacts.synced = 0,
    Contacts.synced = 0,
    CustomerContacts.updatedTime = :updatedTime,
    Contacts.updatedTime = :updatedTime
  WHERE id = :id;
``` 

This gives an error:

```console
[WARNING] drift_dev:analyzer on lib/data/customers/customers.drift:
line 42, column 3: Expected SET after the table name
   ╷
42 │   JOIN Contacts USING(id)
   │   ^^^^
   ╵
```

Changing that JOIN to `JOIN Contacts ON Contacts.id = CustomerContacts.id` "fixes" the problem.

**Comment by simolus3** [comment]
Ok, but it _is_ invalid syntax:

![sqlite3 cli](https://user-images.githubusercontent.com/5738860/236553602-a30db447-0a8f-4eae-b35d-421103824f8e.png)

`USING` can be used in a [UPDATE FROM](https://www.sqlite.org/lang_update.html#update_from) clause, but that doesn't really make sense for your query since you only have one table in your from clause. You also can't use this syntax to update two tables at once, the `FROM` syntax just adds a new table you can refer to in expressions. You also can't use qualified setters in updates (so just use `deleted` instead of `CustomerCOntacts.deleted`).
