### ISSUE TITLE
Auto increment field, which implies primary key is generated as a required filed on DataClass

### ISSUE THREAD

**Issue by jacktattersall1** [simolus3/moor#2446]
Hi, i'm not sure if i'm missing something simple here.

Consider this table declaration which sets an auto increment column, when the DataClass is generated, this field is set to required in the constructor, why would an auto gen field be required?

```@DataClassName('MobileGpsEntity')
class MobileGpsEntities extends Table {
  IntColumn get localDatabaseId => integer().autoIncrement()();
```
  
  
  I am trying to use auto_mappr package to map directly to this DataClass, and all works well, except for this auto increment field.
  
  I can see that the generated definition
  
  ```@override
  late final GeneratedColumn<int> localDatabaseId = GeneratedColumn<int>(
      'local_database_id', aliasedName, false,
      hasAutoIncrement: true,
      type: DriftSqlType.int,
      requiredDuringInsert: false,
      defaultConstraints:
  ```
      
has `requiredDuringInsert: false` so im not sure why the DataClass requires this field
any help greatly appreciated
thanks

**Comment by simolus3** [comment]
Essentially, this is a consequence of null safety in Dart: The id column can either be nullable or required, there's no in-between. Drift-generated row classes are designed to hold a row as it appears in the database - so we know that the id column will be there and non-null. Otherwise, we'd have to generate all columns with some default as nullable, which would get really annoying when parsing results from the database.

To work around this issue, drift generates two classes for you: A row class (with a non-nullable id field), and a "companion" class (where all fields can be explicitly marked as absent). Companions are designed for partial rows, e.g. to describe an update or an insert operation where some columns are left unchanged or designed to receive a default, respectively. If you want to map from JSON to something that you insert into the database, you should probably map to the companion class instead.

**Comment by jacktattersall1** [comment]
Thanks for the explanation @simolus3, makes sense, unfortunately i am leaning on an mapping tool (mappr) for my conversions, mapping to Value() types is proving tricky.

https://github.com/netglade/auto_mappr/issues/80
