### ISSUE TITLE
enum.equals expects String only

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#2463]
Having a column as `TextColumn get status => textEnum<CapillaryScheduleStatus>()();`, the query below should work:

```dart
final cs = select(capillarySchedules)
  ..where(
    (cs) =>
        cs.deleted.equals(false) &
        cs.userId.equals(userId) &
        cs.status.equals(status),
  );
```

But it complains that `The argument type 'CapillaryScheduleStatus' can't be assigned to the parameter type 'String'.`.

`status` is an enum of type `CapillaryScheduleStatus`. I think that `equals` should expect `CapillaryScheduleStatus.draft` instead of `CapillaryScheduleStatus.draft.name`.

**Comment by simolus3** [comment]
You can use [`equalsValue`](https://drift.simonbinder.eu/api/drift/generatedcolumnwithtypeconverter/equalsvalue) on columns with type converters to do that.

The reason this needs an extra method is that `cs.status` still needs to be an `Expression<String>` because it is a string in SQL - you can do stuff like `.length` on it. So we can't make it an `Expression<CapillaryScheduleStatus>` .
