### ISSUE TITLE
 INSERT INTO .. RETURNING doesn't like primaryKey override

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#2485]
**Describe the bug**
```
class Stuffs extends Table {
  IntColumn get id => integer()();
  TextColumn get title => text().withLength(min: 1, max: 32)();
  DateTimeColumn get insertTime => dateTime().withDefault(Constant(DateTime.now()))();

  @override
  Set<Column> get primaryKey => {id, title};
```

`DriftRemoteException (SqliteException(1555): while selecting from statement, UNIQUE constraint failed: stuffs.id, constraint failed (code 1555)
  Causing statement: INSERT INTO "stuffs" ("id", "title") VALUES (?, ?) RETURNING *, parameters: 0, DX2Hb)`

since i provide a unique title value, i am not expecting this error. but, maybe i am missing something. please let me know. thanks!

**Comment by simolus3** [comment]
This works for me:

```dart
import 'package:drift/drift.dart';
import 'package:drift/native.dart';

part 'repro.g.dart';

class Stuffs extends Table {
  IntColumn get id => integer()();
  TextColumn get title => text().withLength(min: 1, max: 32)();
  DateTimeColumn get insertTime =>
      dateTime().withDefault(Constant(DateTime.now()))();

  @override
  Set<Column> get primaryKey => {id, title};
}

@DriftDatabase(tables: [Stuffs])
class MyDatabase extends _$MyDatabase {
  MyDatabase(super.e);

  @override
  int get schemaVersion => 1;
}

void main() async {
  final db = MyDatabase(NativeDatabase.memory());

  final a = await db
      .into(db.stuffs)
      .insertReturning(StuffsCompanion.insert(id: 3, title: 'foo'));
  final b = await db
      .into(db.stuffs)
      .insertReturning(StuffsCompanion.insert(id: 3, title: 'bar'));

  print('works: $a, $b');
}
```

The error message also seems to be unrelated to `RETURNING`. Since there is no unique constraint on `stuffs.id` alone, I think what has happened here is that your database has a different schema than what you have on the table.
For instance, if you've previously declared `id` as `integer().autoIncrement()()` and created the database with that version, `id` will still be the primary key after changing the table. You need to write a [migration](https://drift.simonbinder.eu/docs/advanced-features/migrations/) to apply table changes onto the database.

**Comment by matthewkooshad** [comment]
thanks for confirming it works for you. i agree with you, that it was likely an actual database schema mismatch from the schema code.
