### ISSUE TITLE
`migator.alterTable` works fine, but fails migration tests

### ISSUE THREAD

**Issue by MichaelDark** [simolus3/moor#2497]
[`migrator.alterTable`](https://pub.dev/documentation/drift/2.9.0/drift/Migrator/alterTable.html) is causing issues with migration tests because of its usage of [12-steps procedure](https://www.sqlite.org/lang_altertable.html#otheralter).

Consider the case:
- v1
  - `users` table added:
    - id: int
    - balance: int
- v2
  - `users#savings` non-nullable column added. `columnTransformer` was used
    to prepopulate column: `savings: balance`.
    - id: int
    - balance: int
    - **savings: int** <==
- v3
  - ...
- v4
  - ...
- v5
  - `users#eyeColor` nullable column added.
    - id: int
    - balance: int
    - savings: int
    - **eyeColor: text?** <==

The case described above will fail the sequential migration, but **techically** everything works fine.

The thing is, that if we are testing migration 1=>2, and the current DB schema version is 5, then `.alterTable` will follow 12-step procedure, and re-create table, BUT it will recreate it using the `users` table schema that is defined in v5 because it is the version that we are passing to migrator:

```dart
// v2 migration
migrator.alterTable(
    TableMigration(
        // Here, because we are technically using `DatabaseV5`, users table also contains `eyeColor`, that will be also created.
        users, 
        columnTransformers: {
            users.savings: users.balance,
        },
        newColumns: [
            users.savings,
        ],
    ),
);
```

And thus, it will make all future sequential migrations (v1=>v2, with current v5) impossible.

Possible solutions:
- change `.alterTable` so that it will recreate the table with the existing schema columns + new columns, and not with the provided tables' columns. So, only the table name will be used (to get schema and to create new table with new columns).
- introduce new method to `Migrator` to cover this case.

**Comment by simolus3** [comment]
Thanks for the detailed report! This issue has come up often, so I think we should investigate some options to introduce a version-aware variant of the migrator (#2498).

As a workaround until we have a proper API for this, you could generate schema test code into `lib/` as well, which allows you to write migrations like this:

https://github.com/simolus3/drift/blob/c700b5b4becb1e6af5205dc90dde0d0a17c32c44/examples/migrations_example/lib/database.dart#L31-L39

Since this affects the entire migrator API (including things like `createTable`), I'll close this in favor of a solution that would cover everything (#2498).
