### ISSUE TITLE
How to close  DRIFT database on Windows Release platform

### ISSUE THREAD

**Issue by StormZp** [simolus3/moor#2517]
I use drift on the Windows platform.
`LazyDatabase _openConnection() {`
 ` return LazyDatabase(() async {`
`    final dbFolder = Directory.current.path;`
`    if(Platform.isWindows ){`
`      final file = File(p.join(dbFolder + Constants.windowsDBPath, 'app.db'));`
`      return NativeDatabase(file);`
`    }else if( Platform.isMacOS){`
`      final dbFolder = await getApplicationDocumentsDirectory();`
`      final file = File(p.join(dbFolder.path, 'app.db'));`
`      Logger().e("_openConnection64: file: $file");`
`      return NativeDatabase(file);`
`    }else{`
`      final dbFolder = await getApplicationDocumentsDirectory();`
`      final file = File(p.join(dbFolder.path, 'app.db'));`
`      return NativeDatabase(file);`
`    }`
`  });`
`}`
and then close the program when debugging, and I can see that my program is finished in the task manager.
But in the release version, after closing the program, it still survives in the task manager, and then it is found that app.db is still occupied.
I tried db.close(), but it doesn't work, survived in task manager
`  static close() async {`
`    var db = getDb();`
`    await  db.close();`
`  }`

**Comment by simolus3** [comment]
Are you sure that `static close()` is called? And if so, that `getDb()` returns the existing database instance instead of creating a new one? Calling `db.close()` will close the underlying database, which includes not using the `app.db` file anymore. Given that sqlite3 is responsible for that, I don't think the release/debug mode switch makes much of a difference.

Why is your app still running after closing its windows though? That might be something worth looking at, drift should not contribute to that.
