### ISSUE TITLE
build_runner takes 3-4 mins when just adding drift dependencies

### ISSUE THREAD

**Issue by HasanAlqaisi** [simolus3/moor#2533]
**Describe the bug**

I've a project that I need to add an offline support for it.
I tried to add drift dependencies as listed in docs, and when I try to run **dart run build_runner** it takes 3-4 mins.
Before adding the dependencies, it took only 30-50 secs.
I can't identify why it is taking so much time. Can you help me please?

Note: I haven't added any drift related code yet. Just the dependencies

**Comment by simolus3** [comment]
Even 30s is pretty bad, multiple minutes is a catastrophe :scream: 

Drift uses a fairly modular build setup internally where files are independently analyzed first to find Dart files defining drift tables. The generator later reads the intermediate analysis results to build the structure for the database. If you have a very large workspace, I suspect the initial analysis runs could take a long time since they need to look at every file in the project. For incremental rebuilds, the time should be a lot shorter though.

A general build optimization is to reduce the amount of files some builder runs on. For instance, if you know that your database code will be in `lib/database`, you could create a [`build.yaml`](https://pub.dev/packages/build_config) file next to your pubspec with the following content:

```yaml
targets:
  $default:
    builders:
      drift_dev:
        generate_for:
           - "lib/database/**"
```

That should hopefully reduce build time drastically, but it should have never been at multiple minutes to begin with. I remember `build_runner` being able to spit out a timing diagram for builds, but I can't find anything about that anymore. I'll check how to profile builds and follow up, maybe we can see what's taking so long there.

**Comment by spideythewebhead** [comment]
Hi @simolus3

I have a question - mostly an educational one. Would code generation in a project like drift work if the code you generate is based on the AST model (https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/doc/tutorial/ast.md) and not the Element model? (https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/doc/tutorial/element.md)

I have created a code generator (https://github.com/spideythewebhead/tachyon) that uses only the AST model and so the build times are in general less than build_runner but I am wondering if it can cover "all" the cases that build_runner would.

You see a plugin based on the code generator that wraps dio and generates http services (https://github.com/spideythewebhead/http_client_plugin/blob/main/lib/src/code_generator.dart)

And another one for data class (https://github.com/spideythewebhead/data_class_plugin) - tho this is more complicated

**Comment by simolus3** [comment]
That looks very interesting and I wasn't aware of your work, thanks for sharing!

> Would code generation in a project like drift work if the code you generate is based on the AST model

If it's based on a resolved AST - yes. But unresolved syntax probably won't get us far, and resolving is what is so expensive.

> that uses only the AST model and so the build times are in general less than build_runner but I am wondering if it can cover "all" the cases that build_runner would.

The thing is (apart from the mediocre startup time to load the asset graph), build\_runner really isn't that slow by itself. Drift's documentation [is a static website](https://github.com/simolus3/drift/tree/develop/docs) that, with intermediate assets, involves thousands of build steps and tens of thousand possible assets. When I change a markdown file with `build_runner serve`, it doesn't take more than half a second to rebuild the website and refresh.

Resolving the AST in the analyzer is what is typically making builds slow. The reason is that every transitive import in that file needs to be tracked in the asset graph to ensure correct rebuilds (because, after all, it could affect the elements). Then you also can't reliably cache this since some part files affecting the results are yet to be generated (although https://github.com/dart-lang/build/pull/3405 will improve this somewhat, I should really get back at that).

I know that `source_gen` is doing an optimization for annotation-based processors: They first parse the input file into an unresolved AST (fast), check if there are any annotations on top-level elements (also, fast) and only if that's the case they to get the element model / resolved AST (very slow).
In drift, we look at every Dart file to see if it might define a drift table. So when we see a class like `class MyTable extends Table`, we need to resolve it. You might think that we can do this with (unresolved) syntax alone: When we hit a class definition extending from `Table`, we need to take a look. But what if it only extends `Table` through a chain of other abstract class? Or what if a user decides to write something like

```dart
typedef DriftTable = Table;

class MyTable extends DriftTable { /* ... */ }
```

Now we can't just look for a `NamedType('DriftTable')` in the `extends` clause and be done with it. To know this reliably, we need an resolved AST (or element model) that tells us "yup, this class inherits from the Table class defined in the drift package".


E.g., how do you implement something like `dartType.isCollection` reliably without resolving the AST and without compromising correctness?

**Comment by spideythewebhead** [comment]
@simolus3  Thanks for the detailed explanation. Yes that's true, using the unresolved AST you have to make some assumptions I would say. For example on my code generator I have a custom dart type that makes some assumptions on the types and doesn't actually resolve the full type. So if you have a typedef for the type List it won't work, it works only for the predefined types that the dart provides or I would say the common patterns as least. 

Also some common scenario is to search for a class to check if there's declared method, in my case to resolve this, the generator goes through all the dependencies of the "current file" and searches for that class until it finds a match and returns the AST class declaration. 

I have created a very simple postgres client and then tried to create a simple orm based on my code generator to see if that's possible and that's how I stumble on this library ( which seems amazing 👏 ).

I have one more question, do you believe that meta programming is going to resolve the speed issue of build_runner having to resolve the full AST or does it fall under the same issues?

**Comment by HasanAlqaisi** [comment]
> Even 30s is pretty bad, multiple minutes is a catastrophe scream
> 
> Drift uses a fairly modular build setup internally where files are independently analyzed first to find Dart files defining drift tables. The generator later reads the intermediate analysis results to build the structure for the database. If you have a very large workspace, I suspect the initial analysis runs could take a long time since they need to look at every file in the project. For incremental rebuilds, the time should be a lot shorter though.
> 
> A general build optimization is to reduce the amount of files some builder runs on. For instance, if you know that your database code will be in `lib/database`, you could create a [`build.yaml`](https://pub.dev/packages/build_config) file next to your pubspec with the following content:
> 
> ```yaml
> targets:
>   $default:
>     builders:
>       drift_dev:
>         generate_for:
>            - "lib/database/**"
> ```
> 
> That should hopefully reduce build time drastically, but it should have never been at multiple minutes to begin with. I remember `build_runner` being able to spit out a timing diagram for builds, but I can't find anything about that anymore. I'll check how to profile builds and follow up, maybe we can see what's taking so long there.

After specifying the path of the drift files in `build.yaml`, it has been reduced again to 30-50 secs.
I agree that 30-50 seconds is bad as well, I will have to do more investigation about it.
I think the rest is not related to drift itself, so I will close this issue.
Thanks for helping!

**Comment by simolus3** [comment]
> For example on my code generator I have a custom dart type that makes some assumptions on the types and doesn't actually resolve the full type.

Ideally we should be able to have both, but I think I prefer correctness over build speed.

> I have one more question, do you believe that meta programming is going to resolve the speed issue of build_runner having to resolve the full AST or does it fall under the same issues?

I haven't looked at the meta programming drafts yet. But it seems like they're designed with current generators for `build_runner` in mind, so I assume they will have access to the full AST.
The difference is that macros are deeply embedded into the Dart toolchain. They're called from the CFE (which needs the full AST for compilation either way) and the analysis server (which also keeps a resolved AST around). So ideally the tools implementing meta programming will have access to the required information already and I assume that this will improve performance a lot.

> After specifying the path of the drift files in build.yaml, it has been reduced again to 30-50 secs.

Good to know - if you run into more timing issues that are likely to be drift related, I'm happy to take a look at that as well.
