### ISSUE TITLE
Sqlparser cannot parse a query generated by Drift

### ISSUE THREAD

**Issue by JanezStupar** [simolus3/moor#2535]
The Drift test suite generates the following query (crudTests > "inserting updates a select stream"):

`SELECT f.really_good_friends,"user"."id" AS "nested_0.id", "user"."name" AS "nested_0.name", "user"."birth_date" AS "nested_0.birth_date", "user"."profile_picture" AS "nested_0.profile_picture", "user"."preferences" AS "nested_0.preferences" FROM friendships AS f INNER JOIN users AS "user" ON "user".id IN (f.first_user, f.second_user) AND "user".id != $1 WHERE(f.first_user = $1 OR f.second_user = $1)`

When passing that through the SqlEngine.parse() the following error occurs:
`Malformed sql: Expected identifier after '$' at <FileLocation: 355 unknown source:1:356>, Expected identifier after '$' at <FileLocation: 379 unknown source:1:380>, Expected identifier after '$' at <FileLocation: 401 unknown source:1:402>`

I am not equipped to figure out whether the queries should be round tripable. But since the database executes it, I guess parser should be able to process it.

**Comment by simolus3** [comment]
This is not ideal (sqlparser should accept all valid SQL, which this is), but sort of expected. We use the postgres dialect in those tests because both sqlite3 and postgres support the `$` character to declare variables. We prefer `?` in sqlite3, but that is not supported by postgres.

With drift extensions enabled in the parser, the dollar sign [has a special meaning](https://drift.simonbinder.eu/docs/using-sql/drift_files/#dart-interop) which causes the query to be invalid. If you disable drift extensions in the parser, the query should parse correctly.

Really, we should be running `$1` on postgres and `?1` on sqlite3, and only for packages that care about multiple dialects. I've opened #2536 to track that.
