### ISSUE TITLE
select count from another joined statement

### ISSUE THREAD

**Issue by selvam920** [simolus3/moor#2538]
![image](https://github.com/simolus3/drift/assets/20491308/e5cf4ab6-76a5-4f43-89a2-00c93cd4aabc)

**Comment by simolus3** [comment]
Instead of just pointing a screenshot of your code, could you tell me what you want to do / what query you need?

Do you want to count the rows from a statement in another statement? Construct the inner statement so that it returns only one column - the amount of rows it would return. Then, wrap that in a `subqueryExpression` and add it as a column to your main query.

```dart
final count = subqueryExpression(selectOnly(yourInitialTable)
  ..join([...])
  ..addColumns([countAll()]));
```

**Comment by selvam920** [comment]
it works but unable to read and and also unable to alias to subquery expression
but the above code worked but unable  to select
![image](https://github.com/simolus3/drift/assets/20491308/19442c2a-0992-4e95-92bb-a10afeb8df57)

![image](https://github.com/simolus3/drift/assets/20491308/697da146-93a3-4f76-a647-399c5b2a7a45)

**Comment by simolus3** [comment]
Again, I need more information on what you're trying to do, the query you've written so far and what's going wrong to help here. Having a full stack trace / code would make this much easier.

**Comment by selvam920** [comment]
did you check the screen shot #1,  i have selected few columns with count another table from different query. 
The result got success but unable to select by column name. in the screenshot column name "c4" generated by drift package  i had given alias name for that column that name basis i'm not able to fetch the column value.

**Comment by FaFre** [comment]
I think more information is required about the table structure and the queries you are executing, so we can see what you are trying to do.

**Comment by selvam920** [comment]
select id,name,categoryName, (select count(1) from varients) [varientcount] from products p inner join category c on c.id=p.categoryid

how to write expression for the above query

**Comment by FaFre** [comment]
> select id,name,categoryName, (select count(1) from varients) [varientcount] from products p inner join category c on c.id=p.categoryid
> 
> how to write expression for the above query

You could either use the drift fluent syntax, or the drift generator in case you prefer to write raw SQL.

For fluent syntax you will find the documentation here:
- https://drift.simonbinder.eu/docs/getting-started/writing_queries/#select-statements (basics)
- https://drift.simonbinder.eu/docs/advanced-features/joins/ (joins)

For using the generator, have a look here:
- https://drift.simonbinder.eu/docs/using-sql/ (starting point)

The site also brings in a pretty good search function, that turned out to be very helpful for me.

**Comment by simolus3** [comment]
You can fix the "no SQL error type for Object" error by adding an explicit type argument to `subqueryExpression`, e.g. `subqueryExpression<int>(...)` - sorry for not catching that earlier.

> select id,name,categoryName, (select count(1) from varients) [varientcount] from products p inner join category c on c.id=p.categoryid

Writing this query (well, with `*` instead of a list of column names) with the Dart API would look like this:

```dart
Future<void> query1() async {
  final mainQuery = select(products).join(
      [innerJoin(categories, categories.id.equalsExp(products.category))]);

  final variantsCount =
      subqueryExpression<int>(selectOnly(variants)..addColumns([countAll()]));
  mainQuery.addColumns([variantsCount]);

  final rows = await mainQuery.get();
  for (final row in rows) {
    // you can now read tables and columns from this select statement
    final product = row.readTable(products);
    final category = row.readTable(categories);

    final amountOfVariants = row.read(variantsCount);
  }
}
```

If you want to add a where clause to `(select count(1) from varients) [varientcount]` (for instance if `varients` had a column storing the product it belongs to), you could do that like this:

```dart
Future<void> query2() async {
  final mainQuery = select(products).join(
      [innerJoin(categories, categories.id.equalsExp(products.category))]);

  final variantsCount = subqueryExpression<int>(selectOnly(variants)
    ..where(variants.product.equalsExp(products.id))
    ..addColumns([countAll()]));
  mainQuery.addColumns([variantsCount]);
```
