### ISSUE TITLE
moor_flutter -- expensive db queries locks up app

### ISSUE THREAD

**Issue by ardeaf** [simolus3/moor#254]
On our app, we have some large queries that will lock up the app while (I assume) the app is reading from the db. Is this just purely because Dart is single threaded and will happen anytime you have expensive queries?

Would the `moor_ffi` package solve this problem by allowing the db to be run in another isolate (which as I understand it, is basically another thread in dart)? If so, any solutions without having to migrate over to `moor_ffi`?

**Comment by simolus3** [comment]
> we have some large queries that will lock up the app while (I assume) the app is reading from the db

That could be related, but I'm pretty sure that Flutter's rendering thread is different to the one executing the native plugin (sqflite, in this case). So even if the queries take a long time, this shouldn't cause UI lags.

Just out of interest, what kind of queries are you running that take too long? Sometimes queries can be sped up a lot by [adding indices](https://www.sqlitetutorial.net/sqlite-index/).

The query could slow down the overall app if it returns huge amounts of data, because we get that back as a single list. In that case, maybe you can split the query via some pagination techniques with LIMIT? It's hard to be specific without knowing more, did you try to do some performance analysis with [DevTools](https://flutter.dev/docs/development/tools/devtools)? If you find any bottlenecks related to moor, I can take a look at them.

> Would the `moor_ffi` package solve this problem by allowing the db to be run in another isolate

As you said, an isolate is similar to a thread, but different isolates don't share memory. They instead have to pass messages to each other for communication, which takes more time in general but can reduce work on the main thread. That probably wouldn't help for the problem you're seeing though, as the native platforms are independent from the UI thread already.

**Comment by DevonJerothe** [comment]
#245 I am having a similar problem with larger lists while streaming the results.

**Comment by ardeaf** [comment]
After discussing it more and thinking about it I'm wondering if it's just rendering the large list of results that causes the delay rather than the db query

I'll inspect more with DevTools

**Comment by ardeaf** [comment]
For reference -- I'm not 100% familiar with how the db was set up in the repo I'm working on, but the ui blocking is noticeable. For example, when we read about 5000 entries from the database, it takes about 2s to complete the query, which is totally fine if the UI wouldn't lock up. During a good portion of those 2s, the entire app cannot be interacted with. This doesn't make sense to me, since everything is asynchronous, but alas. I completely isolated it to the function `await query.get()` (which runs after we compose a query with a couple joins).

I should also mention we are on version 1.7

**Comment by ardeaf** [comment]
Closing the issue as it seems like it's just a limitation that has to do with querying so many rows at a time, and a workaround is just to set limits on your queries.
