### ISSUE TITLE
 database is locked 

### ISSUE THREAD

**Issue by ghost** [simolus3/moor#2544]
My app is using the background tasks therefore, we need to open another instance of the database. But when insert, update... get the errors below: 

SqliteException(5): database is locked, database is locked (code 5)
I/flutter (31428): │ ⛔   Causing statement: PRAGMA user_version;

How can I solve this problem?

**Comment by simolus3** [comment]
I'm also looking at this in https://github.com/simolus3/drift/discussions/2496.

Basically, the steps that help are:

- Setting `journal_mode = WAL` in `setup` so that writes and reads can happen concurrently.
- Setting `busy_timeout = 100` so that short concurrent writes will be retried automatically.
