### ISSUE TITLE
Generated getter for auto-increment field

### ISSUE THREAD

**Issue by andim27** [simolus3/moor#2549]
I need insert record to the table with auto increment field.
My code:
```dart
@DataClassName('User')
class Users extends Table {
 IntColumn get id => integer().autoIncrement()();
 TextColumn get name => text()();
}

class LocalAppDatabase extends _$LocalAppDatabase {
  LocalAppDatabase() : super(_openConnection());
 
Future<int> insertUser(User entry) {
    return into(users).insert(entry, mode: InsertMode.insert);
  }

}

//In the code:
//Do I need define new id?
int myId =100;
String myName ="New name";
final insertedId = await DB.insertUser(User(id:myId, name:myName))
```
Question:
**Drift generate id like required class field. Is it a bug or feature?**
Why?
Do I need define new id by myself? I defined getter id like increment.
What why how to correct insert User and not use new id ?

Can I write  my code like this?

`final insertedId = await DB.insertUser(User(name:myName))`

**Comment by simolus3** [comment]
This is explained in the [updates and inserts](https://drift.simonbinder.eu/docs/getting-started/writing_queries/#updates-and-deletes) part of the documentation.

The reason for this is that `User` represents a full row in the `users` table. So if we allowed you to not pass a value for `id`, we'd have to make `id` nullable. That would be very annoying when you're selecting from `Users`, since you'd have to add a bunch of null checks against a value which you already know is non-null.

Instead, drift generates a second class for each table (called a companion). So in your case, you'd have a `User` class for full rows you read from the database, and a `UsersCompanion` class used to partial data (e.g. stuff you insert or update). If you write your code to make use of this, it would look like this:

```dart
@DataClassName('User')
class Users extends Table {
 IntColumn get id => integer().autoIncrement()();
 TextColumn get name => text()();
}

class LocalAppDatabase extends _$LocalAppDatabase {
  LocalAppDatabase() : super(_openConnection());
 
Future<int> insertUser(Insertable<User> entry) {
    return into(users).insert(entry, mode: InsertMode.insert);
  }

}

//In the code:
String myName ="New name";
final insertedId = await DB.insertUser(UsersCompanion.insert(name:myName))
```

The `Insertable<User>` type is essentially a `User | UsersCompanion`. In rare cases it can make sense to insert the full `User` if you happen to know the id. In other cases, using `UsersCompanion` as a parameter makes more sense.
The `insert` constructor of companion has all fields marked as required which don't have a default in the database, which is helpful for writing correct inserts.
