### ISSUE TITLE
Cant store a list of ints in a column using typeconverter

### ISSUE THREAD

**Issue by MadsVETiSearch** [simolus3/moor#2590]
**Describe the bug**

Im having issues storing a list of objects and ints in a column.

the json object:
```
{
   id: 2, 
   title: Arginin, 
   drugs: [216, 217], 
}
```

the table:
```
class OtcIngredients extends Table {
  IntColumn get id => integer()();
  TextColumn get title => text()();
  TextColumn get drugs => text().map(const ListIntConverter())();

  @override
  Set<Column> get primaryKey => {id};
}

```

the converter:
```
class ListIntConverter extends TypeConverter<List<int>, String> {
  const ListIntConverter();

  @override
  List<int> fromSql(String fromDb) {
    return json.decode(fromDb);
  }

  @override
  String toSql(List<int> value) {
    return json.encode(value);
  }
}
```

but when i try to use fromJson i get the following error:
```
flutter: │ type 'List<dynamic>' is not a subtype of type 'List<int>' in type cast
flutter: │ #0   _DefaultValueSerializer.fromJson (package:drift/src/runtime/data_class.dart:244:17)
flutter: │ #1   new OtcIngredient.fromJson (package:database/src/database.g.dart:133:25)
flutter: │ #2   _parseOtcIngredientsJson (package:repositories/src/otc_ingredients_repository.dart:45:40)
flutter: │ #3   compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19:20)
flutter: │ #4   _RemoteRunner._run (dart:isolate:1021:47)
flutter: │ #5   _RemoteRunner._remoteExecute (dart:isolate:1015:12)
flutter: │ #6   _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:17)
flutter: │ #7   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

```

it works if i do the following:

`TypeConverter<List<dynamic>, String> `

but i dont want dynamic, that leads to other issues.

i hope you can help.

**Comment by simolus3** [comment]
Type converters don't apply to the json serialization functionality by default - only to the way columns are stored in the database. Your example is a reason for why that is useful - your JSON stores the list as a JSON list (`[216, 217]`), but in the database the column is a string (`"[216, 217]"`). You can fix this by mixing in the `JsonTypeConverter2` type, which allows declaring a third type for the JSON representation.

Putting everything together, the type converter should look like this:

1. Using `List<int>` as the resolved Dart type used in the data class.
2. Using `String` as the type for the column in the database.
3. Using `List<dynamic>` (or `List<Object?>`) as the type for JSON serialization, since JSON lists in Dart always use a dynamic type.

```dart
class ListIntConverter extends TypeConverter<List<int>, String>
    with JsonTypeConverter2<List<int>, String, List<Object?>> {
  const ListIntConverter();

  @override
  List<Object?> toJson(List<int> value) => value;

  @override
  List<int> fromJson(List<Object?> json) => json.cast();

  @override
  List<int> fromSql(String fromDb) {
    return (json.decode(fromDb) as List).cast();
  }

  @override
  String toSql(List<int> value) {
    return json.encode(value);
  }
}
```

**Comment by MadsVETiSearch** [comment]
First of all thanks for the fast and thorough answer! storing the data works flawless now. 

However i ran into another issue. Im trying to join some tables:
```
await (select(db.otcIngredients).join([
        leftOuterJoin(
          db.drug,
          db.drug.id.isIn(db.otcIngredients.drugs),
        ),
      ])
            ..orderBy([OrderingTerm(expression: db.otcIngredients.title)])
            ..where(db.otcIngredients.deleted_at.isNull()))
          .map((p0) => p0.readTable(db.otcIngredients))
          .get();
```
db.otcIngredients.drugs is of type: 
`GeneratedColumnWithTypeConverter<List<int>, String>`

the problem is this line: 
`db.drug.id.isIn(db.otcIngredients.drugs),`

it gives the following error:
`The argument type 'GeneratedColumnWithTypeConverter<List<int>, String>' can't be assigned to the parameter type 'Iterable<int>'`

How do i get the `List<int>` value from `db.otcIngredients.drugs`, when it has the type `<List<int>, String>`?

**Comment by simolus3** [comment]
It's not currently possible to write that query in drift because `db.otcIngredients.drugs` is a string, not an array (which don't really exist in sqlite3. Adding the necessary APIs for that query sounds interesting though, I'll take a look at that.

That said, typically these kinds of relations are modeled with a third table in SQL:

1. The existing `otcIngredients` table, without the `drugs` column.
2. The existing `drug` table.
3. A third table (say `DrugsInIngredients`) that references the ingredient and the drug.

If an ingredient had three drugs for instance, there would be three rows for that ingredient in the third table. You could then use two joins (first for the `drugsInIngredients` table, and then towards `drug`) to write that query, but it makes inserts more complicated because they now span across two tables.

**Comment by simolus3** [comment]
In the next drift version, you'll be able to use

```dart
final eachIngredient  =ingredients.drugs.jsonEach();
final drugsInIngredients = selectOnly(eachIngredient)..addColumns([eachIngredient.value]);

await (select(db.otcIngredients).join([
        leftOuterJoin(
          db.drug,
          db.drug.id.isInQuery(drugsInIngredients),
        ),
      ])
      // ...
```
