### ISSUE TITLE
Migrating iOS and Android App to Flutter

### ISSUE THREAD

**Issue by abrass** [simolus3/moor#261]
Dear Moor users,

I will start soon a project where I'll rewrite an application from iOS (ObjectiveC) and Android (Java) to Flutter. Both implementations used some kind of SQLite. On Android GreenDAO and on iOS Core Data. The definitions are slightly different, but only 4 classes and maybe 40-50 attributes.

I was wondering if there is a good approach to migrate the data. So a user has already installed the application on Android or iOS. He installs the new version of the app, which is completely written in flutter and I migrate the existing data in the new structures of flutter moor. 

Do you have any hints or examples how to do a migration, if moore and flutter was not used beforehand?

Kind regards

Anton

**Comment by simolus3** [comment]
I can give some high-level overview of how this could be accomplished. If you're having more specific questions on how to accomplish something with moor apis, I can go into more detail about that.

> I was wondering if there is a good approach to migrate the data

For GreenDAO it should be fairly straightforward: You can pull a database file from a device, obtain the `CREATE TABLE` statements used via `SELECT sql FROM sqlite_master WHERE type = 'table'` and put that in a [moor file](https://moor.simonbinder.eu/docs/using-sql/moor_files/). Moor can then generate Dart classes for the tables declared in such file.
Indices and triggers would have to be handled manually, as the generator doesn't support them yet. But in a best-case scenario, you wouldn't even have to do any migrations to the data itself.

I haven't done any native iOS development, so I can't give a lot of advice for the migration. But if you use sqlite as a backend for Core Data, maybe you can do something similar and try to look at the `CREATE TABLE` statements.

There are two remaining issues though. First, if the iOS and Android apps used a different schema, you'd have to pick one and write migrations for the other. I assume that the schema isn't fundamentally different since it's the same app. So when the only problems are different table or column names, you can probably get away with a `insert into select` statement.
Second, you might have to deal with previous migrations on the database. You probably can't assume that all users are using the lastest native version before upgrading to the Flutter version. So they might still have an outdated schema on their devices, and you need to replicate the existing migrations in moor.

**Comment by abrass** [comment]
Hey simolus3,

thx a lot for your insights. That helps me already a lot. I'll try your approach in a near future ^^ 

I compared the models of iOS and Android on the "generator model" layer, since both approaches generate their SQLite Tables based on a model language. On that layer the both models are quite similiar, besides 3 - 4 field names and 2 relationships (bi-directionals vs one directional

Though, I'm not sure what are the differences between the generated SQLite table stutures and datatypes. I'll check that with your approach. It is also possible to get the iOS SQL structures out of a device or test project.

If a moor application starts for the first time and finds an already existing database on the device, it will run a kind of "onMigrate" method, where I can transform data? Is there anything like a "schema_version"-table like in flyway, where moor looks up the version of the database scheme? Or how does the framework know which datbabase version is to migrate? In my scenario there are only existing tables, which moor did not know nothing before.

**Comment by simolus3** [comment]
> If a moor application starts for the first time and finds an already existing database on the device, it will run a kind of "onMigrate" method, where I can transform data?

Yes, you can do that with [migrations](https://moor.simonbinder.eu/docs/advanced-features/migrations/). If you make moor point at your existing database, you can just set the schema version to a higher number.

> how does the framework know which datbabase version is to migrate

Moor doesn't create its own tables to store the schema, but it can use the sqlite "user version" number. Whenever the database is opened, moor will check whether the version number from the file matches the `int get schemaVersion` from the database class. If it doesn't, it will call an `onUpgrade` function for the database.

**Comment by simolus3** [comment]
I'll close this issue since there's not much to add. If you have any more questions, please let me know.
