### ISSUE TITLE
Could not read tables from @DriftDatabase annotation! (dao file, warning)

### ISSUE THREAD

**Issue by wph144** [simolus3/moor#2612]
I'm seeing warnings in my DAO files.
```
Could not read tables from @DriftDatabase annotation! 
Please make sure that all table classes exist.
   ╷
14 │ class SpecDao extends BaseSpecDao with _$SpecDaoMixin {
   │       ^^^^^^^
```

Here's the format of the DAO I wrote and @DriftDatabase.
<img width="523" alt="image" src="https://github.com/simolus3/drift/assets/10491866/fa2fbcb8-eb5a-40b9-97c7-eb65ffa4334c">

<img width="637" alt="image" src="https://github.com/simolus3/drift/assets/10491866/ac180bc0-7012-47b5-95d9-3dde9ad71522">

<img width="859" alt="image" src="https://github.com/simolus3/drift/assets/10491866/4065ae4e-0400-4257-a927-ed986b865f38">

<img width="670" alt="image" src="https://github.com/simolus3/drift/assets/10491866/c7ff6c51-a65e-4a99-a4c4-8521d3b70080">

The peculiar thing is that this warning doesn't appear in last_sync_time_dao. 
All other tables are defined in tables.drift, but only LastSyncTimeEntity was written in Dart code. 
That's why lastSyncTimeEntity is specified like @DriftDatabase(tables: [LastSyncTimeEntity]). 
I tried adding SpecEntity to @DriftDatabase as well, but the same warning still appears in spec_dao.

**Comment by simolus3** [comment]
The warning may be a bit confusing - it talks about `@DriftDatabase`, but when the highlighted class is `SpecDao`, it should be talking about the `@DriftAccessor` annotation not being resolved. I'll fix that inaccuracy in the next version.

Then, you can't include tables defined in a `.drift` file with `tables:`. The reason is that at the time the database or DAO is analyzed, the tables don't exist yet. So the annotation should be `@DriftAccessor(include: {'tables.drift'})` as well. If the accessor is defined in a different directory, you can use a relative path or a `package:myapp/database/tables.drift` package import for the include as well.
