### ISSUE TITLE
Using a .drift file defined view in a Dao causes generator error

### ISSUE THREAD

**Issue by Adam-Langley** [simolus3/moor#2636]
I have a view defined in a drift file - and everything generates fine.
I can use the view from my db variable...

`db.serverSavesAndUnsavedMachines`

However, I want to then use that view in a Dao, so I have defined it...

```
@DriftAccessor(
  tables: [Hazards],
  views: [ServerSavesAndUnsavedMachines])
class MachinesDao extends DatabaseAccessor<AssessmentDatabase> with _$MachinesDaoMixin {
}
```

The generator generates an error, and `_$MachinesDaoMixin` is not produced in the output .g. file.

```
[WARNING] drift_dev on lib/src/assessment_database.dart:
line 61, column 7 of package:minrisk_assessment_entities/src/assessment_database.dart: The referenced element could not be analyzed due to a bug in drift.
   ╷
61 │ class AssessmentDatabase extends _$AssessmentDatabase {
   │       ^^^^^^^^^^^^^^^^^^
   ╵
```

Notes: If I simply remove the `views: [ServerSavesAndUnsavedMachines])` part of the db definition, the builder works again.
I've also tried putting the view in the 'tables:[]' area of the Dao definition - doesnt work here either.

**Comment by simolus3** [comment]
At the time drift is trying to analyze the `@DriftAccessor` annotation, the `ServerSavesAndUnsavedMachines` class doesn't exist yet (since it will be generated by drift as well). So we have no way of knowing what that class means and can't analyze the accessor. The solution is to add the drift file to the `includes` section of the `MachinesDao` class instead.

I'll look into improving the error message here though.
