### ISSUE TITLE
The new `readWithConverter` should perhaps be non-nullable?

### ISSUE THREAD

**Issue by Adam-Langley** [simolus3/moor#2640]
There is no 'as' operator in the implementation, so surely the result is expected to be non-nullable otherwise it will throw a runtime error?

```
  /// Reads a column that has a type converter applied to it from the row.
  ///
  /// This calls [read] internally, which reads the column but without applying
  /// a type converter.
  D? readWithConverter<D, S extends Object>(
      GeneratedColumnWithTypeConverter<D, S> column) {
    return column.converter.fromSql(read<S>(column));
  }
```

**Comment by simolus3** [comment]
It should return nullable values - the fact that it throws for `null`s is a bug that has been fixed in 3ef468b6f8088a09b51fbbb21b7f9fb3128dcfd5. The reason is that even non-nullable columns can be null in that class because they could have been added from an outer join. `read()` returns nullable values for the same reason.
