### ISSUE TITLE
Incorrect models (duplicated columns) generated when view contains literal columns

### ISSUE THREAD

**Issue by Adam-Langley** [simolus3/moor#2641]
In a drift file, I have declared a view which returns a literal, as well as a set of columns:

``
CREATE VIEW Test AS
  SELECT 'client' literal, * from Table;
``

The resulting generated model looks like this (snippet)

```
class TestData extends DataClass {
  final String literal;
  final Guid id;
  final String name;
  final String literal1;
```

Note how the literal column 'literal' is repeated as 'literal1'.

**Comment by simolus3** [comment]
Is it wrong though? If `literal` is a column on `Table`, `SELECT 'client' literal, * from Table` will have two columns both named `literal` (the one you've explicitly mentioned and then again due to the star expansion). At least that's what I get when running the query in the sqlite3 CLI console. We have no good way of knowing that these are the same column, so attach the `1` to be able to represent both.

If `literal` is a column in the table, why mention it again?

**Comment by Adam-Langley** [comment]
Hey @simolus3 
Sorry, I wasn't clear enough...
'literal' is definitely not a column in the table 'Table'.

It doesnt matter what you name the literal column, XXX, Foo, the code generator will create a duplicate column, XXX1, Foo1.

Probably not necessary to know, but my use case is that I have 2 identical tables that I am unioning, and adding a 'discriminator' column (the literal).

**Comment by simolus3** [comment]
Oh you've been clear, I just need to learn how to read :facepalm: Fixed in d0a3feee128c9136fb4fd5db7feb77d5aba2db96!

**Comment by simolus3** [comment]
You can also work around this by mentioning the star first (`*, 'client' literal`). The star column used to expand to every available column in that case, which includes named columns.

**Comment by Adam-Langley** [comment]
Thank you @simolus3, you're an absolute machine. 
Also confirmed the workaround as good.
Gratitude coming your way!

**Comment by simolus3** [comment]
Thanks!!
