### ISSUE TITLE
Documentation issue: Expressions

### ISSUE THREAD

**Issue by CyMathew** [simolus3/moor#2654]
I tried to perform something similar to the following:
>select(users)..where((u) => u.birthDate.year.isLessThan(1950))

based on info in documentation here:
https://drift.simonbinder.eu/docs/getting-started/expressions/#date-and-time

But looks like `isLessThan()` is not available anymore for `Expression<int>`?
I was able to get around the issue by using `isSmallerThanValue()` but I wanted to check if I was doing something incorrectly or maybe the documentation needs to be updated.

**Comment by simolus3** [comment]
You're right, `isSmallerThanValue` is the right method to use. It has been there since the earliest drift versions IIRC. It arguably should have been called `isLessThanValue`, but now it's too late to change that.

I've fixed the snippets on the develop branch, the changes will be visible with the next drift version.
