### ISSUE TITLE
Cannot use custom TypeConverters in drift files with "multiple builders" setup

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#2656]
**Describe the bug**
I'm trying to use a custom TypeConverter for a table defined in a drift file, but it appears to it cannot resolve it correctly when using a build_runner setup with multiple builders. 

## Steps to reproduce

From the `examples/with_built_value` project in the Drift repository
1. Add the following to tables.drift
```sql
import 'converter.dart';

create table config (
    config_key TEXT not null primary key,
    -- The current value associated with the [configKey]
    config_value ANY,
    sync_state INTEGER MAPPED BY `const SyncTypeConverter()`,
    sync_state_implicit ENUM(SyncType)
) STRICT AS "Config";
```
3. Add the converter.dart file
```dart
import 'package:drift/drift.dart';

enum SyncType {
  locallyCreated,
  locallyUpdated,
  synchronized,
}

class SyncTypeConverter extends TypeConverter<SyncType, int> {
  const SyncTypeConverter();

  @override
  SyncType fromSql(int fromDb) {
    return SyncType.values[fromDb];
  }

  @override
  int toSql(SyncType value) {
    return value.index;
  }
}
```

3. Run `dart run build_runner build --delete-conflicting-outputs`

Error log:
```
❯ dart run build_runner build --delete-conflicting-outputs
[INFO] Generating build script completed, took 261ms
[INFO] Reading cached asset graph completed, took 70ms
[INFO] Checking for updates since last build completed, took 415ms
[WARNING] drift_dev:not_shared on lib/database.dart:
Could not read Dart expression const SyncTypeConverter()
AssetNotFoundException: with_built_value|lib/tables.drift_prep.json
[INFO] Running build completed, took 3.9s
[INFO] Caching finalized dependency graph completed, took 36ms
[INFO] Succeeded after 4.0s with 12 outputs (15 actions)
```

Is this a bug or a known limitation?

Thanks in advance!

**Comment by simolus3** [comment]
It's an issue in the build configuration of the example, it should enable `preparing_builder` like this:

```patch
diff --git a/examples/with_built_value/build.yaml b/examples/with_built_value/build.yaml
index 4878939b..824e2e03 100644
--- a/examples/with_built_value/build.yaml
+++ b/examples/with_built_value/build.yaml
@@ -4,6 +4,8 @@ targets:
       # disables the SharedPartBuilder in favor of a PartBuilder from drift_dev
       drift_dev:
         enabled: false
+      drift_dev:preparing_builder:
+        enabled: true
       drift_dev:not_shared:
         enabled: true
```

I've updated the example in 572e79d551735679aa7c59a1a6bc9d28d74a75a2. But if you have a larger project on which you want to mix drift and other builders so that they can see their outputs, using [modular generation](https://drift.simonbinder.eu/docs/generation-options/modular/) may be more efficient and flexible.

**Comment by davidmartos96** [comment]
@simolus3  Thank you!

**Comment by davidmartos96** [comment]
@simolus3 Does the modular setup require any special configuration for multiple builders?
I'm not able to find any example mixing the 2, and the default modular configuration doesn't seem to work with multiple builders setups, like the "with_built_value" example

**Comment by simolus3** [comment]
I think it should work if you push the modular build configuration into its own build target and have the main target depend on that? I think I'll just try it out by converting the built\_value example though, then we know for sure :D

**Comment by simolus3** [comment]
Alright, I've tried that in fcd984f1346b32d60efbcc33be7b72f83a81eda7 and it seems to work fine when adding the dependency between the two targets.

**Comment by davidmartos96** [comment]
@simolus3 Thanks Simon, I got it working with that.
I noticed you didn't include the `drift_dev:analyzer` setting as stated in the docs. Is that necessary, or are the docs out of date?

**Comment by simolus3** [comment]
When enabling `drift_dev:modular`, `drift_dev:analyzer` will implicitly be enabled as well. So with the default option, you don't need to mention drift's analyzer builder explicitly.

When you're enabling options, those should be applied to both builders since some of them only affect code generation (`:modular`) and some of them affect how drift is interpreting tables and other elements (`:analyzer`).

I've added options to the `with_built_value` example in bd2d05d6295cf55eed1d1b68c43a2c6fe3c77afe.

**Comment by davidmartos96** [comment]
@simolus3 Oh I see, that makes sense now. Thank you!
