### ISSUE TITLE
insertOnConflictUpdate fires an 'UpdateKind.insert' during conflict/update

### ISSUE THREAD

**Issue by Adam-Langley** [simolus3/moor#2659]
When calling 'insertOnConflictUpdate' that triggers a conflict and hence branches to perform an UPDATE, the code fires an 'insert' event.

Should probably fire an 'update' so UI knows to update existing records rather than perform a reload/insertion...

`insert.dart`

```
  Future<int> insert(
    Insertable<D> entity, {
    InsertMode? mode,
    UpsertClause<T, D>? onConflict,
  }) async {
    final ctx = createContext(entity, mode ?? InsertMode.insert,
        onConflict: onConflict);

    return await database.doWhenOpened((e) async {
      final id = await e.runInsert(ctx.sql, ctx.boundVariables);
      database
          .notifyUpdates({TableUpdate.onTable(table, kind: UpdateKind.insert)});
      return id;
    });
  }
```

**Comment by simolus3** [comment]
The idea of the `UpdateKind` enum is  to properly consider triggers added to the database when considering which streams need updating. E.g. we when there's a trigger `AFTER UPDATE ON foo BEGIN INSERT INTO bar ... END`, we know that updates on `foo` also invalidate streams listening on `bar`.

There's no way for us to know whether an upsert ran an insert or an update since that decision happens in the database engine and not in Dart. The general statement we're running is an insert, and that's what we're reporting.

> so UI knows to update existing records rather than perform a reload/insertion...

That's not really an accurate way to check for new records. The UI should react to changes of the current snapshot (by comparing the rows with the previous snapshot if necessary).

I'll document the limitation, but I don't think we should try to infer the update kind for upserts.

**Comment by Adam-Langley** [comment]
Thanks @simolus3,
That makes sense.

How I came about that conclusion (which may be incorrect), is I was calling 'insertOnConflictUpdate', which internally looks like this:

```
Future<int> insertOnConflictUpdate(Insertable<D> entity) {
    return insert(entity, onConflict: DoUpdate((_) => entity));
}
```

So it looked like it was an *explicit* decision happening in application code, to respond to a failed insert, with an update....

```
  Future<int> insert(
    Insertable<D> entity, {
    InsertMode? mode,
    UpsertClause<T, D>? onConflict,
  }) async {
    final ctx = createContext(entity, mode ?? InsertMode.insert,
        onConflict: onConflict);

    return await database.doWhenOpened((e) async {
      final id = await e.runInsert(ctx.sql, ctx.boundVariables);
      database
          .notifyUpdates({TableUpdate.onTable(table, kind: UpdateKind.insert)});
      return id;
    });
  }
```

But I guess, as you've explained, there is more going on there - perhaps other code paths to get to that point.

Thanks!
