### ISSUE TITLE
Melos error when using drift postgres

### ISSUE THREAD

**Issue by Leylan24** [simolus3/moor#2674]
Is there a reason the example uses this specific fork of the postgres package?

https://github.com/simolus3/drift/blob/e1b5da3160232403cbe95340218e8e6c762a07cd/extras/drift_postgres/pubspec.yaml#L26

So if you using melos to build a package and you follow the instructions in the readme you get the following error when running flutter upgrade and melos bs:

```
Because every version of drift_postgres from git depends on postgres from hosted and test_package depends on postgres from git, drift_postgres from git is forbidden.
So, because test_package depends on drift_postgres from git, version solving failed.
```

i managed to get rid of the error by unpinning the postgres and letting it use the package from pub.dev

**Comment by simolus3** [comment]
I didn't know pub/melos also apply `dependency_overrides` from external dependencies - the override was just meant as something useful when working on `drift_postgres` itself.

Since a usable version of the v3 preview APIs have since been published to pub.dev, I've just removed the dependency override from the readme.
