### ISSUE TITLE
Edit object that extends DataClass after instantiating it

### ISSUE THREAD

**Issue by froccawork** [simolus3/moor#2697]
I would like to know how to modify an object that I instantiate at the entrance of a class. Let me explain better: 

in the initState of the class I initialize this:

`expenseReportModel = ExpenseReportModelData(
        uuid: const Uuid().v4(),
        expenseReportsTypeCode: "",
        expenseReportsTypeDescription: "",
        dateInsert: DateTime.now(),
      );`

Where expenseReportModel is ExpenseReportModelData. 
ExpenseReportModelData has many fields which I then evaluate in a form and I would like to do something like expenseReportModel.expenseReportsTypeCode = "something", but expenseReportsTypeCode is final so it gives me an error.

What can I do? should I use copyWith? how should I use it?

Thanks

**Comment by simolus3** [comment]
Drift has generally been designed with immutable row classes in mind, but you can make these classes mutable by enabling the `mutable_classes` [builder option](https://drift.simonbinder.eu/docs/advanced-features/builder_options/), which would make the original code work. Otherwise, `copyWith` is a good option as well I think.
