### ISSUE TITLE
PgDataTypes are not compatible with SQLite

### ISSUE THREAD

**Issue by Leylan24** [simolus3/moor#2710]
I am using the postgres data types successfully. However when we trying to use this in a sqlite table we get an error.

```
CREATE TABLE a (
  id int8 NOT NULL PRIMARY KEY,
  guid `PgTypes.uuid` NOT NULL,
```
Inserting into postgres works fine, but if I insert into a sqlite database of the same structure. I get the following error:

`Invalid argument (params[2]): Allowed parameters must either be null or bool, int, num, String or List<int>.: Instance of 'UuidV`

**Comment by simolus3** [comment]
That is intentional - custom types are supposed to directly represent capabilities of the underlying database engine. If you want a uuid column that works with different engines, use a text column with a type converter.

You could write your own uuid type implementation that kind of works with both like this:

```dart
bool get isUsingPostgres;

class MyUuidType implements CustomSqlType<UuidValue> {
  const MyUuidType();

  @override
  String mapToSqlLiteral(UuidValue dartValue) {
    // UUIDs can't contain escape characters, so we don't check these values.
    return "'${dartValue.uuid}'";
  }

  @override
  Object mapToSqlParameter(UuidValue dartValue) {
    if (isUsingPostgres) {
      return TypedValue(Type.uuid, dartValue.uuid);
    } else {
      return dartValue.toString();
    }
  }

  @override
  UuidValue read(Object fromSql) {
    return UuidValue(fromSql as String);
  }

  @override
  String sqlTypeName(GenerationContext context) {
    return switch (context.dialect) {
      SqlDialect.postgres => 'uuid',
      _ => 'TEXT', // no native uuid support, store as text
    };
  }
}
```

You'd have to implement `isUsingPostgres` so that it returns the correct value based on the configuration of your app/server, but then using ``guid `const MyUuidType()` `` should work.

But again, if there's no strong reason to use the uuid column on Postgres and you need the compatibility across engines, using a regular text column and implementing the conversion with a type converter is the intended way.
