### ISSUE TITLE
Insert does not work without id

### ISSUE THREAD

**Issue by listepo** [simolus3/moor#2767]
```
class Accounts extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
}
```

```into(accounts).insert(Account.fromJson(type)``` -  does not work
```into(accounts).insert(Account.fromJson(type).toCompanion(true));``` -  does not work
```into(accounts).insert(Account.fromJson(type).toCompanion(false));``` -  does not work
<img width="476" alt="Screenshot 2023-12-03 at 20 37 25" src="https://github.com/simolus3/drift/assets/2510800/2101cdd0-8f22-4ca4-a97e-f7764ad25712">

my id should be autoIncrement, why is it still necessary?

**Comment by simolus3** [comment]
It's necessary because `Account` is designed to hold a full row as it would appear in the database. If we didn't do this, `id` would have to be nullable which would be very annoying for selects. So `Account.fromJson(type)` fails if `type` doesn't include an id.

You could use this as a workaround:

```dart
  Account.fromJson({
    'id': 2,
    ...type,
  }).toCompanion(false).copyWith(id: Value.absent());
```

But maybe you should consider not using `fromJson` if the originating data is incomplete - use a separate class without the id field and convert that to a companion.
