### ISSUE TITLE
`AccountType` is not a class!

### ISSUE THREAD

**Issue by listepo** [simolus3/moor#2779]
and so on with each class for references
<img width="898" alt="Screenshot 2023-12-08 at 22 40 58" src="https://github.com/simolus3/drift/assets/2510800/f22914ba-9592-43c1-85cc-5bc786bb8f3b">
<img width="898" alt="Screenshot 2023-12-08 at 22 41 50" src="https://github.com/simolus3/drift/assets/2510800/fea164d5-8377-4a30-bf0e-beb73f4e69ae">
<img width="843" alt="Screenshot 2023-12-08 at 22 41 56" src="https://github.com/simolus3/drift/assets/2510800/0bda71aa-ca6d-4d19-8ae1-0aaf9513021b">

**Comment by simolus3** [comment]
You need to reference the table in `references`, not the generated data class. Perhaps this should be `references(AccountTypes, #id)`?

The reason drift gives the somewhat confusing error message is because `Accounts` is generated by drift, so at the time we try to resolve the table, it doesn't exist yet.
