### ISSUE TITLE
The example app does not persist data on reload

### ISSUE THREAD

**Issue by jaseemtan** [simolus3/moor#2792]
The example app is not persisting data on web on page reload.

The web app is compiled using:

```
➜  app git:(develop) flutter build web

Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons), but found (MaterialIcons). This usually means you are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the package that would include them, or
are missing "uses-material-design: true".
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7848 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Compiling lib/main.dart for the Web...                             42.0s
```

Then ran as:
```
http-server .
Starting up http-server, serving .

http-server version: 14.1.1
...
Available on:
  http://127.0.0.1:8080
  http://192.168.1.2:8080
  http://10.211.55.2:8080
  http://10.37.129.2:8080
Hit CTRL-C to stop the server
```
The app is then launched on Edge browser. Adding a todo shows in the list. But when I refresh the page only the two default entries are shown. The newly added todo is not shown. In the browser console I see two errors.

```
Failed to fetch a worker script.
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by jaseemtan** [comment]
I tried the `flutter_web_worker_example` and is facing the same issue.

<img width="1006" alt="Screenshot 2023-12-17 at 12 03 49 PM" src="https://github.com/simolus3/drift/assets/75387973/c642f62e-4689-4788-810b-e530b177c8cc">

**Comment by simolus3** [comment]
You need to run `dart run build_runner build` before building the examples. This is because these examples don't use a prebuilt drift worker but instead compile them with `build_runner`, so if without running that command the worker will be missing and no persistence is possible.

I'll add that information to the readme - let me know if you run into other issues with the examples after the worker has been generated.

**Comment by juanccalzadilla** [comment]
I got the following error on console when i built flutter web app:

<img width="560" alt="Captura de pantalla 2024-01-15 a las 12 24 13" src="https://github.com/simolus3/drift/assets/78725536/fe9c7401-dd73-40f3-9b73-a492d8e136f5">

What could be?


Thanks! @simolus3

**Comment by PrimeTimeTran** [comment]
Might I ask you guys how you got past the following error?

`Using WasmStorageImplementation.sharedIndexedDb due to unsupported browser features:
{MissingBrowserFeature.dedicatedWorkersInSharedWorkers, MissingBrowserFeature.sharedArrayBuffers}` 

I've tried doing the suggestions of this documentation on `pub.dev`

https://pub.dev/documentation/drift/latest/drift.wasm/WasmStorageImplementation.html

Running a server with appropriate headers:
dhttpd '--headers=Cross-Origin-Embedder-Policy=require-corp;Cross-Origin-Opener-Policy=same-origin'
Server started on port 8080

But that page isn't found when I navigate to `http://localhost:8080/`

A bit confused because I've run through the documentation several times and it still doesn't work. I am able to successfully run the example web app though found [here](https://github.com/simolus3/drift/tree/develop/examples/app).

Looking forward to your help =).
