### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by OpenJarvisAI** [simolus3/moor#2799]
I have a table DbMessage, which I can query out messages, 

due the my tablee just defines the originalityId, I want query the message of oriignalityId as well.

But I stucked..

```
 Stream<List<DbMessageWithDbContactOrRoomMember>>
      getMessagesWithContactByRoomId(String roomId) {
    final query = select(messages)
        .join([leftOuterJoin(contacts, contacts.id.equalsExp(messages.fromId))])
      ..where(messages.roomId.equals(roomId))
      ..orderBy([
        OrderingTerm(expression: messages.sendTime, mode: OrderingMode.desc)
      ]);
    return query.watch().map((rows) {
      return rows.map((row) {
        DbMessage dbMessage = row.readTable(messages);
        DbMessageExtra dbMessageExtra = DbMessageExtra.fromDbMessage(
          dbMessage,
          repliedMessages: null, // Set accordingly
          originalityMessage: null, // Set accordingly
        );

        if (dbMessage.originalId != null) {
          // final List<DbMessage> messagesWithOriginalId = select(messages)
          //   ..where(messages.originalId!.equals(dbMessageExtra.originalId!))
          //   ..get();
          // dbMessageExtra.repliedMessages = messagesWithOriginalId;

          final DbMessage originalMessage = (select(messages)
            ..where(messages.id.equals(dbMessageExtra.originalId))
            ..getSingle())!;
        }

        return DbMessageWithDbContactOrRoomMember(
          dbMessageExtra,
          contact: row.readTableOrNull(contacts),
        );
      }).toList();
    });
  }
```

How to do a second select query here?

It;s all stream, I don't know how to assign to my extened DbMessageExtra data strcut. 

Help!!

**Comment by simolus3** [comment]
Running additional queries for each row you encounter might slow things down, but you can load all potentially interesting messages from the database and stitch the reply relations together in Dart (the [many-to-many](https://drift.simonbinder.eu/docs/examples/relationships/) example from the repository is doing something similar).

Assuming that replies can only happen in the same conversation, you only have to change the code in the outer `map` to:

1. Build a lookup `Map` from message IDs to their loaded (`row.readTable(messages)`) row.
2. For `originalityMessage`, load the id from the message object and look it up in that map.
3. For `repliedMessages`, you can use [json_each](https://drift.simonbinder.eu/docs/examples/relationships/#with-json-functions) with a subquery added to the query to load the ids of all nested messages into a single column. You can then read that column, parse it into a list of message IDs via `json.decode` and look those up in the message `Map` from step 1.

**Comment by OpenJarvisAI** [comment]
@kuhnroyal  Hey, rube bird. why are u thumb down my post? It have nothing to do with you.

@simolus3  thank u so much for the answer,  it's above your sub account?

Can u help me some example code how to stich them togather?

I am currently stuck at this ,  fetching messages which contains mesages nested. this should be a comon usage but not any example for it.

> For originalityMessage, load the id from the message object and look it up in that map.

this is exactly what am doing, but it returns a stream, I don't know how to stich it into my data model....

**Comment by kuhnroyal** [comment]
Because your communication and demeanor does not fit the general code of conduct. `Help!` or even more exclamation marks are rude and not a valid issue title in any Github project.
If you need help, be nice.

@simolus3 Sry for the rant.

**Comment by simolus3** [comment]
I agree that the issue could have used a more detailed description of what you've already tried, which schema your messages table has and what the query is supposed to do. That makes it easier to understand what's missing, which leads to more helpful responses :)

> I am currently stuck at this , fetching messages which contains mesages nested. this should be a comon usage but not any example for it.

It's not for this exact scenario, but I think the [many-to-many](https://drift.simonbinder.eu/docs/examples/relationships/) example covers the building blocks necessary for writing such queries.

> this is exactly what am doing, but it returns a stream, I don't know how to stich it into my data model....

I meant resolving the relation inside of `map`, where `rows` is just a list representing the current snapshot instead of a stream. If you give me a standalone example of the messages/contacts schema so that I can try running the query, I can help with the JSON subquery and how to parse it in Dart.

**Comment by OpenJarvisAI** [comment]
@kuhnroyal I don't think a word `help` ruins any regular in community, I have dedicated post my questions, neverthless I am an user of this lib, if I am the author I won't ask any questions I understand whole project, but I am not, so I have to ask, is the word `help` make you uncomfortable? If so, you thumb down the post won't make your happier, just be nice for you to rokiies on this lib like me.

**everybody has a starter period in learning new things, just be nicer to everyone, don't come to thumb down before thinking deep what you are doing**

**Comment by OpenJarvisAI** [comment]
@simolus3  Sorry for my bad English, I have the query like this:

```dart
 final query = select(messages)
        .join([leftOuterJoin(contacts, contacts.id.equalsExp(messages.fromId))])
      ..where(messages.roomId.equals(roomId))
      ..orderBy([
        OrderingTerm(expression: messages.sendTime, mode: OrderingMode.desc)
      ]);
```
then:

```dart
query.watch().map((rows) {
      return rows.map((row) {
```
you mean in rows.map I can get originality message I want, but I seems need select() it first.

Do u know how can I write the query to get message that under roomId, and every originality message under that message?

**Comment by simolus3** [comment]
What I was trying to say is that, since responses can only happen in the same room, you'll already have all the messages you need in `rows` and no additional queries should be necessary. This means that you can write the query like in [this snippet](https://gist.github.com/simolus3/53ef924345368d9a172d4c708028caad).
It's not possible in SQL to have array columns, but you can group multiple rows into a JSON array and read that in Dart to find the id of responses. By creating a map from all involved message ids to their content, finding children is then just a matter of iterating through that array and looking up messages by their id.

-----

> everybody has a starter period in learning new things, just be nicer to everyone, don't come to thumb down before thinking deep what you are doing

This issue tracker is for everyone. By using a clear title and description, others who may have similar issues in the future can quickly find what they're looking for. You're welcome to ask any questions you may have about drift here, but please respect the time of people trying to help you by giving clear and relevant details about the problem.
