### ISSUE TITLE
Wrong generated code when using import alias for Dart tables

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#2845]
Hello!
I noticed that when using an import alias for the `tables` property in the `DriftDatabase` annotation the generated code is not using the alias, so it won't compile.

I'm not sure how actionable this issue is, I'm sure it's not that common to do this. To give more context, in [`electricsql`](https://pub.dev/packages/electricsql) a drift schema is generated automatically based on a Postgres schema, so that then the user only needs to do `@DriftDatabase(tables: kElectrifiedTables)`. The tables list is a constant that is also generated automatically ( `List<Type>`). 
This works, but an user reported that the drift code gen wasn't working when using an import alias for the schema file.

It can be reproduced by editing the `app` example in the repo as follows:

![image](https://github.com/simolus3/drift/assets/22084723/3584552d-54b0-4520-b539-8560d47461b5)

**Comment by simolus3** [comment]
Thanks for opening the issue, I actually wanted to fix this for a long time! In the writer, we only get a name of the element and its definition uri and we have to resolve its import alias based on that. It's not a fully sound solution, but most instances of this should be fixed by 261c151fbf87a580b07bc8565afbd9d7f16e9a07. That looks up all named imports in a library and picks the first one that matches. It's not correct because, if a name is imported both with and without a name, we won't always pick the right one now. But it's likely that most of these cases are already broken today, and this will at least improve some of them.

**Comment by davidmartos96** [comment]
Thanks Simon, as always! 😄
