### ISSUE TITLE
DataClass toJson/fromJson with column names

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#2847]
Hello again Simon!
There is a feature request for drift we got from someone using `electricsql`. The user expected the `DataClass` `fromJson` to use the column names and not the dart field names as the map keys.

I see that there is an option in the generator to use the column names when using drift files (`use_column_name_as_json_key_when_defined_in_moor_file`), but not when using dart table definitions.
Is there any particular reason why is implemented that way and not for both? Looking at the name it looks like a very old option, back when the package was called `moor`. 

I've made the easy change locally in the following location to work on Dart tables too and it seems to work ok, no analysis errors or anything.

https://github.com/simolus3/drift/blob/261c151fbf87a580b07bc8565afbd9d7f16e9a07/drift_dev/lib/src/analysis/results/column.dart#L115

**Comment by simolus3** [comment]
It is a pretty old option. I think we can replace it with a newer one applying to both kinds of table declarations. That said, you can also do this in `electricsql` when generating drift tables by adding a `@JsonKey` annotation to the column (the annotation is from drift, not the one from `json_serializable`). Since you're already generating tables, an alternative might be to generate row classes with a `@JsonSerializable` annotation as well and then add a `@UseRowClass` annotation to generated tables.

IMO, having JSON serialization built into drift is a mistake. That feature was part of the very first version and now I can't really remove it anymore. But serialization and database access are different problems, and ideally drift shouldn't have to deal with JSONs at all. The configuration options drift has to customize serialization properties will always lack behind what `json_serializable` and others have to offer.

**Comment by davidmartos96** [comment]
@simolus3 Yes, I definitely agree, and it adds unneccesary complexity to the drift package. Custom row classes is a nice solution to give more control to the user.
This was just asking for some way to configure it globally. In any case, we'll add an option to annotate with `UseRowClass` if the user needs to. 
Thanks!
