### ISSUE TITLE
How to reference a Table which is in another package?

### ISSUE THREAD

**Issue by sun-jiao** [simolus3/moor#2871]
**Describe the bug**

When Tables and the Database are in different packages, build always fails with the following warning:

```
[WARNING] drift_dev on lib/db/drift_birdart.dart:
line 14, column 7 of package:birdart/db/drift_birdart.dart: The referenced element, BirdTable, is not understood by drift.
   ╷
14 │ class AppDatabase extends _$AppDatabase {
   │       ^^^^^^^^^^^
   ╵
```

When the Tables are placed in the same package, the build will success.

**Comment by sun-jiao** [comment]
Let me explain why I want to do this: I'm writing a dart full stack application (meaning shelf back-end, flutter mobile app and flutter web) and I want to place the shared code - such as the data model definition - in a library, then import them in the shelf project and flutter project. However I realized that drift doesn't seem to allow it. I'm currently using floor and trying drift for the first time today, because drift supports not only sqlite but also mysql or postgresql - obviously, it's not a good idea to use sqlite on the backend.

**Comment by simolus3** [comment]
This is something that should generally work, but requires a bit of setup. The package containing `BirdTable` needs to have a public (so non-dev) dependency on `drift_dev` so that drift's analyzing builder can run on those sources.

> and I want to place the shared code - such as the data model definition - in a library, then import them in the shelf project and flutter project

One thing worth mentioning is that drift's generator is monolithic by default - it generates all the code into a single part file, the one for the database. So all the generated table classes and so on would be duplicated if both the server and the client are declaring a drift database. A solution is to use [modular builds](https://drift.simonbinder.eu/docs/generation-options/modular/), in which drift will generate multiple files and actually allow sharing data classes.

**Comment by sun-jiao** [comment]
Thanks. However, adding `drift_dev` does not fix it. 

I solved the problem by moving the database class to the shared package.

**Comment by simolus3** [comment]
I've also pushed an example using two different database packages sharing some definitions in af55bd0f92cf8431a46f91c9f63c2ed42998e6a5.

**Comment by sun-jiao** [comment]
@simolus3 thanks. I did not run builder in the shared package.
