### ISSUE TITLE
support table-valued function syntax

### ISSUE THREAD

**Issue by galacticgibbon** [simolus3/moor#2877]
**Is your feature request related to a problem? Please describe.**
I tried to get fts working with trigram tokenizer, which seems to require table-valued function syntax .e.g. `SELECT * FROM tri('cdefg');`

But the drift generator doesn't appear to recognize this properly and generates invalid response types 

**Describe the solution you'd like**
Support table-valued function syntax in the generator

**Comment by simolus3** [comment]
We support table-valued functions in the generator, but from a quick look at the documentation it looks like this is a special syntax for selecting from a virtual table? We should support that since it's supported by sqlite3, but you can probably work around this limitation by rewriting the query to use the `MATCH` operator.

**Comment by galacticgibbon** [comment]
Yes using MATCH does seem to work
