### ISSUE TITLE
.moor nested results

### ISSUE THREAD

**Issue by North101** [simolus3/moor#288]
In .moor files it'd be awesome when returning fields from SELECT queries, columns that return all objects for a table/subquery would return a nested object instead. e.g.

`SELECT foo.*, bar.id` would return `FooBarId(Foo, foo, int id)`
`SELECT foo.*, bar.*` would return `FooBar(Foo foo, Bar bar)`

**Comment by North101** [comment]
Just to add to this: if e.g. all of the columns for `Foo` is `null`, then foo should be `null`

**Comment by North101** [comment]
Any more thoughts for this? I think it'd be a great addition. Could use something like `foo.**` instead for backwards compatibility.

e.g.
```
SELECT foo.**, bar.**

FooBar(foo, bar)
```

```
SELECT foo.*, bar.*

FooBar(foo_id, foo_name, bar_id, bar_name)
```

```
SELECT foo.*, bar.**

FooBar(foo_id, foo_name, bar)
```

**Comment by simolus3** [comment]
I really like the `**` syntax, awesome idea!

One of the things that was making this hard is duplicate colums, e.g. if we had 

```sql
CREATE TABLE foo (id INT NOT NULL PRIMARY KEY); 
CREATE TABLE bar (id INT NOT NULL PRIMARY KEY, foo INT REFERENCES foo(id))

query: SELECT foo.**, bar.** FROM bar INNER JOIN foo ON foo.id = bar.foo;
```
The column names would be `id`, `id`, `foo`. On `moor_ffi` we can access columns by their index, but `sqflite` only gives us a `Map<String, dynamic>`.

Since we need to desugar `**` either way, now we might as well expand those columns manually, turning the query into something like
```sql
SELECT foo.id AS "foo.id", bar.id AS "bar.id", bar.foo AS "bar.foo" FROM bar INNER JOIN foo ON foo.id = bar.foo;
```
Since the generator would pick the column aliases and mapping, problem solved :)

**Comment by simolus3** [comment]
Thanks again for the feature request and the `**` suggestion - I agree that this is a valuable feature. It will be released with the next moor version. A working version is on `develop`, but I still need to write more tests and documentation.

> Just to add to this: if e.g. all of the columns for Foo is null, then foo should be null

I've went for a slightly more strict approach: If any non-nullable column of `Foo` is null in the row, then `foo` will be null in the parsed result. I expect that those are mostly equivalent since tables entirely consisting of nullable columns are rare, but this approach seems like it will work better together with nnbd.

There are some restrictions on where `**` can be used
- there is no such thing as `SELECT ** FROM`, one always needs to use the `tableName.**` syntax
- for now, `**` can't be used in compound select statements:
- the table in `table.**` must refer to an actual table (no table-valued function or implicit table from a `WITH` block).

**Comment by North101** [comment]
Oh wow! I was not expecting something so quick! I think i'll give this a test (my app's database.g.dart file is current ~10600 lines long with nearly 40 .moor files)

**Comment by North101** [comment]
> * for now, `**` can't be used in compound select statements:
> * the table in `table.**` must refer to an actual table (no table-valued function or implicit table from a `WITH` block).
A shame but completely understandable

**Comment by North101** [comment]
Found a bug. Its not generating the result type.

```
ListLineageCharacterByResult _rowToListLineageCharacterByResult(
      QueryRow row) {
    return ListLineageCharacterByResult(
      lineageCharacter:
          lineageCharacter.mapFromRowOrNull(row, tablePrefix: 'nested_0'),
      character: character.mapFromRowOrNull(row, tablePrefix: 'nested_1'),
    );
  }

  Selectable<ListLineageCharacterByResult> listLineageCharacterBy(
      Expression<bool> predicate) {
    final generatedpredicate = $write(predicate, hasMultipleTables: true);
    return customSelect(
        'SELECT\n    "lineage_character.id" AS "nested_0.id", "lineage_character.lineage_id" AS "nested_0.lineage_id", "lineage_character.character_id" AS "nested_0.character_id", "lineage_character.name" AS "nested_0.name", "lineage_character.level_id" AS "nested_0.level_id", "lineage_character.xp" AS "nested_0.xp", "lineage_character.gold" AS "nested_0.gold", "lineage_character.bonus_perks" AS "nested_0.bonus_perks", "lineage_character.perk_ticks" AS "nested_0.perk_ticks", "lineage_character.retired" AS "nested_0.retired",\n    "character.id" AS "nested_1.id", "character.character_group_id" AS "nested_1.character_group_id", "character.name" AS "nested_1.name", "character.health_id" AS "nested_1.health_id", "character.color" AS "nested_1.color", "character.spoiler" AS "nested_1.spoiler"\nFROM campaign\nINNER JOIN party\n    ON party.campaign_id = campaign.id\nINNER JOIN lineage\n    ON lineage.party_id = party.id\nINNER JOIN lineage_character\n    ON lineage_character.lineage_id = lineage.id\nINNER JOIN character\n    ON character.id = lineage_character.character_id\nWHERE ${generatedpredicate.sql}\nORDER BY lineage_character.name',
        variables: [
          ...generatedpredicate.introducedVariables
        ],
        readsFrom: {
          campaign,
          party,
          lineage,
          lineageCharacter,
          character
        }).map(_rowToListLineageCharacterByResult);
  }
```

`ListLineageCharacterByResult` doesn't exist

**Comment by North101** [comment]
Some experimentation:

Works:
```
SELECT foo.*, bar.**
```

Doesn't work:
```
SELECT foo.**, bar.**
```
```
SELECT foo.id, bar.**
```

**Comment by North101** [comment]
Been testing it with my PR and works really well. Thanks!

**Comment by kuhnroyal** [comment]
Amazing feature, also works with table aliases which allows to customize the result class fields.
It would be great if we could name the generated class somehow.

```sql
queryMyList AS FooBar:
SELECT foo.**, bar.** FROM foos AS foo JOIN bars AS bar ON foo.id = bar.id;
```

**Comment by kuhnroyal** [comment]
Some of this should probably be documented. I just learned that this works:
```sql
queryWithImageAndCount:
SELECT
foo.**,
bar.**,
image.**,
CAST((SELECT COUNT(*) FROM images WHERE foo_id = foo.id) AS INT) AS imageCount
FROM foos AS foo
JOIN bars AS bar ON foo.id = bar.id
LEFT OUTER JOIN images AS image ON image.foo_id = (SELECT foo_id FROM images WHERE foo_id = foo.id ORDER BY images.created_date_time LIMIT 1);
```

@simolus3 And btw. you should really rename the `Learn More` button on the docu page into `Learn Moor` ;)

**Comment by simolus3** [comment]
The documentation for moor files mentions nested results [here](https://develop--moor.netlify.app/docs/using-sql/moor_files/#nested-results). The example includes table aliases and joins, so it should match everything from your query.

> `Learn More` button on the docu page into `Learn Moor` ;)

Every time I use the word `more` in the docs I think about this, haha. The `Learn More` button looks like a particularly good fit for that, I'll change it ;)
