### ISSUE TITLE
Usage without Row Models

### ISSUE THREAD

**Issue by clragon** [simolus3/moor#2887]
**Is your feature request related to a problem? Please describe.**
I have recently written a a backend in Kotlin using Exposed.
Exposed allows syntax like the following:

```kotlin
MyModel(
 someProp = row[MyTable.someProp]
)
```

As well as

```kotlin
statement[MyTable.somProp] = someProp
```

Basically treating Row results as well as insert/update statements as Maps which can be used with the Table columns to read/write values.

This is extremely practical for assembling models in a non-standard way, e.g. omitting fields or combining from multiple tables. 

Right now it doesnt seem like drift supports anything like this. 
Reading rows which arent part of a (generated) model seems difficult.

**Describe the solution you'd like**

I would like to be able to turn off generated row models and simply map my models by hand using a map-like structure or similar that returns the converted value based on a Table column.

I have no idea if any of this could ever work in dart and or drift given how kotlin is slightly more powerful in its expressive-ness from what I can tell.

#2791 goes somewhat into the direction I wish for but its less free form and more abusing the existing table mechanism.

**Comment by simolus3** [comment]
I think I understand what you want, and I agree that allowing more flexibility in the way queries are interpreted can be useful. But drift can already do most of these things, at least kind of. So it would be good to know what you've tried and what hasn't worked for you.

Through `selectOnly`, it's possible to obtain a [TypedResult](https://drift.simonbinder.eu/api/drift/typedresult-class) row which behaves in a similar way to rows from Exposed. You can call `read` with an expression, including table columns (which aren't static getters in drift but you can do `row.read(myTable.someProp)`). This allows omitting fields and combining multiple tables with joins. Is this kind of what you are looking for (or if not, what makes this inconvenient for you)?

I think we could still support a way to disable builtin row classes, for instance by letting users write `@UseRowClass(TypedResult)` or `@UseRowClass(Map)`. I want to mention that `@UseRowClass(Record)` is already a way to make drift emit considerably less code by using records instead of custom row classes. But if you need that dynamic expressiveness, are row classes actively standing in the way or is that still possible with `selectOnly` and other advanced query builder APIs?

**Comment by clragon** [comment]
I see, yes.

```dart
    (selectOnly(identitiesTable)..addColumns([identitiesTable.id]))
        .map((row) => row.read(identitiesTable.id)!)
        .watchSingle();

    (selectOnly(identitiesTable)..addColumns(identitiesTable.$columns))
        .map((row) => row.read(identitiesTable.id))
        .watchSingle();
```

these things work fine. I knew about selectOnly + addColumns but didnt realize I had to use the generated tables.

I guess this syntax doesnt necessarily feel intuitive to me but I have the feeling we probably cant do much better in dart because of the lack of reflection. An option for no RowClass would not be terrible as I prefer less code generation, but I assume we cant get rid of it entirely.
