### ISSUE TITLE
Very weired query, both true or false can no t be get out

### ISSUE THREAD

**Issue by OpenJarvisAI** [simolus3/moor#2889]
Hi, i have a simple query:

```
Stream<List<DbMessage>> getPinedMsgByRoomId(String roomId) {
    return (select(messages)
          ..where((tbl) => tbl.roomId.equals(roomId) & tbl.pin.not())
          ..orderBy([
            (t) => OrderingTerm(expression: t.sendTime, mode: OrderingMode.desc)
          ]))
        .watch();
  }
```

which get the pined message out, I tried with or without not(), nothing queried out.

my table defines like this:

```@DataClassName("DbMessage")
class Messages extends Table {
 BoolColumn get pin => boolean().withDefault(const Constant(false))();
  BoolColumn get favo => boolean().withDefault(const Constant(false))();
  IntColumn get theme => integer().withDefault(const Constant(0)).nullable()();
}
```

I am not very confused.

it at least be pinned or not piined, but none of them queried out any data.

**Comment by simolus3** [comment]
Just to be sure - rows are returned without the `& tbl.pin.not()` (so there are messages in the room you're querying)?
As far as I know, the only way for `tbl.pin` and `tbl.pin.not()` to both return no rows is if the column is `NULL`. But since the column is not defined as nullable in `Messages`, that's unlikely too.

**Comment by OpenJarvisAI** [comment]
Oh, my fault, I just make mistake on ui
