### ISSUE TITLE
Question about closing a stream

### ISSUE THREAD

**Issue by 32mandev** [simolus3/moor#290]
Hello,
thanks for your great work on moor.
I have a question about disposing a stream created with the watch method on a query:
do you automatically manage the disposal of the stream after the subscription is canceled?

**Comment by simolus3** [comment]
It's a bit complicated. To make it short: We don't explicitly close the underlying stream controller. But we clear all references to it after the subscription is canceled, so that it can be garbage collected.

There are multiple reasons for not closing the underlying stream controller.
1. Semantically, it doesn't make much sense - a database query could always be updated, so those streams aren't ever done.
2. We try to efficiently cache streams so that they work well when called in frequently (like from a build method in Flutter). So when you do
```dart
final a = select(table).watch();
final b = select(table).watch();
```
Moor detects that they're listening on the same query and only creates one stream controller. This is useful, since we have to potentially re-run fewer queries after a table update. But what happens if you then do `await a.first`? There would be a subscription to the stream controller that's closed after one event. Since they use the same stream controller under the hood, closing it would burn the `b` stream, that's now closed as well.
