### ISSUE TITLE
NullAwareTypeConverter not usable from drift files when the column is non-nullable

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#2907]
**Is your feature request related to a problem? Please describe.**
I tried using a custom `NullAwareTypeConverter` in drift files with non-nullable columns.
Neither subclassing nor wrapping seems to work, resulting in:

```
This column is non-nullable in the database, but has a type converter with a nullable SQL type, meaning that it may potentially map to `null` which can't be stored in the database.
```

**Describe the solution you'd like**
I think drift should check if the converter is an instance of `NullAwareTypeConverter` and allow the usage in this case.

**Comment by simolus3** [comment]
This would technically be unsound since you can override `toSql` in a `NullAwareTypeConverter` subclass to return null for non-null inputs.

But is there a reason for using null-aware type converters here? When applying a type converter not supporting null values to a nullable column, drift will actually wrap the converter in a `NullAwareTypeConverter` for you (and I think it should also do this for mapped non-nullable columns in outer joins which might then be null).  So if the intention is to map `null` in Dart to `NULL` in SQL, the easiest way is to declare the converter with non-nullable types and let drift figure out the null handling on columns where that's necessary.

**Comment by kuhnroyal** [comment]
Hmm, I never tried it with a non-nullable converter....

**Comment by kuhnroyal** [comment]
Ok, this works for me, sorry for the noise.
