### ISSUE TITLE
migration not working

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#291]
after change schemaVersion to 2 or 3, moor don't create new column in my table

```dart
class User extends Table {
  //@formatter:off
  IntColumn get id             =>integer().autoIncrement()();
  IntColumn get active         =>integer()();
  TextColumn get name          =>text()();
  TextColumn get email         =>text().nullable()();
  TextColumn get mobileNumber  =>text().nullable()();
  TextColumn get profileCode   =>text()();
  IntColumn  get userId        =>integer()();
  TextColumn get apiToken      =>text()();
  TextColumn get supporter     =>text().nullable()();
  TextColumn get createdAt     =>text()();
  TextColumn get updatedAt     =>text()();
  //@formatter:on
}

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration =>
      MigrationStrategy(
        onUpgrade: (m, from, to) async {
          if(from ==3){
            m.addColumn(user, user.profileCode);
            m.addColumn(user, user.userId);
          }
        },
      );
```

  moor_flutter: ^2.0.0
  moor: ^2.1.1
  moor_generator: ^2.1.1

result:

```bash
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device WAS LX1A...
I/flutter (16423): Moor: Sent SELECT * FROM user ORDER BY id DESC LIMIT 1; with args []
```

**Comment by simolus3** [comment]
You use `if (from == 3)` in a schema migration from 2 to 3. So the right condition would be more like `from == 2`. Be aware that you might need to support migrations from 1 to 3 as well (for users with an older version. So something like `if (from < 3)` might work better.

**Comment by MahdiPishguy** [comment]
in second version of ```schemaVersion``` i tested this solutions:

```dart
flutter packages pub run build_runner build
if(from < 2){

flutter packages pub run build_runner build
if(from > 2){

flutter packages pub run build_runner build
if(from > 1){
```

**Comment by simolus3** [comment]
Did you reset your apps data before trying out the other if statements? I assume it might look this this:

1. you did `flutter run` at `schemaVersion = 3` and `if(from ==3)`
2. the schema of the database on your device is now at 3, but doesn't have the new columns because the if-condition doesn't hold
3. You're changing the if statement, but it doesn't do anything because you're already at version 3, so no migration is happening.

If you don't want to reset your apps' data, you can also set `schemaVersion = 4` and use the `if (from < 3)` as a condition.
