### ISSUE TITLE
SqliteException(1): while preparing statement, near "RETURNING": syntax error, SQL logic error dart test

### ISSUE THREAD

**Issue by bytepoets-jhe** [simolus3/moor#2915]
Getting this error when tests are run on github actions or jenkins

Our primary key changed from row id to uuid, so we are using insertReturning for inserting our data, to get the generated uuid after the insert.
Since then I get these errors, but can't reproduce them locally when running our tests.

Error:
```
 SqliteException(1): while preparing statement, near "RETURNING": syntax error, SQL logic error (code 1)
    Causing statement: INSERT INTO "children_evaluations" ("id", "date_of_survey", "organization_name", "location_name", "group_name", "language", "project_id", "group_associated_by_admin", "license_name", "user_id", "local_interaction_count", "remote_interaction_count") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING *
  package:sqlite3/src/implementation/exception.dart 75:3                 throwException
  package:sqlite3/src/implementation/database.dart 300:9                 DatabaseImplementation._prepareInternal
  package:sqlite3/src/implementation/database.dart 359:19                DatabaseImplementation.prepare
  package:sqlite3/src/ffi/implementation.dart 111:18                     FfiDatabaseImplementation.prepare
  package:drift/src/sqlite3/database.dart 173:29                         Sqlite3Delegate._getPreparedStatement
  package:drift/src/sqlite3/database.dart 151:18                         Sqlite3Delegate.runSelect
  package:drift/src/runtime/executor/helpers/engines.dart 77:19          _BaseExecutor.runSelect.<fn>
  package:drift/src/runtime/executor/helpers/engines.dart 61:20          _BaseExecutor._synchronized
  package:drift/src/runtime/executor/helpers/engines.dart 74:26          _BaseExecutor.runSelect
  package:drift/src/runtime/query_builder/statements/insert.dart 174:30  InsertStatement.insertReturningOrNull.<fn>
  package:drift/src/runtime/api/connection_user.dart 162:64              DatabaseConnectionUser.doWhenOpened.<fn>
```

We now changed the function to insert and then get the evaluation by the row_id and now everything works again.

Hope this helps :)

**Comment by simolus3** [comment]
The error indicates that you're using an old sqlite3 version. `RETURNING` requires sqlite 3.35.0 or later. As unit tests in drift have to use the sqlite3 from the system (they're not running in a Flutter engine, so `sqlite3_flutter_libs` doesn't apply), they can fail if running against old sqlite3 versions.

The easiest fix is to upgrade your sqlite3 install. If that's not possible because you don't control the environment, you can compile sqlite3 yourself, say as part of the CI. I'm not experienced with Jenkins, but for GitHub actions you could take a look at [this workflow](https://github.com/simolus3/sqlite3.dart/blob/main/.github/workflows/main.yml) for inspiration. It's caching the compilation so it doesn't slow down runs, and with a custom `libsqlite3.so`, you can use this to priotize it over the one from the system: https://github.com/simolus3/sqlite3.dart/blob/2ffd871606e0f43f68f1364d8f4e1428dcbf3792/.github/workflows/main.yml#L145-L150 You can also grab precompiled libraries from [here](https://sqlite.org/download.html) and put them into `LD_LIBRARY_PATH`.

**Comment by bytepoets-jhe** [comment]
Thank you for the explanation!
