### ISSUE TITLE
Add Support for Richer SQL Queries(Raw Strings) in customSelect

### ISSUE THREAD

**Issue by PrimeTimeTran** [simolus3/moor#2954]
## Feature Request:
Could we add support for more complicated raw string inputs? Currently, `SELECT` doesn't respect `WHERE` clauses. 

## Description:
It would be awesome to include `WHERE, `GROUP BY`, `HAVING`, etc.

I'm working on a web SQL training tool and it sucks to not be able to add where clauses? I've tested with my DB and I know the DB is good(as evidenced by the screen shots). However when I query using `customSelect` I get `SQL logic error`.

It would be awesome if Drift were able to parse String literals including all the additional clauses within the `customSelect`.

## Data Exists:
![Screenshot 2024-04-14 at 11 12 29 PM](https://github.com/simolus3/drift/assets/16382165/ffb578c7-6cc5-4dae-a3b9-6b83d1372039)

## Queries with `WHERE` clause complains about `SQL Logic Error`:
![Screenshot 2024-04-14 at 11 16 24 PM](https://github.com/simolus3/drift/assets/16382165/df842241-d248-40f5-8390-173b91e5478d)

## Collecting SQL query client side.
![Screenshot 2024-04-14 at 11 17 24 PM](https://github.com/simolus3/drift/assets/16382165/5b288757-d6a0-44da-8f17-3e93e7b36fdf)

**Comment by PrimeTimeTran** [comment]
I poked around the repo trying to identify the issue but nothing sticks out to me [here](https://github.com/simolus3/drift/blob/ca0dee4f83234b053039d23b62d9defd007e7686/drift/lib/src/runtime/query_builder/statements/select/custom_select.dart#L5). 

Might this be a parser issue? Super confusing why it complains `no such column: Brazil` when my query is:
`SELECT * FROM customers WHERE "Country" = "Brazil";`

One more thing, the `SELECT` works without a `WHERE` clause.
![Screenshot 2024-04-14 at 11 45 49 PM](https://github.com/simolus3/drift/assets/16382165/765d4e49-9216-480b-9efa-6009dc939939)

**Comment by simolus3** [comment]
Drift is not parsing custom queries. The problem are the double quotes around `"Brazil"`. We compile sqlite3 with the recommended options, which means that things in double quotes are interpreted as references (so sqlite3 tries to search for a column named Brazil and then aborts the query because no such column exists). To use strings in SQL, use single quotes (`'Brazil'`).

To enable legacy support for double-quoted string literals, add a `setup` parameter to `NativeDatabase` that calls `rawDb.config.doubleQuotedStringLiterals = true`.

**Comment by PrimeTimeTran** [comment]
@simolus3 thanks for your suggestion. That worked like a charm for Native. However I'm targeting web so this is how I got my setup working inside if `web.dart`.

```dart
DatabaseConnection connect() {
  return DatabaseConnection.delayed(Future(() async {
    final result = await WasmDatabase.open(
      databaseName: 'main',
      sqlite3Uri: Uri.parse('sqlite3.wasm'),
      driftWorkerUri: Uri.parse('drift_worker.js'),
      initializeDatabase: () async {
        final data = await rootBundle.load('assets/chinook.db');
        return data.buffer.asUint8List();
      },
    );

    if (result.missingFeatures.isNotEmpty) {
      debugPrint('Using ${result.chosenImplementation} due to unsupported '
          'browser features: ${result.missingFeatures}');
    }
    return result.resolvedExecutor;
  }));
}
```

Could you make a suggestion for this setup? Poking around inside of `wasm.dart` [here](https://github.com/simolus3/drift/blob/ac4947f26684ffe2cf2cbbff20fa8ac3da158efc/drift/lib/wasm.dart#L223) I didn't see how I might do the same thing. 

Forgive me if I missed it. Also thanks so much for your work!

**Comment by simolus3** [comment]
Doing this on the web is a little tricky because your app doesn't own the database, it just accesses it through a separate worker (`drift_worker.js`). We can't sent closures to workers, so no similar API exists.

You can write your own worker that calls `WasmDatabase.workerMainForOpen()` which takes a similar callback used to configure all databases opened by that worker. The file could look similar [to this one](https://github.com/simolus3/drift/blob/develop/examples/app/web/worker.dart), except that it would add the callback.
You can compile your own worker with `dart compile js -O4 web/worker.dart`, or automatically with `build_runner` by adding a dependency on `build_web_compilers` (that is also what the example app is doing so that I don't have to manually copy the compiled worker into it, see [this build configuration](https://github.com/simolus3/drift/blob/develop/examples/app/build.yaml) for a starting point).
