### ISSUE TITLE
Drift file BigInt Generation

### ISSUE THREAD

**Issue by AlexandreAndrade00** [simolus3/moor#2955]
The following drift file generates the classes with int instead of BigInt:

```sql
CREATE TABLE dynamic_tables (
    id BIGINT PRIMARY KEY,
    name TEXT(512) NOT NULL,
    permissions TEXT(512) NOT NULL,
    max_entries INTEGER NOT NULL,
    version INTEGER NOT NULL,

);
```

Generated class:
```dart
late final i0.GeneratedColumn<int> id = i0.GeneratedColumn<int>(
    'id', aliasedName, false,
    type: i0.DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'PRIMARY KEY');
```

The BIGINT keyword shouldn't generate i0.DriftSqlType.bigInt with BigInt generic?

**Comment by simolus3** [comment]
I think the `BIGINT` keyword might be confusing because some users coming from other systems like postgres or mariadb could expect that to alter the storage class of the column.

I've implemented `INT64` as an alias that will make drift generate bigint columns in Dart. That also matches the `int64()` column builder used in Dart.

**Comment by AlexandreAndrade00** [comment]
Thank you for the fast reply and fix :grin:
