### ISSUE TITLE
Better identify variables

### ISSUE THREAD

**Issue by North101** [simolus3/moor#297]
It should be able to infer the variables in the following snippet but it can't.
```
INSERT INTO foo(id, :bar)
SELECT :foo_id, :bar
```
(I know I can do VALUES but I was trying to do a `INSERT INTO SELECT FROM`)

It'd be even nicer if you could specify the variable type yourself.
e.g.
```
createFoo(:foo_id AS TEXT, :bar AS BOOL)
INSERT INTO foo(id, :bar)
SELECT :foo_id, :bar
```

**Comment by simolus3** [comment]
I like the idea and syntax of explicitly denoting variable types. It can help in those cases not currently supported by the resolver. It's implemented on `develop` and will be supported in the next release.

At the moment, type inference works by pretty much only looking at the parent node in the AST (the select statement in this case). With that bottom-up approach, it's becomes tedious to support many special rules, such as the `INSERT INTO SELECT` you mentioned. If we instead used a top-down approach that looked at the insert statement first and then passed the expected column types down to the select statement, it would be much easier.
I've also thought about supporting dependencies on the same level, so that `:foo = :bar AND :bar = 'string'` would infer that `:foo` is a string. I'm not sure if there are many queries where that kind of inference is needed though.

 Working on type inference can be tricky - every difference is technically a breaking change as it affects generated methods. Maybe we can have an experimental build option to enable the new inference. When it turns stable, it can be the only option from the next breaking release.

**Comment by North101** [comment]
Thanks! That was quick!

Really appreciate the work you've done on this. Since I prefer to work with SQL rather than DAOs i'm probably really testing what can be done with it and i'll continue to post issues and suggestions.

**Comment by simolus3** [comment]
While still experimental, the new type inference is in a state where it can be previewed now. It should be compatible with old inference result (even though this was not a design goal and might change). It also supports the `INSERT INTO SELECT` statement you mentioned above. This might sound fairly unspectacular, but the internal model used by the new algorithm is much more accurate and reflects complex relations between different expressions and columns. In particular, this will help when inferring nullability, which will become important in future Dart versions. 

To enable it, you need to be on `develop` (4a2184110fbc18b9d21a2a9c6735a7c5f3357fd0 or later)  and put this into your `build.yaml`:
```yaml
targets:
  $default:
    builders:
      moor_generator:
        options:
          use_experimental_inference: true
```

If you run into cases where the experimental inference provides worse results (or anything you didn't expect, really), please let me know. It's declared to be experimental so that I can still make changes to it without breaking users.
