### ISSUE TITLE
TableUpdates data

### ISSUE THREAD

**Issue by MichalNemec** [simolus3/moor#2980]
Hello, with this code im able to watch every table for insert, update, delete
```
tableUpdates().listen((event) {
      for (var e in event) {
        print(e.table);
        print(e.kind);
      }
    });
```

However, this does not seem useful when i would need to have change tracker. 
My change tracker would need `add(row)` `modify(oldRow, newRow)` and `delete(row)`

How that could be done?

**Comment by simolus3** [comment]
There's no update notification mechanism with row-level accuracy built into drift (because it would not be portable).

But if you're using `NativeDatabase`s exclusively, you can use [updates](https://pub.dev/documentation/sqlite3/latest/sqlite3.wasm/CommonDatabase/updates.html). A way to access them might be via the `setup` parameter of `NativeDatabase`:

```dart
final db = Database(NativeDatabase.memory(setup: (rawDb) {
  rawDb.updates.listen((event) {
    print('Native update event: $event');
  });
}));
```

This gives you the table, kind and row id of every modification (well, not on `WITHOUT ROWID` tables but you're likely not using them). Note that the `setup` parameter is called on a different isolate if you use `NativeDatabase.createInMemory`, you might have to use an [isolate channel](https://pub.dev/documentation/stream_channel/latest/isolate_channel/IsolateChannel-class.html) or another mechanism to pipe these to your main isolate then.
