### ISSUE TITLE
[drift_postgres] Postgres implicit type casts not working in raw queries

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#2986]
Similar to #2981 this explicit casting can break valid Postgres queries.

For instance, passing a String to insert a INT8 column is valid in the postgres driver, but when forcing it to be always `Type.text` it will complain. 

Should we let the values go through to the `postgres` package with unspecified typing?

**Comment by simolus3** [comment]
I think this is working as intended for explicit variables added by drift. For others stumbling across this (e.g. for custom queries), a workaround is to use variables with a `TypedValue` from the `postgres` package that has its type set to `Type.undefined`. These values won't be modified by drift at all and can be used to signal that no explicit type is known.

(if it turns out that drift would benefit from not using explicit types as well, I'm happy to revisit this or perhaps make this an opt-in flag)
