### ISSUE TITLE
.insert() only returns int even when using Uint8List for primary keys.

### ISSUE THREAD

**Issue by britannio** [simolus3/moor#306]
With the new `clientDefault` setting added for #294, an entity can be inserted into the database without knowing the primary key in advance however the `insert()` function only returns an int making it difficult to obtain the primary key of the new entity when it isn't an integer.

`insert()` could return a `Future<dynamic>` or `Future<T>` with T being the type of the primary key. 
It might even be better for `insert()` to return the new entity that was added to the database.

**Comment by simolus3** [comment]
Some background: In sqlite, pretty much every table has an implicit column called `rowid` that serves as the native primary key. When you declare an `INTEGER PRIMARY KEY`, that column becomes an alias for `rowid`. Quite confusingly, any other primary key is just a `UNIQUE` constraint in disguise. See [sqlite docs](https://www.sqlite.org/rowidtable.html) for details.

Since the real primary key is almost always an int, sqlite exposes the [`sqlite3_last_insert_rowid`](https://www.sqlite.org/c3ref/last_insert_rowid.html) function, which is what moor returns for insert statements we well. To my knowledge, there's no builtin api to retrieve the user-defined primary key for the last insert.

A potential solution to this could be to select a primary key like this:
```sql
SELECT pk_column FROM table WHERE rowid = last_insert_rowid();
```

Obviously, changing `insert` would be a breaking change. We could add another method to load the "real" primary key of the last insert, which could return a correctly-typed future. For now, putting the above query in a moor file or into `UseMoor(queries:` should do the trick.

**Comment by britannio** [comment]
Thanks for the details. For now, the best choice for me seems to be avoiding `clientDefault` and instead, generating my primary keys(UUIDs) before running `insert()`. 
Is Dart support for the [WITHOUT ROWID](https://www.sqlite.org/withoutrowid.html) phrase when creating tables be possible? 
Thanks.

**Comment by simolus3** [comment]
>  Is Dart support for the WITHOUT ROWID phrase when creating tables be possible?

Adding this to your table class should work:
```dart
@override
bool get withoutRowId => true;
```

**Comment by britannio** [comment]
> > Is Dart support for the WITHOUT ROWID phrase when creating tables be possible?
> 
> Adding this to your table class should work:
> 
> ```dart
> @override
> bool get withoutRowId => true;
> ```

Is there any way to verify that the change took effect or any other schema change for that matter? Running code generation didn't change anything.
Thanks.

**Comment by simolus3** [comment]
> Running code generation didn't change anything.

The migrator will take a look at that field at runtime and append the `WITHOUT ROWID` to the created statement. https://github.com/simolus3/moor/blob/0cdfc9a4abb803fdb6414af880961a26be952207/moor/lib/src/runtime/query_builder/migration.dart#L134-L136

> Is there any way to verify that the change took effect or any other schema change for that matter? 

You can verify which `CREATE SCHEMA` statements are sent by setting `logStatements: true` on the `FlutterQueryExecutor` or `VmDatabase`, respectively.
I'm also working on a CLI tool that would dump the schema into a json file (part of #240).
