### ISSUE TITLE
Problem during building on Appcenter

### ISSUE THREAD

**Issue by abrass** [simolus3/moor#307]
I get an build error, if I just add moor_ffi as a dev_dependency to my fluuter project, which is built on AppCenter. It seems that there is a problem with linking of used types. Appcenter has following setup for cmake and ndk:

Package name | Description
cmake | 3.6.4111459
lldb | 3.1.4508709
ndk-bundle | 18.1.5063045

```* What went wrong:
Execution failed for task ':externalNativeBuildRelease'.
> Build command failed.
  Error while executing process /Users/runner/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/runner/.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.3.1/android/.cxx/cmake/release/armeabi-v7a --target sqlite3}
  [1/2] Building C object CMakeFiles/sqlite3.dir/sqlite3.c.o
  FAILED: /Users/runner/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=armv7-none-linux-androideabi16 --gcc-toolchain=/Users/runner/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/runner/Library/Android/sdk/ndk-bundle/sysroot -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_DQS=0 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_HAVE_ISNAN -DSQLITE_MAX_EXPR_DEPTH=0 -DSQLITE_OMIT_AUTHORIZATION -DSQLITE_OMIT_DECLTYPE -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_GET_TABLE -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_OMIT_TCL_VARIABLE -DSQLITE_OMIT_TRACE -DSQLITE_THREADSAFE=0 -DSQLITE_UNTESTABLE -DSQLITE_USE_ALLOCA -Dsqlite3_EXPORTS  -O3 -Oz -DNDEBUG  -fPIC -MD -MT CMakeFiles/sqlite3.dir/sqlite3.c.o -MF CMakeFiles/sqlite3.dir/sqlite3.c.o.d -o CMakeFiles/sqlite3.dir/sqlite3.c.o   -c /Users/runner/.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.3.1/android/cpp/sqlite3.c
  In file included from /Users/runner/.pub-cache/hosted/pub.dartlang.org/moor_ffi-0.3.1/android/cpp/sqlite3.c:13763:
  In file included from /Users/runner/Library/Android/sdk/ndk-bundle/sysroot/usr/include/stdio.h:42:
  In file included from /Users/runner/Library/Android/sdk/ndk-bundle/sysroot/usr/include/sys/types.h:36:
  /Users/runner/Library/Android/sdk/ndk-bundle/sysroot/usr/include/linux/types.h:21:10: fatal error: 'asm/types.h' file not found
  #include <asm/types.h>
           ^~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.
```

**Comment by simolus3** [comment]
I've never used appcenter unfortunately, so I can't say a lot about this. It looks like `stdio.h` can't be imported, which is very weird. Just to help diagnose this, can you remove the `moor_ffi` dependency and add [this](https://github.com/requery/sqlite-android) as a dependency to your build.gradle? If that builds in appcenter, it's likely a problem with moor_ffi that I can look into. If it doesn't, it could be something with your setup or appcenter in general.

--------
Ideally, Flutter shouldn't attempt to compile sqlite at all when `moor_ffi` is only used as a `dev_dependency`. I've opened https://github.com/flutter/flutter/issues/45714 for them to change this behavior.

**Comment by unidesigner** [comment]
I had the same problem locally with `ndk-bundle | 18.1.5063045` - updating to `ndk-bundle | 20.1.5948944` with `sdkmanager` in Android Studio solved it (not a dev_dependency, but normal dependency).

**Comment by abrass** [comment]
updating ndk seems not to be an option on appcenter. Although maybe they will update it in the next months... I'll try your dependency and give feedback.

**Comment by abrass** [comment]
I added   implementation 'io.requery:sqlite-android:3.30.1' to my android/app/build.gradle and the build on app center went through.

The issue seems to be connected with ndk, since locally I can also build my project with moor_ffi

Is there maybe an option so I can disable the building of sqllite3.so ? Or maybe set up moor_ffi in android so it is not compiled when a release build is run?

**Comment by simolus3** [comment]
Sorry for the delay on this.

> and the build on app center went through positively.

That's interesting - I've setup a moor_ffi version that's more similar to the way requery builds (ndk build instead of CMake). Can you try adding this to your pubspec? It's identical to the released version 0.3.1, except that it uses the other build system:
```yaml
dependency_overrides:
  moor_ffi:
    git:
      url: https://github.com/simolus3/moor.git
      ref: ndk-build
      path: moor_ffi
```

@vanlooverenkoen this might also help with #311, can you try it out?
If that works better, I'll switch to ndk build in a future release.

> Is there maybe an option so I can disable the building of sqllite3.so?

I don't think it's possible for plugins to have build options, so you probably need a moor fork. If you have a local version, removing these lines should do the trick:
https://github.com/simolus3/moor/blob/e995553623b17d10666ea344a8c8e4a2882e0712/moor_ffi/android/build.gradle#L31-L35

**Comment by abrass** [comment]
sry for my late response, I tried it now.

Your branch works on appcenter, great!

what is the plan with your fix? will you bring it up in the next release? or do we need to fork moor_ffi and add the changes you did in the ndk-build branch?

**Comment by abrass** [comment]
now that it is working the build time increased form 5 -> 15 minutes. 

So we should remove the lines in a fork for not having it built every time?

**Comment by simolus3** [comment]
Thanks for trying it out!

> will you bring it up in the next release

I got numerous issues about build errors with `moor_ffi`. Since requery uses ndk-build, I thought it might be related to using CMake and wanted to compare them. If ndk-build works better for most users, I'll release that version.

> or do we need to fork moor_ffi and add the changes you did in the ndk-build branch

My plan is to keep the `ndk-build` branch alive until I figure out what works best, even if I don't release it in the next version.

> now that it is working the build time increased form 5 -> 15 minutes

Do you mean that the build used to error out at 5 minutes? `moor_ffi` definitely increases the build time, we need to compile sqlite3 for each target platform (there are four of them). This takes around 3-5 minutes on my computer (i7-8550U), it might be slower on a CI. I think the best solution here is to not rebuild `moor_ffi` on every CI run, do you cache the `android/build` folder in your Flutter app?

**Comment by simolus3** [comment]
Actually I have another idea. It's forbidden to upload precompiled code to pub, but uploading packages that depend on precompiled code is perfectly fine. So in theory, we could just make `moor_ffi` depend on requery/sqlite-android. This also makes the build much, much faster. If anyone wants to try it out, you can use
```yaml
dependency_overrides:
  moor_ffi:
    git:
      url: https://github.com/simolus3/moor.git
      ref: requery
      path: moor_ffi
```

The only downside is that it adds unused Java classes, but I assume ProGuard should strip them out in release builds. I'll thoroughly test this in my moor projects, but I think it's the best approach if everything works out fine.

-----

@abrass I also forgot that you're only using moor_ffi as a dev dependency for testing, sorry. In that case the local version where you remove the native build is probably the best approach until https://github.com/flutter/flutter/issues/45714 gets fixed. Switching to any other branch to fix building a package you don't even use seems unnecessary.

**Comment by abrass** [comment]
i tried the requery build and it took 6:43 mins (with upload to appcenter distribution) instead of 17 minutes.

I would prefer that solution :)

**Comment by simolus3** [comment]
This problem should no longer happen, since we changed the way sqlite3 is built on Android.

If you're using `moor_flutter` and only need `moor_ffi` for testing, you can how just drop the `moor_ffi` dependency and simply import `package:moor/ffi.dart` library. You don't need to depend on `sqlite3_flutter_libs` if you only use ffi for testing.
