### ISSUE TITLE
Migration Error when altered same table twice.

### ISSUE THREAD

**Issue by Guang-B** [simolus3/moor#3078]
I have table called `Box` .
The Scenario :
1. I want to add `refferenceId `column  and add it as uniqueKey on version `2`
2. Then in Version `3` , I need to add another column called `refferenceNumber` and also add it as uniqueKey.

This Is My Migration Strategy : 
```
onUpgrade: (Migrator m, int from, int to) async { 
     await transaction(() async {
          if (from < 2) {
            await m.alterTable(
              TableMigration(
                box,
                newColumns: [box.refferenceId],
              ),
            );
          }
          if (from < 3) {
            await m.alterTable(
              TableMigration(
                box,
                newColumns: [box.refferenceNumber],
              ),
            );
          }
     });
}
```
The Case is : 
when My App is upgrading from version `1` to `2` and then upgrade it again from version `2` to `3`, The Migration Works Fine.
But, When My App is directly upgrade from version `1` to `3`, i got this error : 

```
SqliteException(1): while executing, no such column: refference_number, SQL logic error (code 1):  Causing statement: INSERT INTO tmp_for_copy_box ("id", "box_number", "type", "amount", "refference_number") SELECT "id", "box_number", "type", "amount","refference_number" FROM "box";, parameters:
```

So I Assumed that because when the app is upgrading directly from version 1 to 3, the `box` table is altered twice during `onUpgrade`
Please tell me, is this a bug or there is a mistake in my code. 

**Thank you**

**Comment by simolus3** [comment]
Indeed, the problem is that `alterTable` would get called twice when upgrading from 1 to 3 directly. The complicated solution is to account for this in your `onUpgrade` handler by always upgrading to the latest version in every branch, e.g.

```dart
          if (from < 2) {
            await m.alterTable( // 1 -> current
              TableMigration(
                box,
                newColumns: [box.refferenceId, box.refferenceNumber],
              ),
            );
          } else if (from < 3) {
            await m.alterTable( // 2 -> current
              TableMigration(
                box,
                newColumns: [box.refferenceNumber],
              ),
            );
          }
```

Of course, writing migrations that just do a single step and then chaining them is much easier and scales better. However, it requires you to actually migrate towards an intermediate, outdated schema (2) in your migration logic. Since `box` is generated for the current table though, that's not directly possible.
To do this, drift provides tools that [generate step-by-step migrations](https://drift.simonbinder.eu/docs/migrations/step_by_step/) based on exported database schemas. To set this up, you'd have to export your old schemas once (you can probably checkout the revision where you've updated the schema and run `dart run drift_dev schema dump` on that tree). Then, drift can generate all intermediate versions of your schema into a compressed format which provides enough information to write migrations like this:

```dart
    onUpgrade: stepByStep(
      from1To2: (m, schema) async {
        await m.alterTable(schema.box, newColumns: [schema.box.refferenceId]);
      },
      from2To3: (m, schema) async {
        await m.alterTable(schema.box, newColumns: [schema.box.refferenceId]);
      },
    ),
```
