### ISSUE TITLE
v2.19.0 introduced a breaking change

### ISSUE THREAD

**Issue by vaind** [simolus3/moor#3090]
**Describe the bug**

`QueryExecutor.beginExclusive` was added in v2.19.0 which is a breaking change in a non-major release.

```
class SentryQueryExecutor extends QueryExecutor {
      ^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/drift-2.19.0/lib/src/runtime/executor/executor.dart:62:17: Context: 'QueryExecutor.beginExclusive' is defined here.
  QueryExecutor beginExclusive();
                ^^^^^^^^^^^^^^
../../drift/lib/src/sentry_transaction_executor.dart:8:7: Error: The non-abstract class 'SentryTransactionExecutor' is missing implementations for these members:
 - QueryExecutor.beginExclusive
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
```

**Comment by buenaflor** [comment]
I added a fix in the sentry repo: https://github.com/getsentry/sentry-dart/pull/2162

**Comment by simolus3** [comment]
Sorry about the breakage! I've considered this when making the change, but as the docs of `QueryExecutor` mention:

> This is an internal api of drift, which can break often. If you want to implement custom database backends, consider using the new backends API.

`QueryExecutor` is kind of internal in the sense that it's not meant to be implemented directly. So I didn't consider this to be breaking, but obviously I should do a better job pointing that out, as the docstring is not really all that visible. I will also keep this in mind for further changes.

For sentry, which I assume is wrapping an existing implementation to add instrumentation, I suggest using the [QueryInterceptor](https://drift.simonbinder.eu/docs/examples/tracing/) class instead. Ideally that should also make the implementation a bit simpler since you don't need to add different classes for transactions and so on. But the fix adding `beginExclusive` works too of course.

**Comment by buenaflor** [comment]
@simolus3 all good!

iirc you've added the interceptor after we've talked about the drift integration so we didn't have that option back then but I'll deprecate the current api soon in favour of using the interceptor
