### ISSUE TITLE
CountAll not available

### ISSUE THREAD

**Issue by elkSal** [simolus3/moor#3100]
I would like to count all the rows of a specific query with group by.
I see there is available the count() but not countAll() when adding columns.

I checked the Drift repository and I think that `Expression<int> countAll({Expression<bool>? filter})` should be inside the `extension BaseAggregate<DT extends Object> on Expression<DT>` to expose the countAll function.

Link
https://github.com/simolus3/drift/blob/develop/drift/lib/src/runtime/query_builder/expressions/aggregate.dart

**Comment by simolus3** [comment]
Why would `countAll()` be an extension on `Expression`? It is exposed as a top-level function already, and from my view it doesn't make sense to make it an expression because it doesn't operate on a single expression. `countAll` is a `COUNT(*)` and there is no "star expression", so having that as a top-level member seems correct to me.

**Comment by elkSal** [comment]
Maybe I didn't make myself clear. CountAll is not exposed and not available as in this screenshot. Only Count function is available.
Maybe I misunderstood how to use CountAll, if so it would be helpful some documentation :)

![image](https://github.com/user-attachments/assets/2822b6a6-2c92-4742-865b-e7db03b2f2e3)

**Comment by simolus3** [comment]
In SQL, you can either do `COUNT(*)`, which counts all rows, or `COUNT(localWorkouts.name)`, which counts in how many rows `localWorkouts.name` is not null.
In most cases, especially when not using `distinct` or filters, the two forms work out to be the same. Still, drift lets you use both of them. If you want to count all rows, using `COUNT(*)` is typically the preferred form since it makes the intention clear. However, there isn't really an expression to attach the count to - `COUNT(localWorkouts.name)` is `localWorkouts.name.count()` in drift, but how would we write `COUNT(*)` with the same format? We can't, and that's why drift has a separate method for that which is not an extension on expression. You can still add it to your queries of course, it looks like this:

```dart
final numRows = countAll();
yourQuery..addColumns([numRows]);
```

Or, perhaps even simpler `..addColumns([countAll()])`.

I think this is a misunderstanding about being able to add expressions that aren't extensions, right? I'll close the issue, but if you have more questions let me know and I'll answer/re-open :)

**Comment by elkSal** [comment]
Thanks a lot for explaining! Is there a way to count the names even if a row might have a null name and count all these null names as well (each one as a different one) ?

**Comment by simolus3** [comment]
> Is there a way to count the names even if a row might have a null name and count all these null names as well (each one as a different one) ?

Sure! You'd have to keep using `countAll()` to count the nulls, but you can use `groupBy` to count every name (including `NULL` as its own group) separately.

So the query would be something like:

```dart
final query = selectOnly(localWorkouts)
  ..addColumns([localWorkouts.name, countAll()])
  ..groupBy([localWorkouts.name]);
```
