### ISSUE TITLE
Drift file generating incorrect typings

### ISSUE THREAD

**Issue by galacticgibbon** [simolus3/moor#3105]
**Describe the bug**

I have a drift file defining a view that uses a UNION ALL to merge two tables.

In the code provided, it generates the wrong types for some of the columns.

The columns being incorrectly typed in this case are:
- all the boolean columns are strings (archived, deleted, hasPendingWrites)
- date_updated is nullable even though date_created is not, and they are defined in the same way on both tables so that's strange!
- start_time is not nullable
- date_unit is nullable string even though type is correctly typed as its enum

I tried using CAST on the bool columns to no avail

```
import 'entry_row.dart';
import '../../calendar/models/device_events.dart';

CREATE VIEW entries_and_device_events AS
SELECT
  *,
  NULL AS calendar_id
FROM
  entry_rows

UNION ALL


SELECT
  *,
  'event' AS type,
  FALSE AS archived,
  'day' AS date_unit,
  NULL AS date_complete,
  NULL AS date_cancelled,
  NULL AS list_id,
  NULL AS repeater_id,
  NULL AS prompt_id,
  NULL AS parent_id,
  NULL AS tags,
  NULL AS content,
  NULL AS "order",
  NULL AS num_images,
  NULL AS importance,
  FALSE AS deleted,
  FALSE AS has_pending_writes
FROM
  device_event_rows;
```

Entry rows look like so:

```
class EntryRows extends LocalSyncTable {
  TextColumn get type => textEnum<EntryType>()();
  TextColumn get title => text()();
  BoolColumn get archived => boolean()();
  // date stuff
  TextColumn get dateUnit => textEnum<DateUnit>().nullable()();
  DateTimeColumn get dateScheduled => dateTime().nullable()();
  DateTimeColumn get dateComplete => dateTime().nullable()();
  DateTimeColumn get dateCancelled => dateTime().nullable()();
  // foreign ids
  TextColumn get listId => text().nullable()();
  TextColumn get repeaterId => text().nullable()();
  TextColumn get promptId => text().nullable()();
  TextColumn get parentId => text().nullable()();
  TextColumn get tags => text().nullable()();
  // other
  TextColumn get content => text().nullable()();
  TextColumn get order => text().nullable()();
  IntColumn get numImages => integer().nullable()();
  IntColumn get importance => integer().nullable()();
  TextColumn get startTime => text().nullable()();
}

class LocalSyncTable extends Table {
  @override
  Set<Column> get primaryKey => {id};

  TextColumn get id => text()();
  BoolColumn get deleted => boolean()();
  BoolColumn get hasPendingWrites => boolean()();
  DateTimeColumn get dateCreated => dateTime()();
  DateTimeColumn get dateUpdated => dateTime()();
}

class DeviceEventRows extends Table {
  TextColumn get id => text()();
  TextColumn get calendarId => text()();
  TextColumn get title => text()();
  DateTimeColumn get dateScheduled => dateTime()();
  TextColumn get startTime => text().nullable()();
  DateTimeColumn get dateCreated => dateTime()();
  DateTimeColumn get dateUpdated => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}
```

**Comment by galacticgibbon** [comment]
Even if I have a simpler case where DeviceEventRows have the same schema as EntryRows

`class DeviceEventRows extends EntryRows {}
`

And then do

```
CREATE VIEW entries_and_device_events AS
SELECT
  *
FROM
  entry_rows

UNION ALL

SELECT
  *
FROM
  device_event_rows;
```

There are still some incorrect typings, which don't exist when throwing out the union and just selecting entry_rows

**Comment by simolus3** [comment]
I suggest not using `*` in a compound select statement because the column names after the `UNION ALL` don't matter - it's all based on the order of columns. Try running this: `select 'foo' c1, 'bar' c2 UNION ALL SELECT 'bar2' c2, 'foo2' c1;`, the columns in the result are mixed up.

In your example, the first two columns before the `*` are `id, deleted` and the first two after the union are `id, calendar_id`. Given that `calendar_id` and `deleted` have different types, drift is doing its best to make them compatible but the results won't be good.
The order of columns is also not necessarily stable between drift versions, especially when extending other tables. Drift has some guardrails against this to make sure `*` gives the intended results for queries, but we also need to keep the semantics of compound queries which just don't work like this.

I'll take another look at the situation when the tables are identical though, that doesn't sound right. So drift may also be messing some things up here.

**Comment by simolus3** [comment]
The reason it still happens with `class DeviceEventRows extends EntryRows {} ` is that the order of columns is different - we seem to put superclass columns first, but not transitively.

Considering that the order of columns is not supposed to make a difference, I don't consider this to be a bug. Don't use `*` in compound select statements or with `INSERT INTO SELECT`.

**Comment by galacticgibbon** [comment]
Ah gotcha, thank you! 👍
