### ISSUE TITLE
Client Check

### ISSUE THREAD

**Issue by dickermoshe** [simolus3/moor#3121]
We have `withDefault` and `clientDefault`, why not have `check` and `clientCheck` too.

Write the validation in dart. No schema changes are required to add/remove/modify validator. Exception are thrown when creating the dataclass instead when it's inserted.

> [!CAUTION]  
> If there are existing rows which don't validate, then the migration would still pass.   
> An exception will only be thrown when they're fetched.

@simolus3  Is the above issue a dealbreaker?

I'm trying to remove any instances where someone would want a custom dataclass. This would be a big one.

**Comment by simolus3** [comment]
I can see the point for `check` to support `CHECK` column constraints as part of the schema. I'm not so sure about `clientCheck` though.

> I'm trying to remove any instances where someone would want a custom dataclass.

Why? Custom data classes are useful in lots of cases - some users also prefer control over the classes they interact with, and drift's default model of generating data classes on its own is incompatible with that. They also enable better integration with other builders, custom serialization support and so on.
I'm actually considering making custom data classes the default in a future drift version based on macros (by letting users write the classes and using annotations to specify column constraints).

> Exception are thrown when creating the dataclass instead when it's inserted.

Then a change in the validator function may still require a schema change because existing rows may no longer be valid and need to be updated to avoid exceptions when selecting these rows.

**Comment by dickermoshe** [comment]
I would say that drift has 2 problems now:
1. Some options are `build.yaml`, some are decorators, some are part of methods and some are getters on the Table class.
2. We define a table instead of a row.
3. Defining a custom data class duplicates lots of work.

I agree that we should focus our efforts on macros instead of fixing this.

**Comment by simolus3** [comment]
Well, ideally a new API which we'll need for macros either way will solve all three of them :)

**Comment by dickermoshe** [comment]
We can completely break the current api if we provided a refactor using custom_lint.
Although we also need to be backwards compatible with the dumped schema files.
