### ISSUE TITLE
Prefer using dart:js_interop instead of package:js

### ISSUE THREAD

**Issue by llfbandit** [simolus3/moor#3145]
**Is your feature request related to a problem? Please describe.**
`package:js` will be discontinued since dart now provides `dart:js_interop*`.
It also replaces `dart:js` and `dart:js_util`.

**Describe the solution you'd like**
As drift already has a dependency on package:web, which plays around `dart:js_interop*`, it should avoid some problems in the future and maybe slim a bit the package size with this alignment.

https://dart.dev/interop/js-interop

**Comment by simolus3** [comment]
Before we added native wasm support to `package:sqlite3`, drift had the option of wrapping `sql.js` as a JavaScript library for web support.

This legacy web support is in `package:drift/web.dart` and I've just marked it as `@Deprecated` for the next release. Newer drift APIs (`package:drift/wasm.dart`) do not import these legacy SDK libraries (we also [have a test](https://github.com/simolus3/drift/blob/develop/drift/test/source_code_test.dart) for that). So if you're not importing these legacy APIs, drift won't depend on `dart:js` either.
Since `package:drift/web.dart` is a legacy API, I didn't want to migrate it to the newer interop APIs on the off-chance that it breaks something subtle. Given the announcement to remove the legacy APIs, we either have to remove `package:drift/web.dart` from drift entirely or migrate them as well.

**Comment by llfbandit** [comment]
Ah yes, I should have taken a closer look to the source code and mine. Thanks for the answer.

One of my projects has 4 years old with drift/moor (Many thanks for the continuous support! BTW).
I guess it's time to remove the import on `package:drift/web.dart` which was used to enable migration with the previous implementation. 👍

**Comment by simolus3** [comment]
I have migrated the old web implementation (where possible, we have one API directly using `dart:html` types) to `dart:js_interop` as well now. It will probably never really support dart2wasm properly, but it should continue to work for existing users.
