### ISSUE TITLE
Illegal cast in web wasm

### ISSUE THREAD

**Issue by remcoanker** [simolus3/moor#3194]
When I make a web build with the `--wasm` flag, Some statements get an error:
`type 'double' is not a subtype of type 'FutureOr<int>?' of 'value'`

In our app, it happens with these requests:
`StatementMethod.deleteOrUpdate: DELETE FROM "files" WHERE 0; with []` and `RunTransactionAction(NestedExecutorControl.beginTransaction, null)`
Looks like it happens with statements without a result.

It works when i add a type check and cast:
```
if(request?.completer is Completer<int> && msg.response is! int) {
  request?.completer.complete(castInt(msg.response));
} else {
  request?.completer.complete(msg.response);
}
```

in https://github.com/simolus3/drift/blob/develop/drift/lib/src/remote/communication.dart#L88

**Comment by simolus3** [comment]
Thanks for the report This will be fixed in the next drift version.

These issues are super tricky to spot with the current serialization implementation - I've opened https://github.com/simolus3/drift/issues/3195 to investigate a more efficient serialization mechanism that would avoid the `castInt` workaround.
