### ISSUE TITLE
Why withDefault is no effect？is this a bug？

### ISSUE THREAD

**Issue by SAOmi567** [simolus3/moor#3205]
![问题1](https://github.com/user-attachments/assets/61af0e98-ec76-4823-a8b2-ac6f783a3959)
![问题2](https://github.com/user-attachments/assets/8153ca73-9024-49e0-8c48-44aa387011a0)
![问题3](https://github.com/user-attachments/assets/f6b86043-e43a-4f25-9d55-b60afe4f9a3c)

**Comment by SAOmi567** [comment]
the doc said if set default  value when define table struct then we can no fill the value when insert row  right？

**Comment by simolus3** [comment]
`withDefault` affects the schema of the table in the database. When you add `withDefault` after the database has already been created, it has no effect because you're still using the old schema. After making changes to the table class, you need to:

1. Re-run the build runner.
2. Delete the existing database (if you have no existing users and don't care about migrations), or [increment your `schemaVersion` and write a migration](https://drift.simonbinder.eu/docs/migrations/). For the migration code, you can [use this](https://drift.simonbinder.eu/docs/migrations/api/#changing-column-constraints) to add the `withDefault` constraint.

An alternative is to use `clientDefault`, which is computed in Dart instead of in the database, and thus requires no schema change.

**Comment by SAOmi567** [comment]
> `withDefault` affects the schema of the table in the database. When you add `withDefault` after the database has already been created, it has no effect because you're still using the old schema. After making changes to the table class, you need to:
> 
> 1. Re-run the build runner.
> 2. Delete the existing database (if you have no existing users and don't care about migrations), or [increment your `schemaVersion` and write a migration](https://drift.simonbinder.eu/docs/migrations/). For the migration code, you can [use this](https://drift.simonbinder.eu/docs/migrations/api/#changing-column-constraints) to add the `withDefault` constraint.
> 
> An alternative is to use `clientDefault`, which is computed in Dart instead of in the database, and thus requires no schema change.

thanks  I will try
