### ISSUE TITLE
Exported schema do not contain column `check()` constraints

### ISSUE THREAD

**Issue by coffeebeats** [simolus3/moor#3219]
Hey! Thanks for creating a fantastic library. I've found what I think is a bug, which I'm documenting below:

**Describe the bug**

It appears that schema exports do not include `check()` column constraints. This results in errors like the following, where schema migration tests pass but live database migrations fail `validateDatabaseSchema()`:

```
Schema does not match
  users:
   columns:
    creation_time:
     Not equal: `NOT NULL DEFAULT 1704096000` (expected) and `NOT NULL DEFAULT 1704096000 CHECK(NOT 1 AND "creation_time" IS NULL OR 1 AND "creation_time" IS NOT NULL AND "creation_time" > 0)` (actual)
```

In the error we see that the expected value, which is derived from the exported schema, does not include the `check()` constraint on the actual column (derived from the migrator's table information).

I've created a minimum reproducible example at [coffeebeats/example-drift-export-column-check-bug](https://github.com/coffeebeats/example-drift-export-column-check-bug). To see the error in action (and how migration tests hide this issue), clone the repository and follow the reproduction steps.

Please let me know if I can provide any other information. Thanks!

**Comment by simolus3** [comment]
Thank you for this stellar bug report! The underlying problem here is that `drift_dev schema dump` only runs static analysis to infer the schema of your database. Some features (most notably views, but also some others, like `check()`) can't be statically checked however, they require running user code.

I've changed `drift_dev` in 9e3a3c26d279237df3b97bc6f3d039182a5083c0 to remember the Dart code passed to `check()` constraints. Unfortunately, that's not enough to fix this because the `creationTime` self-reference in the column definition does not work with the compact structure we generate for step-by-step migrations. I've confirmed that it works with this after the commit:

```patch
diff --git a/lib/tables.dart b/lib/tables.dart
index acb9acc..e42a824 100644
--- a/lib/tables.dart
+++ b/lib/tables.dart
@@ -10,6 +10,7 @@ class Users extends Table {
   // Column added in version 11
   // Column that can only be set to times after 1950.
   DateTimeColumn get creationTime => dateTime()
-      .check(creationTime.isBiggerThan(Constant(DateTime(2020))))
+      .check(CustomExpression<DateTime>('creation_time')
+          .isBiggerThan(Constant(DateTime(2020))))
       .withDefault(Constant(DateTime(2024, 1, 1)))();
 }
```

I think we can make this more reliable by generating the default code in extension methods that have access to the column though.

You can also work around this issue by defining the constraint directly, which gets included in the schema already

```dart
  DateTimeColumn get creationTime => dateTime().customConstraint(
      'NOT NULL DEFAULT 1704063600 CHECK("creation_time" > 1577833200)')();
```

(I know this feels fragile, but drift parses the `customConstraint` value and verifies it at build time)

**Comment by coffeebeats** [comment]
Thanks for the quick turnaround on this! I can confirm that https://github.com/simolus3/drift/commit/9e3a3c26d279237df3b97bc6f3d039182a5083c0, along with the use of `CustomExpression`s, fixes the issue for me.

I agree that being able to reference the columns (or other variables like shared functions implementing complex constraints) would be nice, but with the above workaround it's not critical.

**Comment by dickermoshe** [comment]
@simolus3 generated step by step is having this issue as well
<img width="835" alt="image" src="https://github.com/user-attachments/assets/6afb6192-9046-4d93-ae95-a30db9fcd14d">

If we are going to present this as the go-to solution for migrations, this must be resolved.

**Comment by dickermoshe** [comment]
@simolus3 Is this on your todo list or should I work on this?

**Comment by simolus3** [comment]
I was planning on fixing this, but I didn't come up with a good solution yet.

The best approach I could come up with right now is to detect references to other columns when creating the `DartCode` tree. So `name.equals("Pizza")` would be `{{column: name}}.equals("Pizza")`. With that information in place, we could emit code as `ColumnReference<String>(tableName, columnName).equals("Pizza")`.
Do you see an alternative solution that might work better? We can probably restructure the way step-by-step code is generated avoid this and keep user code unchanged by keeping everything in table classes. I like that step-by-step code is compressed though, that's kind of important considering it spans every schema version ever.

**Comment by dickermoshe** [comment]
Sounds like a good solution.

We should only generate step by step for dumps version 1.3 and higher?
That way people with existing dumps can generate valid code.

<img width="705" alt="Screenshot 2024-10-02 133221" src="https://github.com/user-attachments/assets/b1b4d604-4b1e-406f-97ca-73a080a824b5">

**Comment by simolus3** [comment]
> We should only generate step by step for dumps version 1.3 and higher?

The current stable `drift_dev` release doesn't include check constraints set on columns in the exported schema at all, so raising the version is not necessary. The first version supporting `check()` will support them properly.

>  That way people with existing dumps can generate valid code.

Even without the compile-time errors the code wouldn't be valid because it doesn't accurately reflect the underlying database schema.

**Comment by saibotma** [comment]
Is there a recommended way on how to migrate the old generated schemas to also include the check constraints? 
I regenerated the old schemas manually, so that they now contain the check constraints. However, this is a tedious process, especially when you have many migrations.

Otherwise, the generated migration tests fail with an error message like:
```
Not equal: `NOT NULL DEFAULT 'message' CHECK("type" = 'message')` (expected) and `NOT NULL DEFAULT 'message'` (actual)
```

**Comment by simolus3** [comment]
I can offer this hacky script as a workaround - I've briefly tested it, but it might need some fine-tuning. Basically, the idea is that `missingCustomConstraints` contains (table, column) pairs that need a check constraint missing in your schema. It then goes through a directory of schema jsons and adds constraints if needed.

I tried running it in the migrations example of this repository where it worked, but I quickly threw this thing together (so definitely back up other schema changes first :crossed_fingers: )

```dart
import 'dart:convert';
import 'dart:io';

import 'package:drift_dev/src/analysis/results/results.dart';
import 'package:drift_dev/src/services/schema/schema_files.dart';

const missingCustomConstraints = {
  ('users', 'id'): 'CHECK("type" = \'message\')',
};

void main() {
  final schemas = Directory('drift_schemas/default');
  for (final file in schemas.listSync()) {
    if (file is File) {
      addMissingCheckConstraints(file);
    }
  }
}

void addMissingCheckConstraints(File file) {
  final parsedJson =
      json.decode(file.readAsStringSync()) as Map<String, dynamic>;
  final reader = SchemaReader.readJson(parsedJson);
  var hadChange = false;

  for (final (i, entity) in reader.entities.indexed) {
    if (entity is DriftTable) {
      for (final (j, column) in entity.columns.indexed) {
        final expectedConstraint =
            missingCustomConstraints[(entity.schemaName, column.nameInSql)];

        if (expectedConstraint != null) {
          final existing = column.customConstraints;
          if (existing == null) {
            parsedJson['entities'][i]['data']['columns'][j]
                ['customConstraints'] = expectedConstraint;
            hadChange = true;
          } else if (!existing.contains('CHECK')) {
            parsedJson['entities'][i]['data']['columns'][j]
                ['customConstraints'] += ' $expectedConstraint';
            hadChange = true;
          }
        }
      }
    }
  }

  if (hadChange) {
    print('Applying changes to ${file.path}');
    file.writeAsStringSync(json.encode(parsedJson));
  }
}
```
