### ISSUE TITLE
Follow-up on SQL Parsing Error Fix (#3218)

### ISSUE THREAD

**Issue by Srimathi622** [simolus3/moor#3230]
I previously raised a ticket for “SQL Parsing Error with Special Characters (e.g., $, ‘’', #) in Query [#3218”](https://github.com/simolus3/drift/issues/3218). You provided a linked commit in the dev branch, which worked as expected.

Could you please let me know if there are any plans to merge this fix into the live branch?

Thanks again for your support.

**Comment by simolus3** [comment]
Of course there are plans to release this eventually :) Typically I release all packages in this repository at once, since they have relatively tight version dependencies. The changes to `sqlparser` to fix your problem broke some `drift_dev` tests for instance.

I'll try to release `sqlparser` this weekend as a standalone update since the other packages have some features still being worked on.

**Comment by simolus3** [comment]
I've just published version 0.39.0 of `sqlparser` to pub.dev.

**Comment by Srimathi622** [comment]
Hi Simolus,
I’m pleased with the quick update :) Thank you for releasing version 0.39.0 of sqlparser. I really appreciate your support. Have a great day!
