### ISSUE TITLE
Compiler Errors in Generated File Due to Missing Imports for Custom Row Classes

### ISSUE THREAD

**Issue by gruvw** [simolus3/moor#3231]
When using `@UseRowClass` on a table that is defined in another file than `database.dart`, the generated file `database.g.dart` contains compiler errors about not having access to the custom row class type (as it is defined in another file and not imported in `database.dart`).

A temporary solution is to manually import every custom row class file at the top of `database.dart` but this is tedious.

I know we can't add an import clause in `database.g.dart` as it already contains a `part of` clause, but is there any alternative that we could use ?

Maybe at least emit a warning message when generating if there are missing imports would be an option ?

**Comment by simolus3** [comment]
> I know we can't add an import clause in `database.g.dart` as it already contains a `part of` clause, but is there any alternative that we could use ?

Yes! You can use [modular code generation](https://drift.simonbinder.eu/docs/generation-options/modular/), which makes drift emit standalone libraries instead of part files. Those can have their own imports, which drift adds automatically. It requires minor code changes (replacing `part` with `import` and changing some `extends` clauses because names can't be private anymore), but I definitely recommend it for larger projects or when import management is tedious otherwise.

> Maybe at least emit a warning message when generating if there are missing imports would be an option ?

This turns out to be quite hard: When we're generating code, we know the URI of the Dart library defining each element we reference. However, most definitions are typically not imported directly but rather through a series of `export`s. Crawling that graph to figure out what is and isn't available is not free and didn't seem like something worth doing.
