### ISSUE TITLE
JoinedSelectStatement with RegEx OrderingTerm containing special characters causes SqliteException

### ISSUE THREAD

**Issue by enloc-port** [simolus3/moor#3256]
Under certain conditions, the query builder seems to make a mistake when building queries which contain regular expressions.

The criteria seems to be as follows:
* `JoinedSelectStatement`
* `OrderingTerm` with `regexp` on one of the table's fields
* the `regexp` must contain a special character within round brackets, e.g. `(+)`

This seems to be a very specific error as I can reproduce it with a `JoinedSelectStatement`, but not with a `SimpleSelectStatement`.
Also, the `()` brackets in the `regexp` are somewhat important, because without them, the query will work in most cases.

I attached a few files, including an example database definition and a test with which this can be reproduced:
[drift_test.zip](https://github.com/user-attachments/files/17216852/drift_test.zip)

It also does not occur with all special characters or combinations of such.
In the tests, I compiled (incomplete) lists of "good" and "bad" characters, which are tested individually.

In our case, this occured with
* `Flutter 3.19.6`
* `drift: ^2.19.1+1` (and older)

But as per the attached files, it also happens with
* `Flutter 3.24.3`
* `drift: ^2.20.3`

**Comment by simolus3** [comment]
> This seems to be a very specific error as I can reproduce it with a `JoinedSelectStatement`, but not with a `SimpleSelectStatement`.

Looking at the code you've sent, that's probably because you're only using `()` in the method with a join.

`regex()` is not a substring match, it uses Dart's [RegExp](https://api.dart.dev/stable/3.5.3/dart-core/RegExp-class.html) class to parse and evaluate a regular expression that can use special characters. And `#(+e)` is just not a valid regular expression, so the error looks correct to me.

If you're trying to filter rows containing another string, use `.like()`. You can also use `RegExp.escape` to construct valid regular expressions from arbitrary characters.

**Comment by enloc-port** [comment]
> And `#(+e)` is just not a valid regular expression

Now that you pointed that out, it is so obvious. 🙈

Thanks, we'll fix our code accordingly. 😅

**Comment by enloc-port** [comment]
> And `#(+e)` is just not a valid regular expression

Now that you pointed that out, it is so obvious. 🙈

Thanks, we'll fix our code accordingly. 😅
