### ISSUE TITLE
watchAllDecks stream relaunches every time, widget`s, consisting StreamBuilder, state changes

### ISSUE THREAD

**Issue by sergiyvergun** [simolus3/moor#329]
Every time SmallDecksList's state changes it relaunches the watchAllDecks streams. 
Because of that, some extra queries are called when there are no changes. 
![image](https://user-images.githubusercontent.com/30001806/72063963-26e52700-32db-11ea-83a8-b5131b589eb0.png)
How it can be fixed?

```
class SmallDecksList extends StatefulWidget {
  @override
  _SmallDecksListState createState() => _SmallDecksListState();
}

class _SmallDecksListState extends State<SmallDecksList> {
  Stream<List<Deck>> decks;

  @override
  void didChangeDependencies() {
    decks = Provider.of<Dao>(context).watchAllDecks();
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
        stream: decks,
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          final decks = snapshot.data ?? List();
          return ListView.builder(
            itemCount: decks.length,
            itemBuilder: (_, index) {
              final Deck itemDeck = decks[index];
              return SmallDeckTile(
                deckItem: itemDeck,
                onPressed: () {
                  deckOnPressed(itemDeck, context);
                },
                onLongPress: () {
                  deckOnLongPress(itemDeck, context);
                },
              );
            },
          );
        });
  }
}
```
Thats how I provide an instance of dao:
![image](https://user-images.githubusercontent.com/30001806/72064034-4da35d80-32db-11ea-9962-d4b29968cb3c.png)

**Comment by simolus3** [comment]
Thank you for the report! I couldn't reproduce your exact issue, but I found some similar issues with the current implementation on the way.

> Every time SmallDecksList's state changes it relaunches the watchAllDecks streams

Do you mean after its dependencies changed? I tried manually calling `setState` on that state, no further query was sent. 

To give some more context on why this happens: Moor caches streams and their latest values internally, but invalidating the cache at the right time is a bit tricky since there are many possible scenarios. There used to be a bug (#166) where a stream emitted stale data when a listener disconnected, then a table was updated and then another listener connected. My solution was to clear the cache after the last listener disconnected. That fixed the problem, but it likely caused this one: When you disconnect and then re-connect (which is what a `StreamBuilder` does internally when the stream instance changes), the cached data will be gone and we have to send the query again.

Now, after the last listener disconnects, we'll keep checking for table updates and keep the cached data for a tiny bit longer (timer with zero duration). Only if after that we still don't have a listener, we close the stream for good.
