### ISSUE TITLE
Custom query for multiple tables (containing columns with same name)

### ISSUE THREAD

**Issue by kylechandev** [simolus3/moor#3368]
**Describe**
If you use customSelect and left join multiple tables, if these tables have the same fields, such as `Food` and `Category` both have `userId` columns, the same `userId` columns will conflict when mapping the results, such as Food.userId=11, Category.userId=22, and the final query result is that the userId of Food and Category are both 11 (this example is not considered for practical significance, it is just an example). 

**The result will be correct if I use Core API to describe this query.**

I read the relevant code of `customSelect`, and it seems that the capabilities of SQL API are weaker than Core API (With Core API, we can use `readTable`, but with `customSelect`, we can only use `QueryRaw.map`, I think the problem is the conflict of map key names.) 

Maybe there is something wrong with the way I use it, please correct me, this is very important to me, thank you!

> Because my original project all uses raw SQL queries, so when I migrate to drift, I want to continue using the original SQL statements

**Minimal Reproduction**

```
mixin TableMixin on Table {
  late final userId = text().nullable()();
}
```

```
class Foods extends Table with TableMixin {
  TextColumn get id => text().named("id")();
  IntColumn get catId => integer().named("cat_id")();

  @override
  String get tableName => "food";
  @override
  Set<Column<Object>> get primaryKey => {id};
}
```

```
class Categories extends Table with TableMixin {
  IntColumn get id => integer().named("id")();
  TextColumn get name => text().named("name")();

  @override
  String get tableName => 'category';

  @override
  Set<Column<Object>> get primaryKey => {id};
}
```

```
class FoodInfo {
  final Food food;
  final Category? category;
  FoodInfo({
    required this.food,
    required this.category,
  });
```

```
Future<List<FoodInfo>> getFoodInfo(String id) {
        return customSelect(
      'select food.*, category.* from food left join category on category.id = food.cat_id where food.id = ?',
      variables: [Variable.withString(id)],
      readsFrom: {foods, categories}, // scream observer
    ).map(
      (row) {
		// ↓ ...PROBLEM HERE...
		// ↓ If in the database, food.userId=11, category.userId=22
		// ↓ But the query results show that the userId of food and category is same 11
        return FoodInfo(
          food: foods.map(row.data),
          category: categories.map(row.data),
        );
      },
    ).get();
  }
```

**Comment by simolus3** [comment]
> Maybe there is something wrong with the way I use it, please correct me, this is very important to me, thank you!

One feature we have that hopefully helps here is [custom queries with a generated API](https://drift.simonbinder.eu/sql_api/custom_queries/#statements-with-a-generated-api). Instead of using `customSelect` directly, you write the SQL statements in an annotation that drift will analyze for you at build time.

This solves the issue with duplicate column names because drift figures out what columns are returned by the query at build time and can rewrite the query to add explicit column names where necessary (so the `food.*` is expanded into named columns, but this happens entirely behind the scenes). Drift _also_ figures out that you're selecting all columns from tables and structures the result into a class that makes the tables accessible directly.

I'm wondering if that feature makes sense in your usecase? It should solve the issues you ran into with `customQuery`, but obviously it is a bit more "heavy" because it relies on code-generation. I'm reluctant to add convenience features to `customQuery` to be honest, I kind of see it has a last-resort escape hatch if neither the generated custom queries nor the Dart query builder work. So if that feature doesn't work for you, I'd rather figure out how it can be improved instead of adding features to `customQuery`.

**Comment by simolus3** [comment]
Closing as not-planned because our compile-time analyzer takes care of this. If you run into issues using that feature, let me know and we can re-open this issue to discuss that.
