### ISSUE TITLE
snippet package is private

### ISSUE THREAD

**Issue by dickermoshe** [simolus3/moor#3370]
<img width="950" alt="image" src="https://github.com/user-attachments/assets/494c1b55-bb80-43a0-9b0f-cf17d9706c5c">

**Comment by simolus3** [comment]
The actual package should be publicly resolvable: https://pub-simonbinder-eu.fsn1.your-objectstorage.com/api/packages/code_snippets, pub can access it.

It is backed by an object storage offering so that I don't have to care too much about hosting this reliably. Not having a directory listing is a downside, but I don't think it's a huge problem?

**Comment by dickermoshe** [comment]
my primary issue is that `melos bootstrap` doesnt work anymore

**Comment by simolus3** [comment]
Could you post the error? It works for me...

**Comment by dickermoshe** [comment]
Forget it. Something was wrong with my network settings
