### ISSUE TITLE
Drift_dev missing import for enum in generated steps and generated test.

### ISSUE THREAD

**Issue by Guang-B** [simolus3/moor#3379]
**Description**

I have an enum called `BackupStatus `used as fieldType  this table :

```
@DataClassName('BackupEntity')
abstract class Backup extends Table {
  IntColumn get id => integer().autoIncrement()();

  TextColumn get refId => text()();

  TextColumn get tableRef => textEnum<EfactTable>()();

  TextColumn get data => text()();

  TextColumn get fileName => text().nullable()();

  IntColumn get status => intEnum<BackupStatus>()
      .withDefault(Constant(BackupStatus.inProgress.index))();

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  TextColumn get createdBy => text()(); // employeeId

  @override
  List<Set<Column<Object>>>? get uniqueKeys => [
        {refId, tableRef},
      ];
}
```

and  It have Default Value : 

> Constant(BackupStatus.inProgress.index)`

then i want to generate the migration steps using :

> dart run drift_dev schema steps drift_schemas/ lib/data/local/database/schema_versions.dart

the generation works well but there are missing import in generated file : 

```
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>('status', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultValue: Constant(BackupStatus.inProgress.index));
```
the generated File error with : 

> Undefined name 'BackupStatus'

It can be fixed when I imported the  related class manually, but it can be annoying when I regenerate the steps every time I  have an update to my Database. I had the same case when i generated the test code. 

Is this A bug? or am I Doing it wrong. please Help.

**Versions**
drift_dev version: ^2.22.1

**Comment by simolus3** [comment]
Thanks for the report! This is a bug in drift. Schema exports (the json files in `drift_schemas`) should be immutable and complete descriptions of a database schema, but they fall short of that by still including the default value as a Dart expression that might change. This is fundamentally broken (even if we fixed the import issue, what happens if you change `BackupStatus`? That might change the index of `inProgress`, meaning that the exported schema no longer represents the historical truth at the time it was created).

In the next drift version, we will fix that by replacing defaults with the actual value obtained by evaluating them once. So the generated code will be `defaultValue: const CustomExpression('0')` if `inProgress` is the first enum value.
Unfortunately, since this is a bug in the way we export schemas, existing json files are still affected. You can fix this manually by checking which index is correct and then replacing `"Constant(BackupStatus.inProgress.index)"` in the generated JSONs with `"Constant(1)"`.
