### ISSUE TITLE
How to update value of a key, where value is an array.

### ISSUE THREAD

**Issue by a-ritwik** [simolus3/moor#358]
I want to store name of images in a column. Eg. "images"  : ["image1.jpg", "image2.jpg"] then when another picture named image3.jpg is clicked then it should be added to that array after image2.jpg. I can not find a way to do this.

**Comment by simolus3** [comment]
This isn't straightforward to do in sql. There are two main options here:

- split the images into another table
- store them as json

In your simple case, storing them as json sounds like the easiest way. With [type converters](https://moor.simonbinder.eu/docs/advanced-features/type_converters/) this is fairly simple, you could write a converter from `List<String>` to/from `String` by using json.

------

This question comes up fairly often, I'll expand the documentation on this specific use-case.

**Comment by a-ritwik** [comment]
Thank you 😊 . I tried and it works as intended.
I have one more question. When I use 
update(assets).replace(Asset(id: id, preferences: Preferences(newPreferences))) 
then it updates id and preferences column, but makes values of other columns as null. I want to keep value of other columns as they were. Any way to do this without send all column's value inside the replace statement?

**Comment by simolus3** [comment]
The preferred way to do updates is using "companions" moor generates for each table, so you could use something like
```dart
AssetsCompanion(id: Value(id), preferences: Value(Preferences(newPreferences)))
```
The reason here that we can't separate between null as in "I don't want to change this column" and null as in "I want to set this column to null". With companions, we use `Value.absent()` and `Value(null)`, respectively. But I think moor should use the first variant for updates and the second for inserts by default, so the columns resetting to null seems odd. I'll take a look at that.

**Comment by simolus3** [comment]
Ah sorry, I double-checked and moor is working as intended here. If you use `replace` it will behave like inserts and set columns back to null. I recommend using companions for inserts and updates - they make the whole thing more explicit so you know what's going to happen.

**Comment by a-ritwik** [comment]
Thank you again.
