### ISSUE TITLE
Incremental migration to Moor

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#370]
Hello, I've been following the repository for a while now and I am amazed with all the features that have come. Great job!
I'm writing the issue because I have a mid/big size project that uses raw sqflite with many defined raw queries already.
I was wondering if there would be a way to include Moor in the project gradually, without the need to change all the existing queries. We were planning to use Moor with the sqflite backend so maybe there is a way. Ideally it would be great if Moor could use the existing sqflite Database object in our project, or viceversa, let Moor provide the internal sqflite Database object.

Thanks again for all the work!

**Comment by simolus3** [comment]
`moor_flutter` could expose the underlying sqflite database object so that you can run raw queries if that makes the migration easier. There would still be some problems, since moor is designed to have full control over the database:

- stream queries wouldn't update for raw updates
- the database has to be opened in moor, and moor needs to run migrations. This shouldn't be a problem, though. You could set the `onCreate` and `onUpgrade` parameters in a `MigrationStrategy`  to just run your existing migration code.

Another way to migrate quickly would be using [moor files](https://moor.simonbinder.eu/docs/using-sql/moor_files/). You can paste your existing `CREATE TABLE` statements and queries into a moor file that you include in a database. Moor will generate matching Dart classes and methods by analyzing the statements. You could also use `qustomSelectQuery('some raw sql').get()` directly.

**Comment by davidmartos96** [comment]
Yes, I am aware that stream queries would not work with existing queries in the project. That would not be a problem. Exposing the underlying sqflite database would be great.
The root of the issue is that we are going to start working in a big feature with a lot of database operations and we would like to use Moor for that, but keep the current functionality with basic sqflite at the same time. 
We would not mind either to use the open/create/update with the Moor library instead of sqflite.

**Comment by simolus3** [comment]
Thanks for your contribution! I've just released `moor_flutter` 2.1.0 which contains it. Let me know if you need anything more!
