### ISSUE TITLE
[proposal] - Web implementation switch to IndexdDB

### ISSUE THREAD

**Issue by rodydavis** [simolus3/moor#390]
Would it be possible to use indexedDB instead of local storage to allow for faster and larger data bases on the web?

**Comment by simolus3** [comment]
I've thought about something similar. Unfortunately it requires a lot of work, since we'd basically have to write an sql engine on top of IndexedDB.

At the moment, the way moor works is that it creates sql statements to send to an underlying database implementation. Since IndexedDB doesn't support sql, we'd have to compile these queries into a sequence of efficient IndexedDB lookups. Going all the way from sql to IndexedDB at runtime would increase code size by a lot (and it wouldn't be fast either). We could pre-compile queries from moor files though. Queries generated with the Dart api would have to be handled at runtime, but at least we don't have to do any parsing there.

Further, there are many sql features that can't be mapped to IndexedDB directly. Even if we don't support these, writing a query planner is really hard and takes a lot of work.

**Comment by rodydavis** [comment]
Well I was meaning using it to store the binary file. Not map to it directly.. 

https://github.com/simolus3/moor/blob/81cf26a2b26552c0e330319ee1d9bdfab49585f0/moor/lib/src/web/web_db.dart#L165

This is the abstract part that would save to indexedDB

**Comment by simolus3** [comment]
That sounds like a good idea, thanks. An experimental version is available on `develop`. You can use it by replacing `WebDatabase(name)` with `WebDatabase.withStorage(MoorWebStorage.indexedDb(name))`.

Note that it doesn't migrate old data from local storage yet. For now, it's a completely different implementation. In the future, the default implementation should probably use IndexedDb when it's available and fallback to local storage otherwise.

**Comment by rodydavis** [comment]
Awesome thank you! This will also help with the 8mb limitation I was running into as well 🥳

**Comment by simolus3** [comment]
As of cdd57f340db7b76fbabff7a3d46e037f99841dcc moor can automatically transfer saved databases from local storage to IndexedDb.  Preview docs are available [here](https://develop--moor.netlify.com/web/#using-indexeddb).

**Comment by rodydavis** [comment]
Thanks 🥳🥳🥳

**Comment by talamaska** [comment]
Ideally I would use real indexedDb instead of storing my binary sqlite and read in web assembly.
If you are looking for a similar api for indexed db this is what I have used before 
https://github.com/google/lovefield
and it seems there is a dart package, very old, but maybe can be migrated to recent dart.
https://github.com/aabluedragon/lovefield-dart and it doesn't need code generation. 
Both libraries were not updated recently, and indexed db doesn't support really advanced aggregation and stuff, but I think that's the right way. of dealing with web apis.

**Comment by simolus3** [comment]
Unfortunately it's not that easy. As you said, InxedDB and lovefield don't support advanced SQL constructs that moor needs to support.
