### ISSUE TITLE
Is it possible to use POW() function of SQL 

### ISSUE THREAD

**Issue by AabhasS** [simolus3/moor#397]
I want to calculate Havershine Distance between the user's current location and location stored in the database.
For this, I need to use POW(sin((lat1 -lat2)/2), y) with constant power(y) that is customizable according to requirement. Also lat2 is a constant i.e the user location latitude. How is this possible?

**Comment by simolus3** [comment]
The set of builtin functions in sqlite is rather limited, it doesn't include many mathematical functions (apart from sum/max/min/etc.).

I _think_ we can use `dart:ffi` to create function pointers from Dart functions, which means we could use [`sqlite3_create_function_v2 `](https://sqlite.org/c3ref/create_function.html) to add those. However, those would only be available when using `moor_ffi`.

If it's possible, we should at least implement `pow`, `sin`, `cos` and `tan`. Do you need any more functions? We should also implement type inference in the `sqlparser` project.

**Comment by AabhasS** [comment]
I need sqrt, asin, acos also. Also, I am using moor_ffi. One things that still remains unclear is how to do calculations using constant values. Currently I cannot do something like : 2* table.id

**Comment by simolus3** [comment]
> I need sqrt, asin, acos also

Sounds reasonable, I'll add those as well 👍 

> Currently I cannot do something like : 2* table.id

Something like `const Constant<int, IntType>(2) * table.id` should work. In the next moor version (#334) it can just be written as `const Constant(2) * table.id`.

**Comment by AabhasS** [comment]
Thanks. This will solve our problem.

**Comment by simolus3** [comment]
This is now implemented on `develop`. When using `moor_ffi` all the functions (pow, sqrt, sin, cos, tan and their arc variants) are available for use in custom queries.

To use them in Dart, a special import is needed (because they're not available across all moor implementations). This is explained in the [documentation](https://develop--moor.netlify.com/docs/other-engines/vm/#moor-only-functions).
To use them in in moor files or compile queries, one needs to enable the `moor_ffi` sql module in the [build options](https://develop--moor.netlify.com/docs/advanced-features/builder_options/#available-extensions).
