### ISSUE TITLE
Not working with DateTime

### ISSUE THREAD

**Issue by anunez-r** [simolus3/moor#40]
I try to insert a row in the table:

![moor_1](https://user-images.githubusercontent.com/47054243/59618361-56a6c480-9128-11e9-877d-9f5412e6396e.png)

However, I get this error. 

```
E/flutter (14884): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'DateTime' is not a subtype of type 'int' in type cast
E/flutter (14884): #0      _DefaultValueSerializer.fromJson (package:moor/src/runtime/data_class.dart:53:55)
E/flutter (14884): #1      new Person.fromJson (package:moor_example/model/model.g.dart:77:29)
```
Why does the library try to convert the DateTime into an int?

**Comment by simolus3** [comment]
The default serialization behavior will represent `DateTime`s as a unix timestamps and hence convert them to an int, so you will get ints from `.toJson()`. Because `toJson` and `fromJson` are compatible, moor expects a `DateTime` value to be encoded as an `int`.

If you're working with json maps not generated from moor, you can still customize the serialization behavior by passing the `serializer` parameter.
```dart
class CustomSerializer extends ValueSerializer {
  const CustomSerializer();
  @override
  T fromJson<T>(json) => json;

  @override
  toJson<T>(T value) => value;
}
```
You can then use this serializer with `new Person.fromJson($yourData, serializer: const CustomSerializer())` and `$person.toJson(serializer: const CustomSerializer())`.

**Comment by anunez-r** [comment]
So that's it. I noticed that, when using person.toJson(), the field birthdate returns an int with the Unix time in millis. I can use it.

**Comment by DN1996** [comment]
> The default serialization behavior will represent `DateTime`s as a unix timestamps and hence convert them to an int, so you will get ints from `.toJson()`. Because `toJson` and `fromJson` are compatible, moor expects a `DateTime` value to be encoded as an `int`.
> 
> If you're working with json maps not generated from moor, you can still customize the serialization behavior by passing the `serializer` parameter.
> 
> ```dart
> class CustomSerializer extends ValueSerializer {
>   const CustomSerializer();
>   @override
>   T fromJson<T>(json) => json;
> 
>   @override
>   toJson<T>(T value) => value;
> }
> ```
> 
> You can then use this serializer with `new Person.fromJson($yourData, serializer: const CustomSerializer())` and `$person.toJson(serializer: const CustomSerializer())`.

How to implement this while declaring the table definition?
