### ISSUE TITLE
'num' can't be used as a setter because it is final. Try finding a different setter, or making 'num' non-final.dart(assignment_to_final)

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#411]
We using moor in our flutter project. When we assign a value to the `.g.dart` file variable which was generated by moor, we will get `'num' can't be used as a setter because it is final. Try finding a different setter, or making 'num' non-final.dart(assignment_to_final)` error.

Example in .dart file below, I need to assign a value to variable abc.

**example.dart**

```
ABC abc;
abc.num = 1

```
**db.g.dart**

` final int num;`

We can easily remove the **final** keyword, but everytime we build another `.g.dart` file again, this error occur again.

**Comment by simolus3** [comment]
Those values being final is by design. The `ABC` class represents a snapshot of a row in the database. If its fields were non-final, users might believe that `abc.num = 1` would somehow update a value in the database, which it doesn't.

You can use this snippet to change a single value in a data class:
```dart
ABC abc;
abc = abc.copyWith(num: 1);
```

**Comment by tony123S** [comment]
Thanks a lot !

**Comment by cyb3rsalih** [comment]
In my case I forgot add `.text` end of controller 🤦‍♂️

**Comment by JoorgeFerrari** [comment]
If this is no longer working after updates due to the Value class, you can try:

`Model.fromJson({ ...modelInstance.toJson(), 'fieldToUpdate': 1 })`
