### ISSUE TITLE
what is the difference of moor,moor_ffi,flutter_moor? and which is the best choice for flutter app ?

### ISSUE THREAD

**Issue by tbm98** [simolus3/moor#415]
I don't know why you create more than one package for one feature ? what is the difference of them?

**Comment by simolus3** [comment]
Perhaps the documentation should be clearer here.

- `moor` is the core package: It contains all the apis to write queries, update streams, handle migrations, transactions, etc. While it can create sql statements and deal with their results, it does not contain a way to actually run those queries (apart from the web executor which is in this package).
- `moor_flutter` is a wrapper to execute queries generated by moor with `sqflite`. It re-exports the core `moor` package, which was a mistake in hindsight.
- `moor_ffi` contains apis to run moor queries on the `sqlite3` native library directly, by using `dart:ffi`.

So, why aren't they just all in one package? `moor_flutter` is in a different package because it can only run on Flutter, whereas `moor` is a pure-Dart project that can also be used on a server. Not depending on Flutter also makes development and testing much easier. The first versions of `moor_ffi` were published before `dart:ffi` was stable, so we couldn't publish that in the main `moor` package.

I'll eventually merge `moor_ffi` and `moor` into a common package because `dart:ffi` is stable and well-supported now. For Flutter apps, using both `moor` (for the core apis) and `moor_ffi` (as an executor) is the recommended approach now.

**Comment by tbm98** [comment]
@simolus3 Thank you!
I think them should be merge to one package in the future.

**Comment by KaungZawHtet** [comment]
I always confuse with those packages but no need to merge. Instead, writing the difference at the top of doc is enough

**Comment by crossle** [comment]
For Flutter apps, using both moor (for the core apis) and moor_ffi (as an executor) is the recommended approach now.
---
Not moor_flutter?

**Comment by simolus3** [comment]
> Not moor_flutter? if flutter app for desktop app.

I choose the name `moor_flutter` because the core `moor` package is pure-Dart and can be used outside of Flutter too. `moor_flutter` contains a Flutter-specific implementation of `moor` ontop of the `sqflite` package, so it actually only works on Android and iOS. While `moor_flutter` is still supported, I wouldn't use it for new projects, especially if you want to target desktop operating systems too.

Since my original comment, I did merge the `moor` and `moor_ffi` packages, so you can just use the `moor` package alone. For iOS and Android, also depend on the `sqlite3_flutter_libs` package. For Desktop, you'll need to make sure that `sqlite3` is installed or bundle it with your app.

**Comment by crossle** [comment]
Merge moor alone nice. I choose moor for desktop platform. Thanks.

**Comment by simolus3** [comment]
I started [this doc page](https://develop--moor.netlify.app/docs/platforms/) to include the information on various platforms and moor implementations. It will be released with the next moor update. I hope that page explains why different moor packages are/were needed and which package to use for which platform. Please let me know if you have more questions that aren't covered by the new documentation, thanks!

**Comment by KirillKarmazin** [comment]
@simolus3  quick question, how can I debug my moor DB from the command line?

**Comment by simolus3** [comment]
@KirillKarmazin What exactly are you trying to debug? You can debug moor code like other Dart code. You can also pull the file from the device and open it with the `sqlite3`.
