### ISSUE TITLE
Can you provide some more examples in the docs?

### ISSUE THREAD

**Issue by 6heads** [simolus3/moor#42]
How are you supposed to use MyDatabase-class? It seems to me that a singleton is the way to go - don't know if all figure that out in the first place.

Then how are you supposed to define migrations? If I just add or remove a field everything works as expected, but what if I want to add a new table and store some of the existing data there and delete the field afterwards?
A common question would be initial data.
There is MigrationStrategy, but I don't know what to define there exactly. And if I have a look at GeneratedDatabase I can't find any use of onFinished.

It would be nice to have some working hello world-ish programs where one could study all aspects of moor :-)

**Comment by simolus3** [comment]
Thanks for taking the time to write down what's unclear in the docs, this feedback is incredibly valuable to me.
To quickly answer some of your questions:
- yes, you're supposed to only have one instance of the `MyDatabase` class. I'll point that out in the "getting started" section of the docs.
- complex migrations are indeed a bit tricky with sqlite: It only let's you add new columns to a table, you can't really drop existing ones without creating a whole new table and copying data. In your `onCreate` and `onUpgrade` methods, you can use [`issueCustomQuery`](https://pub.dev/documentation/moor/latest/moor/Migrator/issueCustomQuery.html) for this, but this definitely needs to be explained in the documentation
- `onFinished` is called after a migration has run, you're ready to use the higher level methods (`select(...)` etc. instead of writing sql manually) at that point. This is handy when you want to populate your database with some initial data.

That said, there is a rather simple but complete example of moor available [here](https://github.com/simolus3/moor/tree/develop/moor_flutter/example). It's a simple todo app with categories highlighting some moor concepts. Embarrassingly, it currently only runs on development because of some typos, but it does feature some of the points you've mentioned. I'll add an example usage of `onFinished` in there as well.

**Comment by 6heads** [comment]
First of all - keep up the good work :+1: and thanks for the always fast replies.

- I can't seem to find any entry to having just one instance of MyDatabase. I checked both https://pub.dev/packages/moor_flutter and https://github.com/simolus3/moor/blob/master/docs/_includes/content/getting_started.md
Maybe it would be nice to generate the singleton with moor_generator and place it inside updated database.dart?
When I followed your link I actually found it in main.dart (BlocProvider): https://github.com/simolus3/moor/blob/develop/moor_flutter/example/lib/main.dart (I wonder though why I didn't find those code examples in the first place :-O).
- If I have a look at the code examples I see your implementation for migrating from version 1 to 2. But I think the example should be a bit clearer, maybe using switch without breaks after each version. I'm still having problems understanding this:
```
if (from == 1) {
          await m.addColumn(todos, todos.targetDate);
}
```
What if you added targetDate at version 2, but removed it on version 3 and now update a client from 1 to 4? The field wouldn't be there anymore, would it? Would you suggest creating new objects if you remove fields (e.g. todos2 instead of todos)?
- Another question related to migrations. I added a field and wanted to store data to the database, but it wasn't created. Is it necessary to update my migration-script then or is it supposed to detect those changes automatically?

It would be really nice if the generator auto-updates the migration-script the same way entity framework does it :1st_place_medal: but I know this is quite challenging.

**Comment by simolus3** [comment]
Thanks for the suggestions.
- I've started to compile some tips under an [faq](https://moor.simonbinder.eu/faq/) sections in the docs, its referenced at the end of the getting started guide. The markdown for that is on `develop`, I'll merge it to master with the next version.  
Generating a singleton with the generator would be nice, but could also be limiting to users: Some might want to make the `FlutterQueryExecutor` a constructor parameter for their database class - we can't generate a singleton for that. If you see the `Provider` section in the referenced link you'll see it's actually pretty convenient to set up a singleton instance, so I think generating the singleton isn't necessary.
- Fall-through switches actually sound like a nice way to implement migration steps, I'll try to use them when I implement more complex migrations in the example app. Migration for columns that were first added but then dropped again are tricky indeed, I haven't really considered this yet.  I guess you could just remove `await m.addColumn` from the migration script in that case as the column will never be relevant for users upgrading straight to version 4.

I you add new fields, you'll have to update your migration script, it won't perform the migration automatically. It really isn't smart at all, the only thing it does by default is creating all tables when the database is first opened because that's almost always what users need. Any schema updates have to be written manually.  
Generating schema updates automatically sounds like a fun idea, but it's also very hard to pull off. I think room on android has some gradle task that let's you persist a snapshot of your schema and then reference it later after changing some tables. Moor could implement something similar, find the diff between two versions and write migration scripts for them automatically. As you said, absolutely possible but challenging to implement. I'll consider this, but I don't think it'll find a way into this library in the near future. There already is so much to do :smile:

**Comment by 6heads** [comment]
> Migration for columns that were first added but then dropped again are tricky indeed, I haven't really considered this yet.  I guess you could just remove `await m.addColumn` from the migration script in that case as the column will never be relevant for users upgrading straight to version 4.

True, I somehow thought about an update from 1 to 3, but no one will use a inbetween version - my bad. Would be still a lot to consider, but I think it's a rare case anyways if you do it right.

> If you add new fields, you'll have to update your migration script, it won't perform the migration automatically. It really isn't smart at all, the only thing it does by default is creating all tables when the database is first opened because that's almost always what users need. Any schema updates have to be written manually.

Thanks for the clarification. I haven't found this in the docs.

> Generating schema updates automatically sounds like a fun idea, but it's also very hard to pull off. I think room on android has some gradle task that let's you persist a snapshot of your schema and then reference it later after changing some tables. 

How is the migration working right now? Is schemaVersion written into the database (I can't seem to find the database, looked for *.sqlite and *.db*)?
If there would be the old structure of an object, it maybe wouldn't be that hard to generate transitions automatically.

**Comment by simolus3** [comment]
>How is the migration working right now? Is schemaVersion written into the database (I can't seem to find the database, looked for *.sqlite and .db to check it myself)?

Sqlite let's users provide a schema version when opening the database. When opening a database with a higher version, we get a callback for the version change, which calls the `onUpgrade` function on the `MigrationStrategy`. No schema information is written to the database or stored elsewhere.
We could theoretically infer the required changes by looking at the current state of the database (listing all tables and their columns) and calculate the diff to the next version. But that's even more complex than persisting schema information into some json once in a while.

**Comment by simolus3** [comment]
Closing this issue as the main part, improving the documentation, is completed. If you have any more questions or feel like that some concepts aren't clear from the documentation, don't hesitate to create another issue :)

I don't really have a plan to integrate the automatic migration generation in moor at the moment - it's hard to automate but relatively easy to just write it down, so I don't see the benefit. Of course, if you think otherwise and want to see this in moor, feel free to create another issue as well.
