### ISSUE TITLE
SelectOnly with where

### ISSUE THREAD

**Issue by gabrypulzio** [simolus3/moor#421]
Hi,
I'm trying to have the distinct months of a table given the year.
I tried:
```dart
final month = rows.date.month;
selectOnly(rows, distinct: true)
  ..addColumns([month])
  ..where((t) => t.date.year.equals(givenYear));
```

but I can't use the where conditions because `t` is of type dynamic instead of `$RowsTable` how can I use the where conditions when i use selectOnly?

**Comment by gabrypulzio** [comment]
It works if I write the code before as this:
```dart
final query = selectOnly(rows, distinct: true)
      ..addColumns([month])
      ..where(rows.date.year.equals(year));
```
Maybe my question is stupid, pardon me, I'm new to Dart and Flutter.

**Comment by gabrypulzio** [comment]
I found out `select` and `selectOnly` methods return two different objects so I can't use the `where` as described in documentation (with the signature `void SingleTableQueryMixin.where(Expression<bool, BoolType> Function($RowsTable) filter`).
`selectOnly` returns a `JoinedSelectStatement` instead of a `SimpleSelectStatement` so the `where` I have to use has the signature `void JoinedSelectStatement.where(Expression<bool, BoolType> predicate)
`.

**Comment by gabrypulzio** [comment]
I'm curious, why `select` and `selectOnly` don't share a common interface? Wouldn't it be better?

**Comment by simolus3** [comment]
They share some interfaces - `Selectable` and less notable `Query` and `LimitContainerMixin`. We can't provide the `(table) => builder`-apis for joined queries, because there are different tables that would be available. Instead of writing `Join1`, ... `Join10` classes (that would take 1..10 parameters in builders), I went for the more general approach that just expects the value directly.
In hindsight, one could argue that the callback for simple queries doesn't make much sense either (what's wrong with `select(table)..where(table.someColumn.equals(someValue))`), but that's how it is now. Moor didn't have joins in the first version, so the initial api wasn't optimized for it. It's not bad enough to justify a breaking change now.
That said, if you see functions that are the same for non-joined queries and joined-queries, then they should probably be moved into a common interface :)
