### ISSUE TITLE
Streams emit stale results

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#429]
Tried upgrading to the latest moor version but unfortunately a bunch of our tests are failing. Here's a repro:
```dart
test("test stream delete", () async {
  await db.customStatement('create table t (id integer)');
  await db.customStatement('insert into t values (1)');
  final before = await db.customSelectQuery('select * from t').watchSingle().first;
  expect(before.readInt('id'), 1);
  await db.customUpdate('delete from t');
  // await Future.delayed(Duration.zero); // Test passes if this is uncommented
  final after = await db.customSelectQuery('select * from t').watchSingle().first;
  expect(after, isNull);
});
```
It looks like this was introduced in https://github.com/simolus3/moor/commit/1b60879a09f6b63934174ee8130ca34e32fd61ff.

**Comment by simolus3** [comment]
Thanks for the report! I see that your `customSelectQuery` don't set any tables to listen to, and `customUpdate` doesn't provide any table to invalidate. Are you doing that in your regular tests as well?

I can reproduce your test, but it passes when I set the `readsFrom` and `updates` parameter. I'm using the following test targeting [this database](https://github.com/simolus3/moor/blob/master/moor/test/data/tables/todos.dart#L106):
```dart
void main() {
  TodoDb db;

  setUp(() {
    db = TodoDb(VmDatabase.memory());
  });

  test('test stream delete', () async {
    await db
        .into(db.todosTable)
        .insert(TodosTableCompanion.insert(content: 'some content'));
    final before = await db
        .customSelectQuery('select * from todos', readsFrom: {db.todosTable})
        .watchSingle()
        .first;
    expect(before.readInt('id'), 1);
    await db.customUpdate('delete from todos', updates: {db.todosTable});
    final after = await db
        .customSelectQuery('select * from todos', readsFrom: {db.todosTable})
        .watchSingle()
        .first;
    expect(after, isNull);
  });
}
```

Moor can't reliably update stream queries that don't have a `readsFrom` set. There was a report (#329) where moor would run the query way too often if listeners attach and detach in quick succession. This can commonly happen when using `StreamBuilder`s in a widget that updates often (say for animations). I would say that your test used to pass because of that. Unfortunately, moor can't properly support `StreamBuilder`s _and_ invalidate queries as soon as a listener detaches.
Since it the test passes when using `readsFrom` and `updates`, I would say moor is working as intended here ([this test](https://github.com/simolus3/moor/blob/808d19493990224be4768e298ace01bbfc12a8f3/moor/test/streams_test.dart#L79-L93) is similar to yours). If you have a repro that fails even though it sets the tables correctly I'd love to take another look.

**Comment by Mike278** [comment]
Ah that makes sense - the failing tests all involve operations performed by triggers or foreign key conflict clauses, which of course don't update streams (yet! #313). I guess the workaround for now would be to manually call `markTablesUpdated`?
FWIW I don't think it's moor's responsibility to accomodate `StreamBuilder` behaviour - it has a [bunch of limitations](https://github.com/flutter/flutter/issues/16465) and we actually ended up making our own `StreamBuilder` because even with perfect stream caching, swapping listeners [still emits an `AsyncSnapshot` with `ConnectionState.waiting`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/async.dart#L150).

**Comment by simolus3** [comment]
> I guess the workaround for now would be to manually call `markTablesUpdated`?

That's probably the best approach, yeah.

I've implemented basic support for update-propagation with triggers on `develop`. So far it only works based on table names. But now that the general infrastructure is here is should be possible to implement more accurate filtering based on what kind of write happened.

> FWIW I don't think it's moor's responsibility to accomodate `StreamBuilder` behaviour

Yeah, `StreamBuilder` can be weird, but it's very commonly used. In #329 it caused moor to execute a query on each widget rebuild, which was too problematic to ignore.

> swapping listeners still emits an `AsyncSnapshot` with `ConnectionState.waiting`

Ah right. It's probably impossible for Flutter to fix that since in general there would still be a microtask-delay between `listen` and the first callback. In very old versions, moor used to emit cached values synchronously, but that didn't work either (the `StreamBuilder` would receive a value before L150 is reached, which would then override the state).
