### ISSUE TITLE
How to use rowid as primary key 

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#445]
I noticed that specifying an id to the `Companion.insert` is necessary when not using `autoIncrement` but the `primaryKey` `Set<Column>` instead.

```dart
class Users extends Table {
  IntColumn get id => integer()();
  TextColumn get name => text()();

  @override
  Set<Column> get primaryKey => {id};
}
```

In SQLite, for this table, `INSERT INTO users(name) VALUES("Jake")` is valid, and it will generate an id automatically without using AUTOINCREMENT, which has performance disadvantages.
```sql
CREATE TABLE users (
   id INTEGER PRIMARY KEY,
   name TEXT NOT NULL
);
```
Can those kind of INSERTs be used with Companions?

**Comment by simolus3** [comment]
Thanks for the report. We already handled this case in the `sqlparser` package, but `moor_generator` incorrectly considered those columns to be required during an insert.

Since the `id` parameter in `UsersCompanion.insert` will change from `int` to `Value<int>`, this is a breaking change that will happen with moor 3.0.
