### ISSUE TITLE
Support for async batch functions

### ISSUE THREAD

**Issue by Max-Might** [simolus3/moor#483]
Hello,

I have noticed that when I pass an `async` function to `batch()` the changes are not committed.
I think the same happens when I pass a non-async function that contains a future.
Is it possible to run async functions for a batch?

**Comment by simolus3** [comment]
Thanks for the feedback. The use case for batches that I had in mind was to iterate over data that's already available and to quickly insert that to the database.

I've implemented support for async functions in batches now because it's a trivial change. But I'd probably recommend to either:

- run the async methods beforehand to construct the necessary statements, then run these in a batch
- use a transaction
