### ISSUE TITLE
sqlparser feature request: Generate List<T> instead of T for WHERE IN ? parameter

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#51]
First of all thanks for your great work on the sqlparser library! I really think generating code from SQL is the best approach to ORMs/persistence libraries, and I'm so glad there's now a solution available for Dart users.

I have a feature request: When a bind argument exists inside an IN clause, the parameter in the generated code should have the type `List<T>` instead of `T`. For example, the query 
```
SELECT * FROM todos WHERE id IN ?
``` 
would generate:
```
Future<List<TodoEntry>> todos(List<int> var1)
Stream<List<TodoEntry>> watchTodos(List<int> var1)
```
instead of:
```
Future<List<TodoEntry>> todos(int var1)
Stream<List<TodoEntry>> watchTodos(int var1)
```

**Comment by simolus3** [comment]
On `develop`, the sql parser can already recognize if a variable should be bound to an array. However, we can't bind an array to a singular variable at runtime, so we'd have to generate code like this (just writing off the top of my head, there probably is a more efficient way).
```dart
// assuming query is "SELECT * FROM todos WHERE id = ? OR id IN ? OR content = ?" to
// make things a bit harder.
Future<List<TodoEntry>> todos(int var1, List<int> var2, int var3) {
 final resolvedVars = <Variable>[Variable.withInt(var1)];
 final var2marks = List.filled('?', var2.length).join(', ');
 var query = 'SELECT * FROM todos WHERE id = ? id IN ($var2marks) OR content = ?'; 
 resolvedVars.addAll(var2.map((v) => Variable.withInt(v));
 resolvedVars.add(Variable.withInt(var3));
 return customSelectStatement('...', variables: resolvedVars).then(map);
}
```

**Comment by Mike278** [comment]
Yeah I think generating an appropriate-length list of `?`s is expected behaviour. Might take a bit of extra effort to make sure it plays nicely with indexed bind args (stuff like `SELECT * FROM todos WHERE id = ?2 OR id IN ? OR content = ?1`).

**Comment by simolus3** [comment]
Works on `develop`. There are two limitations to make the implementation simpler:
1. Array variables cannot be explicitly indexed: `WHERE id IN ?1` won't work.
2. There can't be an explicitly indexed variable that appears after an array variable _and_ has a higher index:  `SELECT * FROM todos WHERE id IN ? OR id = ?2` won't work. Your last example would work, because the array variable will have an implicit index of 3. `WHERE id IN ? OR id = ?` would work as well.

With both of these limitations, we can just replace every array variable in the query with the expanded form with the appropriate length. We don't have rewrite other variables to change their index.
