### ISSUE TITLE
Tables created with .moor files can not be add to DAOs by the table type

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#519]
If you have a table that is created by a `foo.moor` file, I would expect it to be usable in a DAO as type Foo `UseDao(tables: [Foo])`.

It compiles but `this.foo` is not generated.

If I add it as `UseDao(includes: {"foo.moor"})` then it gets generated.

Is this expect because of generation order or can this be fixed?

**Comment by simolus3** [comment]
Dart's build system is hermetic, which includes builders not being able to see code they generated in an earlier build.

I think generation order is also undefined here, so it could either be the dao or the main database with the `Foo` class that gets generated first. It's possible to configure the build so that the generation order is guaranteed to match. But at the moment, the generator doesn't recognize that `Foo` is a generated table class and it can't find the originating moor file. In general it's rather weird to have a builder change it's behavior based on its own output. I can try to support this, but it doesn't look like a commonly used feature since it would require special build configuration for each project that uses it.

**Comment by kuhnroyal** [comment]
I see. No need to implement some hacky way.
So the source of this is us having some tables in moor files and some in Dart classes.
We usually use moor files but we have about 30 tables that have the same structure and for these we have created an abstract table class and just inherit 30 times.

Do you have an idea how this could be done with moor files instead?

**Comment by kuhnroyal** [comment]
I found a TODO for this in my code but the problem is clear for me.
In the meantime we also have everything in moor files, so I will close this.
