### ISSUE TITLE
TextColumn.contains()

### ISSUE THREAD

**Issue by tmarzeion** [simolus3/moor#527]
Hey.
I think its super basic use case when someone wants to get results from DB by string query.
Why there isn't somethin similar to [RealmQuery.contains()](https://realm.io/docs/java/5.8.0/api/io/realm/RealmQuery.html#contains-java.lang.String-java.lang.String-) in moor?

**Comment by simolus3** [comment]
You can use the `like` and `regexp` methods, does that work for you?

Maybe we can have `contains('foo')` as alias for `like('%foo%')`.

**Comment by simolus3** [comment]
I've added support for `contains` which will be available in the next moor version.

**Comment by tmarzeion** [comment]
Its great that we have `like` method, but having `contains` method would have some nice advantages:
1. Its intuitive for people that are not as much familiar with raw SQL queries.
2. No regex required.
3. You could make method that would take optional `caseSensitive` parameter.

**Comment by tmarzeion** [comment]
> I've added support for `contains` which will be available in the next moor version.

You could make method that would take optional `caseSensitive` parameter

**Comment by simolus3** [comment]
I agree that a `caseSensitive` parameter would be useful, but I couldn't find a good way to implement that in sqlite. It looks like `LIKE` is always case-insensitive for the English alphabet, even when I add `COLLATE BINARY`.

**Comment by North101** [comment]
> I agree that a `caseSensitive` parameter would be useful, but I couldn't find a good way to implement that in sqlite. It looks like `LIKE` is always case-insensitive for the English alphabet, even when I add `COLLATE BINARY`.

You need `PRAGMA case_sensitive_like = true;` and then for case-insensitive you would probably need to do something like` LOWER(field) LIKE LOWER(:value)`. Not the best solution though

**Comment by simolus3** [comment]
Using `case_sensitive_like` should work, but it would be breaking if moor started changing that pragma suddenly. That change would also be hard to detect for users, so it's not really an option.

I've implemented this using custom sql functions in `moor_ffi`. The next moor version will have the `containsCase` extension method which takes a `caseSensitive` parameter that defaults to `false`. You need to import `package:moor/extensions/moor_ffi.dart` to use it, since it's a `moor_ffi`-only feature.
This function is implemented in Dart and uses `String.contains` or `String.toLowerCase().contains(other.toLowerCase())`. That doesn't fix all internationalization issues, but it's more consistent than using `LIKE`.
