### ISSUE TITLE
Error building Android bundle: Could not find eu.simonbinder:sqlite3-native-library:3.30.1

### ISSUE THREAD

**Issue by andruli** [simolus3/moor#542]
Hello everyone 👋🏻,

While attempting to run `flutter build appbundle` to generate the android bundle I'm currently facing this issue:

```
Could not determine the dependencies of task ':app:transformClassesAndResourcesWithR8ForRelease'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not find eu.simonbinder:sqlite3-native-library:3.30.1.       
     Searched in the following locations:                               
       - file:/Users/andres/Library/Android/sdk/extras/m2repository/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.pom
       - file:/Users/andres/Library/Android/sdk/extras/m2repository/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.jar
       - file:/Users/andres/Library/Android/sdk/extras/google/m2repository/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.pom
       - file:/Users/andres/Library/Android/sdk/extras/google/m2repository/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.jar
       - file:/Users/andres/Library/Android/sdk/extras/android/m2repository/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.pom
       - file:/Users/andres/Library/Android/sdk/extras/android/m2repository/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.jar
       - https://dl.google.com/dl/android/maven2/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.pom
       - https://dl.google.com/dl/android/maven2/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.jar
       - https://jcenter.bintray.com/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.pom
       - https://jcenter.bintray.com/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.jar
       - http://download.flutter.io/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.pom
       - http://download.flutter.io/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.jar
       - http://download.flutter.io/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.pom
       - http://download.flutter.io/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.jar
       - http://download.flutter.io/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.pom
       - http://download.flutter.io/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.jar
       - file:/Users/andres/projects/macrosfirst/build/app/outputs/repo/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.pom
       - file:/Users/andres/projects/macrosfirst/build/app/outputs/repo/eu/simonbinder/sqlite3-native-library/3.30.1/sqlite3-native-library-3.30.1.jar
     Required by:                                                       
         project :app > eu.simonbinder.moor_ffi:moor_ffi_release:1.0   
```

I'm using the latest versions of `moor` and `moor_ffi`. IOS build works w/o any issue.

```
$ flutter doctor              
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-AR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

• No issues found!
```

I tried running `flutter clean` and removing `~/.gradle` to make sure there was nothing cached.

**Comment by andruli** [comment]
Seems related to https://github.com/simolus3/moor/issues/446

**Comment by simolus3** [comment]
The right maven repository would be `https://dl.bintray.com/sbinder/sqlite3-native-library/`. I'm surprised that doesn't show up in the list, as `moor_ffi` should add that repo:https://github.com/simolus3/moor/blob/94fe04ee354b215c281d0f54b1448d33d8ad1286/moor_ffi/android/build.gradle#L15-L24


Does it work if you manually add that repo to your gradle build script?

**Comment by andruli** [comment]
Sorry, I couldn't test this yet. I'll test it later today and report back.

**Comment by andruli** [comment]
@simolus3 I finally got time to follow on this. Adding the code you mentioned to the `build.gradle` let the compile process to go on and surfaced an error on the `AndroidManifest.xml`. For some weird reason, that was completely removed from the error stream before 🤷 .

This was user error 😅. Thanks for the help!

**Comment by ukor** [comment]
@simolus3 Thank you for all the work you do,

Can we add this to the documentation, it took me hours to figure out that this was the reason my build was failing

> The right maven repository would be `https://dl.bintray.com/sbinder/sqlite3-native-library/`. I'm surprised that doesn't show up in the list, as `moor_ffi` should add that repo:
> 
> https://github.com/simolus3/moor/blob/94fe04ee354b215c281d0f54b1448d33d8ad1286/moor_ffi/android/build.gradle#L15-L24
> 
> Does it work if you manually add that repo to your gradle build script?

**Comment by simolus3** [comment]
Do you depend on `sqlite_flutter_libs`? That package should add my maven repository. I'm using it in most of my project without having to manually add that repo. Do you have a custom buildscript that might cause this?

**Comment by ukor** [comment]
Yes, my project depends on `sqlite_flutter_libs`. I don't have a custom build script. I had to manually insert add that repo to my `build.gradle`

**Comment by jesseframework** [comment]
am having the same problem

**Comment by simolus3** [comment]
@jesseframework Do you depend on the latest version of `sqlite_flutter_libs`? Bintray is not a thing anymore, you need to grab them from maven central to which recent versions of `sqlite_flutter_libs` should point you to.

**Comment by jesseframework** [comment]
I dont event see this sqlite_flutter_libs in my pubspce file a, not sure why am getting the error.

`name: j3enterprise
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.17.3+1
  google_maps_flutter:
  http: ^0.12.0+4
  geolocator: ^6.1.13
  vector_math: any
  sensors: ^0.4.2+6
  battery: ^1.0.7
  material_floating_search_bar: ^0.2.0
  dropdown_search: ^0.4.8
  cupertino_icons: ^0.1.2
  xlive_switch: ^1.0.5
  flushbar: ^1.10.4
  signature: ^3.2.0
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.0
  chopper: ^3.0.0
  flutter_simple_treeview: ^2.0.1
  barcode_keyboard_listener: ^0.0.1
  intl: 
  easy_localization:
  background_fetch: ^0.6.0
  devicelocale: ^0.2.3
  rflutter_alert: ^1.0.3  
  sqflite: ^1.3.0
  provider: ^4.3.2+2
  badges: ^1.1.3
  shared_preferences: ^0.5.8
  flutter_bloc: ^3.2.0
  meta: ^1.1.6
  equatable: ^1.0.0
  moor: ^3.3.0
  moor_ffi: ^0.8.0
  path_provider: ^1.6.11
  # firebase_core: ^0.4.0+9
  # firebase_analytics: ^5.0.2
  # firebase_auth: ^0.14.0+5
  firebase_messaging: ^7.0.3
  bot_toast: ^3.0.0
  device_info: ^0.4.2+4
  encrypt: ^4.0.2
  cryptor: ^0.1.6
  connectivity: ^0.4.8+6
  quiver: ^2.1.3
  logging: ^0.11.4
  flutter_barcode_scanner: ^1.0.2
  kiwi: ^0.1.0
  built_value: ^7.0.0
  flutter_local_notifications: ^1.4.4+1
  get_it: ^4.0.2
  built_collection: ^4.1.0
   
  shamsi_date: ^0.8.1
  random_string_one: ^1.0.2
  dotted_line: ^2.0.2
  twilio_flutter: ^0.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^3.0.0
  moor_generator: ^3.1.0
  build_runner: ^1.3.1
   


 
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:  
    - images/
    - images/cogs.png
    - lang/en.json
    - lang/es.json
    - lang/sk.json
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: CustomIcons
     fonts:
       - asset: fonts/CustomIcons.ttf
   - family: MyFont
     fonts:
       - asset: fonts/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by jesseframework** [comment]
am using moor 3.4 which is depending on sqlite3. am not sure that the same thing. am not seeing sqlite_flutter_libs im my project at all. may be i dont know where to look.

moor 3.4.0
|   |-- collection...
|   |-- convert 2.1.1
|   |   |-- charcode...
|   |   '-- typed_data...
|   |-- meta...
|   |-- pedantic...
|   |-- sqlite3 0.1.8

**Comment by simolus3** [comment]
0.2.0 is not the latest version, the latest is 0.5.3...
