### ISSUE TITLE
Auto increment id field is generated as a @required parameter for the table class which makes any table unusable :(

### ISSUE THREAD

**Issue by nateshmbhat** [simolus3/moor#548]
i'm also facing following issue : 

### Here's my Table : 

```
@DataClassName('RecentSearch')
class RecentSearches extends Table {

  IntColumn get id => integer().autoIncrement()();

  IntColumn get category_id => integer()();

  BlobColumn get category_data => blob()();

  IntColumn get timestamp => integer()();

  TextColumn get key => text()();
}

```

But the generated `RecentSearch` object contains @required annotation for all parameters including the `id` parameter which is supposed to be an auto increment column.

This is a serious blocker for using this library :/ 

### Here's the generated `RecentSearch` table
```
class RecentSearch extends DataClass implements Insertable<RecentSearch> {
  final int id;
  final int category_id;
  final Uint8List category_data;
  final int timestamp;
  final String key;
  RecentSearch(
      {@required this.id,
      @required this.category_id,
      @required this.category_data,
      @required this.timestamp,
      @required this.key});
....

}
```

**Comment by kuhnroyal** [comment]
I am also facing this issue in moor files with `AUTOINCREMENT` but also with `NOT NUL DEFAULT FALSE` which both generate a `@required` annotation.
The `AUTOINCREMENT` should definitely not have an annotation. Columns with default value are debatable but imo should not have an annotation as well.

**Comment by simolus3** [comment]
The generated data classes are designed to hold a full row, as it would appear in the database. Since a row in the database contains a non-null `id`, it's marked as `@required` in the generated class.
Let's say that `id` was not marked as `@required`, and also allowed to be null. When Dart gets non-nullable types real soon now, we'd have to generate the field as `final int? id`. Then, all code that just selects rows from the database and obtains an instance of `RecentSearch` will have to guard against `id` being null, even though this impossible.

If you want to update or insert rows into the database, you only need to provide partial data. Moor generates a `RecentSearchesCompanion` class, which is useful for inserts or updates. You can use  the `RecentSearchesCompanion.insert` constructor, where only columns that are required for inserts are marked as `@required`.

For the reason mentioned above, we can't really make those fields not-required. Companions should solve this problem and still make inserts safe. If you have a scenario where companions are awkward to use, please let me know.

**Comment by kuhnroyal** [comment]
True, I didn't think of NNBD. It needs to be `required` there.

**Comment by nateshmbhat** [comment]
Please update the documentation on inserts regarding this

**Comment by simolus3** [comment]
Kind of. There's an entry on the guide for Dart inserts and updates [here](https://moor.simonbinder.eu/docs/getting-started/writing_queries/#updates-and-deletes).
This issue comes up regularly, so I'll try to make this more prominent in the documentation.

**Comment by felixjunghans** [comment]
When I use ItemsTableCompanion.insert, fields that are AutoIncrement are still displayed as required. What value should I enter in this field if it should be filled in automatically?

**Comment by krunduev** [comment]
I have opposite 
For 
```
class Employees extends Table {
  IntColumn get id => integer().autoIncrement()();
```
I have 
```
  Employee(
      {required this.id,
```
so I cant' create and insert Employee because id is required but before insert is unknown

**Comment by kuhnroyal** [comment]
You need to use the generated companion class, something like `EmployeeCompanion.insert`.
