### ISSUE TITLE
Moor Upsert statement error : insertOnConflictUpdate

### ISSUE THREAD

**Issue by KennanObura** [simolus3/moor#549]
I am trying to insert or update a table depending on whether that key exist or not with this simple statement 

`Future insertOrUpdateUser(Insertable<User> item) => into(users).insertOnConflictUpdate(item); `

This logs  the following error 

> E/SQLiteLog(17529): (1) near "ON": syntax error
I/flutter (17529): DatabaseException(near "ON": syntax error (code 1 SQLITE_ERROR): , while compiling: INSERT INTO users (id, first_name, last_name, phone, profile_pic_url) VALUES (?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET id = ?, first_name = ?, last_name = ?, phone = ?, profile_pic_url = ?) sql 'INSERT INTO users (id, first_name, last_name, phone, profile_pic_url) VALUES (?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET id = ?, first_name = ?, last_name = ?, phone = ?, profile_pic_url = ?' args

These are the  package versions am using:

`moor: ^3.0.2
  moor_flutter: ^3.0.0
  moor_ffi: ^0.5.0`

Can somebody help me understand this? Could it be that the generated code is wrong?

**Comment by kuhnroyal** [comment]
I would guess your sqlite version is too old.
First you only need moor_flutter or moor_ffi, not both.

**Comment by KennanObura** [comment]
@kuhnroyal 
Thanks for your response. AM removing moor_ffi and see what happens. I actually didnt know i only need either and not both. 

And also.. Do i really have to include sqlite ? My understanding is that moor is built on top of sqlite so if i have the latest moor that should be it. The syntax is supported meaning i might be running the new sqlite.

**Comment by kuhnroyal** [comment]
You don't need to add sqlite, moor uses the sqlite library provided by the OS.
But the device you are running may in some cases have an old sqlite library - the `UPSERT` was only added in sqlite 3.24.0: https://www.sqlite.org/lang_UPSERT.html

If you follow the https://moor.simonbinder.eu/docs/getting-started/ then you will see that the current recommendation is to use `moor_ffi`.

**Comment by simolus3** [comment]
If you need a recent sqlite version on Android, you need `moor_ffi` as that bundles the latest sqlite library with your app.
When using `moor_flutter`, moor will use the builtin sqlite library as @kuhnroyal mentioned. That can reduce apk size by a bit, but the downside is that you're stuck with the sqlite version from the OS.

On iOS both `moor_ffi` and `moor_flutter` will use sqlite from the OS. When using `moor_ffi`, you can bundle a custom sqlite version on iOS as well by following these steps: https://github.com/simolus3/moor/issues/547#issuecomment-624526982

The documentation warns about upserts not being available on older sqlite versions and moor generates correct sql here, so I'll close this issue. If you need any help, let me know.

**Comment by tareq3** [comment]
I am having same issue on android only working fine on IOS. I am using moor_flutter and moor_ffi

**Comment by simolus3** [comment]
> I am using moor_flutter and moor_ffi

There's no need to use both of them, you can probably drop the `moor_flutter` dependency.

It's pretty weird that this wouldn't work on Android, since that's where we ship the latest sqlite3 version. Which Android version are you using?

**Comment by KirillKarmazin** [comment]
moor_ffi 0.8.0:
This package has been deprecated! 

All these recommendations, deprecated packages, and confusing package names with moor is a complete mess. 

Please update the docs on the website and make them more clear:
Why not creating separate 'Getting started' docs for Flutter and for Web (plain Dart)? 


Also, this code is bad for Flutter devs since it creates a db file that is not recognized by the new Database Inspector tool in Android Studio 4.1+ which is super handy for debugging while working the DB.


`LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return VmDatabase(file);
  });
}`

In order to make it visible to the Database Inspector the file should be placed in the /database internal folder and has a "db" extension, for example by using this:

FlutterQueryExecutor.inDatabaseFolder(
          path: 'app.db',
          logStatements: true,
        )

**Comment by karmazinkd** [comment]
@kuhnroyal
moor_ffi 0.8.0:
This package has been deprecated!

All these recommendations, deprecated packages, and confusing package names with moor is a complete mess.

Please update the docs on the website and make them more clear:
Why not creating separate 'Getting started' docs for Flutter and for Web (plain Dart)?

Also, this code is bad for Flutter devs since it creates a db file that is not recognized by the new Database Inspector tool in Android Studio 4.1+ which is super handy for debugging while working with your DB.

LazyDatabase _openConnection() { // the LazyDatabase util lets us find the right location for the file async. return LazyDatabase(() async { // put the database file, called db.sqlite here, into the documents folder // for your app. final dbFolder = await getApplicationDocumentsDirectory(); final file = File(p.join(dbFolder.path, 'db.sqlite')); return VmDatabase(file); }); }

In order to make it visible to the Database Inspector the file should be placed in the /database internal folder and has a "db" extension, for example by using this:

FlutterQueryExecutor.inDatabaseFolder(
path: 'app.db',
logStatements: true,
)

but... it requires moor_flutter

**Comment by kuhnroyal** [comment]
Yes the package has been deprecated!

1. Your broad criticism isn't very helpful. I think the getting started page is pretty self explanatory and the documentation  contains much more than you will find in most small open source projects. You are welcome to create an issue or even better a PR  if you think the documentation lacks something.

2. You are answering on an issue from may. In the fast changing ecosystem that Dart and Flutter are, this is basically years old so the information in this issue is outdated.

3. You can always checkout the examples and test cases, in most well-maintained projects these are the best documentation.

4. If you don't like moor and think it is a mess then please don't use it. Feel free to create your own database library.

5. **Most importantly, my opinions don't reflect the opinions of the moor project or its author. You just mentioned me so I am responding.**
