### ISSUE TITLE
Option to make moor generate mutable classes

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#551]
It came up in https://github.com/simolus3/moor/issues/95#issuecomment-625443671. Most users will probably prefer immutable classes, but we can add an opt-in option to generate mutable data classes, companions and result sets.

**Comment by majdi21** [comment]
@simolus3 maybe I'm missing something but why would users prefer immutable classes?

**Comment by kuhnroyal** [comment]
Immutability is kind of a cornerstone for many of the programming paradigms/frameworks that are present in Flutter in some way or another. Be it redux stores, RX/stream implementations, Flutter widget trees. A lot of this comes down to the fact that diffs in data structures (state trees etc.) are much easier to detect when they are immutable.

I have seen many bugs due to mutable state and would always prefer immutable state, but ofc. that is a personal opinion.

**Comment by simolus3** [comment]
The next moor version will introduce the `mutable_classes` build option that can be used to enable this behavior.
