### ISSUE TITLE
[Question] How to access database in background process created by workmanager or background_fetch?

### ISSUE THREAD

**Issue by TheLastGimbus** [simolus3/moor#567]
Hi!
I'm working on app which needs to access database in normal (foreground) widgets, but also in background, where code is periodically executed by [workmanager](https://pub.dev/packages/workmanager) package (or I could also use [background_fetch](https://pub.dev/packages/background_fetch) ).

For now, I've been using database instance in a one, top-level `Provider`. But obviously, background stuff doesn't have any `BuildContext`, so I can't use that.

Your site says:
> you probably use some dependency injection framework like kiwi or get_it

Should I do this in my case? Would it work? In #399 guy had a very similar case.

**Comment by JCKodel** [comment]
Many people uses dependency injection as service locators.

Provider is a service locator. Meaning: `Provider.of<SomeClass>(context)` will return an instance of SomeClass that is registered at startup. If you make SomeClass singleton, you don't need Provider.of! You only need Consumer<SomeClass> because this is reactive.

Dependency injection is similar to service locator, but with 1 tiny difference: you don't use concrete types in DI! Dependency injection should only work with interfaces (abstract classes in Dart). You are basically saying "I have this blueprint of a class that access a database somehow" <-- this is the interface. "My database class that access moor and sqlite" <-- this is your concrete production class. "Some dumb class that do only things in memory for tests only" <-- this is another concrete class for unit test. So, you'll ask the ABSTRACT class to the dependency injection and it will return a concrete class (the production or unit test one, depending how is registered).

So, Dependency Injection will always return a blue print and a unknown concrete class.

In your background process, you don't need reactivity, so you don't need Provider and you don't need service locators.

If you use Dependency Injection, configure it on your background module (if you don't test your background unit, you can skip DI all together and always use the concrete sqlite class). Best practice is to use the same Dependency Injection framework, configurated the same way the main application. (And, remember: Provider **IS NOT** a Dependency Injection framework, nor can be used as one).

Hope it help you somehow.

**Comment by simolus3** [comment]
Do you need writes from the background thread to update the UI in real time (e.g. update stream queries and so on)? For that you'd need to use `MoorIsolate`-related features and an additional setup.
Otherwise, you can just create another database instance from the background process and write in there. sqlite3 should take care of the underlying locking.

**Comment by TheLastGimbus** [comment]
No, background stuff won't affect UI live.
When creating instance in background (workmanager work can lunch while app is running), I get big scary warnings "**NOT TO CREATE TWO INSTANCES AT ONCE**". 
Sooo... can I just ignore them?

(btw, thanks @JCKodel for such broad explenation, altough I don't yet know what abstract classed are etc, but don't bother yourself, I'll try to make sense of it myself)

**Comment by simolus3** [comment]
The "don't create two instances at once" warning should only appear if the two instances are on the same Dart isolate. 

If they are, that actually makes it easier. If you don't want to use a service locator (yet), you can just keep your database as a top-level getter:

```dart
MyDatabase _database;
MyDatabase get database => _database ??= MyDatabase();
```

Now, both the background code and the provider should use the `database` getter instead of creating their own.

**Comment by zmeid** [comment]
I have a similar issue to this one, and my answer is "yes" to your that question @simolus3:

> Do you need writes from the background thread to update the UI in real time (e.g. update stream queries and so on)? For that you'd need to use MoorIsolate-related features and an additional setup.

Basically, I am using firebase messaging and when the app receives a push message while the app is in background, then firebase runs in an isolate that cannot access/be accessed from UI environment. In that isolate, I insert to database, but, changes are not reflected to UI where I listen to changes through streams. Currently, as a workaround, when user takes the app to the foreground, I re-run the queries and get the updates. So, i was wondering how i can make query streams work in that scenario.

I have followed the documentation [here](https://moor.simonbinder.eu/docs/advanced-features/isolates/), but that did not work. I think the reason why it didn't work is because i re-create the executor in firebase isolate. So, I actually have 2 different Moor DB instances(I do that because I cannot pass the executor to the isolate which is created by firebase, i have no control on it's creation). So, since the firebase isolate is not created by me, how can I make writes visible to UI?

**Comment by TheLastGimbus** [comment]
Hi @zmeid! I recently implemented "accessing moor in multiple isolates/environments" problem in my app! I managed to nicely launch background isolate for moor and connect to it if it exists. You can check it out:
- https://github.com/TheLastGimbus/dotmeme/commit/0b6a290fd1600040c618a0d09c72976a7bbe27f8

Here is how it looks now:
- https://github.com/TheLastGimbus/dotmeme/blob/932f3ba1a944ec59cba2385469d3a00371459887/lib/di.dart#L28
- https://github.com/TheLastGimbus/dotmeme/blob/932f3ba1a944ec59cba2385469d3a00371459887/lib/database/memebase.dart#L54-L69

You *could* make it that moor runs on same Isolate as Ui, but that will break if user closes the ui while background event is running... besides, looks like Dart Isolates are getting better and faster to communicate, so it shouldn't be that much of a problem :+1:

**Comment by simolus3** [comment]
@TheLastGimbus I really like the `IsolateNameServer` approach to this problem 👍 I've recently put some work into adding this feature to the core moor package as well. There are some potential issues I ran into, did you encounter them in practice?

- There's a potential race condition if two isolates open the connection at the same time (they'll both find that no port has been registered and then launch a new connection)
- Did you have problems with isolates suddenly shutting down? E.g. if a handler for a work manager launches a isolate, wouldn't that isolate disappear when the task is done? I couldn't find a good way to solve this with `IsolateNameServer` except for requesting a ping and setting a timeout on a `SendPort`.
- Assuming that the active db isolate may stop while other isolates have a connection, I have also considered an approach where the other clients elect a new leader and transparently switch to a new connection. This turned out to be challenging to implement though, and it wouldn't work for transactions.

**Comment by kuhnroyal** [comment]
We are also using the `IsolateNameServer` to publish the moor `SendPort` and tried the approach of always starting the `MoorIsolate` if we can't find an existing one.
There are a couple problems that we noticed.

1. The main problem here is https://github.com/flutter/flutter/issues/14815. `Isolate.resolvePackageUri` does not work from an isolate that was not started by the main Flutter isolate (only on iOS I believe). Which means that any WorkManager, PushNotification, FCM etc. can not start a `MoorIsolate` from the background since `Isolate.resolvePackageUri` is used by `Isolate.spawn`.

2. Additionally it seem that it is not even guaranteed, that the background is starting the `FlutterEngine` in the same Dart VM. `IsolateNameServer` only works inside one VM. This can probably be solved with the new `FlutterEngineGroup` (https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngineGroup.html).

3. `IsolateNameServer` does not get cleared on a Flutter hot-restart. The `SendPort` is still there but the `MoorIsolate` has been killed. This can be solved with a bit of configuration.

We now only start `MoorIsolate` from the foreground and connect to it from other isolates. If the `MoorIsolate` can not be found (via `IsolateNameServer`) then we open the database directly and write to it because most likely the app is not running and will refresh itself once it is started.

**Comment by kuhnroyal** [comment]
> You _could_ make it that moor runs on same Isolate as Ui, but that will break if user closes the ui while background event is running

@TheLastGimbus From my understanding, when the Flutter main isolate is killed/stopped, all child isolates are stopped as well. So if any background job (not started from the main isolate) is running at that time and is connected to the `MoorIsolate`, it will fail.
We basically had exactly the same solution but ran into problems 1 and 2 described above.

**Comment by TheLastGimbus** [comment]
@simolus3 questions:
> race conditions

This may happen, tho I didn't ever encounter it - I usually open foreground service (background) when UI is already open - tho it will probably also be awaken by JobScheduler in future - then, it would need to fire in *exact same*/very close time to UI - i doubut it's possible

> if a handler for a work manager launches a isolate, wouldn't that isolate disappear when the task is done?

Only if you launch *the moor isolate* inside workmanager (i think) - what i do is I launch separte one - so if you have UI and workmanager/foreground service you have 3 isolates - from what i've observed, isolates will exist as long as app process does - so if workmanager fires -> opens moor isolate -> user opens UI -> workmanager finishes -> moor isolate still exists  (**i think**)

@kuhnroyal 
> WorkManager, PushNotification, FCM etc. can not start a MoorIsolate

I didn't yet see this, since I always start [foreground service](https://pub.dev/packages/flutter_foreground_task) from UI - tho may be true :confused: 

>  it is not even guaranteed, that the background is starting the FlutterEngine in the same Dart VM

Hm... maybe... but it's always has been for mine :+1:

**Comment by federicodesia** [comment]
Any update on the issues in that [comment](https://github.com/simolus3/drift/issues/567#issuecomment-934514380)?

**Comment by stevemayne** [comment]
@simolus3 I'm facing a similar issue where my FCM handler updates the database, but leaves the UI isolate(s) with stale data. I wonder - rather than juggling shared isolates, is there a way to force-refresh the foreground on resume, without recreating the database object or things that depend on it?

**Comment by simolus3** [comment]
@stevemayne You can refresh all query streams with

```dart
db.notifyUpdates({
  for (final table in db.allTables) TableUpdate.onTable(table),
});
```

(where `db` is an instance of the generated database class). Is that what you were looking for? Calling that when the UI is resumed should refresh stream queries.

**Comment by brunogabriel** [comment]
@simolus3 Apologies for revisiting this topic, but I have a query I'd like to discuss. Can you help me? Suppose I have two distinct Android engines, each with an instance of a singleton Flutter code that shares the same implementation of Drift, utilizing the following approach to open a database (as specified in the documentation):

```dart
...
return NativeDatabase.createInBackground(file);
```

If I insert data in "engine one" and establish a communication channel between the two engines, perhaps through a method channel or a plugin with a similar concept, and then in "engine two" respond to the callback message by refreshing all query streams (as you suggested), will the data be successfully updated in "engine two"?

The purpose of "engine two" is solely to display the data updated by "engine one."

**Comment by simolus3** [comment]
No worries. And yes, this should work. I recommend enabling [WAL mode](https://sqlite.org/wal.html) by running `pragma journal_mode=wal` on the database for this. That allows two threads/processes to open the same database file concurrently as long as only one of them is doing writes at the same time (so exactly the situation you have here).

Using a method channel to forward stream query updates should work, you can use `db.tableUpdates` to get a stream of updates in engine one.

**Comment by brunogabriel** [comment]
> pragma journal_mode=wal

Thank you for this approach, I'll try it soon. The last one, please, hahah if I use this approach:
https://github.com/simolus3/drift/discussions/2815

Using same isolate server name is it necessary to create a channel to communicate between two instances in different engines?

**Comment by simolus3** [comment]
I'm not too experienced with Flutter, is an isolate name server visible across multiple Flutter engines? If it is, this should work (but then you also don't need manual updates since the two engines would connect to the same database connection).
