### ISSUE TITLE
question about stream queries performance in ListView

### ISSUE THREAD

**Issue by mpcreza** [simolus3/moor#574]
Hi there
I want to check the changes related to a field in a table
To do this, I wrote a stream query and used it in a list
This means that each item in this separate list has a stream builder
Should I worry about performance?

**Comment by simolus3** [comment]
> This means that each item in this separate list has a stream builder

This might get expensive when you show a lot of items simultaneously, yeah. But when you're using a `ListView` from Flutter it should only listen to streams for items that are actually shown, so it's probably not that bad.

Depending on how complex the nested queries are, you could also try to merge everything into a single stream (so that you get a `Stream<List<...>>` instead of `List<Stream>`). Let me know if you need any more info.
