### ISSUE TITLE
Problems with insertAllOnConflictUpdate

### ISSUE THREAD

**Issue by celsobonutti** [simolus3/moor#575]
I'm trying to do a batch upsert, but when I do it like this:
```dart
  Future batchInsertProducts(List<Insertable<Product>> productList) async {
    await batch((batch) {
      batch.insertAllOnConflictUpdate(db.products, productList);
    });
  }
```
I get this error:

PlatformException (PlatformException(sqlite_error, Error Domain=FMDatabase Code=1 "near ")": syntax error" UserInfo={NSLocalizedDescription=near ")": syntax error}, {sql: INSERT INTO products (code, name) VALUES (?, ?) ON CONFLICT() DO UPDATE SET code = ?, name = ?, arguments: [005001000601, APLICADOR, 005001000601, APLICADOR]}))

I suspect this is related to the phone's SQLite version not supporting upsert. If it is that, is there any way for me to update it?

Thank you very much

**Comment by simolus3** [comment]
> I suspect this is related to the phone's SQLite version not supporting upsert

Probably, yes. You try [using `moor_ffi`](https://moor.simonbinder.eu/docs/other-engines/vm/#migrating-from-moor-flutter-to-moor-ffi) instead of `moor_flutter`. It will ship the latest sqlite version along with your app on Android.

On iOS this typically isn't as much of a problem so `moor_ffi` still uses the sqlite version from the phone there. If you want to use the latest sqlite version on iOS as well, you cal follow the steps from #547

**Comment by North101** [comment]
`ON CONFLICT()`

This is the bit that stands out for me, I'm not sure `ON CONFLICT` accepts having no values in the brackets. When writing IN queries if they get generated as `IN ()` (with no items) then the sql will reject it as an error. I think this might be happening here as well.

**Comment by simolus3** [comment]
Good catch, I overlooked that. I think this happens if the table for `Product` somehow doesn't have a primary key?

@cels0 Can you post the definition of the products table? If it doesn't have a custom primary key, you can also set the conflict target manually:

```dart
await batch((b) {
  for (final product in productList) {
    b.insert(
      db.products,
      product,
      onConflict: DoUpdate(
       (_) => product,
       // upsert will happen if it conflicts with columnA and columnB
       target: [db.products.columnA, db.products.columnB],
      ),
    );
  }
});
```

Moor should set the `target` automatically based on the primary key though. If that's not happening here it might be a different bug.
