### ISSUE TITLE
moor_ffi seems to ignore boolean values

### ISSUE THREAD

**Issue by sq6jnx** [simolus3/moor#607]
I stumbled upon a very strange behavior of `moor_ffi` (0.6). Consider this code:

```dart
import 'package:moor_ffi/database.dart';

void main() {
  var db = Database.memory();
  db.execute('''
    CREATE TABLE foo (
      i INT PRIMARY KEY
      , t TEXT NOT NULL
      , b BOOL NOT NULL default false
      );''');

  final insert = db.prepare('INSERT INTO foo (i, t, b) VALUES (?, ?, ?)');
  insert.execute([1, 'a', 1]);
  insert.execute([2, 'a', true]);
  insert.execute([3, 'a', false]);

  final select = db.prepare('SELECT * FROM foo;');
  final results = select.select().toList();
  print(results);
}
```

It prints:

```
[{i: 1, t: a, b: 1}, {i: 2, t: a, b: 1}, {i: 3, t: a, b: 1}]
```

That is strange, because in third row I put `false` to column `b`.

Moreover, if I comment out line:

```dart
//  insert.execute([1, 'a', 1]);
```

My program executes with error:

```
Unhandled exception:
SqliteException(1299): NOT NULL constraint failed: foo.b, constraint failed (code 1299)
#0      PreparedStatement.execute (package:moor_ffi/src/impl/prepared_statement.dart:96:7)
#1      main (file:///media/sq6jnx/extra/jnxlog/commons/.scratches/moor_ffi_bug_on_nulls.dart:14:10)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

I am too new in Dart, but I think that `moor_ffi`:
 - ignores boolean values (at least on INSERTs)
 - stores them somehow on prepared statement.
 
 Second assumption is based on a fact that I get SqliteException if I modyfy example script in the following way:
 
 ```dart
 /// ...
   var insert = db.prepare('INSERT INTO foo (i, t, b) VALUES (?, ?, ?)');
  insert.execute([1, 'a', 1]);
  insert.close();

  insert = db.prepare('INSERT INTO foo (i, t, b) VALUES (?, ?, ?)');
  insert.execute([2, 'a', true]);
```

**Comment by simolus3** [comment]
> `, b BOOL NOT NULL default false`

Note that `BOOL` is not a valid datatype in sqlite. When using moor files, the generator would replace `BOOL` with `INT`. As per [the documentation](https://www.sqlite.org/datatype3.html#determination_of_column_affinity), the column `b` would have the type `NUMERIC`.

As explained in [moor_ffi's README](https://pub.dev/packages/moor_ffi#supported-datatypes), `bool` is not a supported datatype and will be ignored as an argument. This is because sqlite3 doesn't have builtin support for booleans. Instead of ignoring these parameters, I'll change the implementation to throw an exception instead.

**Comment by sq6jnx** [comment]
> Note that BOOL is not a valid datatype in sqlite. 

Thanks, that should do the trick.
