### ISSUE TITLE
Add prominent list of supported types out of the box

### ISSUE THREAD

**Issue by willhaslett** [simolus3/moor#624]
Hi. Thank you for this excellent package. It might be helpful for many to list the supported column types somewhere in the beginning of the getting started section of the documentation. If that list is available anywhere in the docs, I can't find it.

**Comment by simolus3** [comment]
I'm not sure if the beginning of the getting started section is the right place to put this - it already highlights the most important types by using them. I've added it to the [Dart tables](https://develop--moor.netlify.app/docs/getting-started/advanced_dart_tables/) article though, so that there's a useful overview.

**Comment by willhaslett** [comment]
Looks great! Here's hoping moor becomes *the* ORM for Flutter. I've been shopping around, and it looks like you're ahead of the pack to me.
