### ISSUE TITLE
Performance drawback using moor

### ISSUE THREAD

**Issue by MartinHlavna** [simolus3/moor#638]
I am migrating from sqflight to moor using moor_ffi. We are not using Moor as ORM but only as platform independent API that talks to sqlite database. Since we already have our own DAO layer migration was pretty simple. Our dao layer is handling simple query generation and calls QueryExecutor.runXXX methods.

Performing 1000 inserts took twice as much time using moor_ffi than using sqflite alone (without moor). Calling queries via direct connection vs calling via MoorIsolate does'nt  show any significant difference.

This is OK for day to day use, but we are performing write heavy synchronization at first start of application that downloads data from server.

Do you have any idea what may cause slowdowns? I was expecting that using dart_ffi could be litlle faster as it is bypassing AndroidSDK facade.

Thanks

**Comment by simolus3** [comment]
If you're not using high-level moor apis, I would recommend to use `package:moor_ffi/database.dart` (or even [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi) directly). But that should be unrelated to this issue.

Indeed I would expect `dart:ffi` to be orders of magnitude faster by skipping platform channels (and this is what I saw in [benchmarks](https://github.com/hivedb/hive_benchmark/pull/2)). Are you running the inserts in a transaction? That usually makes it much faster since you're saving unnecessary writes. You can further save some sql parsing costs by re-using prepared statements.

**Comment by MartinHlavna** [comment]
Right now we are using only runBatched as optimalization means for some historic reasons. But transactions sounds reasonable.

**Comment by MartinHlavna** [comment]
looks like transactions solves the problem. Thanks for support.
