### ISSUE TITLE
Database is locked error.

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#648]
Hi @simolus3,

I'm receiving this error.

```
flutter: insertStatment>>> REPLACE INTO List2 (id, dateCreated, Image1) VALUES ("0", "", "")
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\runtime\dart_isolate.cc(875)] Unhandled exception:
SqliteException: database is locked

```
```
insertSqlQuery=insertSqlQuery.replaceAll("INSERT", "REPLACE");
await customStatement(insertSqlQuery);
```

Is there a way to do operations as soon as the database is idle or unlocked | or at least check for lock?

**Comment by simolus3** [comment]
The database is only locked if there's someone else using it. That someone is probably your own application - do you open the same database twice?

**Comment by SahajRana** [comment]
Yup, that was the problem. It's resolved now. Thanks!

**Comment by animedev1** [comment]
@SahajRana How did you solve that. I'm stuck with this problem using with Workmanager

**Comment by lucasarcouto** [comment]
I'm having the same issue as @animedev1 referenced. Using WorkManager causes this exception to be thrown every time.

**Comment by simolus3** [comment]
If you use the same database across multiple threads, I recommend enabling [write-ahead logging](https://sqlite.org/wal.html) (you can use `PRAGMA journal_mode=WAL;` in the `beforeOpen` callback of your migration). That reduces the chance of the threads locking each other since the design of WAL allows a write concurrent to reads.

**Comment by lucasarcouto** [comment]
I ended up solving this issue by following the example project.
