### ISSUE TITLE
Implement IN variable for customSelect

### ISSUE THREAD

**Issue by North101** [simolus3/moor#66]
At the moment it doesn't seem possible to do an IN clause in a customSelect as it requires Variable values.

**Comment by cw-dev** [comment]
#51

**Comment by simolus3** [comment]
The referenced issue tracks this feature for queries which are analyzed at compile time.

I'm not sure if we should have a similar feature for `customSelect` directly: Sqlite doesn't have an array type for parameters - that would be pure syntax sugar provided by moor. For instance, if we had something like `id IN ?` and bound the variable to `[1,2]` we'd have to expand the query to `id IN (?, ?)` and execute that.

Doing that work at compile time is okay, because we know which variables are arrays and only have to take these into account. For `customSelect`, neither the sql statement or the type of the variables are known before, which means that  we'd have to rewrite the sql based on the variables. To make things worse, how would we deal with `id IN ? OR id = ?2`? Here, changing the amount of variables we expand the first `?` to can also change the semantic of that expression! We can detect these cases at compile time because we're analyzing the query anyway, but to do that at runtime we'd have to do rather expensive operations on the query.

So, I'd prefer if `customSelect` just executed the statement as it's provided, without modifying it. This means that we can't support this feature. @North101 Are the [compiled queries](https://moor.simonbinder.eu/queries/custom#statements-with-a-generated-api) not an option for your use case? These will support that feature in the next moor version. I'll reconsider & reopen this if anyone finds a good reason to support that at runtime, but I think the disadvantages are too big, so closing this issue for now.

**Comment by North101** [comment]
Ok, thats understandable. the IN operator is something I use a lot, i'm surprised its not supported as a bound param in sqlite.

Having it work in a compiled query would suit just fine. Or maybe having a helper method for it.

e.g.
`Tuple<String, List<Variables>> result = bindListToVariables(list);
return customSelect('SELECT * FROM table WHERE id IN ${result.item1}`, variables: result.item2);
