### ISSUE TITLE
Make a tables & DAOs library and use it in my app

### ISSUE THREAD

**Issue by ThomasKliszowski** [simolus3/moor#672]
👋  Hello there!

First of all, I am sorry in advance if my question is not suitable for an issue.
I tried many times to achieve what I am asking for, and it seems the moor architecture can't let me do it.

## What I want

I have a library, which owns her tables and related DAOs. I can't merge the code in my app because this library will be certified and frozen.
I have tests in this library, to ensure that my DAOs are working fine.
I would like to use the library's tables and DAOs in my app database, so I can query the library's tables the same way I do for my own tables, with joins etc.

## Problem

The DAO have a limitation by design, they are binded to a database class.
This prevents me to add the tables and DAOs to my `@UseMoor(...)`.
The only way I found to make it works is to have 2 independant databases, which is not suitable for me because I lose the capability to query across all my tables (app & library).

How would you achieve that? Is this at least possible with the actual moor design?

Thank you folks 🙏

**Comment by simolus3** [comment]
It's a bit tricky, but possible. Let's say `LibraryDatabase` is the database class you use in your library and `AppDatabase` is the database you're using in your main app.

First, you'll need to enable the `generate_connect_constructor` [builder option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/) and use it in both database classes. With that, the code of your main database could look like this:

```dart
@UseMoor(...)
class AppDatabase extends _$AppDatabase {
  final LibraryDatabase lib;

  // schemaVersion and migration omitted
  
  AppDatabase(DatabaseConnection connection): 
    lib = LibraryDatabase(connection),
    super.connect(connection);

  @override
  Future<void> beforeOpen(QueryExecutor executor, OpeningDetails details) async{
    // Open the nested database first, since we might use its tables in our migration step
    await lib.beforeOpen(executor, details);
    // Next, open this database
    await super.beforeOpen(executor, details);
  }
}
```

With this trick, the two databases will share the same connection and stream queries. You can do joins in the `AppDatabase` by doing something like `select(myTable).join([innerJoin(lib.otherTable, ...)])`.

Be aware that this breaks if `AppDatabase` and `LibraryDatabase` both declare a table with the same name, but apart from that it should work. If you previously used a constructor taking a `QueryExecutor`, you can use `DatabaseConnection.fromExecutor` to transform that to a `DatabaseConnection`.

**Comment by ThomasKliszowski** [comment]
Well, that's perfect, and it seems pretty clean to me, thanks a lot Simon, and thank you for your great work on moor!

**Comment by North101** [comment]
Oh, this is interesting!
So in `LibraryDatabase` I could do something like:
```
  @override
  MigrationStrategy get migration => MigrationStrategy(onUpgrade: (migrator, v1, v2) async {
    if (v1 == v2) return;

    // drop all
    await migrator.createAll();
  });
```
?

**Comment by ThomasKliszowski** [comment]
I have done what @simolus3 explained, and you can do that @North101 because this is exactly what the `beforeOpen` part is achieving.

All works as expected, however I have a minor bug.
As far as I understand, the `beforeOpen` is called lazily. The problem is: if my first query is on my `LibraryDatabase`, `LibraryDatabase.beforeOpen` is called (without the override then), and the `AppDatabase.beforeOpen` is **never called**.
I have to make sure that my first query is on `AppDatabase`, which is not ideal.

Do you have an idea on how to make sure that `AppDatabase.beforeOpen` is called @simolus3 ?

Thank you 🙏

**Comment by simolus3** [comment]
Ok, so there are some gotchas with this approach that I didn't consider yesterday.

First, only the main database can trigger schema migrations now. This is because the `schemaVersion` of the database that causes the underlying open will be used to perform migrations. A workaround for this would be to combine the two schema versions (for instance with `get schemaVersion => (ownSchemaVersion << 32) | lib.schemaVersion`) and then extract the right version when calling `lib.beforeOpen` and `super.beforeOpen`. That feels very fragile though. Another approach could be to roll your own mechanism to determine the schema version of a database (for instance with a custom table to store versions per database class - you can query that through the `QueryExecutor` in `beforeOpen`).

>  So in `LibraryDatabase` I could do something like:

If you use a workaround for the migration issue I outlined above, yes. Just be sure not to read from `sqlite_master` to decide which old tables to delete :wink: 

> Do you have an idea on how to make sure that AppDatabase.beforeOpen is called?

You could add a field to the `LibraryDatabase` that points towards the database embedding it:

```dart
class LibraryDatabase extends _$LibraryDatabase {
  GeneratedDatabase parentDb;

  @override
  Future<void> beforeOpen(QueryExecutor executor, OpeningDetails details) {
    if (parentDb != null) {
      return parentDb.beforeOpen(executor, details);
    }
    return super.beforeOpen(executor, details);
  }

  Future<void> openFromParent(QueryExecutor executor, OpeningDetails details) {
    return super.beforeOpen(executor, details);
  }
}
```

Then, `AppDatabase` would set `lib.parentDb = this` in its constructor. Inside `beforeOpen`, it would use `lib.openFromParent(executor, details)`.
