### ISSUE TITLE
Insert Item at position

### ISSUE THREAD

**Issue by nimi0112** [simolus3/moor#673]
## What am I trying to do?

I have a list which is stored in DB and is working good. When ever I update the whole list from the api response it works fine.

Now I want to insert an item at top position in the list locally,

### What I tried ?
```
 final List<Feed> allPostsList = await AppDatabase.getInstance().feedDao.getAllFeeds();
 allPostsList.insert(0, newPost);
 AppDatabase.getInstance().feedDao.insertFeedList(allPostsList, clearPrevious: true);

                                                       or
 AppDatabase.getInstance().feedDao.insertFeed(newPost);
```
## What I expected to happen?
I expected that the item should be updated at 0 position in the list.

## What actually happened
The new item is always inserted at last position in the list. No matter what I try. When ever an object is updated it move to last position. 
For research purposes I even tried 
```
final List<Feed> allPostsList = await AppDatabase.getInstance().feedDao.getAllFeeds();
 allPostsList.[0]= newPost;
 AppDatabase.getInstance().feedDao.insertFeedList(allPostsList, clearPrevious: true);
```
then also item is moved at last position in the list.

**What am I missing or how can I insert item at 0 position in list ?**.

**Comment by simolus3** [comment]
From a programming perspective, sql tables are unordered sets. When you `select(table)` without an `orderBy` clause, the order of rows returned is actually undefined (it just happens to mostly be in insert order).

If you care about a specific order, for instance because you want rows to behave like a list, you'll need to add an explicit column for ordering. For instance, that could look like

```dart
class Items extends Table {
  IntColumn get order => integer().default(const Constant(0))();

  // All the other columns you already have
}
```

Then, inserting an item as the beginning could look like this:

```dart
Future<void> insertAtBegin(Insertable<Item> item) {
  item = item.copyWith(order: Value(0));
  return transaction(() async {
    // Increment all existing "order" columns by 1
    await update(items).write(ItemsCompanion.custom(order: items.order + const Constant(1)));
    await into(items).insert(item);
  });
}
```

If you select items, you need to order them by their `order` column. If you're inserting multiple rows at once, you could keep a counter and increment the `order` for each item.
