### ISSUE TITLE
Add equals/hashCode/toString and toJson/fromJson for custom query result classes

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#676]
I think it would be great if the custom query result classes would have the same `equals/hashCode/toString` and `toJson/fromJson` methods as DataClasses.

**Comment by simolus3** [comment]
I can see the case for `equals`/`hashCode`/`toString`, and you can enable the `override_hash_and_equals_in_result_sets` option to get the first two. I'll probably add the `toString` override to the same option.

I don't understand how json serialization could be useful for result classes though. Can you share a use case you had in mind?

**Comment by kuhnroyal** [comment]
> I can see the case for equals/hashCode/toString, and you can enable the override_hash_and_equals_in_result_sets option to get the first two.

Thanks, didn't think of looking into the options.

Well, I was think of sending some results to an isolate. Mainly because I didn't want to go through the hazzle of configuring a MoorIsolate and having locking problems with the minimal setup.

**Comment by simolus3** [comment]
> especially since I only have a single read (of a custom result set) in the isolate

This should work. The only real problem happens if two databases run their migrations at roughly the same time, since those aren't transactional and can interfere with each other.

> This should never lock the database instance in the main isolate correct?

sqlite3 might do some locking on its own, so there's a small chance of queries failing due to the database being locked. If you enable [Write-Ahead Logging](https://www.sqlite.org/wal.html), reads and writes can happen concurrently.

I think the `toJson` scenario is mostly covered by #615, so I'll close this issue.
