### ISSUE TITLE
Regression Bug: Column with autoIncrement claims not to have a default value 

### ISSUE THREAD

**Issue by jaggernod** [simolus3/moor#721]
Envoronment:

Updated packages:
moor: 2.4.2 => 3.2.0
moor_ffi: 0.4.0 => 0.7.0
moor_generator: 2.3.1 => 3.2.0

Table Definition:
```
@DataClassName('LanguageEntry')
class Languages extends Table {
  IntColumn get id => integer().autoIncrement()();

  TextColumn get name => text().customConstraint('UNIQUE')();

  @override
  Set<Column> get primaryKey => {id, name};
}
```

Reproduction:
Batch inserting `LanguagesCompanion(name: Value(language)))`

Error:
```
Testing started at 11:50 ...
/work/tools/flutter/bin/flutter --no-color test --machine --plain-name "languages are updated" test/acceptance/experimental/dao/users_dao_test.dart
package:moor/src/runtime/data_verification.dart 74:5                  VerificationContext.throwIfInvalid
package:moor/src/runtime/query_builder/statements/insert.dart 197:51  InsertStatement._validateIntegrity
package:moor/src/runtime/query_builder/statements/insert.dart 96:5    InsertStatement.createContext
package:moor/src/runtime/api/batch.dart 45:10                         Batch.insert
package:moor/src/runtime/api/batch.dart 65:7                          Batch.insertAll
package:yapa/persistance/database/dao/users_dao.dart 22:11            UsersDao.insert.<fn>
package:moor/src/runtime/api/query_engine.dart 390:30                 QueryEngine.batch
package:yapa/persistance/database/dao/users_dao.dart 20:11            UsersDao.insert
test/acceptance/experimental/dao/users_dao_test.dart 29:29            main.<fn>

InvalidDataException: Sorry, LanguagesCompanion(id: Value.absent(), name: Value(pl)) cannot be used for that because: 
• id: This value was required, but isn't present
```

After the update of the moor packages and regeneration of *.g.dart files, the test started failing together with other 22 tests that were creating other companion objects. 

Expected Result:
Using companion objects for tables with `autoIncrement()` column should not require those values defined.

**Comment by simolus3** [comment]
Thanks for the report! I think this came up before, but I couldn't find the exact issue.

Basically, you can't use `autoIncrement` and `primaryKey`. To use `autoIncrement`, that column needs to be the sole primary key column. The following sql query fails in sqlite:

```sql
CREATE TABLE IF NOT EXISTS languages (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR UNIQUE,
  PRIMARY KEY (id, name)
);
```

Moor generates the `PRIMARY KEY AUTOINCREMENT` constraint, but it ignores the `PRIMARY KEY (id, name)` in that case.

In moor 3.0.0, the generator started to closer follow sqlite's [definition for this](https://www.sqlite.org/lang_createtable.html#rowid), which describes it as: "if a rowid table has a primary key that consists of a single column and the declared type of that column is "INTEGER" in any mixture of upper and lower case, then the column becomes an alias for the rowid".  So in this case, the generator decides that `id` is not an alias for the rowid because of the other primary key.

Of course, using both `primaryKey` and `autoIncrement()` should not be allowed in Dart either. I've changed the generator to emit a warning in that case. Since both your `name` and `id` are unique on their own, I think you can just remove the `PRIMARY KEY` override.

**Comment by jaggernod** [comment]
Thanks a lot for the detailed answer @simolus3.
