### ISSUE TITLE
CI/CD failing with: Invalid plugin specification moor_ffi

### ISSUE THREAD

**Issue by NightOwlCoder** [simolus3/moor#727]
My app's CI/CD has been working for over 6 months, today I got below on `master` branch:

```
Running "flutter pub get" in s...                                  24.0s
Invalid plugin specification moor_ffi.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
```

Did we have any breaking change I'm not aware?

**Comment by NightOwlCoder** [comment]
I got "unblocked" by checkout out yesterday's code:

`git checkout adc9dde3ba8563eebb824feb689f95eb947ab745`

So probably something added to day broke the build.

**Comment by gouravd** [comment]
Upgraded to Flutter version 1.21.0-2.0.pre.114 and its failing with same error

**Comment by gouravd** [comment]
Something's missing in the plugin pubsec.yaml because the pub.dev for moor_ffi does not show platforms either

**Comment by gouravd** [comment]
I downgraded Flutter and confirm its working.. so some sort of incompatibilty with latest flutter version

**Comment by simolus3** [comment]
This is an unfortunate situation moor can't do too much about:

- `moor_ffi` can't depend on Flutter since it's a pure Dart package that needs to work without Flutter
- When using the new `flutter.plugins.platforms` key, pub forbids uploads without adding an explicit dependency on Flutter

The solution is to phase out the `moor_ffi` package in favor of a better setup, see #691. If you want to support the latest `master` version of Flutter, you can do this:

- add a dependency on the new `sqlite3_flutter_libs` package
- drop the `moor_ffi` dependency and replace imports with the new `package:moor/ffi.dart` library

You'll also need to use the latest development version of moor:

```yaml
dependency_overrides:
  moor:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: moor
```

Please let me know if you run into any issues with this approach, thanks!

**Comment by cyanglaz** [comment]
@simolus3 @NightOwlCoder This is pubspec I've got for the moor_ffi plugin when I fetch the plugin from pub.
```
https://github.com/simolus3/moor/blame/2332c58742ec0de304385548e4900878643f8b29/moor_ffi/pubspec.yaml#L24-L28
```

I think removing the plugin section in the pubspec will solve the issue.

**Comment by NightOwlCoder** [comment]
@simolus3 your suggestion worked fine.
CI/CD successful, and so far I can detect any issue with the app itself.

**Comment by jims57** [comment]
I come over from [this issue](https://github.com/simolus3/moor/issues/725#issuecomment-662943325).
@simolus3  When will this be fixed?

**Comment by simolus3** [comment]
This will be fixed in the next moor version. You can also take a look at the migration guide from [this comment](https://github.com/simolus3/moor/issues/727#issuecomment-662935493) to use this now.

**Comment by jims57** [comment]
> This will be fixed in the next moor version. You can also take a look at the migration guide from [this comment](https://github.com/simolus3/moor/issues/727#issuecomment-662935493) to use this now.

I am looking forward to your updates, please let me know when all done. Thx.

**Comment by z85510** [comment]
I hope you would fix it ASAP, Thanks 🙏🏽

**Comment by IanDarwin** [comment]
@simolus3 Your July 23 comment above got me back on the air, hence closing #733. Thanks.

**Comment by simolus3** [comment]
I just published `moor` version 3.3.0 and `moor_ffi` version 0.8.0.

You can upgrade `moor_ffi` to fix this problem now, but I recommend migrating to the new `package:moor/ffi.dart` library. With `moor` 3.3.0, you can remove the `dependency_override`. The changelog of `moor_ffi` contains more information on this, but feel free to open an issue if you run into problems when upgrading.

**Comment by jims57** [comment]
@simolus3 This bug is fixed, thanks.

**Comment by mikealphakilo** [comment]
problem when upgrading:

Because no versions of moor_generator match >2.4.0 <3.0.0 and moor_generator 2.4.0 depends on moor ^2.3.0, moor_generator ^2.4.0 requires moor ^2.3.0.

So, because my_app depends on both moor ^3.3.0 and moor_generator ^2.4.0, version solving failed.
pub get failed (1; So, because my_app depends on both moor ^3.3.0 and moor_generator ^2.4.0, version solving failed.)
exit code 1

**Comment by simolus3** [comment]
Both of these versions are pretty old. Could you try depending on `moor: ^4.0.0` and `moor_generator: ^4.0.0`?

**Comment by mikealphakilo** [comment]
can i try flutter upgrade in my pubspec? to upgrade all moor dependencies

**Comment by simolus3** [comment]
`flutter upgrade` will upgrade to the latest dependency that's compatible with what you have in your pubspec. If you write `^2.4.0`, you say that you want a version of `moor_generator` between `2.4.0` and `3.0.0` (exclusive). So `flutter pub upgrade` alone would not give you the latest version. You could run `flutter pub upgrade  --major-versions ` to just upgrade everything.

**Comment by mikealphakilo** [comment]
Oh, thanks for the information.
