### ISSUE TITLE
A column with autoIncrement() gets @required annotation

### ISSUE THREAD

**Issue by majdi21** [simolus3/moor#743]
Hello,

   When a column is created like this:

IntColumn get id => integer().autoIncrement()();

   The generated class would have @required annotation on that attribute in the constructor.

   I don't think such an attribute should be required because autoIncrement implies that the database will just generate the proper value.

Regards

**Comment by simolus3** [comment]
This is actually by design: A generated data class is designed to hold a full row as it would appear in the database. As soon as a row is inserted, it will have an `id`, which is why we mark it as required.
To represent partial rows (which is useful for inserts or updates), you can use a generated companion class. This might sound a bit complicated at first, but there are several reasons for this:
- For updates, `null` could have multiple meanings: To explicitly set the column to `NULL`, or to leave it unchanged. With companions, we use `Value(null)` and `Value.absent()`, respectively. This makes the distinction very clear.
- In a future Dart version, we'll have to explicitly mark fields if they're allowed to store `null`. We'd have to do that for `id` here, but that makes the class annoying to use when reading from the database, since it can't be `null` in those situations.

The [documentation on updates](https://moor.simonbinder.eu/docs/getting-started/writing_queries/#updates-and-deletes) also explains this. For inserts, I would use the `Companion.insert` constructor - it uses `@required` only for the columns that are actually required for an insert. Let me know if you have more questions on this!
