### ISSUE TITLE
Calculating basic statistics using moor

### ISSUE THREAD

**Issue by suha-glal** [simolus3/moor#745]
I am using the below function to get the summary of the last journey 

```dart
 Stream <LastJourneyDetails>lastJourneySummary(){

final query = selectOnly(journeys).join([
  innerJoin(
    routePoints,
    routePoints.journeyId.equalsExp(journeys.journeyId),
    useColumns: false,
  )
])
  ..groupBy([routePoints.journeyId]);

   final journeyIdE=journeys.journeyId;

    final startTimelast = journeys.startTime;
    final endTimelast = journeys.endTime;
    final  LatitudeStartE= journeys.latitudeStart;
    final longitudeStartE= journeys.longitudeStart;
    final  LatitudeEndE= journeys.latitudeEnd;
    final longitudeEndE= journeys.longitudeEnd;
    final avgSpeedlast = routePoints.speed.avg(); //in km/hr
    final avgRisklast = routePoints.riskPoint.avg();
    final totalDistancelast =routePoints.odometer.sum(); // in meters

    query
      .addColumns([
        journeyIdE,
        startTimelast,
        endTimelast,
        totalDistancelast,
        LatitudeStartE,
        longitudeStartE,
        LatitudeEndE,
        longitudeEndE,
        avgRisklast,
        avgSpeedlast
      ]);


    return query.watch().map((row) {

       return LastJourneyDetails(
          startTime: row.last.read(startTimelast),
          endTime: row.last.read(endTimelast),
          distance: row.last.read(totalDistancelast) / 1000, //in KM
          avgSpeed: row.last.read(avgSpeedlast) * 3.6, //in km/hr
          safety: 10 - row.last.read(avgRisklast), // safety =10-risk
          latitudeStart:row.last.read(LatitudeStartE),
          longitudeStart:row.last.read(longitudeStartE),
          latitudeEnd: row.last.read( LatitudeEndE),
          longitudeEnd:row.last.read(longitudeEndE),
        );

      });


  }

```

I have three questions...
1. Is the above code correct ?...is it the right way to use moor to get the above details or there is a better shorter way to do that ....for example, I don't think 'join' is necessary since summarizing statistics I need can exist in each table separately but I tried to do it without join and it did not work
2. How can I calculate new statistics using moor....specifically the median, mode, std,.....etc?
Is it possible to do something like below using moor

```dart
 final medianSpeedlast = routePoints.speed.median(); 
 final modeSpeedlast = routePoints.speed.mode(); 
```

3. If this feature is not available in moor currently how can I get these statistics using moor syntax?

Finally thanks a lot for your amazing plugin and your amazing effort to keep it up-to-date and thank you very much for answering all my questions promptly.

**Comment by simolus3** [comment]
From a quick look, your code looks correct to me.

> I don't think 'join' is necessary since summarizing statistics

You're summarizing statistics of `routePoints` though (via `avgSpeedlast`, `avgRisklast`, `totalDistancelast`). For it to be available, you need to join that table. The `groupBy` is necessary since you want to take stats for each journey independently.

> How can I calculate new statistics using moor....specifically the median, mode, std,.....etc?

You can do that, but it requires some special setup which I'll share below. Alternatively, you could also load the `routePoints` in Dart and just use them. That might be more efficient if you're calculating multiple values at once.

To do this, you need to use `moor` version `3.3.0` or later. You also need to migrate from `package:moor_ffi` to `package:moor/ffi`, as described [here](https://pub.dev/packages/moor_ffi).
Since sqlite3 doesn't have a builtin implementation for most statistical functions, you'll need to write them yourself. For example, an implementation for `MEDIAN` could look like this:

```dart
class _MedianSqlFunction implements AggregateFunction<List<double>> {
  const _MedianSqlFunction();
  
  @override
  AggregateContext<List<double>> createContext() {
    // Initial state: Empty list
    return AggregateContext([]);
  }

  @override
  void step(List<Object> arguments, AggregateContext<List<double>> context) {
    // Processing a new row: Add its value to the list
    assert(arguments.length == 1);

    final value = arguments[0];
    if (value is num) {
      context.value.add(value.toDouble());
    }
  }

  @override
  Object finalize(AggregateContext<List<double>> context) {
    final value = context.value..sort();

    if (value.isEmpty) {
      // Can't compute the median of an empty function, so return null
      return null;
    }

    // You might want to use a different implementation that takes an average if the list has an odd length
    return value[value.length ~/ 2];
  }
}
```

Next, you'll register that custom function when the database is opened. For this, you can use the new `setup` parameter on `VmDatabase`:

```dart
VmDatabase(yourDatabaseFile, setup: (db) {
  db.createAggregateFunction(
    functionName: 'MEDIAN',
    function: const _MedianSqlFunction(),
    argumentCount: const AllowedArgumentCount(1),
  );
});
```

For convenience, you can define an extension method to use your function from moor:

```dart
extension AdvancedStats on Expression<num> {
  Expression<double> median() {
    return FunctionCallExpression('MEDIAN', [this]);
  }
}
```

This allows you to write `routePoints.speed.median()` to get the median speed, for instance.

In a similar fashion, you could implement the other functions that you were interested in:

- stddev: Also as a `AggregateFunction<List<double>>`, just change `finalize` to compute the standard deviation instead
- mode: You could implement this as a `AggregateFunction<Map<int, int>>`, mapping from values to how often they appeared. `createContext` initializes the context to an empty map. `step` increments `map[value]`, `finalize` selects the highest value.

**Comment by suha-glal** [comment]
Thanks alot

**Comment by suha-glal** [comment]
Just like you said since I am calculating multiple values at once it is better to load `routPoints` to Dart.
Moor has been very efficient in most of the use cases and I thought there is an efficient way to perform this task but I am not aware of it.

Nevertheless, it was nice to know how it could be done if I need to do it using moor syntax.
