### ISSUE TITLE
[Suggestion] Allow .moor predicates to be optional/null

### ISSUE THREAD

**Issue by North101** [simolus3/moor#753]
I'll have e.g.
```
listThing:
SELECT *
FROM thing
WHERE $predicate
```
and i'll sometimes i'll want everything and sometimes i'll want to filter it. At the moment I need to do something like this for when I want everything:
```
db.listThing(CustomExpression('1 = 1')).watch()
```

If `$predicate` is `null` it'd be nice if it automatically did that. With NNBD coming it might be better to do something like:
```
listThing:
SELECT *
FROM thing
WHERE $predicate?
```

**Comment by simolus3** [comment]
Instead of `CustomExpression`, you could also use

```dart
const sqlTrue = Constant(true);

db.listThing(sqlTrue).watch()
```

That's a bit more convenient, but I agree that moor should have some builtin mechanism to make this easier.

One issue that I have with nullable parameters is that the default value is not obvious. For instance, I think it's not unreasonable to assume that a null `$predicate` would generate `NULL` in sql. Those `$templates` can also be used outside of a boolean context, where the default value might be less obvious. They don't even have to be expressions (they can be ordering terms, order by clauses and limits too).
Maybe we can introduce a mechanism to provide the default value in the query, for instance

```sql
listThing ($predicate OR TRUE): SELECT * FROM thing WHERE $predicate
```

This would make the `predicate` parameter nullable and use the provided default value otherwise. This would also work for non-boolean parameters. The additional syntax is a bit annoying of course, but I think it's necessary to remove ambiguity.

**Comment by North101** [comment]
Thanks for the reply, I agree on all your points.

Instead of `OR` maybe it should be `=` to more closely look like dart.
```
listThing ($predicate = TRUE): SELECT * FROM thing WHERE $predicate;
```

**Comment by simolus3** [comment]
This should now work on the `develop` branch!
