### ISSUE TITLE
Getting error WARNING (moor): It looks like you've created the database classAppDatabase multiple times Please help

### ISSUE THREAD

**Issue by PercyMcfly** [simolus3/moor#759]
Hello, we are Trying to find a way to fig the problem with this error. 

`flutter: WARNING (moor): It looks like you've created the database classAppDatabase multiple times. When these two databases use the same QueryExecutor, race conditions will ocur and might corrupt the database. 
Try to follow the advice at https://moor.simonbinder.eu/faq/#using-the-database or, if you know what you're doing, set moorRuntimeOptions.dontWarnAboutMultipleDatabases = true
Here is the stacktrace from when the database was opened a second time:
#0      GeneratedDatabase._handleInstantiated (package:moor/src/runtime/api/db_base.dart:90:30)
#1      new GeneratedDatabase.connect (package:moor/src/runtime/api/db_base.dart:69:12)
#2      new _$AppDatabase.connect (package:system_wall/classes/localdata/SQL.g.dart:8261:55)
#3      new AppDatabase.connect (package:system_wall/classes/localdata/SQL.dart:94:62)
#4      _backgroundConnection.<anonymous closure> (package:system_wall/classes/localdata/SQL.dart:75:42)
<asynchronous suspension>
#5      _backgroundConnection.<anonymous closure> (package:system_wall/classes/localdata/SQL.dart)
#6      LazyDatabase._awaitOpened (package:moor/src/utils/lazy_database.dart:30:26)
#7      LazyDatabase.ensureOpen (package:moor/src/utils/lazy_database.dart:43:12)
`
We are using Kiwi in the newest version.
We also use moor_ffi and Moor un the newest version

The Kiwi code:

`
void main() {
  KiwiContainer kiwi = KiwiContainer();
  kiwi.registerSingleton((container) => AppDatabase());
  runApp(MyApp());
} 
`

Our only Call of the Kiwi for now 

`static KiwiContainer kiwi = KiwiContainer();
static AppDatabase database = kiwi.resolve<AppDatabase>();`

Our Database Constructor

`class AppDatabase extends _$AppDatabase {
  //static final AppDatabase instance = AppDatabase();

  AppDatabase() : super(LazyDatabase(() async {
    MoorIsolate isolate = await _createMoorIsolate();
    DatabaseConnection isolatedConnection = await isolate.connect();
    final isolatedDatabase = AppDatabase.connect(isolatedConnection);
    return isolatedDatabase.executor;
  }));

  @override
  int get schemaVersion => 15;

  //neu für isolate
  AppDatabase.connect(DatabaseConnection connection) : super.connect(connection);
....
}`

we copy pasted the _createMoorIsolate from this website

https://moor.simonbinder.eu/docs/advanced-features/isolates/

I hope you can help us

**Comment by simolus3** [comment]
Sure! In your case, the problem is that the constructor of `AppDatabase` creates a second `AppDatabase` (through the `connect` constructor).

Unfortunately in this case, there's no way to synchronously connect to an isolate, so you'd have to make it a `Future`:

```dart
static Future<AppDatabase> create() async {
  MoorIsolate isolate = await _createMoorIsolate();
  DatabaseConnection isolatedConnection = await isolate.connect();

  return AppDatabase.connect(isolatedConnection);
}
```

But thanks to this issue, I had the idea for `DatabaseConnection.delayed` that will be available in the next moor version. Then, you'll be able to use:

```dart
factory AppDatabase() {
  return AppDatabase.connect(DatabaseConnection.delayed(Future(() async {
    MoorIsolate isolate = await _createMoorIsolate();
    return isolate.connect();
  })));
}
```

This allows you to construct the `AppDatabase` synchronously while using a background connection.

--------

If you only use the `AppDatabase` on one isolate (which, judging by the code you posted, you do), you can just do this now:

```dart
factory AppDatabase() {
  final executor = LazyDatabase(() async {
    MoorIsolate isolate = await _createMoorIsolate();
    DatabaseConnection connection = await isolate.connect();
    return connection.executor;
  });

  return AppDatabase.connect(DatabaseConnection.fromExecutor(executor));
}
```

You could also skip the `connect` constructor and just use `AppDatabase(executor)` like you would regularly. In this approach, stream queries won't work across databases on different isolates. If you only use the database on a single isolate, this is not a problem at all.

I hope that helps, let me know if need anything more!
