### ISSUE TITLE
Use two database files

### ISSUE THREAD

**Issue by jamontes79** [simolus3/moor#765]
Hi, 

Thanks for this great package.

My question is because I have an old android application (without any sql helper) and now I'm migrating it to flutter user moor and I want to restructure the old database in new tables with new structure and migrate the current data in the new database.

I'm not sure how to deal with it and I don't find any solution neither in documents neither in internet, and maybe you can help me giving me some idea.

Thanks a lot in advance.
Best regards

**Comment by simolus3** [comment]
You can open the old database by using the [sqflite](https://pub.dev/packages/sqflite) or [sqlite3](https://pub.dev/packages/sqlite3) packages. I recommend the former if you're using `moor_flutter` and the latter if you're using `moor/ffi`.
This would allow you to read the old data using raw sql queries, transform them as necessary and then store them in the new database. Finally, you could delete the old database.

There isn't much information on this since this process is highly specific to your application, but that should outline the general idea.

**Comment by jamontes79** [comment]
Thanks a lot for your quickly answer.

It's very usefull for me.
