### ISSUE TITLE
Transaction does not wait to refresh the database and call watchers

### ISSUE THREAD

**Issue by mikededo** [simolus3/moor#787]
Hello!

I have the following code:
```dart
Future addNewWorkoutWithExercices(WorkoutWithExercices entry) {
  return transaction(() async {
    int workoutId = await into(db.workouts).insert(entry.workout);

    // All exercices are existent
    for (ExerciseWithTags ex in entry.exercices.keys) {
      await into(db.workoutExercices).insert(
        WorkoutExercise(
          workout: workoutId,
          exercise: ex.exercise.id,
        ),
      );

      for (ExerciseSet es in entry.exercices[ex]) {
        await into(db.exerciseSets).insert(
          ExerciseSet.fromJson(es.toJson()),
        );
      }
    }
  });
}
```

As you can see, I'm creating a transaction so the changes are not seen in the database until it has finished (I guess I understood correctly what they are suposed to be used for). However, the `Stream` that watches the `Workouts` table, in this case (the one where I do the first insert) gets called immediately after the insert is done. This throws an exception where that `Stream` is built since it does not have any `Exercise` linked to it (when usin `Rx.combineLatest`).  

Am I using the transaction properly or am I missing something?

**Comment by simolus3** [comment]
Moor batches up writes that occurred inside a `transaction` block and then dispatches them when it completes. We also have a test for this, so I'm pretty confident that it's working as intended: https://github.com/simolus3/moor/blob/5cbc331ddaf7a3031d98a905c2e05080d9fbb2c8/moor/test/transactions_test.dart#L147-L161

There's a slightly different behavior when creating streams inside the `transaction` block: Those see the changes made in the transaction and update before it has completed. It looks like you're not doing that though.

>This throws an exception where that `Stream` is built since it does not have any `Exercise` linked to it (when usin `Rx.combineLatest`).

I think I have a possible explanation: The two streams don't update at exactly the same time. So they both update after the transaction completes, but there's a small frame where the latest value of the streams is inconsistent? I think you'd probably have to guard against that, return `null` in `combineLatest` and then add a `.where((e) => e != null)` afterwards.

Moor could add some logic to first run queries on all streams and then update them all in the same microtask. This might solve the problem, but I'm a bit reluctant to add that feature since it adds a lot of additional complexity (and streams in moor are complicated enough already). And since stream values aren't guaranteed to dispatch updates synchronously, so we'd still have the same problem when combining more complex streams (e.g `combineLatest(someMoorStream(), anotherMoorStream().asyncMap(...))`

**Comment by mikededo** [comment]
So I should catch the exception on the first stream and after the second stream is called in `combineLatest`  it will work properly.  
Thanks for the point, I'll give it a try.

**Comment by mikededo** [comment]
>The two streams don't update at exactly the same time. So they both update after the transaction completes, but there's a small frame where the latest value of the streams is inconsistent?  

Definetely what was causing the error. After the other items are inserted, the `combineLatest` gets called again with the new data and it works perfectly. I only had to add an if statement.

Much appreciated :smile:

**Comment by DennisMuchiri** [comment]
@mikededo please share what you did here. I have a problem where my stream does not fire after a batch transactionhas inserted data.
`Future insertAllStoredfsdbosCompanion(
    List<StoredfsdbosCompanion> storedfsdbosCompanionList,
  ) async {
    return await batch((b) {
       b.insertAll(
        storedfsdbos,
        storedfsdbosCompanionList,
      );
    });
  }`

**Comment by simolus3** [comment]
What is the problem here exactly? The streams don't fire after `insertAllStoredfsdbosCompanion`, but only if `deleteCacheDatabaseData` was called immediately before that?

**Comment by DennisMuchiri** [comment]
@simolus3 Yes. It does not fire after batch insert.

**Comment by DennisMuchiri** [comment]
@simolus3 moved the issue here for more visibility

https://github.com/simolus3/drift/issues/1906
