### ISSUE TITLE
[QUESTION] - Error on lookup method

### ISSUE THREAD

**Issue by brenoasm** [simolus3/moor#791]
Hi, I've migrated to use sqlite3_flutter_libs and since then everytime I restart my app I get this error, which does not closes the app or something like that. What is this error and can I do something to resolve it?

<img width="1440" alt="Captura de Tela 2020-08-31 às 17 08 40" src="https://user-images.githubusercontent.com/25211056/91763988-e198a100-ebac-11ea-8b2d-513c75d994b5.png">

I've found that maybe is a problem with settings.graddle, but mine is the same as the one marked as "right".

Thanks in advance.

**Comment by simolus3** [comment]
We try to lookup a function that might not exist (`sqlite3_prepare_v3`). If that throws an error, we fallback to another function (`sqlite3_prepare_v2`). Catching an error is a bad practice, we no longer do this with `sqlite3: ^0.1.5`.

You see this exception because you have "All Exceptions" checked, it shouldn't show up with "Uncaught Exceptions" only. But you can also run `flutter pub upgrade` or add an explicit dependency on `sqlite3: ^0.1.5` to fix this problem.
