### ISSUE TITLE
withDefault value and partial updates

### ISSUE THREAD

**Issue by PascalSenn** [simolus3/moor#819]
I ran into an issue with partial updates. 
What i wanted to do is creating a companion of a entity and then apply the provided values with `copyWith`. The idea is that only one method is required to update a database entity. 

```dart
  Future<bool> updateWith({
    Value<String> title = const Value.absent(),
    Value<String> situationDescription = const Value.absent(), 
  }) {
    var companion = new IdeCompanion().copyWith(
        title: title, 
        situationDescription: situationDescription);
    return _dao.updateEntry(companion);
  }
```

The issue is as soon as a default value is applied to the column it is automatically being applied to the update statement 
https://github.com/simolus3/moor/blob/master/moor/lib/src/runtime/query_builder/statements/update.dart#L122-L128

I am not sure if this is intended behaviour or i understand something wrong :) 

While working with streams it is not guaranteed to have a representation that is up to date. So a partial update would be the way to go, but only if the values are not set to default

**Comment by simolus3** [comment]
The intended behavior of `replace` is to, well, replace a row. So semantically, it should behave very similar to `insert`, except that it also removes an existing row. This includes applying default values.

In your scenario, it sounds like you're only trying to update an existing row? I don't understand what's preventing you from simply using `update` instead of `replace`. If you want to do an insert with default values, but fall back to a simple update (without defaults) when the row exists already, you could use `into(table).insert(companion, onConflict: DoUpdate((_) => companion))`

**Comment by PascalSenn** [comment]
never mind, it was late 
i probably just was beeing stupid. 
thanks for the headsup ;)

**Comment by KokeCacao** [comment]
> onConflict: DoUpdate((_) => companion)

Hi. The system sqlite on the phone is old and therefore it doesn't support "DoUpdate((_) => companion)", is there a workaround?

**Comment by simolus3** [comment]
You could consider using a `VmDatabase` with the `sqlite3_flutter_libs` package to ship the latest sqlite3 version with your app.

You could also split the query into a select (to check whether a row needs to be replaced) and then use an insert or an update depending on that result.
