### ISSUE TITLE
Tables can't override primaryKey and use autoIncrement()

### ISSUE THREAD

**Issue by raedinkhaled** [simolus3/moor#832]
Hello,

I'm getting this error: 

`There were some errors while running moor_generator on package:graduation/data/moor_database.dart:
[INFO] moor_generator:moor_generator on lib/data/moor_database.dart:line 32, column 7 of package:graduation/data/moor_database.dart: Tables can't override primaryKey and use autoIncrement()
   ╷
32 │ class Doses extends Table {
   │       ^^^^^
   ╵`

here is my code: 

```
class Doses extends Table {
  IntColumn get doseID => integer().autoIncrement()();
  IntColumn get patientid =>
      integer().customConstraint('REFERENCES patients(patientID)')();
  IntColumn get medicid =>
      integer().customConstraint('REFERENCES medics(medicID)')();
  IntColumn get posolgie => integer()();
  DateTimeColumn get date => dateTime()();
  @override
  Set<Column> get primaryKey => {doseID,patientid, medicid};
}
```

I really need the doseID Coulumn to be autoIncremented and at the same time I need the patientid and medicid to be primary keys because they are foreign keys

**Comment by simolus3** [comment]
The `AUTOINCREMENT` keyword would be ignored by sqlite if that column wasn't the sole primary key, which is why moor forbids this too.

> primary keys because they are foreign keys

I don't understand why they would have to be part of the primary key of `Doses`. `medicID` should be the primary key of `medics` and `patientID` the primary key of `patients` since you're referencing them. But I don't think they need to be in the primary key of `Doses` too, especially since `doseID` alone uniquely identifies a row.

**Comment by simolus3** [comment]
I'm closing this since the current behavior appears to be correct and unlikely to change. Let me know if you need more help with the primary key.
