### ISSUE TITLE
update date with trigger

### ISSUE THREAD

**Issue by callawey** [simolus3/moor#857]
how can we achieve auto updating "creation date" and "update date" fields with triggers inside moor file ? i want and automatic update on those fields when insert or update happens on a table but have no idea how to pass miliseconds data to trigger.

Can we have a sample for it if its possible ? i am sure this will help a lot of people

**Comment by simolus3** [comment]
If you use a `DATETIME` (or `dateTime()` in Dart) column, moor will only store seconds internally. This is because all date and time functions in sqlite operate on a per-second accuracy. If that works for you, you could just set the `updatedAt` column to `CURRENT_TIMESTAMP` in a trigger.

At the moment, there's no way to obtain the current time with a millisecond accuracy in SQL. However, moor could provide a custom function for that. Let me know if you need such function, I can add it and mention it in the documentation.

**Comment by callawey** [comment]
Yes, if you could add such a function with a sample, i will be glad, thanks in advence

**Comment by callawey** [comment]
By the way, i think i found a way to provide miliseconds since epoch like below. This gives correct value

`strftime('%s','now') || substr(strftime('%f','now'), 4)`

```
CREATE TRIGGER TAU_ORDERS AFTER INSERT ON "Orders" BEGIN
  UPDATE "Orders" SET CREATED_AT = strftime('%s','now') || substr(strftime('%f','now'), 4) WHERE _ID = new._ID;
END;
```

**Comment by simolus3** [comment]
Your approach should work (although I'd probably cast the result into an int to be sure). In the next moor version, you'll also be able to do

```sql
CREATE TRIGGER TAU_ORDERS AFTER INSERT ON "Orders" BEGIN
  UPDATE "Orders" SET CREATED_AT = current_time_millis() WHERE _ID = new._ID;
END;

```
