### ISSUE TITLE
Bug: Why moor fails to get the right rows based on today

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#871]
![image](https://user-images.githubusercontent.com/1920873/95854513-a67fb500-0d89-11eb-8c7a-a5b661170718.png)

**Comment by simolus3** [comment]
This is probably caused by timezones - see also https://github.com/simolus3/moor/issues/286. Depending on which queries you use, you could store dates with a custom typeconverter using `DateTime.toIso8601String()` and `DateTime.parse()`:

```dart
class FormattedDateTimes extends TypeConverter<DateTime, String> {
  const FormattedDateTimes();

  @override
  DateTime mapToDart(String fromDb) {
    if (fromDb == null) return null;

    return DateTime.parse(fromDb);
  }

  @override
  String mapToSql(DateTime value) => value?.toIso8601String();
}
```

You can then replace usages of `dateTime` in your table definitions by using `text().map(const FormattedDateTimes())`.

In your query, you could then use `n.nextReviewTime.like('2020-10-13%')`

**Comment by jims57** [comment]
@simolus3 I have another question about this. If I replace it into `n.nextReviewTime.like('2020-10-13%')`, will it affect the performance of the query, compared with the old one? 

> This is probably caused by timezones - see also #286. Depending on which queries you use, you could store dates with a custom typeconverter using `DateTime.toIso8601String()` and `DateTime.parse()`:
> 
> ```dart
> class FormattedDateTimes extends TypeConverter<DateTime, String> {
>   const FormattedDateTimes();
> 
>   @override
>   DateTime mapToDart(String fromDb) {
>     if (fromDb == null) return null;
> 
>     return DateTime.parse(fromDb);
>   }
> 
>   @override
>   String mapToSql(DateTime value) => value?.toIso8601String();
> }
> ```
> 
> You can then replace usages of `dateTime` in your table definitions by using `text().map(const FormattedDateTimes())`.
> 
> In your query, you could then use `n.nextReviewTime.like('2020-10-13%')`

**Comment by simolus3** [comment]
No, it should have a similar performance, as both queries require a full table scan.
