### ISSUE TITLE
[Question] Can this project use `TEXT` instead of `VARCHAR`?

### ISSUE THREAD

**Issue by sudhanshu16** [simolus3/moor#886]
I am working on a project in which we need to read the same database file from native side (both ios and android). We use Room for this purpose in android and it reads `String` as `TEXT` and cannot read `VARCHAR` at all. 
I changed [this variable](https://github.com/simolus3/moor/blob/master/moor/lib/src/runtime/query_builder/schema/columns.dart#L166)'s value to `"TEXT"` and everything worked as expected. In my case nothing actually broke. 

Also, it seems that `VARCHAR` isn't a valid [data type](https://www.sqlite.org/datatype3.html) in sqlite3, it gets converted to `TEXT` and length provided is ignored.

Is there any particular reason why this project doesn't use `TEXT`? Can we use `TEXT` instead of `VARCHAR`?

PS: I understand many existing projects will probably break if the type is changed. Can we avoid this by any chance?

**Comment by simolus3** [comment]
Since `VARCHAR` and `TEXT` both resolve to the same type in sqlite, I don't think changing the type in moor would break anything. 

Changing the type to `TEXT` sounds reasonable since that's what one would normally use in sqlite. I'll focus on releasing moor 3.4 first, but we can have this eventually :+1:
