### ISSUE TITLE
How to write `UpdateCompanion` for `update table set columnA = 'newValue' where columnB = 'condition'`

### ISSUE THREAD

**Issue by jerryzhoujw** [simolus3/moor#91]
## Requirement
How to write `UpdateCompanion` for `update table set columnA = 'newValue' where columnB = 'condition'`

## replace()
I know how to use `update(tableA).replace(UpdateCompanionData)`  which only **`update all column`**, and update `default column` with `default value`.

But my requirement is to `update specific column`, and **`keep other columns not change`**.

## where()?
With `update(tableA).write(UpdateCompanionData).where?`, I couldn't found how to write this `where(Expression<bool, BoolType> Function(T) filter)` condition.

I know solution to write sql directly or write **all column** values in `UpdateCompanion`, but not good.

**Comment by simolus3** [comment]
Thanks for the issue. You can use `.where` on updates just like you would use it on select statements. To only write individual columns, use `write` instead of `replace` - it will leave all fields of the companion which are absent untouched. So this:
```dart
await (update(table)
     ..where((row) => row.columnB.equals('condition'))
  ).write(SomeCompanion(columnA: Value('new value')))
```
should work for you. Let me know if you run into any problems, thanks!
