### ISSUE TITLE
Feature request: "async: false"

### ISSUE THREAD

**Issue by willhaslett** [simolus3/moor#935]
It would _so_ simplify my life if Moor queries took an optional `async` parameter that defaults to `true` (current behavior), returning `<Thing>` rather than `<Future<Thing>>` when `async` is `false`.

It's of course sensible to have database queries be non-blocking by default for the sake of UX, but my particular application has a somewhat complex on-device SQLite database, and I simply need to perform many operations synchronously (e.g. a large database seeding operation when the db is created).

What I have now works, but it's an `await` jungle that could be _so_ clean if I could just flag calls as `async: false`. Would this be straightforward to implement?

**Comment by davidmartos96** [comment]
@willhaslett Wouldn't the jungle of awaits turn into a jungle of `async: false`?
I think the purpose of the Future API is that the user should be aware that the call is not synchronous and it may take some time.
If you really really want synchronous database operations you can take a look at the `sqlite3` packages, which is essentially a wrapper of the native Sqlite library. It's used under the hood by moor. It will not be as high level as moor though.
On top of that, on a Flutter at least, you may not want database queries running synchronous because that could possibly make the UI interaction laggy.

**Comment by kuhnroyal** [comment]
I am using a lot of `await Future.wait([...])` for seeding, updates etc. to reduce the overhead and not await everything by itself.

**Comment by simolus3** [comment]
> Would this be straightforward to implement?

No, sorry. Almost everything would have to be changed. Even worse, asynchronous and synchronous apis don't really mix, so we'd essentially end up with two implementations and twice the work for me. Most of moor's internal code is async too.

If you want to do chunks of work synchronously, you could also do that in a batch or use the approach Peter suggested.

**Comment by willhaslett** [comment]
Thank you all for the useful feedback!
