### ISSUE TITLE
To what extent does customConstraint override other constraints?

### ISSUE THREAD

**Issue by cervonwong** [simolus3/moor#949]
Hi, loving this package so far,

I was wondering how I would write my getter if I want an `id` column to be non-nullable and unique and is a primary key but not autoincrementing.

This is how I am currently doing it.
```
IntColumn get id => integer().customConstraint('UNIQUE')(); 

@override
Set<Column> get primaryKey => {id};
```
1. Do I need to specify `customConstraint('UNIQUE')` if the column is a primary key?
2. If so, do I need to specify `customConstraint('NOT NULL UNIQUE')`?

If I want another column `code` which has a withLength constraint and is unique, do I do this?
```
TextColumn get code => text().withLength(min: 6, max: 7).customConstraint('UNIQUE')();
```
Do I need to add something more into `customConstraint()` if it overrides `withLength()`?

Thanks for the prompt replies :D

**Comment by simolus3** [comment]
> Do I need to specify `customConstraint('UNIQUE')` if the column is a primary key?

Quoting [sqlite's documentation](https://sqlite.org/lang_createtable.html):

> Each row in a table with a primary key must have a unique combination of values in its primary key columns. For the purposes of determining the uniqueness of primary key values, NULL values are considered distinct from all other values, including other NULLs. If an INSERT or UPDATE statement attempts to modify the table content so that two or more rows have identical primary key values, that is a constraint violation. 

So I think you don't need the additional unique constraint. Unique constraints have the same behavior regarding `NULL`s, so they're not of much help here. If you specify a `customConstraint` and want the column to be non-nullable, you'll have to include `NOT NULL` in the custom constraint though!

Note that, if you have a single-column primary key AND that column is an integer, sqlite uses an optimized implementation where that columns is called a "rowid". This usually makes queries faster, but note that sqlite will also pick defaults for it if you don't manually choose them. Read [this](https://sqlite.org/autoinc.html) if you're interested in the details.

>If I want another column `code` which has a `withLength` constraint and is unique, do I do this?

No, but that's because `withLength` is enforced in Dart only. It doesn't have an effect on the schema.

**Comment by cervonwong** [comment]
Quick question again:

If I want the column to be non-nullable, do I need to do:
`TextColumn get code => text().withLength(min: 6, max: 7).customConstraint('NOT NULL UNIQUE')();`
or is 
`TextColumn get code => text().withLength(min: 6, max: 7).customConstraint('UNIQUE')();`
fine?

A quick scroll through GitHub project shows that most people do not put NOT NULL. Thanks!
