### ISSUE TITLE
Setting a field back to null

### ISSUE THREAD

**Issue by raphmte** [simolus3/moor#95]
Hello @simolus3 how are you? I need to do the following. In the example below:
```dart
class Todos extends Table{

  IntColumn get id =>
      integer().autoIncrement()();

  TextColumn get name =>
      text().nullable()();
}
````
When I create an object of this class with the following values:
```dart
Todo item = Todo( name: 'Test' );
````

If I try to return my Name field to NULL I can't, is there any way to do this?
```dart
item = item.copyWith( name: null );
print(item);
````
This will display the following (without the field turning back to NULL):
```dart
Todo( id: null name: Test )
````
I have a situation in my system that in some case I need to return the fields to NULL, including the object's Key field, in this case the ID.

Can you help me?

**Comment by simolus3** [comment]
Unfortunately, we don't have a way to set fields back to null on data classes by using `.copyWith`. The problem is that a parameter that is not set when calling `.copyWith` is implicitly set to null, so we can't know whether `item.copyWith(name: null)` means "I don't wan't to change the name" or "I want to set the name to null".

Since moor 1.5, we generate an additional class called a "Companion" for each data class, which allows to set fields back to null. So you could to something like this:
```dart
Todo item = loadSomeTodoItem();
TodosCompanion withNullName = TodosCompanion(id: Value(item.id), name: Value(null));
```
You can use these companions instead of the regular data classes for both inserts and updates.
The companions are very simple classes that don't override `hashCode`, `==` or `toString` so I wouldn't use them to represent data, but they're useful when inserting null values or running an update statement that sets fields back to null. Does that help?

**Comment by raphmte** [comment]
I had read about the Companions Class before coming to talk to you, they would solve my problem if I had to go back to NULL right in the db, but that's not my problem, I need to go back to the Object field itself.

But I already had an idea how to solve, create another Object and copy the data I want to it. Only problem is that there are more than 30 fields. hahaha

Thanks @simolus3 , thank you in advance for your help.

**Comment by simolus3** [comment]
Manually copying 30 fields can become annoying of course, but AFAIK there's no non-breaking change to this.

Maybe, in moor 2.0, we can make a breaking change and have the `copyWith` method take `Value` wrappers instead of the direct values, so that we can separate between `Value(null)` and `Value.absent()`, e.g. `entry.copyWith(name: Value(null))`. I'll think about that.

**Comment by raphmte** [comment]
In fact it won't be that hard the way my code is. And if that comes in any upcoming updates I would be extremely happy.

Have a great day @simolus3 .

**Comment by majdi21** [comment]
@simolus3 is there a reason why DataClass attributes are all generated as final? Why not introduce some annotation to allow us to make them mutable?

**Comment by simolus3** [comment]
Most users prefer immutable classes as those make code easier to reason about.

I can understand how that would be useful here though. We could introduce a build option to make generated models mutable.

**Comment by JoseGeorges8** [comment]
> Manually copying 30 fields can become annoying of course, but AFAIK there's no non-breaking change to this.
> 
> Maybe, in moor 2.0, we can make a breaking change and have the `copyWith` method take `Value` wrappers instead of the direct values, so that we can separate between `Value(null)` and `Value.absent()`, e.g. `entry.copyWith(name: Value(null))`. I'll think about that.

@simolus3  Have you thought about this? is it something you're planning to implement?

**Comment by simolus3** [comment]
This has been implemented with the `generate_values_in_copy_with` [build option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/).

**Comment by lucasjinreal** [comment]
@simolus3 Hi,

I foudn the data is used Value(null), and the printed json is null, but when stores to sql, it didn't chagned value at all

```
Future<int> updateBoardData(DbBoardData data) async {
    // return into(boardData).insertOnConflictUpdate(data);
    var c = await (select(boardData)..where((tbl) => tbl.id.equals(data.id)))
        .getSingleOrNull();
    if (c != null) {
      // data = data.copyWith(id: data.id, title: data.title);
      kLog("=========########!!!!!!!!!!!!!****>>>>>> ${data.toJson()}");
      return into(boardData).insertOnConflictUpdate(data);
    } else {
      return into(boardData).insertOnConflictUpdate(data);
    }
  }
```

 the json shows a value 👍 

```
[KLOG] =========########!!!!!!!!!!!!!****>>>>>> {id: cfaef0c0-382f-4e16-8197-96379819662f, typeName: Todo, content: I should add to system reminder and calendar when user prompted.

, title: add something to someone, createdAt: 1757815450000, updatedAt: 1757820438000, status: Todo, startTime: 1757817250000, dueTime: 1757824450000, autoFollow: false, remindTime: null<…>
```

the remindTime can not be set back to null at all.

Did I missed something, this is weired!
