### ISSUE TITLE
 SqliteException(1299): NOT NULL constraint failed

### ISSUE THREAD

**Issue by apoleo88** [simolus3/moor#960]
I don't understand why and if always, but sometimes this happens:

A Table:
```
class Runnings extends Table {
  @override
  IntColumn get id => integer().autoIncrement()();
  BoolColumn get group => boolean().withDefault(const Constant(false))();
  IntColumn get count=> integer().withDefault(const Constant(0))();
}
```
A new Instance of an Entry of the table:
`Running run = Running();`

if I check `run.group` is null.

I insert it in db: no error.
`int runId = await database.insertRunning(run)`

I update my var with the id:
`      run = run.copyWith(id: runId);`

if I check `run.group` is null.

Now if I update `run` in db I get this error:
`SqliteException(1299): NOT NULL constraint failed: runnings.group, constraint failed (code 1299)`

I use the following options:
```
          write_from_json_string_constructor: true
          mutable_classes: true
```
```
  moor: ^3.4.0

dependency_overrides:
  analyzer: 0.40.5

dev_dependencies:
  moor_generator: ^3.4.0
  build_runner: 1.10.2
```

Shouldn't the correct behaviors to always create the Instance with the default values instead of when the row is inserted in db?
Because otherwise how can I get the corrected row, I have to query a row that just inserted?

**Comment by simolus3** [comment]
TL,DR: Always use companions to represent partial rows.

This is working as intended here. When you use `withDefault`, that value will only be applied when you insert values into the database, it's not reflected in the Dart data class.
Also, `null` in a data class can have two different meanings for inserts or update. It could mean "this field was set to null, so please also set it to null in the database" or "this field was set to null, so please use the default value / don't write the field at all". For inserts and updates on data classes, we chose the second interpretation and for `replace` we chose the first. This exists mostly for backwards compatibility, moor also generates "companions" which don't have this problem.

This has always been a problem, but it will get worse when we introduce null safety. Clearly, `Running.id` should be a non-nullable field since its non-nullable in the database. But we can't set that value in Dart since we only know the id after an insert. You'll notice that the column is `@required` now, so you might get a static hint. After null safety, it will be a compile time error to instantiate `Running()` without an id.

For this reason, you should always use companions to represent partial rows (pretty much all rows you don't get via a select`). For instance, you could use

```dart
// the .insert() constructor has @required parameters for columns that really are required for 
// an insert. In your case, none.
var run = RunningsCompanion.insert();
int runId = await database.insertRunning(run);

run = run.copyWith(id: Value(runId));
// Can update, but that wouldn't do anything in this calse.
```

Btw: You can use `Insertable<Running>` as a type to allow both the data class and companions.

**Comment by apoleo88** [comment]
I strongly disagree.

1. **The Dart Data Class should be generated with the default value used in the table.**
There is no downfall, it eliminates eventual errors and gives you complete control over the default value. (like accessing the default value from anywhere and have to declare it only once in the table)

2. **Any updates should check if nullable is supported and replace it with the default.**
Since a field does not support nullable, why allow to null it? You should use flags to define changed fields OR the Value(null) only when you want to specify no updates to the field. Not for null assignments, because null assignments should directly assign null or the default value to the row.
So, 
at the moment of the assignment to null: `run.group = null;` it should `run.group = false;`
OR 
at the moment of the update into the table, the null values (not Value(null) that to me are emptiness) should be replaced with the default ones. This is the job that I would expect from the generated moor class.

3. **Companions should be removed**
Companions could and should be removed from the front use.

_Please don't close and allow discussion_

**Comment by simolus3** [comment]
> __The Dart Data Class should be generated with the default value used in the table.__

That's not unreasonable, but we can't know all values from Dart: An `autoIncrement()` is essentially a default value, but we can't query it before the `insert`. Defaults like `currentDateAndTime` are similar: They reflect the time of insertion, which we don't know when the object is created.

> __Any updates should check if nullable is supported and replace it with the default.__

Okay, but let's say that we _had_ a nullable field

```dart
class Foo extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get bar => integer().nullable().default(const Constant(42))();
}
```

Let's say I want to run this sql statement: `UPDATE foo SET bar = null`. How would I write that in Dart with the behavior you describe? Having a different behavior for nullable and non-nullable columns would be confusing to the user IMO: If you later change a non-nullable column to be nullable, you get very hard to spot problems in your code because the behavior just changed behind the scenes.

Another example: Let's say that I change the default of `group` from `false` to `true`, but I only want to do that for new rows. When I do `update(Running(count: 1))`, I want moor to run `UPDATE runnings SET count = 1`. With the behavior you suggest, it would run `UPDATE runnings SET count = 1, group = true` which would replace the default for existing rows.

> So, at the moment of the assignment to null: `run.group = null;` it should `run.group = false;`

If the `group` setter accepts null, Dart 2.12 will enforce the `group` getter to be nullable too. That's clearly not what we'd want, since `group` is supposed to be non-nullable.

> __Companions should be removed__

Companions solve the problem that a full row and a partial row need different data structures.  I don't see how your suggested changes make companions obsolete.

> _Please don't close and allow discussion_

Sorry, I interpreted your issue as a question.

**Comment by apoleo88** [comment]
Autoincrement values should be excluded, in fact, assign the id after the insertion is completely reasonable.

Just proposing on top of my head, 
I would generate a static final Map in the Foo class, that says which field can be nullable and which couldn't, and a static final class with the default value.
The Instances instead generate a class with a Map of the _changed_ variables.

```
class Foo extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get bar => integer().nullable().default(const Constant(null))();
  IntColumn get bas => integer().default(const Constant(42))();
  IntColumn get cuz => integer()();
}
```
so If I call
```
Foo foo = Foo(cuz: 1);
// then foo.changed['cuz'] == true //  all the other are false.
// also the other variables with a default values will get it. foo.bar == null; foo.bas == 42;

// if I do:
foo.bas = 20;
// then foo.changed['bas '] == true //  all the other changed except cuz are always to false.

// Now if I run insert(foo) I won't need the changed map, all the values are already set.

// if I run update(foo), it will update only the var with changed == true

// if I set any var to null
foo.bar = null;
// it will:
if(bar nullable)
  bar = null
else
  if(bar has a default value)
     bar = default
  else
     error: you are setting a non nullable field to null!
anyway:
 changed['bar'] = true;

// An update could be written:
.write(foo(bar: 1))
// since it has only changed['foo'] == true
// or if you know how, even remove the need of foo() inside and just write(bar:1)

// For example, I would love to have only a select query and use the write directly in my code.
await db.SelectNiceFoo(...).write(bar: 1);
// I would expand the same reasoning to the selects functions 
// to reduce the boilerplate when possible like db.foo.select(id: 1).write(bar: 1); but maybe another time
```

I know I am making an example with many changes all at once.

I am not sure companions are needed in other parts but with this example, it isn't.
I would anyway limit the need of the companions as much as possible since it is counterintuitive.

**Comment by apoleo88** [comment]
I forgot to mention that you can use `Value(null)`  as default value for all in the constructor.
So you can know in the initialization which value has been set to `null`, and which are not been initialized `Value(null)`

**Comment by victorcatn** [comment]
I was thinking about this right now. It will be aweasome if we can see the default values in dataclasses before insertion

**Comment by simolus3** [comment]
>  The Instances instead has a Map of the _changed_ variables.

Data classes and companions were designed to be immutable. We generate mutable classes for users that prefer them, but I'm not interested in adding first-class library support for mutable data classes. The much more common scenario is to use companions for inserts.

> It will be awesome if we can see the default values in dataclasses before insertion

What would you be using this for? This would be tough for nullable columns with default values, since then we don't know if `null` should be the default or `NULL`.

**Comment by victorcatn** [comment]
> What would you be using this for?

That way I can keep the default values in only one place, and work with that values to finally generate the rest of the class and send that to the database.

>  This would be tough for nullable columns with default values, since then we don't know if null should be the default or NULL.

Maybe we can add the option to select if we prefer the defaults over nulls, or if it's not possible, maybe add the default values in a static member of the dataclass to be able to use it from the code.

**Comment by apoleo88** [comment]
> Data classes and companions were designed to be immutable. We generate mutable classes for users that prefer them, but I'm not interested in adding first-class library support for mutable data classes. The much more common scenario is to use companions for inserts.

I think mutable gives you a nicer control and avoids having to use copyWith every time that does make a whole copy every time.
I don't see any pro to have the variable immutables. I don't think developers need protection from making the mistake of changing the values.


> What would you be using this for? This would be tough for nullable columns with default values, since then we don't know if `null` should be the default or `NULL`.

It would give you the assurance that what you have is the effective row that is going to be recorded in the database with already all the default values. You can check without having to retrieve it again and edit and updating it. (the main problem why I opened this issue) 
If the field is nullable, then `= null` will assign `null` independently from the default value.  If you don't like that it is possible to assign the default value by giving a null assignment because could be misinterpretable, maybe just a method toDefault() for the field, so it will be clearer the intent.
