### ISSUE TITLE
Collection of breaking changes for moor 4

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#965]
This issue lists breaking changes planned for moor 4. The list is not necessarily complete yet though.

- (from #810, done): Remove the `QueryEngine` mixin, add its methods to `DatabaseConnectionUser`.
- (from #628): Throw from `TypedResult.read()` and `TypedResult.readTable()` if the table/expression is not part of the query (currently returns `null`)
- (done) rename `getSingle()`/`watchSingle()` to `getSingleOrNull()`/`watchSingleOrNull()`. Then add `getSingle()`/`watchSingle()` methods that return non-nullable values. This is subtly breaking, which is bad, but IMO the best way forward since `(await x.getSingle())!` is annoying to use with null safety
- (done): made the `args` parameter in `QueryExecutor` a `List<Object?>`, it used to be a raw `List`
- (done): Remove an unused type parameter from `TypedResult.read`
- (done) remove the legacy type inference algorithm in `sqlparser`

If you disagree with any of those changes, please let me know. Similarly, if you have found annoyances that could be solved with a minor breaking change, feel free to suggest them here.

**Comment by davidmartos96** [comment]
Have you thought about splitting the Column types (TextColumn, ...) into nullable and non nullable versions? With the current migration the underlying generic type is nullable. 
Related to that, the expressions API always returns nullable types, even when the "input" is not. 
I'm not sure how much effort could that be, but I think it would be a bit nicer API

For the expressions maybe we could have definitions such as 

```dart
extension SomeExtension on Expression<B extends bool?>
```

instead of `on Expression<bool?>`

That way a method could return B explicitly to match the input Expression type, or bool? if the method could result in a null (although no example comes to my mind for the latter)

**Comment by simolus3** [comment]
I like the idea of `B extends bool?` to have nullable and non-nullable variants.

One problem with non-nullable columns are joins though: If we use a non-nullable columns from a joined table, it's hard to accurately know the actual nullability of that column. It's hard to reflect that in Dart's type system.
We'll have the same problem for compiled queries, but that at least gives us some options to reason about nullability (e.g. if there's a foreign key constraint and we join on the same columns, we can assume its non-nullable).

**Comment by simolus3** [comment]
Moor version `4.0.0-nullsafety.1` has been released and includes the breaking changes listed here.

**Comment by CDDelta** [comment]
fyi. the change to move the single utilities into the `SelectableUtils` extension is a breaking change as files that didn't import `moor` before will not have access to those methods. 😃

**Comment by simolus3** [comment]
@CDDelta Good point, I'll add that to the changelog as well.
