### ISSUE TITLE
null-safe, Expression<bool>.& operator casts to Expression<bool?>

### ISSUE THREAD

**Issue by SteveAlexander** [simolus3/moor#970]
Converting some code to be null-safe.

```dart
    return (select(items)
          ..where((t) => t.base.equals(baseId) & t.folderPath.equals(path))
          ..orderBy([(t) => OrderingTerm(expression: t.name)]))
        .get();
```

The `where` wants an `Expression<bool>`, which is fine except the that `&` operator makes the type `Expression<bool?>` even if the left and right hand arguments are `Expression<bool>`.

Solution seems to be to manually cast, which is a bit ugly.

```dart
    return (select(items)
          ..where((t) => (t.base.equals(baseId) & t.folderPath.equals(path)) as Expression<bool>)
          ..orderBy([(t) => OrderingTerm(expression: t.name)]))
        .get();
```

**Comment by simolus3** [comment]
The manual cast would also fail with strong null safety I believe. This problem was already brought up here: https://github.com/simolus3/moor/issues/965#issuecomment-742836513 Unfortunately, it will be very challenging to accurately map SQL's nullability behavior to Dart's type system. The approach for now is to use the nullable variant in most places and then gradually introduce non-nullable versions where it's safe to do so. I changed remaining moor apis to accept an `Expression<bool>` in d9cf6660ecf24f6d54cb00aceb94097589f2f80a.

**Comment by SteveAlexander** [comment]
Thanks, the changes in d9cf666 allowed me to fix my code
